# 2022–2023 ACADEMIC CALENDAR {#sec-academic-calendar}

### FALL TERM 2022

   |   
:-|---:
Tues, August 23 |	Open Registration 
Wed, August 24 |	Classes Begin
Tues, August 30 |	Last Day to Add or Drop a Full-Term, or 1st Half-Term Course without a W
Fri, September 2 |	Census Date, Attendance Due on My.Coe
Mon, September 5 |	No Classes (Holiday) Labor Day
Fri, September 9 |	Date of Record
Thurs, September 22 |	Last Day to Withdraw &\/ or Change Method of Grading for First-Half Courses
Mon–Tues, October 10–11 |	Fall Term Break
Thurs–Sat, October 13–15 |	Homecoming
Mon, October 17 |	Mid-Term Progress Report Due on My.Coe (11\:59 PM)
Mon, October 17 |	Begin Second-Half Term Courses
Fri, October 21 |	May Term deposit and registration due
Fri, October 21 |	Last Day to Add or Drop a Second-Half Term Course without a W 
Mon, October 24-Fri, November 11 |	Advising Season 
Fri, October 28 |	Last Day to Withdraw &\/or Change Method of Grading for Full-Term Courses 
Mon–Fri, November 14–18 |	Registration for Spring Term 2023
Tues, November 15 |	Last Day to Withdraw &\/or Change Method of Grading for Second-Half Courses 
Mon–Fri, November 21–25 |	No Classes (Holiday) Thanksgiving Recess
Thurs, December 1 |	Open Online Registration until Last Day of Finals
Fri, December 2 |	Last Day of Fall Term Classes
Sat, December 3 |	Reading Day
Mon–Thurs, December 5–8 |	Final Exams
Wed, December 14 |	Final Grades and Attendance are Due from the Faculty on My.Coe (11\:59 PM)  


### SPRING TERM 2023

   |   
:-|---:
Wed, January 11 |	Classes Begin
Mon, January 16 |	No Day Classes (Holiday) Martin Luther King Jr. Day
Wed, January 18 |	Last Day to Add or Drop a Full-Term or 1st Half-Term Course without a W
Fri, January 20 |	Census Date, Attendance Due on My.Coe
Thurs, January 26 |	Date of Record Mon, February 6
Mon, February 6 |	Last Day to Withdraw &\/or Change Method of Grading for First-Half Courses 
Mon, March 6 |	Begin Second-Half Term Courses
Tues, March 7 |	Mid-Term Progress Report Due Online (11:59 PM)
Fri, March 10 |	Last Day to Add or Drop a Second-Half Term Course without a W
Mon–Fri, March 13–17 |	Spring Term Recess (Starting after Class on Friday, March 10)
Mon–Fri, March 20–April 7 |	Advising Season Thurs, March 30
Thurs, March 30 |	Last Day to Withdraw &\/or Change Method of Grading for Full-Term Courses 
Mon–Fri, April 10–14 |	Registration for Fall Term 2023
Mon, April 10 |	Summer Registration Opens
Tues, April 11 | 	Last Day to Withdraw &\/or Change Method of Grading for Second-Half Courses
Wed, April 12 |	Student Research Symposium ** No Day Classes ** Evening Classes Will Meet 
Fri, April 28 |	Last Day of Spring Term Classes
Sat, April 29 |	Reading Day
Mon–Thurs, May 1–4 |	Final Exams
Sat, May 6 |	Honors Convocation \/ Baccalaureate
Sun, May 7 |	Commencement
Tues, May 9 |	Final Grades and Attendance are Due for Non-Graduating Students on My.Coe (11:59 PM)  



### MAY TERM 2023

   |   
:-|---:
Wed, May 10 |	Classes Begin
Fri, May 12 |	Last Day to Add or Drop a Course Without a W
Mon, May 15 |	Attendance Due Online; Last Day to Change Method of Grading for May Term
Wed, May 17 |	Last Day to Withdraw from May Term Courses
Fri–Sat, May 19–20 |	Meeting of the Board of Trustees
Mon, May 29 |	No Classes (Holiday) Memorial Day
Fri, June 2 |	Last Day of May Term Classes
Sat, June 3 |	Residence Halls Close
Sun, June 4 |	Final Grades and Attendance for May Term Due on My.Coe (11:59 PM)


### SUMMER TERM 2023*
    
   |    
:-|---:
Mon, June 5 |	Classes Begin
Fri, June 9 |	Last Day to Add or Drop a Full-Term Course Without a W
Mon, June 19 |	No Classes (Holiday) Juneteenth
Fri, June 23 |	Last Day to Change Method of Grading &/or Withdraw from Block A Courses 
Tues, July 4 |	No Classes (Holiday) Independence Day
Fri, July 7 |	Last Day of Block A Courses
Mon, July 10 |	Classes Begin: Block B Courses
Tues, July 11 |	Mid-Term Progress Report Due Online (11:59 PM); Block A Final Grades Due
Fri, July 14 |	Last Day to Add or Drop a Course Without a W for Block B Courses
Mon, July 17 |	Last Day to Change Method of Grading &/or Withdraw from Full Term Courses
Tues, July 25 |	Last Day to Change Method of Grading &/or Withdraw from Block B Courses
Fri, August 11 |	Last Day of Term Classes: Block B and Full-Term Courses
Tues, August 15 |	Final Grades and Attendance Due (Block B and Full-Term) on My.Coe (11:59 PM)

\*Courses taught at the Wilderness Field Station are subject to the broad dates of the summer, but will provide a specific add/drop and withdraw calendar to students at the time of application. 
