## AREAS OF STUDY {#sec-areas-of-study}

The three undergraduate degrees have areas of study associated with them. The Bachelor of Science in Nursing’s area of study is nursing; the Bachelor of Music’s areas of study are performance, composition, and education. The Bachelor of Arts’ areas of study, commonly referred to as majors, are listed below.

Students should declare an area of study by the end of their sophomore year. All students must earn at least a 2.00 GPA in courses required to complete their areas of study, as well as meet specific requirements set forth for the areaof study.

:::::::::::::: {.columns}
::: {.column width="50%"}
- Accounting, Managerial
- Accounting, Public
- African American Studies
- Art
- Art History
- Asian Studies
- Biology
- Business Administration
- Chemistry
- Communication Studies
- Computer Science
- Creative Writing
- Data Science
- Economics
- Elementary Education
- English
- Film Studies
- French & Francophone Studies
- General Science
- History
- Interdisciplinary
:::
::: {.column width="50%"}
- French & Francophone Studies
- Interdisciplinary Studies*
- International Business
- International Economics
- International Studies
- Kinesiology
- Literature
- Mathematics
- Music
- Philosophy
- Physics
- Political Science
- Psychology
- Religion
- Social & Criminal Justice
- Sociology
- Spanish
- Spanish Studies
- Theatre Arts
- Writing (Rhetoric)
:::

::::::::::::::

 




\* A coherent interdisciplinary sequence of courses devised by the student, in consultation with faculty, suited to the student’s individual goals and approved by the Academic Policies Committee (see p. 135).
In addition to the areas of study/majors listed above, the following **COLLATERAL MAJORS** are offered, which require a student to satisfy the requirements of a major from the list above in addition to the selected collateral major.

- Biochemistry
- Molecular Biology
- Public Relations
- Environmental Science
- Neuroscience
- Environmental Studies
- Organizational Science

### AREAS OF STUDY (MINOR) FOR B.A.
- African American Studies
- Anthropology
- Art
- Art History
- Asian Studies
- Chemistry
- Classical Studies
- Communication Studies
- Computer Science
- Creative Writing
- Data Science
- Economics
- English
- Film Studies
- French & Francophone Studies
- Gender and Sexuality Studies
- Health & Society Studies
- History
- Interdisciplinary French &
- Francophone Studies
- International Economics
- Mathematics


### AREAS OF STUDY (MAJORS) FOR B.M.
- Keyboard or Instrumental Performance
- Vocal Performance
- Composition
- Instrumental Music Education
- Vocal Music Education

### AREA OF STUDY (MAJOR) FOR B.S.N.
- Nursing
