# GENERAL EDUCATION COURSES


## Diverse Cultural Perspectives: Non-Western Perspectives



## Diverse Cultural Perspectives: United States Pluralism



## Diverse Cultural Perspectives: Diverse Western Perspectives



## Independent Studies



## Internships



## PRACTICUM

A practicum experience is required of all students for all undergraduate degrees, except those earning second degrees.  

Typically completed in the student’s junior or senior year, all practica are experiences that integrate academic components with career or other life goals and are significant educational exercises outside the classroom.  A practicum experience can consist of an internship, off-campus study, community-based project, honors project, or some other kind of independent activity.

Depending upon the type selected, some practica are graded A–F, while others are P/NP. Some practica are credit bearing, while others are not. In some instances, the practicum must be approved by the student’s major department. 

1. Full-Term (16-week) Off-Campus Study 
2. Wilderness Field Station Summer Courses 
3. Crimson Fellows Thesis or Crimson Fellows Project, etc. as stated
4. Independent Project (in list of courses that follows starred courses * require department approval for practicum credit): 
5. †Internship (see a complete listing of internships on p. 29)
6. †Community-Based Project (see course description on p. 70)

†A maximum of two course credits earned through any combination of Internships and Community-Based Projects may be included in the 32 course credits required for graduation.

- AAM-444 Independent Study
- ANT-205 Archaeological Field School
- ANT-444 Independent Study
- ANT-474 Research Participation
- ARH-444 Independent Study in Art History
- ARH-474 Senior Seminar II & Senior Project (WE)
- ART-394 Directed Studies in Art
- ART-444 Independent Study
- ART-474 Senior Seminar II & Senior Exhibition
- AT-40_ Clinical Athletic Training (successful completion of sequence of AT-20_/ -30_ and-40_ - required to receive full credit)
- BIO-115 Marine Biology
- BIO-444 Independent Study
- BIO-454 Research Participation
- BIO-462 Advanced Biology Laboratory I
- BUS-444 Independent Study
- BUS-454 Research in Business
- CHM-444 Independent Study
- CHM-454 Undergraduate Summer Research
- COM-394 Directed Studies in Communication Studies (WE)
- COM-444 Independent Study in Communication Studies* (WE)
- CRW-112 Advanced Literary Magazine Editing (two terms)
- CRW-394 Directed Studies in Creative Writing (WE)
- CRW-492 Manuscript Workshop (WE)
- CS-444 Independent Study
- CS-454 Research in Computer Science
- DS-444 Independent Study in Data Science
- DS-454 Research in Data Science
- ECO-444 Independent Study
- ECO-454 Research in Economics
- EDU-215 Practicum in Education (WE)
- EDU-481 Student Teaching in Art at the Secondary School (WE)
- EDU-482 Student Teaching in Physical Education at the Secondary School (WE)
- EDU-483 Student Teaching in Art at the Elementary School (WE)
- EDU-485 Student Teaching in Physical Education at the Elementary School (WE)
- EDU-489 Student Teaching in the Senior High School (WE)
- EDU-490 Student Teaching in Middle School or Junior High School (WE)
- EDU-491 Student Teaching in the Upper Elementary Grades: Grades 3-6 (WE)





