# FIRST-YEAR EXPERIENCE

The student’s First-Year Experience at Coe is a deliberate strategy to engage first-year students across multiple dimensions of college life in the first year.  Components of the First-Year Experience include writing exercises, various campus events, and the First-Year Seminar (FYS).

The First-Year Seminar is required for all students who have not yet completed a full-time college term after high school graduation.  During the Fall Term, a variety of First-Year Seminars—topics courses exploring issues from multiple perspectives—are offered.  The seminars emphasize critical thinking, writing, speaking and research skills.  

All First-Year Seminars carry the writing emphasis designation.  First-Year Seminar courses cannot fulfill any distributional, cultural perspective, or major requirements.  Students who drop or fail their First-Year Seminar are required to complete a replacement course designated by the Registrar the following term.  The completion of this Spring Term course makes it possible for the student to fulfill the FYS graduation requirement.  For students who fail the Fall Term First-Year Seminar, successful completion of the Spring Term course also allows the grade in the FYS to be changed from “F” to “NP” on the transcript.

Students who begin their college enrollment in the Spring Term must also complete a course designated as a replacement.

