# WRITING EMPHASIS COURSES {#sec-writing-emphasis-courses}

**Writing Across the Curriculum: Statement of Guiding Principles**

As stated in the Coe College Mission Statement, our reason to exist as an institution is to ready students intellectually, professionally, and socially to lead productive and satisfying lives in the global society of the 21st century. In accordance with this mission, our curriculum requires that students undertake “a series of intensive writing experiences, spread across four years of study.” This requirement is known as Writing Across the Curriculum, the guiding principles of which are detailed below.

As a philosophy, Writing Across the Curriculum asserts that writing is most effectively learned in context: to varied audiences, with varied purposes. In adopting this philosophy, Coe College has committed to making writing-intensive experiences available to students in all disciplines. Known as “Writing Emphasis” credits, these courses are divergent in subject matter but aligned in their commitment to giving students content-rich and context-specific writing experiences that foster a critical flexibility in transferring knowledge about effective writing to multiple, even unknown, contexts.

Therefore, students who complete the requisite number of writing emphasis courses will graduate from Coe knowing that writing is both a means and an end: a method for exploring ideas and deepening one’s knowledge as well as a tool for sharing that knowledge and expressing one’s point of view. Similarly, graduating students will know that the practice of writing is a recursive process rooted in revision, which refers both to the reconsideration of one’s ideas and to the refinement of prose, and this process unfolds over a lifetime. Understanding that students will encounter innumerable writing situations in their lives, many of which may be unfamiliar to them, they will graduate from Coe having developed the confidence and self-efficacy necessary to adapt or draw from their existing knowledge in order to navigate new contexts. 

Although many courses at Coe may include writing activities, courses endorsed by Writing Across the Curriculum are those in which:

- Students are given opportunities to practice revision, whether via multiple drafts of a single project or multiple iterations of the same type of assignment;

- Students receive instructor feedback on written work to facilitate revision; and

- Writing assignments are frequent enough that they are integral to the learning throughout the course, enabling students to develop in one or more of the following learning outcomes, as appropriate to discipline and course objectives:

  - **How to write for specific purposes and audiences**

    - *Including attention to the ways purposes and audiences shape form, mode, voice, method, organization, engagement with and citation of research, and/or creativity and imagination*

  - **How to engage in critical thinking**

    - *Particularly how to conduct analysis, how to synthesize information, how to interpret and/or use evidence and data, and how to present one’s ideas coherently and stylistically*

  - **How to practice, assess, and develop effective habits for writing**

    - *Specifically, how to read deeply, how to begin and later practice selection in research, how to be a skilled reader of one’s own and others’ in-process writing, how to accept and interpret feedback, and how to revise writing, all of which are parts of the process of learning how to have and develop ideas*

  - **How to engage in writing as a method for learning and discovery**

    - *For deepening knowledge, thinking through questions and problems, and reflecting on connections and growth*

  - **How to name and describe one’s own knowledge for others**

    - *For example, in the form of personal statements for application to graduate study, cover letters and resumes for entering and advancing in the workforce, or other forms of self-summary that facilitate transition from the baccalaureate environment through the broader public.*


Many writing emphasis sections are offered each year, and, in addition, the College’s rhetoric department offers several interdisciplinary writing courses designed to guide students learning to write effectively at the college level. (See course descriptions starting on p. 87). General Education or major courses that are also designated as writing emphasis courses may be used to satisfy both requirements.

In this catalog, writing emphasis courses are designated by a (WE) after the course title, e.g. “RHE-200 Rhetorical Theory & Practice (WE).” In other contexts, the course code may end with a “W” (e.g. RHE-200-W). All sections of such a course, regardless of instructor, will carry writing emphasis credit.

Fulfilling the Writing Emphasis Requirement:

Only designated WE courses in which a student earns a grade of “C” (2.0) or better count toward fulfillment of this requirement.

Only designated courses taken at Coe College count toward fulfillment of this requirement.

Undergraduate degree-seeking* students

- who start at Coe College or who transfer fewer than 8 course credits earned after graduation from high school must complete at least 5 writing emphasis courses. Of these 5, one will usually be the FYS. Of the remaining 4, it is recommended (but not required) that at least 1 be taken outside the student’s intended major(s).

- who transfer at least 8 but fewer than 16 course credits to Coe, earned after graduation from high school, must complete at least 3 writing emphasis courses.

- who transfer 16 or more course credits to Coe, earned after graduation from high school, must complete at least 2 writing emphasis credits.

For all students, regardless of transfer credit, it is recommended (but not required) that at least one writing emphasis course be taken in the upper division within the student’s intended major(s). “Upper division” courses are defined in this case as those numbered 300 and above; upper division writing emphasis courses could include both scheduled classroom courses and arranged writing-based capstone projects (such as a thesis). See Departmental Writing Plans for more information on writing in the major(s).

*Students seeking a second undergraduate degree from Coe should see Second Baccalaureate Degree p. 13.


## COURSE NUMBERING
- Courses numbered 100–199 are introductory to the subject. 
- Courses numbered 200–299 assume a capacity for the independent acquisition of material and generally build on the methods and subject matter of 100-level courses. 
- Courses numbered 300–399 are typically oriented toward a major or minor. They require a strong foundation of knowledge specific to the discipline. 
- Courses numbered 400–499 are courses in the major or minor that are designed to challenge students to integrate discipline-specific knowledge in advanced ways. These courses typically contain advanced disciplinary coursework, capstone projects, and/or independent research.
