# GENERAL EDUCATION COURSES {#sec-general-education-courses}

Completion of the General Education Program, described here, is required for all students earning B.A. or B.S.N. degree at Coe College, but not required of students earning a B.M. degree.  An appropriate transferred course, determined by the Office of the Registrar, with a grade of “C” (2.0) or better may be accepted to meet an individual requirement.  
Advanced Placement and International Baccalaureate courses may not be used to meet any part of this requirement.  No more than two courses with the same prefix may be used to fulfill the General Education Core Requirements.

**A) Liberal Arts Core**

1. A total of at least **one** course credit in the **Fine Arts Core** (courses with a prefix of ARH, ART, FLM, MU, MUA, THE)
2. A total of at least **two** course credits in the **Humanities Core** (courses with a prefix of AAM, AMS, CLA, COM, CRW, ENG, FRE, GER, GRK, HIS, HUM, LTN, JPN, PHL, REL, RHE, or SPA)
3. A total of at least **two** course credits in the **Natural Sciences and Mathematics Core** (courses with a prefix of BIO, CHM, CS, DS, MTH, PHY, STA, one of which must be a lab science with a prefix of BIO, CHM, or PHY)
4. A total of at least **two** course credits in the **Social Sciences Core** (courses with a prefix of ANT, ECO, POL, PSY, or SOC) 

**B) Diverse Cultural Perspectives (DCP) Core**

A liberally educated person should have some knowledge of other cultures and some tools to aid in seeing one’s own culture from other perspectives. 

The Diverse Cultural Perspectives courses (Non-Western Perspectives (course number ends in 6), United States Pluralism (course number ends in 7), Diverse Western Perspectives (course number ends in 8) help students to understand their own cultural identities and to develop appreciation for the range of different cultures to be found in the world, in the nation, and on campus. These courses explore other cultures in their own terms and as they interact with American culture. As a group, they encourage reflection on different ways in which cultural identities are formed, expressed and contested. Students are encouraged to combine these courses with the study of a world language and with study abroad. 

Completion of **one** of the following options *(see p. 34-38 for descriptions and approved courses)*:

- Non-World Language Option (all of the following):
  - Any DCP course (course number that ends in 6, 7, 8) 
  - Non-Western Perspectives (course number that ends in 6)
    (A semester-long study abroad experience can fulfill the Non-Western Perspective and DCP requirement.)
  - United States Pluralism (course number that ends in 7)
    (A semester-long U.S. off-campus study experience can fulfill the U.S. Pluralism and DCP requirement.)
- Elementary World Language Option (all of the following):
  - Any DCP course (course number that ends in 6, 7, 8)
  - Two elementary world language courses in the same language not previously studied (may also fulfill one of the Humanities Core courses)
- Intermediate World Language Option (all of the following):
  - Any DCP course (course number that ends in 6, 7, or 8)
  - One intermediate (-215) or above World Language course (*may also fulfill one of the Humanities Core course requirements*)

## Diverse Cultural Perspectives: Non-Western Perspectives {#sec-diverse-cultural-perspectives-non-western}

The Non-Western Perspectives (NWP) group includes courses in which a preponderance of the content analyzes human experience from the perspectives of diverse peoples outside of Western culture. Such cultures often are characterized by values and beliefs different from those of the United States and Western Europe. 

- ANT 116 Cultural Anthropology
- ANT 286 Topics in Anthropology:NWP
- ARH 106 World Art
- ARH 296 Topics in Art History:Global Persp
- ASC 106 May Term in Asia
- ASC 176 China and Japan
- ASC 186 Modern South Asia
- ASC 196 Modern South East Asia
- +++MISSING INFO: c.asc216.long +++
- BUS 446 International Business Management
- BUS 466 Adv Top Mrktg:non-west persp
- BUS 476 Ad Top Mgmt:non-west persp
- COM 236 Intercultural Communication
- ECO 336 Divergent Economic Growth
- ECO 436 Econ Development
- ECO 446 International Econ
- ENG 146 Intro Postcolonial Literature
- ENG 206 Gender and Literature: NWP
- FRE 146 French Literature Translation:NWP
- FRE 446 Colonial & Multicultural Narratives
- FSA 146 Turkey: History &Culture
- GS 136 Gender in Non-Western World
- HIS 136 East Asian Civilization
- HIS 216 History of Modern Korea (WE)
- HIS 246 History of Modern China
- HIS 256 History of Modern Japan
- HIS 276 The "Discovery" of America: Clash
- HIS 286 Modern Middle East
- HIS 306 Revolution, Social Struggle, Testim
- HIS 316 Topics in History:Non-Western Persp
- HIS 466 Seminar Modern East Asian History
- IS 116 Intro to International Studies
- IS 126 HumanRightsBurmeseMigrant
- IS 136 May Term in Mongolia
- JPN 106 Images Foreign Culture
- MU 166 Topics in Music:Non-Western Perspct
- PHL 206 Buddhist Thought
- POL 266 Latin American Politics
- POL 276 African Politics
- POL 286 Asian Politics
- POL 296 Topics Pol Sci: Non-West Persp
- POL 386 International Development
- REL 106 Eastern Religions
- REL 116 Buddhism
- REL 136 Religions of China
- REL 196 Hinduism
- REL 206 Buddhist Thought
- REL 226 Religions of China:Daoism
- REL 236 Zen Buddhism
- REL 296 Topics in Religion NWP
- REL 306 Comparative Religion
- REL 336 Tibetan Buddhist Cultrue
- +++MISSING INFO: c.rel386.long +++
- RHE 146 Creative Nonfiction:Global Perspect
- SOC 226 Gender and Globalizaton
- SOC 236 Topics in Sociology NWP
- SPA 336 Hispanic Life/Cult-Latin America
- SPA 446 Latin Am. & Spanish Short Stories
- SPA 486 Topics in Hispanic Lit:Latin Amer
- THE 486 Spc Top Theatre or Film: NWP
- WSH 286 Topics in Washington, D.C:NWP

## Diverse Cultural Perspectives: United States Pluralism {#sec-diverse-cultural-perspectives-united-states}

The United States Pluralism (USP) group includes courses in which a preponderance of the content addresses one or more of the groups within the United States whose values, beliefs, and experiences differ from or oppose those of the majority culture. These courses increase students’ knowledge of the history of such groups; of the ways members of these groups have experienced democracy and culture in America differently because of factors like social class, race, gender, and religion; and of reform movements like feminism and civil rights, through which such groups have attempted to achieve social and economic equality. 


- AAM 107 Intro to African American Studies
- AAM 137 African American Literature	 
- AAM 217 Sport and Black Culture	
- AAM 227 Blackness & Identity in America
- AAM 287 Topics in African American Studies
- AAM 367 Topics in AfricanAmericanLiterature
- AAM 387 Adv Topics in African American Stud
- AAM 447 Drtd Learn in African American Stds
- AAM 457 Drtd Learn in African American Stds
- AAM 467 Seminar in African American Lit
- ARH 107 Gender and Art	
- ARH 297 Topics in Art History: US Pluralism	
- ARH 307 Modern and Contemporary Art
- BUS 387 Adv Top:Human Res Mgt
- BUS 437 Strategic Compensation	
- BUS 457 Employment and Discrimination Law
- BUS 467 Consumer Behavior	
- COM 157 Introduction to Media Analysis
- COM 237 Interpersonal Communication
- COM 337 Persuasion	
- COM 357 Sex, Race, & Gender in Media
- COM 437 Special Topic Applied Communication
- COM 447 Special Topics Production
- COM 457 Special Topics in Media Studies
- COM 467 Special Topics in Public Discourse
- ECO 237 Labor Economics	
- ECO 247 Health Economics	
- ECO 447 Urban Economics	
- ECO 457 US Econ History	
- EDU 117 Exceptional Learners	
- EDU 187 Human Relations	
- EDU 237 English Language Learners
- EDU 247 Foundations of Reading	
- ENG 107 Exploring Literature:US Pluralism	
- ENG 117 Asian American Literature
- ENG 127 Social Justice and Literature
- ENG 137 African American Literature
- ENG 157 Latinx/Chicanx Literature
- ENG 207 Gender & Lit:US Pluralism
- ENG 327 Literature of American Renaissance
- ENG 337 American Realism & Naturalism
- ENG 347 Study in Modern or Contemp Amer Lit
- ENG 357 Studies in Latinx/ChicanxLiterature
- ENG 367 Studies in African Am Literature
- ENG 467 Seminar inLit:USPluralism
- +++MISSING INFO: c.evs137.long +++
- GS 107 Intro Gender & Sexuality Studies
- GS 127 Dress, Gender, and Identity
- GS 247 Gender & Sexuality StudiesSymposium
- GS 327 Thry&Mthds/Gender &Sexuality Stdy
- GS 387 Topics: Gender & Sexuality Studies
- HIS 217 American War in Vietnam
- HIS 227 American Civil War	
- HIS 257 Native American History
- HIS 297 Women in America	
- HIS 317 Topics in History:US Pluralism	
- HIS 347 African American History
- HIS 387 American Colonial History
- KIN 347 Adapted Physical Education
- MU 157 Introduction to Jazz History
- NUR 137 Human Sexuality	
- NUR 297 Parent Child Relationships	
- NUR 387 Alternative Therapies for Hlth/Heal
- PHL 277 Philosophy of Gender & Race
- POL 207 Religion & American Politics
- POL 277 Women & Poltics in US
- PSY 137 Human Sexuality	
- REL 217 Religion in America	
- RHE 137 Creative Nonfiction U.S.-Pluralism
- RHE 257 Environmental Rhetoric	
- RHE 377 Cultural Studies	
- SOC 107 Introductory Sociology	
- SOC 207 Sociology of the Family	
- SOC 217 Sociology of Religion	
- SOC 237 Topics in Sociology:U S Pluralism	
- SOC 247 Sociology of Race	
- SOC 417 Sociology of Sex & Sexuality
- SPA 457 US LatinX Literature	

## Diverse Cultural Perspectives: Diverse Western Perspectives {#sec-diverse-cultural-perspectives-western}

The Diverse Western Perspectives (DWP) group includes courses in which a preponderance of the content addresses one or more subgroups of the Western world outside of the United States and the ways in which they experience Western culture. These courses increase students’ knowledge of the history of particular groups and the ways they have interacted with Western values. They typically address issues of difference and conflict between and within Western cultures by examining the influence of factors such as class, race, gender, and religion. 

- ANT 288 Topics Anthropology/Archaeology:DWP
- ANT 488 Adv Top Anthro/Archaeo:DWP
- ARH 128 Introduction to Art History
- ARH 218 The World of Renaissance Art
- ARH 248 Baroque, Rococo, and Neoclassicism
- ARH 268 History of Architecture
- ARH 298 Topics in Art History:Div West Pers
- CLA 108 Images of Foreign Culture
- ENG 108 Exp Lit:Diverse Western Perspective
- ENG 208 Gender & Lit:DWP
- ENG 378 Studies in Transatlantic Literature
- ENG 388 Romantic Literature
- FRE 148 French Literature Translation:DWP
- FRE 158 France & Francophone World
- HIS 208 The First World War (WE)
- HIS 218 The Second World War (WE)
- HIS 238 Modern France
- HIS 248 The French Revolution
- HIS 268 Latin America
- HIS 288 Renaissance & Reformation
- HIS 308 Legacies of the Cold War inLatin Am
- HIS 318 Topics in History :Div West Persp
- HIS 328 Modern France
- MU 458 Music History & Literature III
- NUR 268 Cult Diver & Health
- PHL 128 Morality & Moral Controversies
- PHL 138 Freedom, State, and Society
- POL 108 Introduction to Politics
- POL 248 Political Violence and the Violent
- POL 258 World Politics
- POL 298 European Politics
- POL 398 Religion & World Politics
- PSY 208 Gender Psychology
- REL 108 Western Religions
- REL 128 Judaism
- REL 138 Modern Judaism
- REL 148 Islam
- REL 178 Christianity
- REL 278 Mysticism
- REL 338 Modern Religious Thought
- SOC 238 Topics in Soc Div West Perspectives
- SOC 328 Urban Sociology
- SOC 338 Political Sociology
- SPA 148 Spanish Literature in Translation
- SPA 258 Spanish Lang Learn in Spain
- SPA 338 Hispanic Life/Culture:Europe
- SPA 418 Gender & Sexuality in Hispanic Wrld
- SPA 428 Indigeneity, Blackness, & EthnicLit
- SPA 458 Travel Writing & Transatlantic Lit
- THE 118 Theatre & Arts in Serbia
- THE 228 History of Theatre and Drama I
- THE 238 History of Theatre and Drama II
- THE 288 History of Dress
- THE 488 Special Topics in THE/ FLM

## Independent Studies {#sec-independent-studies}

The one-credit independent study or directed readings students are expected to complete a minimum of 140 hours of academic work, including meeting with faculty members and independent work between meetings. 

## Internships {#sec-internships}

The internship is a work or volunteer experience in the context of an independent academic investigation of site-related issues and personal aptitudes, values, and goals. The one-credit internship includes a minimum of 140 hours of on-site or remote experience and the required documentation and/or academic journal or paper as determined by the faculty member.  The details of the academic component are determined by prior arrangement with the faculty internship advisor.

Ordinarily internships are completed during the academic year as one of the 32 credits for graduation, or over the summer for a credit-bearing or non-credit bearing-practicum fulfillment activity.  In unusual circumstances where an internship presents an opportunity to extend the educational component of the experience significantly, an internship may earn two credits. Application for non-departmental, two-credit internships requires consultation with the Internship Faculty Advisor and approval of the Committee on Petitions; departmental two-credit internships, when permitted, are overseen by the department. 

A combined maximum of 2.0 course credits may be counted toward the 32 credits required for graduation through Internships or Community-Based Project (see p. 87). Many internships are completed in the Cedar Rapids area; however, it is permissible to complete an internship outside of the area during the summer, or done remotely if authorized by the Internship Faculty Advisor. 

Students interested in internships should consult with their Career Specialist in C3: Creativity, Careers, Community, as well as with the appropriate academic department who will be overseeing the internship experience.

Each internship must include the consent of an Internship Faculty Advisor and completion of the internship request form housed on the College’s online platform for internships.

Courses with an INT prefix and those on this list count as internship credit:

- AAM 494 Internship in African American Stds
- ANT 494 Internship in Anthropolgy
- ARH 494 Internship in Art History
- ARH 494 Internship in Art History
- ART 494 Internship in Art
- AT 494 Internship in Athletic Training
- BIO 494 Internship in Biology
- BUS 494 Internship in Business
- CHM 494 Internship in Chemistry
- COM 494 Internship in Journalism/Communicat
- CRW 494 Internship in Creative Writing
- CS 494 Internship in Computer Science
- DS 494 Internship in Data Science
- EDU 494 Internship in Education
- ENG 494 Internship in English
- FLM 494 Internship in Film
- FRE 494 Internship in French
- HIS 494 Internship in History
- HSS 494 Health Professions Externship
- INT 115 May Term: Topics 2
- INT 494 Internship
- INT 499 Summer Internship
- KIN 494 Internship in Kin, Health & Rec
- MTH 494 Internship in Mathematics
- NUR 494 Internship in Nursing
- NYT 394 Internship in New York City
- PHL 494 Internship in Philosophy
- PHY 494 Internship in Physics
- POL 494 Internship in Political Science
- PR 494 Internship in Public Relations
- PSY 494 Internship in Psychology
- REL 494 Internship in Religion
- RHE 494 Internship in Writing
- SOC 494 Internship in Sociology
- SMT 494 Internship in Sports Management
- SPA 494 Internship in Spanish
- THE 494 Internship in Theatre Arts
- WSH 494 Washington Experience

Students completing internships that are not department specific should register for one of the INT-494 or INT-499 courses on p. 49 (see the ***Coe Student Accounts Handbook*** for fee).

## Practicum {#sec-practicum}

A practicum experience is required of all students for all undergraduate degrees, except those earning second degrees.  

Typically completed in the student’s junior or senior year, all practica are experiences that integrate academic components with career or other life goals and are significant educational exercises outside the classroom.  A practicum experience can consist of an internship, off-campus study, community-based project, honors project, or some other kind of independent activity.

Depending upon the type selected, some practica are graded A–F, while others are P/NP. Some practica are credit bearing, while others are not. In some instances, the practicum must be approved by the student’s major department. 

1. Full-Term (16-week) Off-Campus Study 
2. Wilderness Field Station Summer Courses 
3. Crimson Fellows Thesis or Crimson Fellows Project, etc. as stated
4. Independent Project (in list of courses that follows starred courses * require department approval for practicum credit): 
    5. †Internship (see a complete listing of internships on p. 39)
    6. †Community-Based Project (see course description on p. 87)

†A maximum of two course credits earned through any combination of Internships and Community-Based Projects may be included in the 32 course credits required for graduation.

- AAM 444 Ind Study-Afr-Am St
- ANT 205 Archaeological Field Schl
- ANT 444 Independent Study: Anthropology
- ANT 474 Research Participation:Anthropology
- ARH 444 Independent Study: Art History
- ARH 474 Senior Seminar II
- ART 394 Directed Learning  in Art
- ART 444 Independent Study in Art
- ART 474 Senior Seminar II & Senior Exhibit
- +++MISSING INFO: c.at40.long +++   (*successful completion of sequence of AT-20/-30 and -40 required to receive full credit*)
- BIO 115 Marine Biology
- BIO 444 Independent Study
- BIO 454 Research Participation
- BIO 462 Advanced Research Lab I
- BUS 444 Ind Study-Bus Admin
- BUS 454 Research in Business
- CHM 444 Independent Study Chemistry
- CHM 454 Undergraduate Summer Research
- COM 394 Directed Learning  in Communication
- COM 444 Independent Study in Comm Studies
- CRW 112 Advanced Literary Magazine Editing
- CRW 394 Directed Studies in Creative Writin
- CRW 492 Manuscript Workshop
- CS 444 Ind Study-Comp Sci
- CS 454 Research in Computer Science
- DS 444 Independent Study in Data Science
- DS 454 Research in Data Science
- ECO 444 Ind Study-Economics
- ECO 454 Research in Economics
- EDU 215 Practicum in Education
- EDU 481 Stu Tchg Sec: ART
- EDU 482 Stu Tchg Sec: Phys Education
- EDU 483 Std Teaching Elem: ART
- EDU 485 Std Teaching Elem: Phys Ed
- EDU 489 Student Teaching Sr HS
- EDU 490 Student Teaching Jr HS
- EDU 491 Student Teaching 4-6
- EDU 492 Student Teaching K-3
- EDU 444 Ind Study-Tchr Ed
- ENG 394 Directed Learning in English
- ENG 454 Honors Research
- FLM 442 Independent Study in Film
- FLM 464 Seminar in Film II:  (0.5 cc) and FLM 474 Senior Seminar II in Film & Senior (0.5 cc)
- FRE 394 Directed Learning  in French
- FRE 444 Ind Study-French
- HIS 444 Ind Study-History
- KIN 444 Ind Study-KIN
- MTH 444 Ind Study-Math
- MTH 454 Research in Mathematics
- MU 421 Student Teaching Elementary Music
- MU 422 Student Teaching Secondary Music
- MU 444 Ind Study-Music
- MUA 490 Senior Recital
- NUR 444 Ind Study-Nursing
- NUR 455 Leadership & Cont Issues in Nursing
- PHL 394 Directed Learning in Philosophy
- PHL 444 Ind Study-Philos
- PHL 490 Philosophy Colloquium (0.0 cc)
- PHY 255 Advanced Laboratory I
- PHY 355 Advanced Laboratory II
- PHY 444 Ind Study-Physics
- POL 444 Ind Study-Pol Sci
- PSY 354 Research Participation
- PSY 444 Ind Study-Psychology
- PSY 455 Advanced Experimental Psychology
- REL 394 Directed Learning in Religion
- REL 444 Ind Study-Relig
- RHE 394 Drtd Learning in Writing & Rhetoric
- RHE 444 Independent Study in Writing (WE)
- RHE 490 Publications Practicum
- SCJ 444 Independent Study in Social and Cri
- SOC 365 Research Participation I
- SOC 444 Ind Study-Soc
- SPA 394 Directed Learning: Spanish
- SPA 444 Ind Study-Spanish
- THE 442 Adv Proj-Design/Tech Production
- THE 444 Ind Study-Theatre
- THE 452 Advanced Projects in Acting
- THE 462 Advanced Projects in Directing


