# SPECIAL PROGRAMS AND OPPORTUNITIES

## Clinical Laboratory Sciences/Medical Technology

In cooperation with the St. Luke’s Methodist Medical Laboratories in Cedar Rapids, or upon arrangement with other accredited laboratories and the approval of the College, Coe offers a four-year course leading to a Bachelor of Arts degree and registration as a Clinical Laboratory Scientist/Medical Technologist. 

The first three years are spent in residence at Coe, where candidates must complete all of the requirements for the B.A. degree, including general education requirements and an approved major. The minimum requirements of the Clinical Laboratory Sciences/Medical Technology program in biology and chemistry are five course credits in each field and at least one course in mathematics. The fourth year is a full calendar year spent at St. Luke’s or another accredited medical laboratory approved by Coe. 

The St. Luke’s Hospital Medical Laboratory is approved as a school of clinical laboratory sciences/medical technology by the Committee on Allied Health Education and Accreditation of the American Medical Association. Candidates completing the course are eligible to take the certification examinations of the American Society of Clinical Pathologists and the National Certification Agency and, if approved, may practice anywhere in the United States. 

## Crimson Fellows Program

Steffens, Westberg (Program Directors). 

To graduate as a Crimson Fellow, a student must earn at least a 3.3 cumulative grade point average for all courses taken at Coe College and complete all of the following: 

1. CFP 104 Topics in Crimson Fellows Program (0.2 cc)
2. CFP 205 Introduction to Engaged Scholarship 
3. CFP 301 Communicating Across Disciplines I (0.5 cc)
4. CFP 302 Communicating Across Disciplines II (0.5 cc)
5. CFP 401 Action Research I (0.5 cc)

Applications to the Crimson Fellows Program are accepted and reviewed on a rolling basis.

Completed applications are assessed on ACT/SAT score, the high school transcript, teacher recommendations, and the student essay. Although there are no minimum thresholds, the historical average ACT score has been over 27 with an average high school GPA above 3.70. Emphasis will be placed on the student essay.

- **CFP 104 Topics in Crimson Fellows Program**
  - Reading and discussion of one or more classic texts from across intellectual disciplines. Students are expected to demonstrate mastery of the material and actively engage in class discussions. S/U basis only. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: consent of instructor. (0.2 course credit)
- **CFP 145 CFP: Culture and Revolution**
  - Designed to examine cultures that subsequently undergo revolutionary change. The first part is devoted to giving a sense of the culture that is destroyed by the revolution, and the second part to the forces that lead to the revolution. This course focuses on masterworks in history, political science, philosophy, and literature.
- **CFP 155 Style and Transformation in the Art**
  - Focuses on periods during which the arts undergo a major transformation. The class studies both the artistic ideas that are being changed and the characteristic styles that result from these changes. The scope of this course may include literature, painting, music, and architecture.
- **CFP 175 Continuity &Transition Non-West Soc**
  - Focuses on the great traditions in non-western cultures. By selectively dealing with the major traditions present in such cultures, the class deals with the dynamics of continuity and transition, which are crucial to understanding non-western societies.
- **CFP 184 Topics in Scientific Inquiry**
  - Designed to lead students to an intimate understanding of how the scientific process works and how scientific thought develops. Historical readings and discussions develop students’ understanding of the course topic sufficiently for them to focus on particular scientific questions. Experimental approaches to these questions are discussed and developed into research projects. Results are shared and integrated, providing group members with greater knowledge of the course topic and an acute awareness of the process and limitations of science.
- **CFP 205 Introduction to Engaged Scholarship**
  - Establishes the foundation of the Fellows experience. Fellows write essays on a series of connected subjects designed to encourage critical thinking and reflection. The course includes discussions on education reform ideas, action research, student-driven education, the passion of life-long learning, global citizenship, community advocacy and civic engagement. Grounded in critical pedagogy, the course introduces students to the ideas of
engaged scholarship. Students take command of their own education, developing their sense of agency, selfdiscipline, initiative, and self-direction. Prerequisite: admission to the Crimson Fellows Program or consent of instructor. (Offered Spring Term)
- **CFP 301 Communicating Across Disciplines I**
  - Focuses on developing competencies in communication across multiple audiences and perspectives. Students engage content/material related to their understanding and development of a year-long research project. The central objective of the course is to enhance student collaboration and communication skills. Prerequisite: Introduction to Engaged Scholarship (CFP-100) or consent of instructor. (0.5 course credit)
- **CFP 302 Communicating Across Disciplines II**
  - Students work in multi-disciplinary teams to address a topic of local and/or global social interest. Prerequisite: Communicating Across Disciplines I (CFP-301) or consent of instructor. (0.5 course credit)
- **CFP 401 Action Research I**
  - Students work in multi-disciplinary teams to conduct a year-long project that addresses a specific challenge/issue for a local/regional community partner (e.g. sustainability, water quality, soil degradation, health care, partner violence, refugees, immigration, civil rights, etc.). Faculty provide specific content related to working with community groups/agencies at the onset of the course. Prerequisite: Communicating Across Disciplines II (CFP-302) or consent of instructor. (0.5 course credit)

### Crimson Fellows Projects & Graduating with Distinction

To graduate with Distinction, at the time of graduation a student must have:

1. earned at least a 3.2 cumulative grade point average for all courses taken at Coe College,
2. earned at least a 3.5 GPA (or higher if set higher in the program in which you are pursuing distinction) in the courses taken toward the major or minor in which distinction is sought,
3. earned at least 14 course credits of graded courses at Coe College,
4. satisfactorily completed a Crimson Fellows project in a major or minor,
5. completed the “Graduating with Distinction Form” found on My.Coe and submitted it to the Office of the Registrar no later than March 15 of the Spring Term before graduation,
6. submitted a thesis or project artifact, approved by the majority of the student’s Crimson Fellows Program examining committee, to the Director of Library Services no later than Reading Day of Spring Term.

### Latin Honors 

*Cum laude* is awarded to all graduating seniors with a cumulative GPA of 3.60 or higher. 

*Magna cum laude* is awarded to graduating seniors with a cumulative GPA of 3.80 or higher who have completed an honors project. 

*Summa cum laude* is awarded to graduating seniors with a cumulative GPA of 3.98 or higher who have completed an honors project. 

### Dean’s List 

Special recognition is given to students who show exceptional academic performance during Fall and Spring Terms. The designation “Dean’s List” is awarded a student if, at the end of a given grade reporting period, the student: 

1. was enrolled as a full-time, degree-seeking student; 
2. earned at least a 3.5 GPA for the grading period, having no incomplete marks, no repeat courses, and at least three letter graded courses; and 
3. ranked in the top ten percent of the student body for that grading period. 



## Cross-Registration with Mount Mercy University

This agreement: 

1. Covers only courses that are not offered at Coe College in the same term unless a time conflict exists that cannot be resolved. 
2. Is permitted on a space-available basis two weeks after the regular registration at Mount Mercy.
3. Holds students subject to administrative rules of the host institution for the courses taken.
4. Requires the student to register at both institutions. 
5. Requires that a student be full-time and degree seeking in the term of the request and for at least one previous term at Coe College.

Coe students wishing to enroll at Mount Mercy University may not be on academic probation (see @sec-academic-probation) and may not have been dismissed from Coe College.  Prior to registering, students must submit a cross-registration request form to the Registrar, who grants approval to students wishing to register at Mount Mercy University. If the course is to be counted toward a major or minor, the approval of the appropriate Coe department chair is also required. Declarations of Pass/Not Pass options are made at Coe according to Coe policies. Both course credit and the letter grade given at Mount Mercy are recorded in the student’s permanent record, as well as the fact that the course was taught at Mount Mercy. Under the agreement no additional fees are charged for cross registration, although the sum of the credits registered at both institutions are used to determine full-time status and/or the need to petition to take 5.0 course credits or more. 

A cross-registered student missing a class at a cooperating college because of calendar differences shall not be penalized for missing the class. The student, however, is responsible for making up any work missed in the class. 
Before registering for a course at Mount Mercy under this agreement, a student must complete the Mount Mercy–Coe College Cross Registration Form to be processed to ensure that all stipulations of the agreement are met.


## English As A Second Language Program

Drexler (Director), Welsh.

English as a Second Language (ESL) programs at Coe College are designed to help study abroad and undergraduate international students assimilate into the College and local community through English language instruction.

Coe College offers the following programs: 

- Intensive English Language program (IELP). IELP accepts students whose TOEFL ITP score falls lower than 500. IELP students enroll in 18 hours of English language courses per week for one or two terms. Students who successfully complete IELP may matriculate to the College. 
- English Academic Bridge (ELAB) program. ELAB accepts students whose TOEFL ITP score falls between 500 and 520, the Admission requirement. ELAB students are admitted as undergraduates with the following course requirements for their first term at the College: one ESL course, one Coe-credit course designed for English language learners, First-Year Seminar, and their choice of another Coe-credit course. 
- Short Intensive English Language program (SIELP). SIELP accepts study abroad students for seven weeks during the Spring Term. SIELP students enroll in 18 hours of English language course per week and live on campus. 
- Summer Academic Orientation program (SAOP). SAOP accepts students who intend to study abroad or become undergraduates in colleges and universities in the United States or Canada. SAOP students enroll in 20 hours of ESL courses per week for the first week of August. 

In addition to these programs, Coe international students who are not enrolled in an ESL program may register for ESL courses and work with ESL faculty on a one-on-one basis to support their language needs.

- **ESL 195 Reading Writing Workshop**
  - Strengthens critical reading, academic writing, and reasoning skills by engaging with a variety of texts. Students identify, challenge, and write arguments by practicing summary, analysis, paraphrase, and response to published work as well as work of their peers. May be taken more than once with consent of the program director provided the topics are substantially different. Prerequisite: enrolled in ELAB or undergraduate program with appropriate TOEFL score or consent of instructor.
- **ESL 180 Topics in Listening**
  - Develops academic listening and note-taking skills with a focus on micro listening such as listening for numbers, word stress, thought groups, and accent differences as well as macro listening like listening for headings, transition words and phrases, and distinguishing main ideas from details. May be taken more than once with consent of the program director provided the topics are substantially different. Prerequisite: enrolled in ELAB or undergraduate program with appropriate TOEFL score or consent of instructor.
- **ESL 185 Topics in Speaking**
  - Develops speaking fluency through vocabulary building by using language in authentic contexts and practicing pronunciation by studying language prosody (intonation and rhythm) and morphemes (minimal parts of language). May be taken more than once with consent of the program director provided the topics are substantially different. Prerequisite: enrolled in ELAB or undergraduate program with appropriate TOEFL score or consent of instructor.
- **ESL 190 Topics in Structure**
  - Develops grammar with the goal of using accurate grammar in presentations and written work. Students study various grammar points, practice grammar interactively, and integrate learned grammar into presentations and written work on a wide spectrum of topics. May be taken more than once with consent of the program director provided the topics are substantially different.
- **ESL 210 Seminar in Culture**
  - Develops language skills and explores American culture through texts, art, film, and community engagement. May be taken more than once with consent of the program director provided the topics are substantially different. Prerequisite: enrolled in ELAB or undergraduate program with appropriate TOEFL score or consent of instructor.



## Pre-Professional Programs


### Pre-Law

J. Christensen (Program Director).

The cooperative 3+3 program allows qualified undergraduates from Coe College to earn both a bachelor's degree and a law degree in six years through partnership with the University of Iowa College of Law.

If eligible, students admitted under the 3+3 program will receive three years of financial aid and pay Coe College tuition for the first three years. Qualified undergraduates from Coe must have satisfied all graduation requirements with the exception of the 32-course credit requirement by the conclusion of their junior year for admission into the College of Law. Students are not eligible for campus housing or extracurricular activities at Coe during their fourth year. During the fourth year of the program, which is the first year of law school, students will pay tuition only to Iowa Law and apply for financial aid through the University of Iowa. Credits earned during the first year of law school at Iowa, which would have been their senior year at Coe, will also apply to their undergraduate degree to complete the final credit requirements at Coe. At the end of their fourth year of study, students in the program will receive their bachelor's degree from Coe College, while also having a year of law school completed at the University of Iowa College of Law.

There is no prescribed curriculum for students intending to enter law school after graduation. Law schools report that their most successful students are those who have acquired a broad academic background in the liberal arts, developed a capacity for logical analysis, and mastered the ability to write clearly. 

Study in one or several of a variety of disciplines will prepare students to undertake legal training. Students interested in law should consult their department advisor and the pre-law program director.

### Health Professions

Storer (Program Director). 

Coe’s program for those interested in the health professions, such as medicine and dentistry, is a flexible one based on the requirements of the health professions’ schools. Students interested in a health profession usually major in one of the sciences, but all majors offered by the College are acceptable. 

### Professional School Degree Completion Plan 

Students who complete three years of coursework at Coe (24 course credits), including general education and area of study requirements, and who enter a college of architecture, engineering, or a physical therapy program, can receive a baccalaureate degree from Coe. Required for satisfactory completion of this program are (1) approval of the program by the Provost and Dean of the Faculty before transferring to the professional institution and (2) one year of full-time acceptable study there.  

### Cooperative Degree Program With The University Of Iowa’s College Of Public Health

This combined undergraduate and graduate 5-year program allows students to earn a Bachelor of Arts degree from Coe College and a Master of Public Health (MPH) degree from the University of Iowa.  This program is available to students electing any undergraduate major offered by Coe.  The first four years in the program are spent in residence at Coe College.  Interested students take one University of Iowa undergraduate course in the spring of their second year (*Fundamentals of Public Health*).  In their third year, students take the GRE and apply to the Master’s program in Public Health.  If accepted, the student completes up to four graduate-level MPH courses during the fourth year at Coe College (*Introduction to Biostatistics, Introduction to Health Promotion and Disease Prevention, Global Environmental Health, and/or Epidemiology*). UI Public Health courses are accepted in transfer to Coe College as elective credit.  
