# OFF-CAMPUS STUDY

The College endorses a wide variety of off-campus experiences for students. Coe strongly believes that students can benefit from study in Washington, New York, and the Wilderness Field Station, as well as in programs around the world. 

Numerous domestic and international study programs are available to Coe students. The four programs sponsored by Coe College are Asia Term, New York Term, Washington Term and Wilderness Field Station courses.  In addition, programs are offered by the Associated Colleges of the Midwest (ACM) and others, including several exchange programs, by colleges, universities, and educational agencies in America and abroad. Students who wish to study off-campus on Coe’s sponsored programs must apply to the individual program’s director. Student proposals to study on exchange programs must be submitted to the Director of Off-Campus Studies at least six weeks before the end of the term just prior to the off-campus experience.  Student proposals to study on all other off-campus programs must be submitted to the Director of Off-Campus Studies by the last day of classes of Fall Term of the academic year prior to the program. 

Credits earned on off-campus programs are applied toward graduation on the same basis as credits earned on campus. Any academic credit earned from programs not sponsored by Coe may be transferred back to the College in accordance with the College’s general policy on transfer credit. Application is open to sophomores, juniors, and seniors who have a minimum 2.25 GPA at both the time of application and of enrollment for the off-campus study.  

NOTE: *International students may not receive Coe College financial aid for off-campus study outside the U.S.*

## Domestic Programs

### New York Term

Carson (Program Director)

The New York Term is open to all students who meet the basic requirements for off-campus study. Offered in odd-numbered years in the Spring Term, this program provides abundant opportunity for experiences in the performing and visual arts, as well as internship opportunities for students from any major. 

The central course, Fine Arts in New York City (NYT-250), which includes attendance at concerts, theatre, and dance productions as well as tours to art exhibits and film screenings, consists of five 0.4 credit courses: art, music, theatre, dance, and film. A faculty member for each area grades the respective course. An internship (or other project approved in advance by the College) completes the program.

There is an extra fee for New York Term. All Coe financial aid applies, and students are eligible to apply for additional financial aid based on the additional costs of the term. (See p. 72 for descriptions and course offerings.)

### Washington Term 

B. Nesmith (Program Director).

The Washington Term is open to all students who meet the basic requirements for off-campus study. Students accepted for Washington Term spend Fall or Spring Term in the nation’s capital. Washington provides an unusual opportunity to study national politics and government and to enjoy a variety of cultural activities in the fine arts.  (See p. 75 for descriptions and course offerings.)

### Wilderness Field Station

Ellis (Program Director).

The Coe College Wilderness Field Station, located on remote Low Lake in Minnesota’s Superior National Forest, offers students a unique and unparalleled opportunity for off-campus study. Courses take advantage of the serene surroundings for field observation, wilderness study, and outdoor learning. Biology courses are at the heart of the field station and often include aquatic biology, animal behavior, ornithology, and behavioral ecology of vertebrates. Students use the base camp’s laboratories, herbarium, and library to supplement their field work. Non-science electives, such as nature writing and wilderness and the law, are also offered. There is an independent study option as well. Participants take one course during a four-week session. 

The program runs from mid-June to mid-July, mid-July to mid-August, or both. Each course is limited to eight students. Each course offered at the field station is one course credit. Particular courses satisfy lab science and other general education requirements and can be used as major elective credits. Any course taken at the field station satisfies the College’s practicum requirement. The regular application deadline is March 1st; the final deadline is April 15th, with rolling applications after that date. For more information and application materials, visit The Field Station Webpage: www.coe.edu/academics/coe-difference-centers-and-programs/off-campus-study/wilderness-field-station.


## ACM \& International Programs

Coe offers opportunities to study in locations around the world. Some programs are for students wishing to broaden their liberal arts perspectives, while others allow intensive research and study in a specific academic area. Although some programs provide grades in the courses, all grades transfer back to Coe as P/NP. For detailed information and applications, students should contact directors for each program or visit http://www.acm.edu/off_campus_study/index.html.

### OCC-350 — Japan Study

Nordmann (Program Director).

Students study at Waseda University’s School of International Liberal Studies in Tokyo after a brief orientation providing intensive language practice and cultural discussions. In addition to required language study, electives may be chosen from a wide range of Asian studies courses taught in English. A family living experience in Tokyo provides an informal education in Japanese culture and is in many ways the dominant feature of the program, offering total immersion in the Japanese way of life. The program is recommended for a full year of study, although students usually cannot receive Coe gift aid for more than one term. The full-year program includes a month-long cultural practicum or internship in another region of Japan, usually in February or March. Administered by Earlham College, Japan Study is recognized by both ACM and GLCA. Learn more at http://www.acm.edu/programs/8/japan/index.html.

### OCC-360 — Newberry Seminar: Research in the Humanities

Swenson Arnold (Program Director).

Students in the Newberry Seminar do advanced independent research in one of the world’s great research libraries. They join ACM and GLCA faculty members in close reading and discussion centered on a common theme, and then write a major paper on a topic of their choice, using the Newberry Library’s rich collections of primary documents. The Fall Seminar runs for a full term; the Spring Seminars are month-long. Students live in Chicago apartments and take advantage of the city’s rich resources. The Newberry Seminar is for students looking for an academic challenge, a chance to do independent work, and possibly planning to attend graduate school. Administered by ACM, the Newberry Seminar is also recognized by GLCA. Learn more at http://www.acm.edu/programs/14/newberry/index.html.

### OCC-325 — Field Museum Semester: Research in Natural History

Hughes (Program Director).

An intensive research-and class-based experience for upper-level students interested in natural history research with a background in evolutionary biology, anthropology, or related discipline.  The program provides the opportunity for students to explore scientific research and the Field Museum collections through a substantive internship, a course taught by the visiting Faculty Director, and a seminar led by Field Museum professional staff.  See ACM website for more information (https://acm.edu/students/off-campus-study-programs/field-museum-semester-research-in-natural-history/).

### OCC-365 — Oak Ridge Science Semester

St. Clair (Program Director).

The Oak Ridge Science Semester is designed to enable qualified undergraduates to study and conduct research in a prestigious and challenging scientific environment. As members of a research team working at the frontiers of knowledge, participants engage in long-range investigations using the facilities of the Oak Ridge National Laboratory (ORNL) near Knoxville, Tennessee. The majority of a student’s time is spent in research with an advisor specializing in biology, engineering, mathematics, or the physical or social sciences. Students also participate in an interdisciplinary seminar designed to broaden their exposure to developments in their major field and related disciplines. In addition, each student chooses an elective from a variety of advanced courses. The academic program is enriched in informal ways by guest speakers, departmental colloquia, and the special interests and expertise of the ORNL staff. Administered by Denison University, Oak Ridge Science Semester is recognized by both ACM and GLCA.
Learn more at http://www.acm.edu/programs/15/oakridge/index.html.

## Asia Term

Nordmann (Program Director).

The Asia Term is open to all students who meet the basic requirements for off-campus study. Usually offered in the Spring Term, this program provides students an opportunity to experience a variety of Asian cultures in such countries as Thailand, Vietnam, and Cambodia.  At each site, students study language, read works in English about the culture, engage in service learning, and work with students at the host universities to gain a functional understanding of how each culture works.  Students are accompanied to Asia by Coe faculty members.

Students take four credits of coursework, typically one credit of Asian Tonal Languages, one credit of Asian studies, and two credits of independent study.  In some iterations of the program, students take an elective course in art, English, history, sociology, education, or another discipline, depending on the field of the instructor leading the program, and one credit of independent study.  (See p. 70 for descriptions and course offerings.)

## Exchange programs

Coe College sponsors a number of programs with cooperating foreign universities, offering Coe sophomores, juniors and seniors each year the opportunity to study in a foreign setting. Coe College accepts in return junior-level students from the foreign institution. Applications of the recommended students are sent to the host institution, with the host reserving the right to admit or reject each student nominated. 

Any student who applies for one of these programs must have completed at least one year of continuous study at their home institution. Students may apply to any appropriate academic program offered at the host institution as full-time, non-degree seeking, or unclassified students. Any academic credit earned at the host institution is transferred back to the home institution in accordance with the rules of that institution. The length of stay may not exceed one academic year. Upon completion of the time period specified at the host institution, the participating students must return to their home institution. Any extension of stay must be approved by both cooperating institutions. The exchange student must abide by all rules and regulations of the host institution. 

An exchange student must register and pay tuition and required fees at his or her home institution. In return, the student receives a tuition waiver at the host institution. The host institution helps arrange the necessary visa documents and also provides appropriate advising and other assistance to the incoming students from Coe College. Please see individual program descriptions for information regarding housing costs. The host institution assists in finding housing on the foreign university campus; Coe College assists in finding residence housing for students from the foreign university. At the end of the school year, the host institution submits to the home institution and official transcripts of grades and credits earned. Grades from exchange programs transfer to Coe as P/NP.

Beyond tuition and fees, the participating student is responsible for the following expenses: meal expenses; transportation to and from the host institution; medical insurance and/or medical expenses; textbooks, clothing, and personal expenses; passport and visa costs; and all other debts incurred during the course of the year.


### OCC-205 — Coe/Kongju National University (South Korea)

Nordmann (Program Director).

Course offerings in Business, Economics, and Asian studies.  Students pay the cost of living at the destination.  Credits earned from the Kongju exchange program are evaluated on a P/NP basis. 

### OCC-210 — Coe/Chiang Mai University (Thailand) 

Chaimov (Program Director).

Coe students usually pursue an independent research project based on prior study in Thailand, as CMU offers no courses in English.  Students pay cost of living at destination.

Credits earned from the Chiang Mai exchange program are evaluated on a P/NP basis. 

### OCC-213 — Coe/Rangsit University (Thailand) 

Chaimov (Program Director).

Rangsit University. Coe students are responsible for securing their own accommodations. Rangsit University offers English language bachelor’s degree programs in communications, international business, and international political economy.  Students pay cost of living at destination.

Credits earned from the Rangsit University exchange program are evaluated on a P/NP basis. 

### OCC-215 — Coe/Mid Sweden University (Sweden) 

Carstens (Program Director).

Courses in English are available in such areas as business, social sciences, and environmental studies.  Students pay cost of living at the destination.  Credits earned from the Mid Sweden exchange program are evaluated on a P/NP basis. 

### OCC-220 — Coe/Nagoya-Gakuin University (Japan) 

Nordmann (Program Director).

One year of Japanese language study is recommended for students applying for this program.  Exchange students from Coe pay room expenses at Coe College. In return, students receive a room expense waiver. Other costs of living are paid at Nagoya-Gakuin University. Credits earned from the Nagoya-Gakuin exchange program are evaluated on a P/NP basis. 

### OCC-225 — Coe/Northern Ireland Scholars Program (Northern Ireland, UK)

Farrell (Program Director).

Students with a high GPA may be selected to study at one of several universities in Northern Ireland, including Queens University Belfast and the University of Ulster. Applications for this consortial exchange are due in December of the year before study.  Students pay cost of living at destination.

Credits earned from the Northern Ireland exchange program are evaluated on a P/NP basis.

### OCC-230 — Coe/University of Jaume I (Castello, Spain) 

Rodríguez Moreno (Program Director).

Courses in Spanish in a wide range of topics. Students pay cost of living at destination.  UJI requires Coe students to have completed two Spanish courses at Coe.  Spanish language courses are available for an extra cost.

Credits earned from the Jaume I exchange program are evaluated on a P/NP basis. 

### OCC-235 — Coe/Sookmyung University (South Korea) 

Nordmann (Program Director).

Courses offered in English on areas including the arts, linguistics, international studies, business, biology, and political science. Students pay cost of living at destination.  Credits earned from the Sookmyung exchange program are evaluated on a P/NP basis. 

### OCC-240 — Coe/University of Landau (Germany) 

Chaimov (Program Director).

Courses in English are available in, art, English literature, linguistics, other topics. Also, a wide range of subject areas taught in German. Students pay cost of living at the destination.

Credits earned from the Landau exchange program are evaluated on a P/NP basis. 

### OCC-245 — Coe/University of Quebec (Saguenay, Canada) 

Janca-Aji (Program Director).

Courses in French are offered in a wide range of topics for students who pass a proficiency test in French.  Students pay cost of living at destination.  Credits earned from the Quebec exchange program are evaluated on a P/NP basis. 

### OCC-250 — Coe/Izmir Institute of Technology (Turkey) 

Akgun (Program Director).

Coe may send a student of Chemistry and a student of Physics to study those subjects in an English-language setting at a science university in Turkey. Students are responsible for housing, food, and all other costs of living.

Credits earned on the Izmir exchange program are evaluated on a P/NP basis.

### OCC-255 — Coe/Polytechnic University of Upper France (France) 

Janca-Aji (Program Director).

Students choose from courses in English on business, communications, and marketing or a wide range of courses in French. Students pay costs of living at the destination.  Credits earned from the France exchange program are evaluated on a P/NP basis. 

### OCC-260 — Coe/National University of Villa Maria (Argentina)

Students with a good command of Spanish can take courses in Spanish in a wide range of areas, including literature, rural development, social sciences, environmental studies, communication, and computer science. Students pay costs of living to Coe before departure and must transfer at the same time as an incoming student from UNVM.

Credits earned on the Argentina exchange program are evaluated on a P/NP basis.

### OCC-265 — Coe/Istanbul Altinbas University (Turkey)

Duru (Program Advisor)

Teaches entire majors in English in psychology, sociology, international relations, political science, economics, business.  Students pay cost of living at the destination.  Credits earned from the Altinbas exchange program are evaluated on a P/NP basis.

### OCC-270 — Coe/Ashesi University (Ghana)

Eichhorn (Program Director).

Courses in African studies (sociology, anthropology, political science, history, arts), computer science, business. Coe students pay room and board expenses at Coe College and receive a waiver of these expenses in Ghana. They must exchange at the same time as an Ashesi student.

Credits earned on the Ashesi exchange program are evaluated on a P/NP basis.

### OCC-275 — Coe/University of Salford (England)

Kuennen (Program Director).

The University of Salford offers courses in business, contemporary European history, psychology, and many other areas.  Students pay cost of living at the destination and must arrange their own housing.

Credits earned from the Salford exchange program are evaluated on a P/NP basis. 

### OCC-285 — Coe/University of Neuchatel (Switzerland)

Janca-Aji (Program Director).

Coe students take courses at the Institute of French Language and Civilization.  Students pay costs of living at the destination. Credits earned from the Neuchatel exchange program are evaluated on a P/NP basis. 

### OCC-290 — Coe/Jinan University (China)

Nordmann (Program Director).

Located in southern China, this international university offers courses in English in international economics and business, journalism, computer science, and Chinese studies as well as the study of Chinese language.  Students pay costs of living at the destination.

Credits earned from the Jinan exchange program are evaluated on a P/NP basis.

### OCC-291 — Coe/Istanbul Kultur University (Turkey)

Duru (Program Advisor).

Offers English curriculum in psychology, business, economics, international relations, and other areas.  Students pay costs of living at the destination.  Credits earned from the Istanbul Kultur University exchange program are evaluated on a P/NP basis.


