# EFFECTIVE CATALOG

Students ordinarily are graduated under the provisions of the catalog of their matriculation date. A student’s matriculation date is the day of first enrollment following admission. If the student is readmitted, the matriculation date becomes the day of first enrollment following readmission. However, students will be expected to satisfy, to the extent practical, the graduation requirements of the catalog in effect at the anticipated date of graduation. Any necessary modification of general degree requirements will be worked out by the Provost and Dean of the Faculty, the Registrar, the appropriate department chair, and the Academic Policies Committee. Modification of major or minor requirements will be worked out by the department chair involved, the Registrar, and the student’s advisor. A student has the right of petition to the Committee on Petitions.

### Grading

**GRADES**

|    |                                   |                                    |
|----|-----------------------------------|------------------------------------|
| A  | Excellent                         | 4.0 grade points per course credit |
| A- |                                   | 3.7 grade points per course credit |
| B+ |                                   | 3.3 grade points per course credit |
| B  | Above average                     | 3.0 grade points per course credit |
| B- |                                   | 2.7 grade points per course credit |
| C+ |                                   | 2.3 grade points per course credit |
| C  | Satisfactory, minimum expectation | 2.0 grade points per course credit |
|    | credit                            |                                    |
| C- |                                   | 1.7 grade points per course credit |
| D+ |                                   | 1.3 grade points per course credit |
| D  | Passing, below expectation        | 1.0 grade points per course credit |
| D- |                                   | 0.7 grade points per course credit |

### Status Marks
 
- **W**	Approved withdrawal from a course. 
- **X**	Course extends beyond term.  An “X” status grade is given in courses designated in the Catalog as having coursework that extends beyond the end of the term.  Under no circumstances can an “X” grade remain unresolved for more than one calendar year.
- **O**	No mark had been reported by the instructor by the time academic reports were processed. 
- **I**	Incomplete. An “I” status grade is reported only for students who are unable to complete the work in the course due to extenuating circumstances.  The normal length of time for resolution of an incomplete is within four weeks of the next Fall or Spring term in which the student enrolls.  If the instructor believes the resolution of the incomplete will take longer, the instructor will note the later deadline when reporting the incomplete status grade.  An unresolved incomplete will automatically become a failing grade after the deadline, unless the instructor notes otherwise when reporting the incomplete.  Under no circumstances can an “I” grade remain unresolved for more than one calendar year.
- **R**	The prefix “R” to a grade (i.e., RA, RB, RC, RD, RF) indicates a grade of repeated course. A student may repeat a course previously taken, and registration must indicate this repeat. Failure to register for a repeat course properly results in no recognition of the second attempt. Only the grade earned when the course is retaken is used in computing the GPA. Credit may be earned only once for a given course. Courses may be repeated only once, although, students may petition for a second repeat if extenuating circumstances exist. 
- **EQ**	Equivalent credit recognized; no credit given. Does not increase courses attempted. For a student who has completed four course credits of student teaching and who has high school or life experience equivalent to a regular catalog course, the said course, upon recommendation of the Education chair and the chair of the department in which equivalent credit is being recognized, may be listed on the student’s transcript with the appropriate credit and a status mark of “EQ.” 


### Audited Courses 

Students may audit courses with the consent of the instructor. In doing so, they attend class but are not required to take tests or submit papers. Audited courses receive no credit and do not appear on transcripts. Auditors pay a reduced tuition charge. 

### First Course Grading For Non-Traditional Students 

Individuals who have been away from the collegiate routine for several years may register on an audit basis in their first course, participate fully in the class (including tests, papers, etc.), and decide at the conclusion of the course if they wish to pay the other half of the tuition and receive credit for the course. This policy applies only to the first course—not to succeeding courses. 

### Pass / Not-Pass Graded Courses 

Courses are graded A–F unless otherwise indicated in the course description that only P/NP is an option (e.g., student teaching, internships).  Courses graded P/NP count as credits towards graduation but do not affect the student’s GPA. In addition, students may opt to take up to four A–F graded courses on a P/NP basis.  When students opt for P/NP grading, the Office of the Registrar converts any grade a faculty member provides of D- or better to a P, and any grade of F to an NP. In order to count for Writing Emphasis credit, a submitted grade of C or higher must be earned.

The following regulations apply: 

1. Students are permitted to change the method of grading for a course from a letter grade to P/NP.  This change is allowed from the start of the term of enrollment through the last day to withdraw from courses during that term. See Academic Calendar Section 3.0.1 for official dates.
2. Students may elect to take up to four graded courses during their undergraduate career on a P/NP basis. However: 
    a. Students cannot use a course for which they elected P/NP grading to satisfy the requirements for a major or minor. 
    b. Students cannot elect P/NP grading while on academic probation, though provisionally-admitted First Year students are allowed the option of P/NP grading. 
3. The Registrar will not inform the instructor of the student’s request for P/NP grading and the instructor must provide the Registrar with an appropriate letter grade. 
4. A student’s request for P/NP grading may be nullified at any time before the end of the third business day after grades are due in the student’s final term.  A written notice must be sent to the Office of the Registrar to communicate the student’s intent to replace the P or NP grade with the instructor’s letter grade. 
5. A student’s request to change their method of grading to P/NP in lieu of a letter grade counts as one of the four P/NP elected courses during the student’s undergraduate career, regardless of whether it is later nullified. 
6. Ordinarily a student is limited to one course credit per term on an elected P/NP basis.  A student wishing to exceed this limitation must present a convincing rationale or significant mitigating circumstances to the Committee on Petitions. 

### Midterm Grades 

Midterm grades are not official evaluations and are not part of the official transcript. The goal of midterm grades is to help students take responsibility for their academic progress. Faculty submit midterm grades of A-F for students in all full-term courses. Midterm grades are not intended to be a guarantee, promise, or contract regarding the final grade a student will earn in the class. Instead they provide information for students about their academic performance.


