# ACADEMIC INTEGRITY POLICY

At Coe College, we expect academic integrity of all members of our community. Academic integrity assumes honesty about the nature of one’s work in all situations. Such honesty is at the heart of the educational enterprise and is a precondition for intellectual growth. Academic dishonesty is the willful attempt to misrepresent one’s work, cheat, plagiarize, or impede other students’ academic progress. Academic dishonesty interferes with the mission of the College and will be treated with the utmost seriousness as a violation of community standards. 

### Forms of Academic Dishonesty 

Cheating is the attempt to deceive an evaluator by claiming credit for work one has not done or by knowingly assisting such an attempt. It includes (but is not limited to) the use of unauthorized sources of information on in-class or take-home exams, or other assignments; copying from other students on exams, assignments, or lab reports; fabrication of data, research, quotations, or other information; and taking credit for collaborations to which one has not contributed. 

Plagiarism is the use of someone else’s words or ideas without acknowledgement and, when intentional, is a form of academic dishonesty. The unacknowledged use of words or ideas from any published or unpublished sources, including Internet resources or other student papers, constitutes plagiarism. Plagiarism may occur intentionally or unintentionally through the omission of appropriate citations. Any ideas or information the student adopts from a source, whether or not directly quoted, must be acknowledged by specific reference in notes or the text. 

Any words or phrases that are taken from a source must be quoted and cited. Any paraphrase—the restatement of an idea in your own words—must be cited. 

The methods of citation and documentation vary from discipline to discipline. Students are responsible for determining the appropriate method for any given assignment or, in the absence of a clearly stated protocol, using any accepted academic method. Guidelines can be found on the library website and in the Writing Center. 

Other forms of academic dishonesty include (but are not limited to) deliberately impeding other students’ work and misuse of common academic property, in the libraries, labs, and elsewhere. 

### Sanctions 

Instructors have responsibility for determining whether academic dishonesty has occurred. Instructors shall proceed with sanctions accordingly. Any act of academic dishonesty that results in one of the sanctions below shall be detailed in a formal report filed with the Provost and Dean of the Faculty. 

Cases of unintentional plagiarism may be dealt with through educational procedures such as further assignments requiring the student to practice documentation and citation methods, or other means determined by the instructor. 

Acts of academic dishonesty will be subject to one or more of the following sanctions:

1. failure of the assignment, i.e. exam, paper, lab report, etc. 
2. failure of the class 
3. suspension or expulsion 

An instructor may impose the first two of these penalties. Suspension or expulsion may only be carried out by the Provost and Dean of the Faculty. 

Repeated acts of academic dishonesty will result in suspension or expulsion. When academic dishonesty has been determined to have occurred a second time, the Provost and Dean of the Faculty shall decide on the student’s status at the College. 

### Procedure

When an instance of academic dishonesty is suspected, the instructor will meet with the student to discuss the incident and will decide which, if any, of the above sanctions is appropriate. 

If warranted, the instructor will send a report to the Provost, with a copy given to the student, which details the nature of the violation and the steps taken to address it.   The Provost will send a letter to the student within ten business days of receipt of the faculty member’s report. The letter will reiterate the incident, describe the sanctions, and inform the student of their right to appeal. The report and letter from the Provost will remain on file in the Academic Affairs Office until five years after the student’s graduation or severance from Coe. The Vice President for Student Life will be notified that a report has been filed. Information in the file will be confidential, to be shared only at the discretion of the Provost and Dean of the Faculty for a legitimate educational or legal purpose. 

### Appeals Process

The student may appeal the charge and/or the sanction within ten business days of receiving the Provost’s letter of notice by emailing the Provost and Dean of the Faculty requesting an appeals hearing. Students wishing to appeal are strongly encouraged to consult with the Director of Academic Achievement, who has been designated by the College to provide information and advocacy in these matters. 

The Provost’s Office will convene an Academic Integrity Appeals Board within ten business days of receipt of the request for appeal to hear the appeal. The Academic Integrity Appeals Board will be chaired by either the chair or co-chair of the Academic Policies Committee. Additional members of the board will include: one additional faculty member on the Academic Policies Committee, the senior Student Life officer, one faculty member from the Committee on Admission, Retention, and Enrollment, and the Associate Dean for Student Academics.  In any hearing the Provost may replace the Associate Dean for Student Success, or other member of the board to avoid conflicts of interest. The student may choose to have a faculty or staff member present as an observer. The student and the instructor will each appear as witnesses and each may request that other pertinent witnesses appear. 

A majority vote of the Appeals Board is necessary to uphold or overturn a sanction. If a sanction is overturned, the Appeals Board may impose a lesser sanction. The Appeals Board will submit a written finding which will be sent to the student and the faculty member(s) involved in the case and which will become part of the student’s file. If the appeal’s outcome is to overturn the dishonesty charge, the report in the Academic Affairs Integrity file will be removed.
