# ACADEMIC STANDING {#sec-academic-standing}

All students are expected to meet the College’s standards for academic performance (see chart below). These are in place to keep students on track towards meeting the graduation requirements of the college (32 credits with a cumulative GPA of 2.0). Students who do not meet Coe’s academic standards may be put on probation or suspended from the College.

To make sure that students are aware when their academic standing is in jeopardy, a series of communications are issued throughout an academic term including D/F notices, academic warnings, and notices of academic probation. Unless otherwise stated, these communications will be sent to the student by email and by a letter to the student’s Coe mailbox. Additionally, an email will be sent to the student’s advisor.

### D/F Notices

Academic notices are issued at midterm to students who earn a D, F, or NP in one or more courses. Students receiving these notices are expected to meet with their academic advisor to identify appropriate support.

### Academic Warnings {#sec-academic-warnings}

Academic warnings will be issued to students who earn a term grade point average below 2.00. Students receiving academic warnings are strongly encouraged to re-evaluate their current approach to their studies and/or their academic plans. They are expected to meet with their academic advisor and/or a Learning Commons staff member.

### Academic Probation {#sec-academic-probation}

The Academic Standing Committee reviews academic records of all students at the conclusion of both the Fall and Spring Terms. A student is placed on academic probation if the cumulative GPA falls below the minimum GPA levels listed below:

| **Total Course Credits Attempted** | **Minimum GPA Levels** |
|------------------------------------|------------------------|
| 0.0 – 4.99                         | l.50                   |
| 5.0 – 7.9                          | l.75                   |
| 8.0 – 11.9                         | 1.80                   |
| 12.0 – 15.9                        | 1.90                   |
| 16.0+                              | 2.00                   |

To return to good standing and be removed from academic probation, a student shall earn a cumulative GPA greater than the threshold for academic probation as specified above. If the student’s cumulative GPA decreases at the end of any term on probation, the student is subject to academic suspension. Students who are placed on academic probation have a maximum of two (2) consecutive terms, excluding May and Summer, to return to good standing before they are subject to academic suspension.

Students who are on academic probation:

- Are expected to comply with any requirements outlined by the Academic Standing Committee.
- May not elect P/NP grading in lieu of a letter grade.
- May not be excused from attending class to participate in extra-curricular activities.

The status of academic probation is noted on a student’s transcript.

Students on probation who are not meeting the conditions of their probation and not performing at a passing level in their courses may be withdrawn from the College during the term on the recommendation of the Academic Standing Committee. If the student had previously appealed a suspension, the suspension is reinstated. Otherwise, the student will exit the College with a leave of absence and is eligible to return on probation the following term. Students may appeal this decision to the Provost.

### Academic Suspension {#sec-academic-suspension}

Students who do not meet the conditions of their academic probation or who fall below retention thresholds (see below) will be considered for academic suspension by the Academic Standing Committee, and, if suspended, will be unable to take courses at Coe College for a period of at least one academic year. (One academic year is defined as a Fall and Spring Term, and does not count May or Summer Terms.) A registration hold preventing registration will be placed on the student’s account. A student already registered for the following term will be dropped from those courses.

| **Total Course Credits Attempted** | **Minimum GPA Levels** |
|------------------------------------|------------------------|
| 0.0 – 4.99                         | 0.50                   |
| 5.0 – 7.9                          | l.00                   |
| 8.0 – 11.9                         | 1.50                   |
| 12.0 – 15.9                        | 1.70                   |
| 16.0 – 19.9                        | 1.80                   |
| 20.0 – 23.9                        | 1.90                   |
| 24 +                               | 2.00                   |

Students who are placed on suspension for academic reasons will receive a letter notifying them of their suspension at their home residence, by registered mail, as well as a letter in their Coe mailbox and an email to their Coe email. Suspended students have the right to appeal for immediate readmission if they can provide evidence of circumstances that would warrant reconsideration by the deadline indicated in their suspension letter.

To appeal for immediate readmission:

- A suspended student appealing for readmission must submit an appeals letter by mail, email, or delivery in person to the Office of the Provost. The letter must include an explanation of any circumstances that affected the student’s academic performance. The letter should provide a detailed plan with specific actions that the student will take to improve their academic standing, and explain how the student will overcome the obstacles that affected their academic performance. Student appeals will not be considered if a written statement is not received by the deadline.
- Although not mandatory, the suspended student appealing for readmission is urged to schedule to meet with the Academic Standing Committee on the date designated in the suspension letter. At this meeting the student will have the opportunity to respond to questions the Committee may have on the circumstances outlined in the student’s letter requesting readmission.
- A suspended student appealing for readmission is encouraged to request a letter of support for immediate readmission from a faculty advisor or other faculty or staff member at Coe, if the letter can shed light on the student’s ability and motivation to do well in future academic endeavors. Similarly, the student is encouraged to consult with one or more faculty or staff members to prepare a strong case for readmission.

Students who have been suspended for academic reasons from the College once, can return to the College either through a successful appeal for immediate readmission or through readmission after leaving for at least one academic year. A student who is suspended for academic reasons more than once cannot appeal for immediate readmission and must leave the College for at least one academic year.


### Interim Suspension {#sec-interim-suspension}

Interim Suspension is a situation where it is determined that a student’s continued presence at the college constitutes an immediate threat of harm to the student, other individuals, or to the stability and continuance of normal College functions.  The Provost and Dean of Students or their designee may suspend a student pending disciplinary proceedings. Such suspension may become effective immediately and without prior notice. 
 
Interim suspension shall be considered an excused absence until the conclusion of formal hearings.  The student will be offered the opportunity to make up any academic work missed during the time in which the interim suspension was imposed. It is the student’s responsibility to make specific arrangements with faculty members to complete academic work. The Dean of Students will initiate communication with the appropriate faculty.

### Readmission Following Suspension {#sec-readmission-following-suspension}

Coe College’s academic suspension policy allows students, who are not readmitted immediately through appeal, to apply for readmission after at least one academic year has passed.

To be considered for readmission, the student must submit a letter of appeal to the Office of the Provost. In the appeals letter, the student must present evidence that demonstrates how the circumstances that led to the student’s academic suspension have been addressed, and how the student plans to be successful in his or her academic future. Readmission is determined by the Academic Standing Committee. The Academic Standing Committee reserves the right to conduct its own investigation, review the case, and make a final decision concerning the student’s reinstatement to the College. When appropriate, certain academic stipulations may be applied. If a suspended student provides evidence of successful course completion elsewhere and/or written evidence of motivation and maturity necessary to be academically successful at Coe, the student may be readmitted on probation at Coe.

### Exiting the College {#sec-official-withdrawal-process}

The exit process at Coe College, whether through withdrawing or taking a leave of absence, is initiated by the student. The exit procedure is initiated in the Learning Commons (Stewart Memorial Library) and begins with an interview with the Associate Dean of Student Academics or the Director of the TRIO-Academic Achievement Program.  At the interview, the student is given an official exit form on which to secure signatures from the following: the Student Financial Services Office, to verify a balance due or a credit to be refunded, as well as Student Loan information, to be aware of financial aid adjustments; the Library, to ascertain that all materials have been returned; and the Resident Director of the student’s residence hall, to arrange for room checkout.  The completed exit form is returned to the Learning Commons which will then notify other pertinent areas of the student’s withdrawal.

If a student is unable to complete the official withdrawal process, the intent to withdraw or take a leave of absence can be communicated to one of the following offices: Registrar, Student Financial Services, Student Life.

If a student withdraws from all courses during a period of enrollment for which he or she received financial aid, the Student Financial Services Office will determine how much, if any, of the student’s financial aid proceeds must be returned to the College, based on a federally mandated refund formula (*see Return of Title IV Funds/Institutional Refund Policy, @sec-federal-title-IV-refund-calculation-policy*).

Special consideration is given to students who withdrew due to a call to active duty. Coe’s “Military Call Up/Refund” and “Readmission of Service Member” policies are published on the Admission/Financial Aid webpage. Copies of these policies can be requested from the Student Financial Services Office.

### Leave of Absence

A student may find it necessary to interrupt a program of study at the College. Under this condition, the student may apply for a leave of absence. A leave of absence may be granted for a period not to exceed 12 months. Students may extend a leave of absence for up to a total of 36 months by contacting the Office of the Registrar via email at o-registrar@coe.edu. Students that do not renew their Leave of Absence, or return to Coe, will be officially withdrawn from the College. Coursework completed while on leave from the College is subject to the same conditions as work in transfer. 

### Requesting a leave of Absence

Students planning to leave of absence from the College should consult their academic advisor and then they **must declare** their intent to one of the following designated offices: Student Financial Services, Registrar, Residence Life, or the Learning Commons. Please refer to the previous section on exiting the College for the steps that follow. 

### On Leave of Absence

The Coe community is committed to supporting students while they are away from the College. Thus, the Associate Dean of Student Academics may assign a designee who will be the point of contact to each student on a Leave of Absence. This designee will stay in contact with the student during their time away from the College, as appropriate, and will assist with the return process once the student is ready to resume coursework. 

### Returning to Coe after a Leave of Absence

Students planning on returning to the College do not need to apply for readmission, but must submit a statement of intent to re-enroll to the Office of the Registrar and the Associate Dean of Student Academics, or designee, who will assist with the return process. Students are strongly encouraged to schedule a consultation with the Associate Dean of Student Academics, or designee, by December 1st for returning the Spring Term, or August 1st to return the Fall Term. If a student wants to register during the regular registration time (November for Spring Term or late March / early April for Fall Term), they will need to submit their statement of intent and contact the Associate Dean of Student Academics, or designee, at least two weeks before Registration. The exact date of Registration can be found on the Academic Calendar on the Coe website under the Academics tab. 

### Withdrawal from the College and Readmission

Admission for work toward a degree terminates and the student is considered withdrawn from the College if: 

1. A full-time student does not enroll at Coe for the next term (excluding May Term) and has not completed a Leave of Absence form. This does not apply to students in College-approved off-campus study programs. 
2. A part-time student does not enroll for a course at Coe in a 12-month period and has not completed a Leave of Absence form. 

Students wishing to resume work toward a degree, once admission status has terminated, must apply for readmission.

Students previously enrolled at Coe and readmitted after an absence of two years or more may request that all previous work at Coe be re-evaluated by the Registrar on the same basis as credits offered in transfer. Re-evaluation means that only courses with grades of C or better will be counted for credit toward graduation. All courses affected by the re-evaluation and the grade earned for each course will remain on the student’s permanent record but will not factor into the cumulative GPA or be counted toward graduation.
