# TRANSCRIPT EVALUATION POLICIES

Official transcripts for courses taken at Coe College can only be issued by the Office of the Registrar and only after the office has received a written request and payment from the student.

## General Policy On Transfer Credit

To honor its mission and to preserve its academic integrity as a liberal arts institution, the College accepts a course in transfer for the equivalent earned credit (4 semester hours = 1 course credit), if that course meets the spirit of the College’s mission and is from a regionally accredited institution.  In cases where it is unclear whether the course would be acceptable for transfer credit, the Registrar and the appropriate department chair will consult. Other exceptions are referred to the Committee on Petitions.

## Evaluation Of Credits In Transfer

The Office of the Registrar is responsible for the evaluation of transfer credit. Credits accepted in transfer do not affect the cumulative GPA. Grades for the credits accepted are not recorded on Coe’s transcript. Thus, transfer credits increase only the total courses attempted and the total course credits earned. Credit is not accepted for course work earning a grade below “C” (2.0 on a 4.0 scale).

## Junior or Community College Credit

No more than 50% of the course credits required for a degree at Coe will be accepted in transfer from 2-year colleges.  A maximum of 16 credits will be accepted as transfer credit from 2-year regionally accredited institutions. Transfer students who complete a regionally accredited A.A. degree program or a regionally accredited college-parallel A.S. degree program will be accorded junior status (16 course credits) at Coe. Transfer students who complete an A.A., A.S., or A.A.S. degree from a regionally accredited institution with which Coe has a specific articulation agreement will be awarded credit consistent with that agreement.

## European Credit Transfer System (ECTS)

ECTS credits are a relative rather than an absolute measure of student workload.  They specify how much of a year’s workload a course unit represents at the institution or department allocating the credits. ECTS is thus based on a full student workload and not limited to contact hours only.
In ECTS, 60 credits represent the workload of a normal undergraduate academic year of study and normally 30 credits for a semester and 20 credits for a term. Thus, ECTS credits will normally be transferred to Coe College at a rate of 7.5 ECTS credits: 1 Coe credit.

## Occasional Transfer Credit For Degree-Seeking Students

Degree-seeking students sometimes wish to transfer credit from another institution toward their degree at Coe. Such credit must be approved in advance of completion of the course by the Registrar. Departments must approve in advance any courses counting toward a major, a minor, or teacher certification requirements. Credit from junior or community colleges is not accepted for students who have junior or higher status at Coe. 

## Evaluation of Credits For Graduation

The Office of the Registrar certifies the completion of general degree (see p. 16) and general education requirements (see p. 23). Credits toward a major, minor, endorsement, license, authorization, etc. are approved by the appropriate department chair, administrative coordinator, or by Academic Policies Committee for interdisciplinary majors. 

## Credit By Examination

A maximum of eight course credits in satisfaction of degree requirements may be applied from credit earned through the Advanced Placement Program and International Baccalaureate. 

## Updating Course Work

In the natural course of reviewing academic records, a student may be required to repeat certain courses (or appropriate substitutes) taken more than four years prior to the review to bring studies in those areas up to date. Review cases may be brought to the Academic Policies Committee by any member of the faculty, and this committee makes the final decision. 

## Advanced Placement (AP)

Coe College’s Advanced Placement code is 6101.

Coe College grants college credit for approved Advanced Placement examination scores of 4 or 5.  AP credit cannot be used to fulfill any general education requirement, including First-Year Seminar, Liberal Arts Core, Diverse Cultural Perspectives, the writing emphasis requirement, credit in transfer to reduce the number writing emphasis courses required, or academic practicum.  Each AP exam may earn 1.0 course credit up to a maximum of eight course credits towards graduation.  Credit is granted upon receipt of the results of the examination, which must be received directly from the Educational Testing Service.  Further information regarding Advanced Placement examination reporting to the College may be obtained in the Office of the Registrar and on Coe’s website. If an equivalent course is taken at Coe College, the AP credit is removed from the transcript.

## International Baccalaureate (IB)

Coe College credit may be awarded for International Baccalaureate work.  Students may earn 1.0 course credit for each higher-level examination score of 5, 6, or 7 to a maximum of eight course credits.  No credit is granted for standard level examinations.  Students may not receive college credit for both AP and IB in areas of similar content.  IB credit cannot be used to fulfill any general education requirement, including First-Year Seminar, Liberal Arts Core, Diverse Cultural Perspectives, the writing emphasis requirement, credit in transfer to reduce the number of writing emphasis courses required, or academic practicum.  Credit is granted upon receipt of the results of the examination, which must be received directly from IB.  Further information regarding International Baccalaureate examination reporting to the College may be obtained in the Office of the Registrar and on Coe’s website.  If an equivalent course is taken at Coe College, the IB credit is removed from the transcript.

## Class Attendance

Regular class attendance is expected, although the instructor of each course sets the standard expected to be met by the students. The College expects attendance on all scheduled days, including the first and last day of a term, as well as the class days immediately preceding and following College holidays. Students officially representing the College are excused as necessary prior to the absence. Students on academic probation are not excused from attending class to participate in extra-curricular activities. 

## Final Exams

The final exam schedule is published by the Registrar. It is expected that final exams will be given during the time scheduled for each course. There may be extraordinary cases when an individual student has a compelling reason for taking an exam at a time other than that scheduled. In such cases the instructor may properly decide to let that individual take the exam at another time. Having more than two exams scheduled on one day would justify allowing a student to take a third exam on another day. The instructor of the course with the highest course number will move the exam, for that student only, to a mutually convenient time.

## Participation In Commencement

Students can participate in Commencement when they have met all the requirements for graduation for one of Coe’s degrees, their financial obligations to Coe College are met, and they have completed their Intent to Graduate form and it has been approved.  In addition, all students, unless excused in writing by the Provost, must complete a survey assessing their educational experience at Coe.  All pending graduates must participate in Commencement exercises unless excused in writing by the Registrar..

## Pending Graduates

Students who need to earn no more than 2.0 course credits to complete all graduation requirements may be permitted to participate in Commencement exercises as long as the remaining course credits are scheduled to be completed by August 15 of that year.  Pending graduates will be listed in the Commencement booklet, but since Latin honors (see p. 36) are bestowed only after all graduation requirements are met, they cannot be listed in the Commencement booklet for Latin honors, although any earned honors will be listed on their diploma and transcript.
