# RESERVE OFFICER TRAINING CORPS 


## Aerospace Studies 
Clark, Spyker.

### Air Force ROTC Courses

The Air Force Reserve Officers’ Training Corps (AFROTC) program at Coe College is administered through a cross-enrollment agreement with the Department of Aerospace Studies at the University of Iowa in Iowa City. Classes are held at the University of Iowa or at Coe College. Information on the Air Force ROTC program is available by contacting the Department of Aerospace Studies at 319-335-9222.

Air Force ROTC is typically a four-year program divided between the General Military Course (first two years), field training, and the Professional Officer Course (last two years). Enrollment in the General Military Course is open to all students and carries no service obligation. Students can join the program any time during their first or freshman year. Students who complete the General Military Course attend a paid two-week field training course. Normally, students attend the camp between the sophomore and junior years of college. Successful completion of field training and the Professional Officer Course culminates in the student receiving a commission as an officer in the United States Air Force. Opportunities are available in approximately 100 career fields. 

Students are supplied all AFROTC books, uniforms, and necessary materials free of charge. All students in the Professional Officer Course receive a monthly stipend of either $450 or $500. Veterans continue to draw both the AFROTC stipend plus any GI Bill benefits to which they are entitled. General Military Course Students are eligible to apply for AFROTC two- and three-year scholarships which provide tuition, books, fees, and between $300-$500 tax-free monthly stipend. 

- **MSA 110 Air Force Heritage and Values I**
  A survey course designed to introduce students to the United States Air Force (USAF) and Air Force Reserve Officer Training Corps (AFROTC). Featured topics include: structure of the U.S. Air Force, the Air Force 2019s capabilities, career opportunities, benefits, Air Force installations, core values, leadership, teambuilding, and communication skills. Prerequisite: first-year or sophomore standing. (0.25 course credit)   
- **MSA 110L AFROTC Leadrshp Lab I**
  A progression of experiences designed to develop leadership ability; includes military customs and courtesies, drill and ceremonies, military professional development, and the life and work of a junior officer; leadership skills in a practical, supervised military lab setting. Corequisite: Foundations of the U.S. Air Force I (MSA-110); Prerequisite: first-year or sophomore standing. (0.25 course credit) 
- **MSA 120 Air Force Heritage and Values II**
  A survey course designed to introduce students to the United States Air Force (USAF) and Air Force Reserve Officer Training Corps (AFROTC). Spring semester featured topics include: Evolution of the U.S. Air Force/Air Force history, Principles of War/Tenets of Air Power, What the Air Force Brings to the Joint Fight and a look at the Department of the Air Force and Air Force Major Commands. It will also introduce several leadership concepts, to include ethical decision-making, communication, and professional speaking opportunities. Prerequisite: first-year or sophomore standing. (0.25 course credit)
- **MSA 120L AFROTC Leadrshp Lab II**
  See MSA-110L. Corequisite: Air Force Heritage and Values II (MSA-120) (0.25 course credit) 
- **MSA 210 Team and Leadership Fundamentals I**
  Provide the foundation for both leadership and team building. The concepts will be applied in team building activities and class discussion to include demonstration of basic verbal and written communication. Featured topics include: listening, followership, and problem solving efficiently. (0.25 course credit)
- **MSA 210L AFROTC Leadrshp Lab ASP I**
  See MSA-110L. Corequisite: Team and Leadership Fundamentals I (MSA-210). (0.25 course credit)
- **MSA 220 Team and Leadership Fundamentals II**
  {{< var c.msa220.desc >}
- **MSA 220L AFROTC Leadrshp Lab ASP II**
  {{< var c.msa220l.desc >}
- **MSA 310 Leadership Studies: I**
  Course is designed to build on the leadership fundamentals taught in AERO 2100 and AERO 2200. The class studies leadership and leadership skills to use in your future Air Force environment. You will study the profession of arms, communications skills, and ethics. Case studies will be used to examine Air Force leadership situations, and to demonstrate and exercise practical application of the concepts you study. (0.75 course credit)
- **MSA 310L AFROTC Leadrshp Lab AFLS I**
  See MSA-110L. Corequisite: Leadership Studies: Leading People and Effective Communication I (MSA-310). (0.25 course credit)
- **MSA 320 Air Force Leadership Studies II**
  Class studies leadership and leadership skills used in your future Air Force environment. You will continue to study the profession of arms, communications skills, and ethics taught in AERO 3100, in addition to learning more about creating a vision, mentoring, and other leadership fundamentals. Additionally, you will continue to hone your reading, writing, and speaking skills via several communication studies applications. Case studies will be used to examine Air Force leadership situations, and to demonstrate and exercise practical application of the concepts you study. The goal is to instill a more in-depth understanding of how to effectively lead people and organizations. (0.75 course credit)
- **MSA 320L AFROTC leadrshp Lab AFLS II**
  See MSA-110L. Corequisite: Leadership Studies: Leading People and Effective Communication II (MSA-320). (0.25 course credit)
- **MSA 410 National Security / Leadership I**
  Class will introduce you to the national security process, regional studies, advanced leadership ethics, and Air Force doctrine. It will focus specifically on current Air Force organization, leadership and practical knowledge needed for your future as an Air Force officer. Additionally, you will improve your oral and written communication skills and delve into military professionalism and ethics. (0.75 course credit)
- **MSA 410L National Security Leadership I**
  See MSA-110L. Corequisite: National Security / Leadership Responsibilities and Commissioning Preparation I (MSA-410). (0.25 course credit)
- **MSA 420 National Security / Lead II**
  National Security / Leadership Responsibilities and Commissioning Preparation I (MSA-340) introduced the national security process, regional studies, advanced leadership ethics, and Air Force doctrine. This class will expand your knowledge to comprehend the responsibility, authority, and functions of an Air Force commander and selected provisions of the military justice system. It is designed to prepare cadets for life as a second lieutenant. Additionally, you will continue to improve your oral and written communication skills. (0.75 course credit)
- **MSA 420L National Security Lab**
  See MSA-110L. Corequisite: National Security / Leadership Responsibilities and Commissioning Preparation II (MSA-420). (0.25 course credit) 
    
## Military Science 
Guderski.

### Army ROTC Courses

The Army Reserve Officers’ Training Corps (ROTC) program at Coe College is administered through a cross-enrollment agreement with the Department of Military Science at The University of Iowa in Iowa City. Classes are held either at The University of Iowa or at Coe College, depending upon the size of class enrollment. Information on the Army ROTC program is available by contacting the Department of Military Science at (319) 399-8297 or the website at [ARMY ROTC](http://armyrotc.com/edu/univia/index.htm)

All students are eligible to apply for ROTC two-, three-, and four-year scholarships which cover tuition and fees, books and supplies, and a tax-free monthly stipend during the academic year. The Army National Guard and Army Reserve also provide financial assistance through membership with a respective unit. 

#### Basic courses{.unnumbered}

The ROTC Basic Course is primarily for first- and second-year students. It provides the fundamentals of leadership and management and introduces the roles of the military as influenced by national and foreign policy. Enrollment in the Basic Course is open to all students and carries no service obligation. Students with prior military training normally are exempt from the Basic Course requirements. 

Students may complete the Basic Course requirements over a one- or two-year period, or during a four-week fully-paid summer training session, the Leader’s Training Course (LTC), held at Fort Knox, Kentucky. Students normally attend the camp between the sophomore and junior years of college. 

- **MIL 101 Leadership & Pers Devel**
  Introduces students to the personal challenges and competencies that are critical for effective leadership. Students learn how the personal development of life skills such as critical thinking, goal setting, time management, physical fitness, and stress management relate to leadership, officership, and the Army profession. The focus is on developing basic knowledge and comprehension of Army leadership dimensions while gaining a big picture understanding of the ROTC program, its purpose in the Army, and its advantages for the student. (0.25 course credit) (Offered Fall Term; Spring Term by arrangement) 
- **MIL 102 Intro Tactical Leadership**
  Overviews leadership fundamentals such as setting direction, problem-solving, listening, presenting briefs, providing feedback, and using effective writing skills. Students explore dimensions of leadership values, attributes, skills, and actions in the context of practical, hands-on, and interactive exercises. Continued emphasis is placed on recruitment and retention of cadets. Cadre role models and the building of stronger relationships among the students through common experience and practical interaction are critical aspects of the class. (0.25 course credit) (Offered Spring Term; Fall Term by arrangement)
- **MIL 103 Innovative Team Leadership**
  Explores the dimensions of creative and innovative tactical leadership strategies and styles by examining team dynamics and historical leadership theories that form the basis of the Army leadership framework (trait and behavior theories). Students practice aspects of personal motivation and team building in the context of planning, executing, and assessing team exercises and participating in leadership labs. Focus is on continued development of the knowledge of leadership values and attributes through an understanding of Army rank, structure, and duties and basic aspects of land navigation and squad tactics. Case studies provide tangible context for learning the Soldier 2019s Creed and Warrior Ethos as they apply in the contemporary operating environment (COE). Prerequisites: MIL-101, MIL-102, or consent of instructor. (0.5 course credit) (Offered Fall Term; Spring Term by arrangement)
- **MIL 104 Foundations of Tactical Leadership**
  Examines the challenges of leading tactical teams in the complex contemporary operating environment (COE). The course highlights dimensions of terrain analysis, patrolling, and operation orders. Further study of the theoretical basis of the Army leadership framework explores the dynamics of adaptive leadership in the context of military operations. This course provides a smooth transition into Adaptive Tactical Leadership (MIL-105). Students develop greater self-awareness as they assess their own leadership styles and practice communication and team building skills. COE case studies give insight into the importance and practice of teamwork and tactics in real-world scenarios. Prerequisites: MIL-101, MIL-102, and MIL-103 or consent of instructor. (0.5 course credit) (Offered Spring Term; Fall Term by arrangement)   

#### Advanced courses{.unnumbered}   

The ROTC Advanced Course is open to any student who meets the prerequisites. Its design is primarily for students who wish to pursue a commission as a lieutenant in the U.S. Army upon graduation. Most students in the advanced course incur an obligation to the military via the Active Army, Army National Guard, or Army Reserve. Students agreeing to serve in the armed forces, through a contractual obligation with the ROTC program, receive a tax-free monthly stipend.

To enter the Advanced Course, students must fulfill the requirements of the Basic Course, attain junior status, and earn a minimum cumulative GPA of 2.00. Students must complete the Leadership Development and Assessment Course (LDAC), a six-week course held at Fort Lewis, WA, usually during the summer between the third and fourth years of instruction. The course may be delayed until the summer following the final ROTC class with permission of the professor of military science. 

Students in the Advanced Course complete the following list of courses:
	- MIL 209 Leadership Lab
	- MIL 220 Adaptive Tactical Leadership 
	- MIL 305 Leadership in Changing Environs 
	- MIL 350 Developing Adaptive Ldrshp 
	- MIL 360 Leadership in Complex World 
In addition, students choose **one** course in history from the following list:
	- HIS 145 History of United States to 1865 
	- HIS 155 History of United States since 1865 
	- HIS 217 American War in Vietnam 
	- HIS 227 American Civil War 
	- HIS 387 American Colonial History 

Students earning a degree in nursing normally are exempt from this requirement, and students may, with the approval of the professor of military science, use other courses to meet the requirement. 

- **MIL 209 Leadership Lab**
  Hands-on training of basic soldier skills, such as customs and courtesies, drill and ceremony, first aid, weapons employment, and troop movement techniques. In addition, students learn the application of leadership dimensions to improve students 2019 abilities to perform as officers in the U.S. Army. This course is designed to enhance the training received in the classroom. (0.0 course credit). 
- **MIL 215 Adv Military Fitness Training**
  Developed around the army physical fitness training program. This course covers aerobics and running, muscular strength and endurance, flexibility, and nutrition. Students also learn how to evaluate and measure fitness improvement. This course models the use of ability groups to improve the fitness levels of all individuals from the unfit to the tri-athlete or bodybuilder. Lab fee required. Course may be repeated up to three times. (0.5 course credit) 
- **MIL 220 Adaptive Tactical Leadership**
  Challenges students to study, practice, and evaluate adaptive leadership skills as they are presented with challenging scenarios related to squad tactical operations. Students receive systematic and specific feedback on their leadership attributes and actions. Based on such feedback, as well as their own self-evaluations, students continue to develop their leadership and critical thinking abilities. Students 2019 tactical leadership abilities are developed to enable them to succeed at ROTC 2019s summer Leadership Development and Assessment Course (LDAC). Corequisite: Leadership Laboratory (MIL-209). Prerequisites: Leadership and Personal Development (MIL-101), Introduction to Tactical Leadership (MIL-102), Innovative Team Leadership (MIL-103) and Foundations of Tactical Leadership (MIL-104) or completion of Army Basic Training or the Leaders Training Course. (0.75 course credit) (Offered Fall Term; Spring Term by arrangement) 
- **MIL 305 Leadership in Changing Environs**
  Uses increasingly intense situational leadership challenges to build student awareness and skills in leading tactical operations up to platoon level. Students review aspects of combat, stability, and support operations Military briefings are conducted and proficiency is developed in garrison operation orders. The focus is on exploring, evaluating, and developing skills in decision-making, persuading, and motivating team members in the contemporary operating environment (COE). Students are evaluated on what they know and do as leaders as they prepare to attend the ROTC summer Leader Development Assessment Course (LDAC). Corequisite: Leadership Laboratory (MIL-209). Prerequisites: Leadership and Personal Development MIL-101, Introduction to Tactical Leadership MIL-102, Innovative Team Leadership (MIL-103), and Foundations of Tactical Leadership (MIL-104), or completion of Army Basic Training or the Leaders Training Course (LTC) and Adaptive Tactical Leadership (MIL-220). (0.75 course credit) (Offered Spring Term; Fall Term by arrangement.) 
- **MIL 350 Developing Adaptive Ldrshp**
  Develops student proficiency in planning, executing, and assessing complex operations, functioning as a member of a staff, and providing performance feedback to subordinates. Students assess risk, make ethical decisions, and lead fellow ROTC cadets. Lessons on military justice and personnel processes prepare students to make the transition to Army officers. Students in this course analyze, evaluate, and instruct students at lower levels. Both the classroom and battalion leadership experiences are designed to prepare students for their first unit of assignment. Responsibilities of key staff are identified, staff roles are coordinated, and situational opportunities are used to teach, train, and develop subordinates. Corequisite: Leadership Laboratory (MIL-209). Prerequisites: Adaptive Tactical Leadership (MIL-220) and Leadership in Changing Environs (MIL-305). (0.75 course credit) (Offered Fall Term; Spring Term by arrangement) 
- **MIL 360 Leadership in Complex World**
  Explores the dynamics of leading in the complex situations of current military operations in the contemporary operating environment (COE). Students examine differences in customs and courtesies, military law, principles of war, and rules of engagement in the face of international terrorism. Aspects of interacting with non-government organizations, civilians on the battlefield, and host nation support are also explored. Significant emphasis is placed on preparing students for their first unit of assignment. Case studies, scenarios, and  201cWhat now, Lieutenant? 201d exercises are used to prepare students to face the complex ethical and practical demands of leading as commissioned officers in the United States Army. Corequisite: Leadership Laboratory (MIL-209). Prerequisites: Adaptive Tactical Leadership (MIL-220), Leadership in Changing Environs (MIL-305), Developing Adaptive Leaders (MIL-350). (0.75 course credit) (Offered Spring Term; Fall Term by arrangement) 
- **MIL 380 Readings Contmp Miitary Issues**
  Designed for cadets with an interest and experience in military science and to generate interest in the participating students 2019 knowledge of current military and worldwide events. Students prepare novel reviews from a reading list provided by the instructor. The list contains topics ranging from historical battles and campaigns to the global impact of US political policies. Students may opt to write an operations order (OPORD) as it relates to an ROTC event or similar project as it relates to the historical significance of the ROTC Department (the student must work in conjunction with instructor). This course can be taken for 0.25 to 0.75 credit hours based upon the number of reviews completed or the length and value of the final project. Prerequisites: : Leadership and Personal Development (MIL-101), Introduction to Tactical Leadership (MIL-102), Innovative Team Leadership (MIL-103), and Foundations of Tactical Leadership (MIL-104), or completion of Army Basic Training or the Leader 2019s Training Course. (0.25 to 0.75 course credit) 