# FINANCIAL INFORMATION {#sec-financial-information}

## FEES
Rates subject to change.

The Coe College annual fees and student accounts policies can be found in the **Coe Student Accounts Handbook** located at <https://www.coe.edu/student-life/student-life-resources/business-office/student-accounts-handbook> .

### Full-time and Part-time Students

A student is full-time in the Fall or Spring Terms if registered for three or more course credits per term. Students who are taking fewer than three credits are considered part-time.

Part-time students may not participate in the complete program of College activities unless they pay the activity fee.  A part-time student cannot be an on-campus resident student, unless special written permission has been granted by the Office of Residence Life.

### Enrollment Fee 
A $300 non-refundable enrollment fee is paid to the College by the accepted candidate.

### Comprehensive Fee 

Coe College charges tuition, room, board, and student fees. The student fees include Health Services and an Activity Fee which is allocated to the Student Senate for apportionment among various student activities such as the student newspaper, literary magazine, and social events. Expenses not covered by the Comprehensive Fee include some music lessons, books, linen service, personal expenses, certain specific campus events, and health and accident insurance. 

|                                              |          |
|:---------------------------------------------|---------:|
| Tution                                       | $50,314  |
| Board                                        | $5,726   |
| Room                                         | $5,194   |
| Student Fees (Health Services & Activity Fee)| $350     |
| Total On-Campus Resident                     | $61,584  |

: Comprehensive Fee 2022-23 (For Full-Time Students) {tbl-colwidths="[75,25]"}

### On-Campus and Off-Campus Resident Students {#sec-full-time-residence-requirements}

As a residential, liberal arts college, we seek to provide an environment where learning by all members of the community occurs in and out of the classroom and where curricular and co-curricular activities reinforce our commitment to the life of the mind. Such experiences occur best when students are living and learning full-time on campus. The residential life program is an integral part of the education program and support services at Coe College. Residence halls and hall staff provide a structure by which the experience of the classroom is joined with the out-of-class learning experience of the student.

Full-time students are required to live in residence and take meals in the college dining hall and, thereby, are charged for room and board unless exempt for one or more of the following reasons:

1. Married students – must provide copy of signed marriage license
2. Live with parent(s)/guardian(s) within 25 miles of campus (address on file with College is verified)
3. Dependent child (person must provide copy of child’s birth certificate)
4. Completed 8 semesters living on campus
5. Students who are 25 years or older.

 Other exceptions to the residence requirement must be applied for in writing to the Dean of Students. Approval or denial is determined on a case-by-case basis following evaluation of the extenuating circumstances provided for review. Students are notified in writing of the decision. Permission to live off campus must be on file in the Residence Life Office and must be renewed each year. Students who violate the residence requirement are charged full room and board costs for the entire year. Coe funded scholarships and grants will typically be reduced by approximately 10 percent when a student moves off campus.

### ACM and Other Off-Campus Study Programs 

Students desiring to study off-campus must first obtain approval from the Director of Off-Campus study. In every case, students are responsible for their own transportation and living expenses. Each student is advised to check with the program’s director as to the cost (and other details) of each program. This charge could vary significantly from the cost of remaining on campus. The tuition charged for Fall or Spring Term off-campus programs will be Coe’s tuition or the tuition for the off-campus program if greater than Coe’s tuition. In addition to tuition, Coe will charge the off-campus program fee as billed by the off-campus program. Students maintain their eligibility for federal and state financial aid; however, Coe financial aid availability is subject to approval by the Committee on Internationalization. Students registered for the optional May Term who desire to study off-campus (except Coe-sponsored programs) are billed a surcharge fee for tuition and/or program costs which are greater than 10% of Coe’s annual tuition. Tuition and fees for ACM off-campus study programs or study programs sponsored by other colleges must be paid in full prior to attending the off-campus program. 

**NOTE**: *Students on regular-term Coe-administered programs including exchanges are able to use their Coe College gift aid to pay tuition that term.  Domestic students on other providers’ programs may be able to utilize a portion of their Coe gift aid.  International students may be able to utilize a portion of their Coe gift aid toward tuition for ACM or other providers’ domestic but not international programs.  In all cases, students in an off-campus program are not charged the student-activity or health fee.* 

### GENERAL FINANCIAL REGULATIONS 
1. Registration is not completed and a student is not enrolled in classes until College charges are paid in full or satisfactory arrangements are made in writing with the Business Office.
2. At the discretion of the College administration, a student may be suspended for non-payment of indebtedness to the College. If the account is later paid, the student may seek reinstatement. 
3. No diploma, certificate, official transcript, letter of honorable dismissal, is granted to any student failing to make a satisfactory settlement of any indebtedness to the College. 
4. Residence halls are not open for student occupancy during winter and spring breaks. Students living some distance from the campus may make housing arrangements through the Office of Student Life. The residence halls are open during the fall break and Thanksgiving recess. Meals are served during the fall break but not during Thanksgiving recess. 
5. The College does not carry insurance on personal property of students and is not responsible for the loss of or damage to such property. Information regarding student health and accident insurance is available through the Office of Student Life. 
6. The College reserves the right to revise charges as conditions may warrant.

### PAYMENT POLICY 

The Net Comprehensive Fee, the Comprehensive Fee less financial aid (with the exception of the work study) is due and payable by August 1^st^ for the Fall Term and January 10^th^ for the Spring Term.

### Monthly Payment Plan 
The College offers a monthly payment plan for those parents/students who desire to budget the costs of tuition, room, and board in 5 monthly payments per term. Under this plan, the first payment for the Fall Term is due August 1^st^, and the final payment is due December 10^th^. The payment plan for the Spring Term begins January 10^th^ and the final payment is due May 10^th^ (graduating seniors’ final payment is due the last Friday in April). There is a $50 non-refundable enrollment fee per term to be on the monthly payment plan. Students enroll in the monthly payment plan through CASHNet via their <my.coe.edu> account.

If, after enrolling in the monthly payment plan, the student’s charges or financial aid changes, the student account and monthly payments are adjusted accordingly. All refunds are made in accordance with the refund policy as stated in the *Coe Student Accounts Handbook*. If a student on the monthly payment plan withdraws from Coe, charges and excess payments will be refunded in accordance with the College’s refund policy. The $50 enrollment fee will not be refunded. Information on this plan is available on <my.coe.edu>. 

To give parents/students as much time as possible to make arrangements for their financial obligation or to take advantage of Coe’s monthly payment plan, the Business Office generates an online billing statement in mid-July. Any special fees, such as music lessons, are billed after the start of classes and are payable by the tenth of the following month. 

### Late Payments

If a student chooses to pay his/her college charges on the semester payment schedule (payment in full is due August 1^st^ and January 10^th^) late payments are subject to a late fee/finance charge of 1.25% per month (or fraction thereof) on the full amount that is past due. This is equivalent to an annual rate of 15%. 

### FINANCIAL IMPACT OF WITHDRAWING OR CEASING ATTENDANCE IN ALL COURSES

### Official Withdrawal from all Courses

Students who withdraw from or cease attendance in all of their courses have the responsibility of initiating the official withdrawal process (see @sec-official-withdrawal-process ).

If a student is unable to complete the official withdrawal process, the intent to withdraw can be communicated to one of the following offices: Registrar, Student Financial Services, Student Life, Student Success and Persistence.

Special consideration is given to students who withdrew due to a call to active duty. Coe’s “Military Call Up/Refund” and “Readmission of Service Member” policies are published on the Admission/Financial Aid webpage. Copies of these policies can be requested from the Student Financial Services Office.

### Unofficial Withdrawal from all Courses

Students who did not earn credit for any of the courses they were registered for in a given term and did not officially withdraw or otherwise provide notice of their intent to withdraw, must be considered “unofficially withdrawn”. Federal regulations mandate that, a federal Title IV refund calculation, using the withdrawal date of either the midpoint of the term or the last date of attendance at a documented academically related activity, must be performed.

**A student’s withdrawal date is:**

The earlier of the date that the student began the official withdrawal process or otherwise provided official notification to a designated office of their intent to withdraw; 

- OR If official notification could not be provided because of circumstances beyond the student's control, the date the college determines is related to the particular circumstance; 
- OR If the student ceased attendance without providing official notification, the midpoint of the term;
- OR The student’s last date of attendance at a documented academically related activity.

### Federal Title IV Refund Calculation/Policy {#sec-federal-title-IV-refund-calculation-policy} 

In accordance with federal regulations, a Title IV refund calculation must be performed for students that are recipients of Federal Student Aid (FSA) who cease attendance in all courses, including students who are expelled, or are granted a leave of absence. The FSA programs that are covered by this law are: Federal Pell Grants, TEACH Grants, Stafford Loans, PLUS Loans, Federal Supplemental Educational Opportunity Grants (FSEOG), Iraq Afghanistan Service Grant, and other Title IV Programs. The Coe College Student Financial Services Office determines, based on the federally mandated formula[^note], the amount of FSA assistance students have earned based on the date in the term a student is considered to be withdrawn. An example of the refund calculation is published online in the [Financial Aid Handbook] (https://www.coe.edu/admission/financial-aid-scholarships/financial-aid-handbook) and a handout may be obtained from the Student Financial Services Office.

### Return of Financial Aid Funds Policy Steps

* Step 1: Determine the percentage of enrollment period completed by the student. If the calculated percentage is equal to or greater than 60%, the student has “earned” all aid for the enrollment period and no adjustment in financial aid occurs.

	Days Attended ÷ Days in Enrollment Period = Percentage Completed

* Step 2: Apply the percentage completed to the Title IV aid award to determine the student’s eligibility for financial aid prior to the withdrawal.

	(Total Aid Disbursed + Aid that could have been disbursed) x Percentage Completed = Earned Aid

* Step 3: Determine the amount of unearned financial aid to be returned to the appropriate Title IV financial aid program.
	
	Total Disbursed Aid – Earned Aid = Unearned Aid to be Returned

    + If the aid already disbursed equals the earned aid, no further action is required.
    + If the aid already disbursed is greater than the earned aid, the difference must be returned to the appropriate Title IV aid program.
    + If the aid already disbursed is less than the earned aid, a late disbursement may be made to the student.
* Step 4: Determine if the institution and/or the student must return the unearned funds.
    + Total Aid – Earned Aid = Unearned aid that must be returned 
    + Unearned Aid > assessed charges = Unearned aid that must be returned by the student
    + Unearned Aid ≤ assessed charges = Unearned aid to be returned by the College

The Coe College Student Financial Service Office is required to return any unearned FSA funds that were applied towards institutional charges within 45 days in the following order:
	+ Direct Unsubsidized Stafford Loan
	+ Direct (Subsidized) Stafford Loan
	+ Direct Graduate PLUS Loan (for graduate students)
	+ Direct PLUS Loan (for parents of undergraduate students)
	+ Pell Grant
	+ SEOG
	+ TEACH Grant
	+ Iraq Afghanistan Service Grant

The student will be informed by the Student Financial Services Office of the type and amount of FSA program funds that are being returned on their behalf and of the amount the student must return. If the student’s portion of aid to be returned is a loan, the terms of the original loan repayment agreement will apply. The amount of unearned grant funds a student must repay is limited to the amount by which unearned grant funds disbursed exceed half of the original grant award by $50 or more. In general, the Student Financial Services Office will return the grant funds to the appropriate federal program and charge the student’s Coe account, which will result in debt to the college.

* Step 5: Determine earned FSA assistance that has not been disbursed.
	
	Total Aid Earned – Total Aid Disbursed = Earned Aid not Disbursed

Grant aid that was earned, but had not been applied before the student withdrew, will be applied to the students account within 45 days. Loan proceeds that could be disbursed after the student withdrew will only be disbursed if the student requests a disbursement within 14 days of receiving notice from the Student Financial Services of their eligibility of a post-withdrawal loan disbursement.

[^note]: the federal work-sheet used to calculate the amount of FSA assistance earned is available from the Student Financial Services upon request.

### Institutional Refund Calculation/Policy

The Student Financial Services will follow the federal Title IV Refund Calculation/ Policy in determining the amount of earned and unearned Coe scholarships and grants and state assistance.

Tuition, Board and Student Fees will be charged pro-rata based on the percentage of the enrollment period completed up to the 60-percentage point in time of the term. Room charge will not be refunded after Date of Record for the term. Please see the Coe *Student Accounts Handbook* to review the institutional refund policy for tuition, fees, room and board.

### May Term (optional) 

The first May Term course taken by a student is a non-tuition charge term for all Coe full-time degree-seeking students enrolled in the Spring Term, therefore, no institutional aid is awarded to students. A $1000 fee per May Term course will be assessed for subsequent May Term courses taken by a student. Please see the *Coe Student Accounts Handbook* for more information about May Term.

### Enrollment Status Changes

Changes in enrollment status from full-time to part-time may affect a student’s financial assistance. In general, the amount of financial aid a student is eligible to receive is based on the enrollment status as of the College’s official date of record.  Federal direct loans will no longer be in an in-school deferment status for a student who drops below half-time at any time during the term Students should consult with the Student Financial Services to discuss how enrollment changes will affect their financial aid eligibility and loan deferment status.

### Part-Time Students

A part-time student withdrawing from all courses in the Fall or Spring Terms shall be subject to *Return of Title IV Funds/Institutional Refund Policy*, see @sec-federal-title-IV-refund-calculation-policy for more information. 

### Summer Students

A summer student withdrawing from class will be subject to Return of Title IV Funds/Institutional Refund Policy (see @sec-federal-title-IV-refund-calculation-policy ) which credits earned aid and assessed charges on a prorated basis predicated on the term/session enrolled.
