# DIRECTORIES


## The Faculty

### Full-Time Faculty

- MARIO AFFATIGATO  
  Professor of Physics.  
  B.A., Coe College; M.S., Ph.D., Vanderbilt University.

- UGUR AKGUN  
  Professor of Physics.  
  B.S., Middle East Technical University, Turkey; Ph.D., University of Iowa.

- BRIE SWENSON ARNOLD  
  B.A., Concordia College; M.A., Ph.D., University of Minnesota.

- KATE ASPENGREN  
  Assistant Professor of English.  
  B.A., M.F.A., University of Iowa.  

- LARRY D. ATWATER  
  Assistant Professor of Kinesiology.  
  B.A., Coe College; M.A., Northeast Missouri State University.  

- MARIE BAEHR  
  Special Assistant to the President; Professor of Physics.   
  B.A., Denison University; M.S., University of New Hampshire; Ph.D., The Ohio State University.  

- MICHAEL BAKER  
  Professor of Psychology.  
  B.A., Coe College; M.S., Ph.D., Iowa State University.  

- RYAN BARANOWSKI  
  Associate Professor of Stead Department of Business Administration and Economics.  
  B.A., Coe College; M.A., Ph.D., University of California, Irvine.  

- DENNIS BARNETT  
  Professor of Theatre Arts.  
  B.A., Indiana University; M.F.A., Florida State University; Ph.D., University of Washington.  

- LISA A. BARNETT  
  Associate Professor of Sociology.  
  B.S.J., Northwestern University; M.A., Ph.D., Washington State University.  

- LYNDA BARROW  
  Professor of Political Science.  
  B.A., Albion College; M.A., The Johns Hopkins University; M.T.S., Wesley Theological Seminary; Ph.D., Syracuse University.  

- ALISSA BOGUSLAW  
  Assistant Professor of Sociology   
  B.A., 2007, University of Minnesota; M. A., M.Phil., The New School for Social Research.   

- CAIO BARCA BRAGATTO  
  Assistant Professor of Physics.  
  B.A., Universidade de Sao Paulo; M.A., Ph.D., Universidade Federal de Sao Carlos.  

- ABBIE BREWER  
  Assistant Professor of Music  
  B.M., Wartburg College; M.M., Azusa Pacific University; D.M., University of Iowa  

- SAMANTHA BROWN  
  Assistant Professor of Psychology.  
  B.A., Creighton University; Ph.D., University of Iowa.  

- DEREK N. BUCKALOO  
  Professor of History.  
  B.A., Stanford University; M.A., Ph.D., Emory University.  

- HEIDE BURSCH  
  Associate Professor of Nursing.  
  B.S.N., M.S.N., Ph.D., University of Iowa.  

- ALLISON CARR  
  Associate Professor of Rhetoric.  
  B.A., Coe College; M.A., Ph.D., University of Cincinnati.  

- WILLIAM S. CARSON  
  Professor of Music.  
  B.A., Macalester College; M.M., Southern Illinois University; D.M.A., Arizona State University.  

- PAMELA J. CARSTENS  
  Professor of Business Administration and World Affairs.  
  B.A., Coe College; M.B.A., Ph.D., University of Iowa.  

- VANESSA CASTILLO  
  Assistant Professor of Psychology.  
  B.A., Concordia College; B.S., PhD. Iowa State University.  

- JOHN BRADLEY CHAIMOV  
  Associate Professor, Director of Off-Campus Study.  
  B.A., University of California, San Diego; M.A., Ph.D., University of Chicago.  

- JOHN M. CHANDLER  
  Assistant Professor of Kinesiology  
  B.S., University of Wisconsin, Madison; M.A., University of Northern Iowa.  

- JIA-YUH CHEN  
  Professor of Stead Department of Business Administration and Economics.  
  B.S., National Taiwan University; M.B.A., University of California, Irvine; Ph.D., University of California, Santa Cruz.  

- BENJAMIN CHIHAK  
  Assistant Professor of Psychology.  
  B.A., Macalester College; Ph.D., University of Minnesota.  

- JOSHUA CHRISTENSEN  
  Associate Professor of Stead Department of Business Administration and Economics.  
  B.A., Wartburg College; J.D., University of Iowa College of Law.  

- RANDOLPH N. CHRISTENSEN  
  Professor of Biology.  
  B.S., Brigham Young University; Ph.D., The Ohio State University.  

- ZEN COHEN  
  Assistant Professor of Art and Film Studies  
  B.F.A., California College of the Arts; M.F.A., University of California at Davis  

- CASSY COZINE  
  Associate Professor of Biology.  
  B.S., University of Southern Mississippi; Ph.D., University of Iowa Carver College of Medicine.  

- GAVIN MORRISON CROSS  
  Professor of Statistics.  
  B.A., B.S., Miami University; M.S., University of Missouri-Rolla; M.S., Ph.D., University of Iowa.  

- HANNAH DEHNER  
  Assistant Professor of Nursing.  
  BSN, MSN, University of Iowa.  

- THERESA A. DONOFRIO  
  Associate Professor of Communication Studies.  
  B.A., Miami University; M.A., Ph.D., University of Maryland.  

- FIRDEVS DURU  
  Associate Professor of Physics.  
  B.S., Bosphorus University; M.S., Ph.D., University of Iowa.  

- RICHARD G. EICHHORN  
  Professor of Stead Department of Business Administration and Economics.  
  B.S., University of Tulsa; M.A., Ph.D., Colorado State University.  

- JESSE ELLIS  
  Associate Professor of Biology.  
  B.A., Lewis & Clark College; Ph.D., Cornell University.  

- JULIE FAIRBANKS  
  Associate Professor of Anthropology.  
  B.S., Georgetown University; M.A., Harvard University; Ph.D., Indiana University.  

- MARC FALK  
  Professor of Music, Associate Dean for Faculty Development  
  B.A., Macalester College; M.M., University of Minnesota; D.M.A., University of Iowa.  

- SARA K. FARRELL  
  Professor of Psychology.  
  B.A., University of Iowa; M.A., Minnesota State University, Mankato; Ph.D., Northern Illinois University.  

- STEVEN FELLER  
  Professor of Physics.  
  B.S., Clarkson College of Technology; Sc.M., Ph.D., Brown University.  

- JENNY FERGUSON  
  Assistant Professor of Creative Writing.  
  B.A., York University; M.A., University of Windsor; Ph.D., University of South Dakota.  

- LUCILLE GOODSON  
  Associate Professor of Art.  
  B.A., Black Hills State College; M.F.A., Indiana University.  

- SHARON GUTHRIE  
  Associate Professor of Nursing.  
  A.A., A.S., Kirkwood Community College; BSN, MSN, Ph.D., University of Iowa.  

- SHAWN P. HARMSEN  
  Assistant Professor of Communication Studies.  
  B.A., Wartburg College; M.A., University of Northern Iowa; Ph.D., University of Iowa.  

- CHRISTOPHER HATCHELL  
  Associate Professor of Religion.  
  B.A., Columbia University; M.A., Ph.D., University of Virginia.  

- GINA HAUSKNECHT  
  Professor of Literature and Creative Writing.  
  B.A., Oberlin College; M.A., Ph.D., University of Michigan.  

- DAVID HAYES  
  President, Professor of Business Administration.  
  B.A., Coe College; J.D., University of Iowa; L.L.M., University of Iowa Law School.  

- NANCY HAYES  
  Associate Professor of Education.  
  B.A., University of Illinois, Urbana-Champaign; M.A., Pennsylvania State University; Ph.D., University of Iowa.  

- STACY HAYNES-MOORE  
  Assistant Professor of Education.  
  B.A., Truman State University; M.A.T, Ph.D., University of Iowa.  

- WILLIAM KENT HERRON  
  Professor of Mathematics.  
  B.A., University of Dubuque; M.S., Ph.D., University of Iowa.  

- JEFFREY L. HOOVER  
  Professor of Philosophy.  
  B.A., Eastern Mennonite College; M.A., Ph.D., University of Notre Dame.  

- TERRY R. HOSTETLER  
  Professor of Mathematics and Computer Science.  
  A.B., Augustana College; M.S., University of Illinois; Ph.D., University of Iowa.  

- DANIEL F. HUGHES  
  Assistant Professor of Biology.  
  B.S., Humboldt State University; M.S., Shippensburg University; Ph.D., University of Texas at El Paso.  

- STEPHEN B. HUGHES  
  Associate Professor of Computer Science.  
  B.S., Dickinson College; M.S., Indiana University; Ph.D., University of Pittsburgh.  

- JOYCE M. JANCA-AJI  
  Associate Professor of French.  
  B.A., Southern Illinois University-Carbondale; M.A., Ph.D., Indiana University at Bloomington.  

- CHRISTOPHER JOHNSON  
  Assistant Professor of Education and African-American Studies.  
  B.S., Florida Agricultural & Mechanical University; M.E., Ph.D., The University of Georgia.  

- BETHANY A. KEENAN  
  Associate Professor of History.  
  B.A., Douglass College, Rutgers; M.A., The State University of New Jersey; M.A., Ph.D. University of North Carolina – Chapel Hill.  

- SCOUT KELLY  
  Assistant Professor of Psychology.  
  B.A., University of Puget Sound; M.A., Ph.D., Kent State University.  

- MEIRA Z. KENSKY  
  Professor of Religion.  
  B.A., Sarah Lawrence College; M.A., Ph.D., University of Chicago Divinity School.  

- ALEESA KITTRELL  
  Assistant Professor of Nursing  
  B.S.N. Mount Mercy University; M.S.N., Clarke University; D.N.P., Capella University.  

- SARAH KRESS  
  Assistant Professor of Education.  
  B.A., Coe College; M.S., Drake University.  

- ROBERT D. KUENNEN  
  Assistant Professor of Stead Department of Business Administration and Economics.  
  B.A., University of Notre Dame; M.B.A., University of Iowa.  

- KIMBERLY RAE LANEGRAN  
  Professor of Political Science.  
  B.A., Grinnell College; M.A., Ph.D., University of Florida.  

- KAYTI LAUSCH  
  Visiting Assistant Professor of Film Studies.  
  B.A., Cornell University; M.A., University of Texas at Austin; Ph.D., University of Michigan.  

- ELLEN LEE  
  Assistant Professor of Psychology.  
  B.S., Loyola University, Chicago; M.A., Ph.D., Northern Illinois University.  

- MARGARET LEMAY-LEWIS  
  Assistant Professor of English.  
  B.A., Barnard College; M.F.A., University of Iowa Writers’ Workshop.  

- JOHN PAUL LEMOS  
  Professor of Philosophy.  
  B.A., University of the South; Ph.D., Duke University.  

- CHELSEA LENSING  
  Assistant Professor of Stead Department of Business Administration and Economics.  
  B.A., Coe College; Ph.D., University of Iowa.  

- MICHAEL R. LEONARDO  
  Professor of Biology.  
  B.A., Knox College; M.A., Ph.D., Southern Illinois University, Carbondale.  

- CHAD LIBBY  
  Assistant Professor of Kinesiology; Director of Athletic Training Education.  
  B.S., Morningside College; M.S., Louisiana State University.  

- LUKE LOVEGOOD  
  Assistant Professor of Music - Choral Music Education  
  B.M., Coe College; M.M.E., VanderCook College of Music  

- RANELLE KNIGHT LUETH  
  Assistant Professor of Art History.   
  B.A., South Dakota State University; M.A., Ph.D., University of Iowa.  

- NEAL McNABB  
  Assistant Professor of Social and Criminal Justice.  
  B.A.; M.A., University of Central Oklahoma; Ph.D., University of Oklahoma.  

- LaTANYA McQUEEN  
  Assistant Professor of English and Creative Writing.  
  B.F.A; M.F.A., Emerson College; Ph.D., University of Missouri.  

- CARRIE MELCHER  
  Associate Professor of Stead Department of Business Administration and Economics.  
  B.S., Ohio State University; M.P.H., Drake University.  

- BRITTNEY MILLER  
  Associate Professor of Mathematics.  
  B.S., University of Southern California; Ph.D., Purdue University.  

- BRETT MOMMER  
  Visiting Assistant Professor of Biology  
  B.S., Iowa State University; M.S., Ph.D. University of Illinois, Champaign.  

- LAISSA RODRIGUEZ MORENO  
  Assistant Professor of Spanish.  
  B.A., Universidad Nacional de Colombia; M.A., Ph.D., University of Wisconsin – Madison.  

- BRUCE F. NESMITH  
  Professor of Political Science and Director of Washington Term.  
  B.A., North Central College; M.A., Ph.D., University of Illinois.  

- JANE NESMITH  
  Assistant Professor of Rhetoric, Director of Writing Center.  
  B.A., The College of Wooster; M.A., Indiana University; Ph.D., University of Iowa.  

- VINH Q. NGUYEN  
  Associate Professor of Stead Department of Business Administration and Economics.  
  B.A., National Economics University, Vietnam; M.B.A., Asian Institute of Technology, Thailand; Ph.D., Mississippi State University.  

- DAVID A. NORDMANN  
  Associate Professor of History.  
  B.A., Coe College; M.A., University of Kansas; Ph.D., Indiana University.  

- OLUWADAMILOLA OPAYEMI  
  Assistant Professor of Communications Studies.  
  M.S., Central Connecticut State University; Ph.D., University of Alabama.  

- NIALL PEACH  
  Assistant Professor of Spanish.  
  B.A., Durham University, St. Aidan’s College; M.A., Ph.D., Purdue University.  

- AMY PERRY  
  Assistant Professor of Stead Department of Business Administration and Economics.  
  B.B.A., M.A., University of Iowa.  

- KARA RECKER  
  Assistant Professor of Psychology.  
  B.S., Arizona State University; Ph.D., University of Iowa.  

- LAURA RISKEDAHL  
  Interim Director of Library Services.  
  B.A., University of Northern Iowa; M.A., University of Iowa.  

- KATIE RODGERS  
  Associate Professor of Sociology.  
  B.A., Coe College; M.A., Rutgers University; Ph.D., University of Oregon.  

- JENNIFER ROGERS  
  Associate Professor of Art.  
  B.A., Coe College; M.F.A., University of Minnesota.  

- AMY RUSSELL  
  Assistant Professor of Education.  
  B.S., Mount Mercy College; M.A., University of Iowa.  

- ELAINE CARR RYDZE  
  Assistant Professor of Kinesiology.  
  B.S., Michigan State University; M.A., University of Iowa.  

- MARTIN ALAN ST. CLAIR  
  Professor of Chemistry.  
  B.S., Butler University; Ph.D., California Institute of Technology.  

- PAULA J. SANCHINI  
  Professor of Biology.  
  B.A., Hartwick College; Ph.D., University of Colorado – Boulder.  

- BENJAMIN SCHMIDT  
  Instructor in Theatre Arts.  
  B.A., University of Iowa.  

- STEVEN SHANLEY  
  Associate Professor of Music.  
  B.M., University of Northern Iowa; M.E., University of Minnesota; M.A., Ph.D., University of Iowa.  

- AMBER SHAW  
  Associate Professor of English.  
  B.A., Rhodes College; M.A., Ph.D., University of Georgia.  

- KELLY SIEMS  
  Assistant Professor of Nursing.  
  B.S.N., Mount Mercy College; M.S.N.-Ed, Regis University; D.N.P., Clarke University.  

- STEVEN SINGLETON  
  Professor of Chemistry.  
  B.S., Fort Lewis College; Ph.D., University of Denver.  

- MELISSA SODEMAN  
  Professor of English.  
  B.A., University of Washington – Seattle; M.A., Ph.D., University of California – Los Angeles.  

- ANTONIO SPIKES  
  Assistant Professor of Rhetoric.  
  B.S., Georgia Southern University; M.A., Ph.D., Southern Illinois University.  

- CHRISTOPHER STEAD  
  Assistant Professor of Chemistry.  
  M.S., University of Manchester Institute of Science and Technology; Ph.D., Medical College of Georgia.  

- MICHAEL STOBB  
  Assistant Professor of Mathematical Science.  
  B.A., Humboldt State University; M.S., Humboldt State University; Ph.D., University of California.   

- PAUL STORER  
  Associate Professor of Biology.  
  B.S., Allegheny College; M.S., Duquesne University; Ph.D., Loyola University, Chicago.  

- SCOTT J. STOUDT  
  Associate Professor of Chemistry.  
  B.A., Pennsylvania State University; Ph.D., Michigan State University.  

- PETER JOHN THOMPSON  
  Professor of Art.  
  B.A., M.A., M.F.A., University of Iowa.  

- MICHELLE UMBARGER-MACKEY  
  Associate Professor of Nursing.  
  B.S.N., M.S.N., Ph.D., University of Iowa.  

- PATRICIA VALDERRAMA  
  Assistant Professor of English.  
  B.A., Princeton University; Ph.D., Stanford University.  

- DREW WESTBERG  
  Associate Professor of Economics.  
  B.A., Coe College; M.S., Ph.D., University of Missouri - Kansas City.  

- JONATHAN J. WHITE  
  Professor of Mathematics.  
  B.A., Coe College; M.S., University of Iowa; Ph.D., University of Oklahoma.  

- SUSAN WOLVERTON  
  Professor of Theatre Arts, Interim Associate Dean for Student Academics  
  B.A., Carleton College; M.F.A., University of Iowa.  

- HONGBO XIE  
  Instructor and Head of Library Technical Services.  
  B.S., Nanjing Institute of Meteorology, Nanjing, China; M.A., University of Iowa.  

- ANGELA ZISKOWSKI  
  Interim Provost and Dean of the Faculty; Associate Professor of History.  
  B.A., University of Cincinnati; M.A., Ph.D., Bryn Mawr College.  

### Faculty Emeriti
(Dates in parentheses indicate years of active faculty service.)

- CHARLES WILLIAM AUKEMA, M.F.A.  
  Professor of English, Emeritus (1971–2016).  

- JOHN A. BECKELMAN, M.F.A.  
  Robert O. Daniel Professor of Art, Emeritus (1978–2015).  

- JOHN E. BROWN  
  President, Emeritus (1982-2001)  

- EDMUND BURKE, Ph.D.  
  Professor of Humanities, Emeritus (1974–2012).   

- ROSEMARY F. CARROLL, Ph.D.  
  Henry and Margaret Haegg Distinguished Professor of History, Emerita (1971–2001).  

- JAMES P. COTTINGHAM, Ph.D.  
  Professor of Physics, Emeritus (1989–2011).  

- ROBERT DANIEL DREXLER, Ph.D.  
  William P. and Gayle S. Whipple Professor of English, Emeritus (1974–2016).  

- RICHARD D. DOYLE, M.A.  
  Professor, Emeritus; Director of Library Services and Director of Technology (1972–2010).  

- MARIA A. DEAN  
  Professor of Chemistry, Emeritus (1984–2020).  

- WENDY DUNN  
  Professor of Psychology , Emeritus (1980–2020).  

- ALLEN P. FISHER, Ph.D.  
  Stead Family Professor of Sociology, Emeritus (1978–2011).  

- HARLO HADOW, Ph.D.  
  Heins-Johnson Professor of Biology and Director of the Coe Wilderness Field Station, Emeritus (1977–2019).  

- JEANNINE HAMMOND, Ph.D.  
  Joanne M. Pochobradsky Professor of French, Emerita (1973–2006).  

- DWIGHT W. HANSEN, M.A.  
  Associate Professor of Stead Department of Business Administration and Economics, Emeritus (1978–2016).  

- TERRY L. HELLER, Ph.D.  
  Howard Hall Professor of English, Emeritus (1975–2013).  

- GLENN ALFRED JANUS, Ph.D.  
  Henrietta Arnold Professor of History, Emeritus (1971–2011).  

- ROGER P. JOHANSON, Ph.D.  
  Professor of Education, Emeritus (1986–2015).  

- DEAN MEREDITH KARNS, M.A.  
  Professor of Mathematics and Music, Emeritus (1960–1999).  

- BARBARA LAREW, Ph.D.  
  Elnora H. and William B. Quarton Professor of Business Administration and Economics, Emerita (1981–2017).  

- JAMES BRIAN LARKIN, Ph.D.  
  Professor of Spanish, Emeritus (1961–1990).  

- DONALD JOHN LISIO, Ph.D.  
  Henrietta Arnold Professor of History, Emeritus (1964–2001).  

- MARGIE VATHAUER MARRS, M.A.  
  Pearl M. Taylor Professor of Music, Emerita (1978–2014).  

- ROBERT L. MARRS, Ph.D.  
  The Esther and Robert Armstrong Professor of Rhetoric, Emeritus (1986–2014).  

- PETER N. McCORMICK, Ph.D.  
  Professor of Philosophy, Emeritus (1974–2018)   

- MICHAEL McDONALD, M.A.  
  Professor of Business Administration and Economics, Emeritus (1981–2005).  

- DAVID W. McINALLY  
  President, Emeritus (2013-2021)  

- TERRY FUELLING McNABB, Ph.D.  
  Professor of Education, Emerita (1995-2016); Associate Dean of the Faculty, (2010–2015).  

- EVELYN J. MOORE, Ph.D.  
  Professor of Nursing, Emerita (1983–2014).  

- THOMAS B. MOYE, Ph.D.  
  Professor of Psychology, Emeritus (1989–2017).  

- JERRY MICHAEL OWEN, Ph.D.  
  Alma A. Turechek Professor of Music, Emeritus (1969–2006).  

- JAMES R. PHIFER, Ph.D.  
  President of the College, Emeritus, and Professor of History, Emeritus (1985–2013).  

- MICHAEL E. PUFALL, Ph.D.  
  Professor of Theatre Arts, Emeritus (1976–2000).  

- JAMES H. RANDALL, M.A.  
  Stead Professor of English, Emeritus (1969–70; 1971–2010).  

- KURT E. REDBORG, Ph.D.  
  Professor of Biology, Emeritus (1988–2017).  

- MICHAEL L. SANDBERG, Ph.D.  
  Louie J. And Ella Pochobradsky Professor of Business Administration, Emeritus (1976–2007).  

- FLOYD SANDFORD, Ph.D.  
  Professor of Biology, Emeritus (1971–2005).  

- CALVIN VAN NIEWAAL, M.S.  
  Professor of Computer Science and John F. Yothers Professor of Mathematics, Emeritus (1981–2018).  

- STANLEY READ WATKINS, Ph.D.  
  Professor of Chemistry, Emeritus (1958–1993).  

- PETER PETTINER WICKHAM, Ph.D.  
  Henry and Margaret Haegg Distinguished Professor of Chemistry, Emeritus (1969–2000).  

- MICKEY TAI CHUIEN WU  
  George R. Baker Professor of Business Administration and Economics (1979-2019).  

- NŰKHET D. YARBROUGH, Ph.D.  
  Stead Family Professor of Psychology, Emerita (1985–2019).  

### Adjunct Faculty

- GEOFF CHAPLIN  
  Adjunct Assistant Professor of Religion.  
  B.A., Oberlin College; M.A., University of Chicago.  

- EMILY GANFIELD  
  Instructor in Theatre Arts; Costume Shop Manager/Supervisor.  
  B.A., Coe College; M.F.A., Purdue University.  

- JOE HALL  
  Instructor of Stead Department of Business Administration and Economics.  
  B.A., M.A., M.F.A., University of Iowa.  

- SHERIF IBRAHIM  
  Adjunct Assistant Professor of Chemistry.  
  B.S., University of Maryland; Ph.D., University of Iowa.  

- KARLA KEYES  
  Instructor of Biology.  
  B.A., Coe College; M.S., Washington University School of Medicine.  

- JOSHUA LANGSETH  
  Instructor in Humanities.  
  B.A., Concordia College; M.A., Ph.D., University of Iowa.  

- AMY LUTTINGER  
  Adjunct Assistant Professor of Biology.  
  B.S., Massachusetts Institute of Technology; Ph.D., Princeton University.  

- MEGUMI POTTER  
  Adjunct Instructor of Japanese.  
  B.A., University of Iowa; M.A., Baylor University.  

- KELLI MARIE RICE  
  Adjunct Instructor of Kinesiology.  
  B.A., Central College; M.A., University of Iowa.  

- KARLA STEFFENS  
  Assistant Professor of Theatre Arts and Gender and Sexuality Studies; Coordinator of Crimson Fellows Program.  
  B.A., Southern Illinois University; M.A., Johns Hopkins University; M.F.A., University of Iowa.  

- CHERISH STEPHENSON  
  Adjunct Instructor of Psychology.  
  B.A., Coe College; M.S., University of North Carolina at Chapel Hill.  

- JAMES WETZEL  
  Adjunct Instructor of Astronomy.  
  B.SC., University of Iowa.  

- BRETT A. WOLGAST  
  Assistant Professor of Piano; College Organist.  
  B.M., Kansas State University; M.A., M.F.A., D.M.A., University of Iowa.  

### Special Program Faculty

- ANNA DREXLER  
  Instructor and Director of English as a Second Language.  
  B.A., Coe College; M.F.A., University of Oregon.  

- KATHY WELSH  
  Instructor in English as a Second Language.  
  B.A., M.A., University of Iowa.  
