# ADMISSION 

Coe College students are motivated individuals who come from widely diverse geographic regions, economic backgrounds, and religious faiths, and who possess a variety of academic and extracurricular talents, abilities, and interests. When considering students for admission, Coe seeks to admit students who will contribute to, and benefit from, the academic and extra-curricular program. Applicants who have demonstrated strong academic achievement, intellectual curiosity, extracurricular participation, and community involvement are selected for admission. 

## Interviews and Visiting the campus 

Prospective students and their parents are always welcome at Coe. A campus interview is highly recommended, although not required, to support a student’s application for admission. A campus visit gives students an opportunity to determine if Coe is the best college for their particular needs, goals, and interests. Students desiring an interview at the Office of Admission should call (1.877.CALL.COE) or e-mail ( [admission@coe.edu]{.underlined} ) at least one week in advance requesting a specific hour for an appointment. Appointments are scheduled between 8 a.m. and 4 p.m., Monday through Friday, throughout the year, and between 9 a.m. and 12 noon on select Saturdays September through April.

## First-Year Applicants
### Academic Record 

Coe is a selective, private, nationally-recognized liberal arts college whose applicants are evaluated through a competitive admission process. The Office of Admission looks at a number of factors including high school academic record, class rank, standardized test scores, and involvement in high school or community activities.
 
For regular admission, a student’s minimum academic profile is expected to be at or above a 3.0 GPA (4-point scale), 20 ACT (1020 combined SAT), and within the top 40% of his or her graduating class. A student’s academic transcript should reflect a college preparatory curriculum with sufficient breadth to enable the student’s adjustment to a rigorous college liberal arts program. Four years of English; three years of mathematics, science, and history; and two years of world language are recommended for all students.

This academic profile is a general guideline, and students who have a lower GPA, standardized test score, or class rank may be requested to provide additional information (seventh term grades, personal statement, personal interview, etc.) for the evaluation process. Coe recognizes that many factors or circumstances may have affected a student’s high school performance and students who do not meet our regular admission standards are evaluated more thoroughly by the Office of Admission. Supporting recommendations may be provided by high school guidance counselors, teachers, and administrators. Some students may be accepted on a provisional status upon enrolling at the College. 

Students accepted with provisional status must register for one of the following during their first semester at Coe: 
- **{{< var c.skd115.long >}}** (0.3 credit) 
  {{< var c.skd115.desc >}} 
- **{{< var c.skd120.long >}}** (0.0 credit) 
  {{< var c.skd120.desc >}}
- **{{< var c.skd125.long >}}** (0.3 credit) 
  {{< var c.skd125.desc >}} 

A provisionally admitted student must successfully complete one of these three choices, and maintain a GPA above the College’s Minimum GPA Levels, see @{college-minimum-gpa-level} to have their provisional status removed. Failure to do so in the first semester of enrollment will subject students to academic probation for the second semester. 
 
### Standardized Test Scores 

The results of entrance examinations are considered as part of the student’s overall achievement record. Median SAT scores at Coe are in the mid to high 500s for both the verbal and mathematical sections. Similarly, the median ACT composite score is 26. 

### Methods of Application

Coe provides students with three application options and deadlines: 
	1. Students have the opportunity to apply for admission using a binding **Early Decision Plan**. It is understood that students will apply under one early decision plan. A completed application must be postmarked or electronically submitted no later than November 15^th^ to be considered for Early Decision. Applicants are notified by December15^th^ or as soon as possible after their files are complete. Three decisions can be given: admit, deny or defer to regular decision. If an applicant is admitted under early decision, they are expected to submit a $300 non-refundable enrollment fee.
	2. Students who wish to learn of an admission decision before the regular admission deadline may apply under the non-binding **Early Action Plan**. Students may apply at any time during the first term of their senior year. A completed application must be postmarked or electronically submitted no later than December 10 to be considered for Early Action. Applicants are notified by January 20^th^ or as soon as possible after their files are complete. All accepted applicants who intend to enroll at Coe must submit a $300 non-refundable enrollment fee by May 1 to reserve a place in the fall class. 
	3. Students applying under the **Regular Decision Plan** should have a completed application postmarked or electronically submitted by March 1^th^. Applicants are notified on or before March 15^th^ or as soon as possible after their files are complete. All accepted applicants who intend to enroll at Coe must submit a non-refundable $300 enrollment fee by May 1 to reserve a place in the fall class. 

Before an admission decision can be made, the Office of Admission must have received from each candidate:
	1. A completed application for admission
	2. Official results of either the SAT or ACT examination
	3. An official high school transcript

First-year candidates for admission may select either Coe’s application or the Common Application. All application forms, as well as instructions, may be obtained online at *www.coe.edu/apply.* 

Admission of high school seniors is contingent upon their maintaining a satisfactory record and completing high school graduation requirements. Final high school transcripts must be submitted to Coe College upon completion of the requirements for a high school diploma. The College reserves the right to withdraw its offer of admission, and refund the $300 enrollment fee when information received after the admission decision indicates the student will not benefit from or contribute to the Coe community. 

Following admission, but prior to enrollment, students are required to receive a physical examination from a health professional and to file a health report. The appropriate form is furnished by the College. 

## Transfer Applicants

Each year Coe welcomes a significant number of transfer and non-traditional students to the College. Successful candidates for admission will be those students who have been or are in satisfactory academic standing at their former college or university. Students who transfer to Coe from another institution, should see p.  for further information.

Admission notification is on a rolling basis. Once Coe receives a completed application for admission, including official transcripts from their high school and all colleges/ universities previously attended, students are notified of their admission status (see Evaluation of Credits in Transfer, @evaluation-of-credits-in-transfer ).
 
New students may enroll at the College at the beginning of the Fall Term or Spring Term. (Students should consult the Academic Calendar, @academic-calendar ) to determine which term is most appropriate for their educational plans.) 

## International Applicants

Students from other countries are encouraged to apply to Coe College. Applications should include the following information:
	1. Completed application for admission
	2. Official certified translated copy of all secondary school work and college (if applicable)
	3. Certified copy of all national exam results (‘O’ levels, ‘A’ levels, GCE, SLC, WAEC, etc.)
	4. Results from IELTS, TOEFL, etc. (if English is not first language) and SAT/ACT exams, GTEC CBT
	5. Completed financial documents (International Student Certification of Finances and certified bank statement). 

An English Language Academic Bridge Program exists for students with a TOEFL score between 500-520 pBT or 61-67 iBT.  A combination of English courses and degree-seeking courses will be provided for the first academic term.  

An intensive English as a Second Language Program is available for secondary school graduates with TOEFL scores below 520 pBT or 61 iBT. Coe has two International Student Advisors, and the Office of Diversity and Inclusion provides special orientation sessions for new students as well as ongoing assistance with U.S. immigration rules and regulations. 

## Post-Secondary Enrollment

Early admission procedures are available for mature, high-ability students wishing to enroll at Coe before completion of a normal secondary school course of study. These students should follow the regular application process and have strong recommendations from both the secondary school principal and counselor. 

## Deferred Admission

The deferred admission procedure is available for students wishing to defer their date of enrollment after being formally accepted to Coe College. These students should follow the regular application process indicating the month and date in which they wish to enroll. 

**NOTE**: *The College reserves the right to change admission procedures for any given year. All changes will be communicated directly to prospective students, parents, and counselors for that specific year.*
