# HISTORY OF COE COLLEGE {.unnumbered}

Adding some text.

Coe College claims the shortest name of any American institution of higher education, but the school has actually carried five titles through its history. When the Rev. Williston Jones founded the college in 1851, he called it The School for the Prophets. Cedar Rapids’ first resident minister opened the parlor of his home to a group of young men with the goal of educating them for the ministry to serve churches in the Midwest. Two years later, while Jones was canvassing churches in the East for money to send three of his students to Eastern seminaries, a Catskills farmer named Daniel Coe stepped forward with a pledge of $1,500 and urged Jones to start his own college in the frontier town of Cedar Rapids. Legend has it that the $1,500 raised by Coe was brought west from New York, sewn into the petticoat of a lady visitor traveling by stagecoach to Iowa. Coe gave this generous gift with the stipulation that the proposed institute should be “made available for the education of females as well as males.”  Accordingly, Coe was coeducational from its founding.

With Jones’ blessing, the Cedar Rapids Collegiate Institute was incorporated in 1853 by a group of Cedar Rapids leaders chaired by Judge George Greene. They used Daniel Coe’s money to purchase two downtown lots for the school and 80 acres of farmland on what was then the edge of town. The farm evolved into today’s campus. In 1868, in a failed attempt to secure the Lewis Parsons estate, the trustees renamed the school Parsons Seminary. After a period of severe financial difficulties, the institution was reestablished in honor of its original benefactor as the Coe Collegiate Institute in 1875.

T.M Sinclair, founder of the Sinclair Meat Packing Company, played the key financial role in the final step toward the firm establishment of Coe College. Sinclair liquidated all the debt from Parsons Seminary and the Cedar Rapids Collegiate Institute. The Sinclair gift made it practical for the property of the Coe Collegiate Institute—including the original land paid for by Daniel Coe—to be transferred to Coe College with the Iowa Presbyterian Synod to assume major responsibility for the institution. Coe College has operated continuously since its incorporation under that name on Feb. 2, 1881. From the first, the College was committed to intellectual excellence. It has continued in this tradition ever since.

The compact campus on the east edge of Cedar Rapids grew with many building projects in its early years, including Old Main (1868), Williston Hall (1881), Marshall Hall (1900), the first gymnasium (1904), and the first T.M. Sinclair Memorial Chapel (1911). In 1907, Coe earned accreditation from the North Central Association of Colleges and Universities. Over the decades, Coe’s reputation as a superior liberal arts college has continued to grow. One recognition of this came in 1949, when Coe was granted a Phi Beta Kappa chapter, a distinction reserved for about 10% of American colleges and universities.

Central to the educational philosophy of Coe College is the belief that a liberal arts education is the best preparation for life. Students have the opportunity to experience a variety of subjects outside their respective programs of study. Coe offers more than 40 areas of study that cover a range of fields. The College awards the following undergraduate degrees: Bachelor of Arts (B.A.), Bachelor of Music (B.M.), and Bachelor of Science in Nursing (B.S.N.). 

There are a number of factors that contribute to Coe College’s strong academic quality. The key to Coe’s tradition of excellence in academic quality relates directly to small class sizes and the interest shown by professors to make learning a personalized experience. At Coe, the average class size is 16, and the student-faculty ratio is 11:1. Classes are taught by our involved and committed faculty, 91% of whom hold the highest degree in their field. This means classes are taught by experienced professionals who have in-depth knowledge of their subjects. To provide students with a well-rounded experience and solid preparation for the future, Coe offers, along with quality instruction from superb faculty, an abundance of out-of-class opportunities which include student-faculty collaborative research, honors projects, service learning, and internships. Within one year of graduation, according to the annual survey results from the Center for Creativity and Careers, 98% of Coe graduates are engaged in post-graduate activity such as employment, graduate school, military, or travel/adventure.

With the addition of the east campus, Coe has nearly doubled in size since 1989. New facilities on the east side of College Drive include Athletic Recreation Center (2017), Clark Racquet Center and athletic fields (1989), Clark Alumni House (1993), Nassif House (1999), and four student apartment buildings (Morris House and Schlarbaum House in 2000, Brandt House and Spivey House in 2002). McCabe Hall (2005), named in honor of former Coe President Joseph E. McCabe, houses the offices of the president, provost, advancement and alumni relations, and The Center for Creativity, Careers and Community (C3) making way for the remodeling of Coe’s oldest building, Stuart Hall, and the first significant addition of classroom space since Peterson Hall was built in the 1960s.  In 2012 and 2013, Peterson Hall of Science was completely renovated to support Coe’s science programs.
To further enhance the campus environment, Coe completed the largest capital project in its history in 2017. Make Your Move – the Campaign for Eby and Hickok – included $24 million in essential enhancements, including an Athletic and Recreation Complex project as well as the renovation and expansion of Hickok Hall, one of the College’s main academic buildings. The result is vastly improved academic, recreational, wellness and competition facilities to benefit future generations of students.
