## THE ACADEMIC CALENDAR {.unnumbered}
The academic year consists of three terms (see Academic Calendar, p. 15).  Students normally take four course credits in the Fall Term and four course credits in the Spring Term. Thus, eight course credits are completed in an academic year.  During optional May Term, students may enroll for up to one course credit in one of the limited selection of courses.  Summer term is limited in scope and is not considered a regular term. (The maximum course load is described in Course Load, p. 53).


## MAY TERM (OPTIONAL) {.unnumbered}
Students may enroll for up to one course credit during May Term in one of the limited selection of courses.  All May Term courses require consent of instructor prior to registration.
May Term courses are designed to meet at least two of the following shared learning outcomes:

- Evaluate and engage with complex interdependent systems and demonstrate understanding across diverse contexts.
- Critically describe and break apart issues or problems through systematic analysis and illustrate logic for conclusions.
- Engage with experiential learning practices such as learning by doing, while utilizing abilities to think critically, problem solve and make connections between knowledge gained in the classroom and experience beyond.

May Term courses are expected to have the same amount of contact time and academic rigor per course credit as courses which meet over a Fall or Spring Term.  For every 1 course credit of May term students are expected to complete 140 hours of work.  Such contact time includes class meetings, lectures by the instructor, supervised course related activities and independent out of class activities.  Off-campus May Term courses at an off-campus location provide certain educational benefits through site visits, guest lectures, etc., that also contribute to the contact time for the course.

## COE PLAN {.unnumbered}
Coe College’s requirements for graduation, commonly known as the Coe Plan were developed with the following outcomes in mind:

- Creation of a bridge from high school to Coe College that helps students understand the importance of a liberal arts education, the ways to develop the skills needed by any learner, and the opportunities they will have by going to Coe College.
- Development of required curriculum that exposes the students to ways of learning in various contexts, big ideas in a myriad of disciplines, ways of being and understanding of cultures around the world, and processes to develop the skills needed by any learner.
- Creation of a bridge from Coe College to life after Coe.

These outcomes are met through the College’s First-Year Experience, General Education program, Writing Emphasis courses, and the College’s Practicum experiences and areas of study, described in this section of the Catalog.

## GRADUATION REQUIREMENTS {.unnumbered}

All students who graduate from Coe College must complete at least one major and earn at least 32 course credits (cc) with grades leading to a cumulative grade point average (GPA) of 2.0 or higher.  (The course is the unit of academic credit.)  Courses are one credit unless otherwise indicated.  Students are expected to complete 180 hours of work to earn one course credit, although class times vary from course to course.  Other institutions may convert Coe credit to their system by considering one course credit to be 6 quarter hours, or 4 semester hours.)  No more than a total of two course credits from courses which are less than 0.5 credit can be used to meet the 32-credit graduation requirement.  No more than eight course credits earned of Advanced Placement or International Baccalaureate credit can be used to satisfy this requirement.

Students must meet one of the following requirements:

- Complete at least the final academic year of required courses registered through Coe. 
- Earn a total of 16 course credits or the equivalent at Coe.  The last eight course credits needed for graduation must include at least four earned at Coe. Approved off-campus study programs and internships can be used to fulfill this requirement.  

A student may be simultaneously awarded two degrees (B.A., B.M., B.S.N.) after satisfactorily completing 40 course credits and the requirements for both degrees. However, a simultaneous Bachelor of Music plus a Bachelor of Arts with a music major is not permitted.

In addition, students must fulfill the requirements of the First-Year Experience, General Education, Writing Emphasis, and Practicum.

To participate in Commencement exercises, students must submit a completed Intent to Graduate form to the Office of the Registrar, preferably three terms prior to Commencement.  

### Second Baccalaureate Degree

A student who holds a baccalaureate degree from another institution may earn a second baccalaureate degree at Coe, if the following criteria are met:

- The first degree must be from a regionally accredited institution as recognized by the US Department of Education, or another appropriate accrediting body. 
- The first degree must be completed (not in progress) before beginning the second degree at Coe. 

Students accepted at Coe to pursue a second degree are granted a maximum of 24 course credits in transfer credit towards the 32 course credits required for graduation.  To graduate, at least eight course credits must be earned at Coe College and all requirements for the major area of study must be met with at least 40% of the major course credits taken at Coe.  Students must earn a cumulative GPA of at least 2.0 as well as meet any GPA or grade requirements in their area of study.

Second baccalaureate students are exempt from the following requirements: first-year experience, general education, writing emphasis, and practicum.  They are not eligible to graduate with Latin Honors or for induction in Phi Beta Kappa or Phi Kappa Phi.

### Transfer Student Information

To honor its mission and to preserve its academic integrity as a liberal arts institution, the College accepts a course in transfer if that course meets the spirit of the College’s mission and is from a regionally accredited institution.  This section includes information, in addition to that included in the section, Graduation Requirements (see p. 16), germane to students who are transferring to Coe College from another college or university.

Courses transferred to Coe can, as approved by the Registrar, fulfill some graduation requirements.  From institutions on a semester hour system (at Coe, 1 course credit = 4 semester hours), only courses with three or more semester hours can be used to fulfill any major or general education requirements. From institutions on other than a semester hour system, only courses equivalent to at least 0.75 course credits can be used to fulfill any major or general education requirement.  In some cases, in consultation with the Registrar, multiple courses within the same field may be used to fulfill one requirement.

Transfer credits earned after high-school graduation and before Coe matriculation count towards the eight term, full-time residence requirement (see p. 230).  Full-time enrollment may include participation in Coe College exchange programs, ACM off-campus study programs, and other approved off-campus study programs. 

All students must complete at Coe at least 40% of the total course credits required for each declared major or minor or three course credits, whichever is greater.  In addition to completing at least one major area of study, transfer students must abide with the following to complete the requirements for graduation:

- First-Year Experience.  Transfer students are not required to fulfill the requirements of the First-Year Experience, if they have completed at least one full-time college term since graduation from high school.
- Writing Emphasis. (See Writing Emphasis Courses, p. 21).
- General Education.  Requirements include Liberal Arts selections in the four divisional areas (Natural and Mathematical Sciences, Social Sciences, Humanities, Fine Arts) and Diverse Cultural Perspectives courses.  Any courses accepted in transfer for at least 0.75 course credit that fit the criteria of the Liberal Arts and/or Diverse Cultural Perspectives core groups can be applied towards the general education requirements as determined by the Registrar.  Advanced Placement and International Baccalaureate courses may not be used to meet any part of the General Education requirements.
- Academic Practicum.  Transfer students are required to fulfill this requirement.

