# FAST FACTS {.unnumbered}

**COE COLLEGE** is a private, four-year co-educational liberal arts college that was founded in 1851 and is historically affiliated with the Presbyterian Church (U.S.A.), yet is ecumenical in practice and outlook. 

### LOCATION

Coe is located just 225 miles west of Chicago in Iowa’s second largest city, Cedar Rapids (metropolitan population 175,000). The city is easily accessible by the interstate highway system, bus services and several airlines.  

### CAMPUS

Situated on 65 acres in the center of the metropolitan area, the campus is urban but enclosed, with 30 buildings occupying an attractive landscape.  

### ENROLLMENT

The student body of approximately 1,400 students represents most states and around 15 foreign countries. All students are required to live on campus unless they are residents of Cedar Rapids. 

### LIBRARY

Stewart Memorial Library is in the very center of the main campus. It contains over 500,000 volumes and 16,000 pieces of media, and subscribes to 3,500 print and online periodical subscriptions providing access to over 100 databases. Coe’s library offers students a variety of research assistance, study areas, a small theater, preview room, a media editing room, and a 3D printer and laser cutter. The Library houses the Learning Commons and the College's permanent art collection.

### ACCREDITATION

Coe College is accredited by the Higher Learning Commission (hlcomission.org), an institutional accreditation agency recognized by the U.S. Department of Education.  Coe College’s Bachelor of Music program is accredited by the National Association of Schools of Music; its education program is accredited by the Iowa Department of Education, and its Bachelor of Science in Nursing is accredited by the Commission on Collegiate Nursing Education (http://aacn.nche.edu/ccne-accreditation).  Coe College’s chemistry program is certified by the American Chemical Society.  Copies of accrediting and approval statements are available online at https://www.coe.edu/why-coe/consumer-information.

### MEMBERSHIPS

Coe is a charter member of the Associated Colleges of the Midwest, whose other members are: Beloit, Carleton, Colorado, Cornell, Grinnell, Knox, Lake Forest, Lawrence, Luther, Macalester, Monmouth, Ripon, and St. Olaf. Other memberships include: Phi Beta Kappa, Phi Kappa Phi, the National Association of Independent Colleges and Universities, the American Association of Colleges and Universities, Council on Undergraduate Research, the Association of Presbyterian Colleges and Universities, the American Rivers Conference, and the National Collegiate Athletic Association. 

### ACADEMIC PROGRAM

Academic areas of study are offered in managerial or public accounting, African American studies, art, art history, Asian studies, biology, business administration, chemistry, communication studies, computer science, creative writing, data science, economics, elementary education, English, film studies, French & francophone studies, interdisciplinary French & francophone studies, general science, history, international business, international economics, international studies, kinesiology, literature, mathematics, music (B.A. or B.M.), nursing (B.S.N.), philosophy, physics, political science, psychology, religion, social & criminal justice, sociology, Spanish, Spanish studies, theatre arts, and writing. Interdisciplinary and/or collateral majors are also available in biochemistry, environmental science, environmental studies, molecular biology, neuroscience, organizational science, and public relations. Coe also offers certificate programs in primary and secondary education. 

### EXTRA-CURRICULAR ACTIVITIES

Students can participate in 11 men’s and 11 women’s NCAA Division III varsity athletic teams, 5 coed varsity athletic teams, 8 club sports, 10 nationally affiliated men’s and women’s social fraternities, and 65 student organizations including but not limited to student government, newspaper, intramural sports, departmental clubs, and residence hall activities. Various vocal and instrumental ensembles are available for course credit. 

### FINANCIAL ASSISTANCE

Coe College is committed to assisting those families in need of financial assistance. The average aid package for incoming students enrolled during the 2021–2022 academic year totaled more than $48,000. The total cost of full-time tuition, room, board, and activity fee for the 2021–2022 academic year is $59,324.
