project:
  type: book
  pre-render: create_variable_list.py

execute:
  warning: false
  message: false
  output: asis
  freeze: true

book:
  title: "Course Catalog 2022-2023"
  date: "8/1/2022"
  cover-image: cover.png
  page-footer: "*Coe College Catalog (2022-2023)*"
  chapters:
    - index.qmd
    - catalog_sections/01_mission.qmd
    - catalog_sections/02_fast_facts.qmd
    - catalog_sections/03_academic_calendar.qmd
    - catalog_sections/04_education_program.qmd
    - catalog_sections/05_areas_of_study.qmd
    - catalog_sections/06_academic_advising.qmd
    - catalog_sections/07_first_year_experience.qmd
    - catalog_sections/08_writing_emphasis.qmd
    - catalog_sections/09_general_education_courses.qmd
    - catalog_sections/10_special_programs_and_opportunities.qmd
    - catalog_sections/11_off_campus_study.qmd
    - catalog_sections/12_campus_resources.qmd
    - catalog_sections/13_student_life.qmd
    - catalog_sections/14_college_regulations.qmd
    - catalog_sections/15_effective_catalog.qmd
    - catalog_sections/16_class_designation.qmd
    - catalog_sections/17_registration.qmd
    - catalog_sections/18_academic_integrity_policy.qmd
    - catalog_sections/19_academic_standing.qmd
    - catalog_sections/20_transcript_evaluation_policies.qmd
    - catalog_sections/21_ferpa_rights.qmd
    - catalog_sections/22_courses_of_instruction.qmd
    - catalog_sections/23_academic_programs.qmd
    - catalog_sections/24_departmental_programs.qmd
    - catalog_sections/25_reserve_officer_training_corps.qmd
    - catalog_sections/26_financial_information.qmd
    - catalog_sections/27_financial_aid_and_scholarship.qmd
    - catalog_sections/references.qmd

bibliography: references.bib
suppress-bibliography: true

toc: true
toc-depth: 2

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true
    template: custom.latex
    include-in-header:
      text: |
              \RedeclareSectionCommand[beforeskip=-2.5ex plus -1ex minus -.2ex,afterskip=0.3ex plus -.2ex]{section}
              \usepackage[top=0.5in, left=0.5in, right=0.5in, bottom=1in]{geometry}
              \bibliographystyle{catalog}
              \usepackage{makeidx}
              \makeindex
              \renewcommand\toprule[2]\relax
              \renewcommand\bottomrule[2]\relax
              \usepackage{fancyhdr}
              \lfoot{\textit{Coe College (2022-2023)}}
    include-after-body: 
      text: |
          \printindex
          
          
