project:
  type: book
  output-dir: docs
    #  pre-render: create_variable_list.py

execute:
  warning: false
  message: false
  output: asis
  freeze: true

book:
  title: "Course Catalog 2022-2023"
  date: "8/1/2022"
  cover-image: cover.png
  page-footer: "*Coe College Catalog (2022-2023)*"
  sidebar:
    search: true
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "INTRODUCTORY RESOURCES"
      chapters:
      - catalog_sections/01_mission.qmd
      - catalog_sections/02_fast_facts.qmd
      - catalog_sections/03_academic_calendar.qmd
      - catalog_sections/04_education_program.qmd
      - catalog_sections/05_may_term.qmd
    - part: "ACADEMIC RESOURCES"
      chapters:
      - catalog_sections/06_coe_plan.qmd
      - catalog_sections/07_graduation_requirements.qmd
      - catalog_sections/08_areas_of_study.qmd
      - catalog_sections/09_academic_advising.qmd
      - catalog_sections/10_first_year_experience.qmd
      - catalog_sections/11_writing_emphasis.qmd
      - catalog_sections/12_general_education_courses.qmd
      - catalog_sections/13_special_programs_and_opportunities.qmd
      - catalog_sections/14_off_campus_study.qmd
    - part: "CAMPUS RESOURCES"    
      chapters:
      - catalog_sections/15_campus_resources.qmd
      - catalog_sections/16_student_life.qmd
    - part: "COLLEGE REGULATIONS"  
      chapters:
      #- catalog_sections/17_college_regulations.qmd
      - catalog_sections/18_effective_catalog.qmd
      - catalog_sections/19_class_designation.qmd
      - catalog_sections/20_registration.qmd
      - catalog_sections/21_academic_integrity_policy.qmd
      - catalog_sections/22_academic_standing.qmd
      - catalog_sections/23_transcript_evaluation_policies.qmd
      - catalog_sections/24_ferpa_rights.qmd
    - part: "COURSES OF INSTRUCTION"
      chapters:
      #- catalog_sections/25_courses_of_instruction.qmd
      - catalog_sections/26_academic_programs.qmd
      - catalog_sections/27_departmental_programs.qmd
      - catalog_sections/28_reserve_officer_training_corps.qmd
    - part: "FINANCIAL RESOURCES"
      chapters:
      - catalog_sections/29_financial_information.qmd
      - catalog_sections/30_financial_aid_and_scholarship.qmd
    - catalog_sections/references.qmd

bibliography: references.bib
suppress-bibliography: true

toc: true
toc-depth: 2

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true
    template: custom.latex
    include-in-header:
      text: |
              \RedeclareSectionCommand[beforeskip=-2.5ex plus -1ex minus -.2ex,afterskip=0.3ex plus -.2ex]{section}
              \usepackage[top=0.5in, left=0.5in, right=0.5in, bottom=1in]{geometry}
              \bibliographystyle{catalog}
              \usepackage{makeidx}
              \makeindex
              \renewcommand\toprule[2]\relax
              \renewcommand\bottomrule[2]\relax
              \usepackage{fancyhdr}
              \lfoot{\textit{Coe College (2022-2023)}}
              \renewcommand{\part}[1]{\addcontentsline{toc}{part}{#1}}
    
    include-after-body: 
      text: |
          \printindex
          
          
