## African American Studies
Rodgers (Administrative Coordinator). 

The African American Studies major offers students the opportunity to study African American culture through an interdisciplinary approach.  Students take courses in areas such as literature, history, and sociology in order to gain a more complete understanding of the major figures and movements that helped define the culture.

### African American Studies Major 

A major in African American studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. AAM 107 Intro to African American Studies 
2. +++MISSING INFO: c.aam/eng137.long +++ 
3. HIS 347 African American History 
4. One of the following: 

  - HIS 145 History of United States to 1865 
  - HIS 155 History of United States since 1865 
  - HIS 227 American Civil War 
    
5. Five additional courses, at least three of which are numbered 200 or above, chosen from the following: 
  -**(a)** Elective courses:
    - AAM 217 Sport and Black Culture 
    - AAM 287 Topics in African American Studies 
    - AAM 367 Topics in AfricanAmericanLiterature 
    - AAM 387 Adv Topics in African American Stud 
    - +++MISSING INFO: c.aam447/457.long +++ 
    - AAM 467 Seminar in African American Lit 
    - AAM 494 Internship in African American Stds 
    - COM 236 Intercultural Communication 
    - COM 357 Sex, Race, & Gender in Media 
    - EDU 187 Human Relations 
    - HIS 145 History of United States to 1865 
    - HIS 155 History of United States since 1865 
    - HIS 227 American Civil War 
    - MU 157 Introduction to Jazz History 
    - SOC 247 Sociology of Race 

  -**(b)** Elective courses (when topic is appropriate):
	These courses can count toward the major or minor as determined by the African American Studies administrative coordinator. 
    - ARH 297 Topics in Art History: US Pluralism 
    - COM 157 Introduction to Media Analysis 
    - COM 161 Visual Rhetoric 
    - COM 361 Communication & Social Change 
    - ENG 107 Exploring Literature:US Pluralism 
    - ENG 207 Gender & Lit:US Pluralism 
    - ENG 347 Study in Modern or Contemp Amer Lit 
    - ENG 394 Directed Learning in English 
    - HIS 297 Women in America 
    - HIS 444 Ind Study-History 
    - HIS 472 Seminar American History I 
    - HIS 473 Seminar American History II 
    - SOC 237 Topics in Sociology:U S Pluralism 
    - SOC 464 Capstone Seminar in Sociology 
    - THE 488 Special Topics in THE/ FLM 

6. AAM 444 Ind Study-Afr-Am St (completed during the senior year)

### African American Studies Minor 
1. AAM 107 Intro to African American Studies     
2. +++MISSING INFO: c.aam/eng137.long +++ 
3. HIS 347 African American History     
4. One of the following:

  - HIS 145 History of United States to 1865 
  - HIS 155 History of United States since 1865 
  - HIS 227 American Civil War 

5. Two additional courses from either list **5a** or, when appropriate, **5b** as listed above for the major 

### COURSES IN AFRICAN AMERICAN STUDIES

- **AAM 107 Intro to African American Studies** 
What is African American culture, and what accounts for its cultural distinctions? This course introduces students to the study of African American culture and the field of African American Studies. through an interdiciplinary approach (literature, history, music, art and film) students will examine central themes and key debates pertinent to African American culture and history from its beginning to present.
- **AAM 137 African American Literature** 
Reading and discussion of the writings of African Americans, with emphasis on the 20th century. May include some relevant writings on African Americans by other groups. Study of the artistic values and of the social and cultural significance of these writings. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different.
- **AAM 217 Sport and Black Culture** 
Examines through cultural analysis the complex relationships between sport and Black culture. This course addresses the way sport has evolved from being merely a physical activity to a cultural expression in Black communities. This course emphasizes the historical patterns and current conditions of Blacks; participation in sport through various articles, videos, and books. The course also examines how many Black people have used sport as a means of resistance, survival, and social mobility. Students learn to analyze cultural expression, to understand race and its continuing impact in American life, and to understand how various sports pursuits by Black athletes are invested with multiple meanings.Major topics and themes covered include: the concept of race, Black culture, the historical presence of Black athletes in sport, their current impact, and their dominance in certain sports.
- **AAM 227 Blackness & Identity in America** 
Gathers a wide range of scholarship about race and identity to explore what race is, why it matters, racial dynamics in organizations, and how best to address them. Students will explore questions of identity, privilege, ethnicity, gender, and class. In this course,  201crace 201d is reviewed as a shorthand for the interconnected complexity of race, ethnicity, culture, and color, and will be carefully analyzed to distinguish among such terms and ideas. Students will critically analyze the social construct and the popular understandings of race and identity as reinforced through cultural institutions. Students will understand and evaluate the foundational concepts and theories of race and identity and synthesize their knowledge through research, presentation, and writing.
- **AAM 287 Topics in African American Studies** 
Examines an important theme or subject specific to African American experiences and culture. Content varies and is determined by the instructor. Students learn to understand African American experiences in context, to analyze texts and events from multiple disciplinary perspectives, and to write in clear, analytical prose. May be taken more than once for credit, provided the topics are substantially different.
- **AAM 367 Topics in AfricanAmericanLiterature** 
nan
- **AAM 387 Adv Topics in African American Stud** 
Examines an important theme or subject specific to African American experiences and culture. Content varies and is determined by the instructor. Students learn to understand African American experiences in context, to analyze texts and events from multiple disciplinary perspectives, and to write in clear, analytical prose. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to African American Studies (AAM-107) or consent of instructor.
- **AAM 444 Ind Study-Afr-Am St** 
Study of individually chosen research topics in African American studies under the direction of a faculty member in the area. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: Introduction to African American Studies (AAM-107) or African American Literature (AAM-137); consent of African American Studies administrative coordinator and submission of a written proposal for a project.
- **+++MISSING INFO: c.aam447/457.long +++** 
+++MISSING INFO: c.aam447/457.desc +++
- **AAM 467 Seminar in African American Lit** 
Intensive study of selected works and subjects in African American literature. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different. Prerequisites: junior standing and The Art of Literary Research (ENG-301). May be taken more than once.
- **AAM 494 Internship in African American Stds** 
nan 
