## Accounting {#sec-accounting}

Students majoring in accounting have two options: the managerial accounting major and the public accounting major. The managerial accounting major is designed for students interested in pursuing a career in private industry or the not-for-profit sector. The public accounting major is designed for students interested in practicing public accounting and those desiring the Certified Public Accounting (CPA) designation. Because of the identical core course requirements in the managerial accounting and public accounting majors, only one of the two majors can be elected by a student. A student receiving a managerial accounting major may pursue a post-baccalaureate major in public accounting, but when completed, the public accounting major would replace the managerial accounting major in the student’s records. 

Requirements for becoming a CPA differ from state to state. All states require that students pass the Uniform CPA examination and many require the completion of 150 semester hours of education prior to certification. The 150 hours can be completed in undergraduate or graduate programs. To become a CPA in Iowa, the Iowa State Board of Accountancy requires that students pass the CPA examination, complete 150 semester hours of education, and complete specified course work in accounting and business subjects. Students majoring in accounting, business, or economics are required to have a minimum of 24 of their 150 semester hours in financial accounting, auditing, taxation, and management accounting courses above the elementary level. If students majoring in any other field wish to become a CPA in Iowa, they must, in addition, complete at least 24 semester hours in business-related courses (not including internships). (One course credit completed at Coe is counted as four semester hours.)  Accounting students at Coe should work closely with faculty in the department to determine their plan of study. Students wishing to become a CPA should also check the state board’s education requirements for the state in which they wish to practice.

### Managerial Accounting Major

A major in managerial accounting requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. ACC 171 Principles of Accounting I
2. ECO 175 Principles of Macroeconomics
3. BUS 190 Statistical Analysis
4. ACC 215 Principles of Accounting II
5. ECO 215 Prin Microeconomics
6. ACC 301 Intermediate Accounting I
7. ACC 315 Managerial Accounting
8. BUS 315 Business Law I
9. ACC 334 Computer Applications - Accounting
10. ACC 351 Intermediate Accounting II
11. ACC 413 Auditing
12. ACC 415 Adv Managerial Accounting

### Public Accounting Major

A major in public accounting requires a minimum cumulative 2.0 GPA in all courses counted toward the major. Students wishing to prepare for the examination to become a Certified Public Accountant should select the Public Accounting major, which meets the guidelines for the breadth of business and accounting courses recommended by The American Institute of Certified Public Accountants. Students at Coe can meet the 150-semester hour requirement by completing 37.5 credits.

If degree requirements are not completed by the end of four years, students pursuing a major in public accounting, who are in good academic standing, and who are full-time students, receive a 60% discount on tuition in the consecutive fifth year. They continue to be eligible to apply for student loans and any available federal and state government grants

1. ACC 171 Principles of Accounting I
2. ECO 175 Principles of Macroeconomics
3. BUS 190 Statistical Analysis
4. ACC 215 Principles of Accounting II
5. ECO 215 Prin Microeconomics
6. ACC 301 Intermediate Accounting I
7. ACC 315 Managerial Accounting
8. BUS 315 Business Law I
9. ACC 334 Computer Applications - Accounting
10. ACC 351 Intermediate Accounting II
11. ACC 413 Auditing
12. ACC 422 Tax Accounting
13. ACC 463 Advanced Auditing
14. **One** of the following:

    - BUS 410 Business Law II
    - BUS 412 Entrepreneurship & New Business Frm
    - BUS 464 Seminar in Management
    - BUS 470 Strategic Management

15. **Three** of the following:

    - ACC 313 Fraud Examination
    - ACC 401 Fund Acctg & Adv Top
    - ACC 451 Advanced Accounting
    - ACC 472 Advanced Tax Accounting

### Courses in Accounting

 **ACC 171 Principles of Accounting I**  
A study of the accounting process and preparation of financial statements, primarily for external reporting purposes. Includes analyses of asset and liability accounts and owners’ equity accounts of corporations.  
 **ACC 215 Principles of Accounting II**  
Continuation of the study of financial accounting, including the statement of cash flow. A study of managerial accounting and the analysis of financial information for management decision making. Prerequisite: Principles of Accounting I (ACC-171).  
 **ACC 301 Intermediate Accounting I**  
An in-depth study of financial accounting topics. Emphasis is on income determination, evaluation, and presentation of assets, liabilities, and owners’ equity. Prerequisite: Principles of Accounting II (ACC-215).  
 **ACC 313 Fraud Examination**  
An examination of real world cases that represent the many types of accounting fraud in order to gain an understanding of the behavioral and social factors that motivate offenders. Emphasis is placed on understanding the exposures to loss and the appropriate prevention, detection, and investigation approaches, including legal requirements for testifying as an expert witness. Prerequisites: Principles of Accounting II (ACC-215) or consent of instructor. (Offered alternate years)  
 **ACC 315 Managerial Accounting**  
A study of the principles of managerial accounting and the methods of analyzing financial information. Includes analyses of accounting for the costs of production and the use of various decision models for planning and control. Prerequisite: Principles of Accounting II (ACC-215).  
 **ACC 334 Computer Applications - Accounting**  
An introduction to specialized accounting software used in financial accounting, tax accounting, and auditing. Application of generalized software to topics covered in managerial accounting and financial accounting. S/U basis only. Prerequisites: Computers in Business (BUS-125) or knowledge of Excel, junior standing, and completion of at least three upper-level accounting courses or consent of instructor. (0.5 course credit)  
 **ACC 351 Intermediate Accounting II**  
A continuation of Intermediate Accounting 1 ACC-301. Prerequisite: Principles of Accounting II (ACC-215).  
 **ACC 401 Fund Acctg & Adv Top**  
Fiduciary accounting, accounting for not-for-profit entities, consignment sales, and other advanced accounting topics. Prerequisite: Intermediate Accounting I (ACC-301) and Intermediate Accounting II (ACC-351). (Offered alternate years)  
 **ACC 413 Auditing**  
A study of the audit function primarily as it relates to the independent CPA. An integration of auditing theory and practice in an environment of legal liability and professional responsibility. Prerequisites: Principles of Accounting II (ACC-215) and junior standing, or consent of instructor. (Offered alternate years)  
 **ACC 415 Adv Managerial Accounting**  
A continuation of the study of managerial accounting and the methods of analyzing financial information. Topics covered include management control systems, pricing decisions, operations management, and regression analysis. Prerequisite: Managerial Accounting (ACC-315) or consent of instructor.  
 **ACC 422 Tax Accounting**  
A study of the federal income tax system with an emphasis on individual taxation. Development of a basic understanding of gross income, exclusions from gross income, and deductions which pertain to individuals, corporations, and partnerships. Prerequisite: Principles of Accounting II (ACC-215). (Offered alternate years)  
 **ACC 451 Advanced Accounting**  
A study of business combinations, international business transactions, international subsidiaries, fund accounting, and accounting for partnerships. Prerequisite: Intermediate Accounting (ACC-301/-351). (Offered alternate years)  
 **ACC 463 Advanced Auditing**  
A continuation of Auditing (ACC-413) with emphasis on special reports, compilation and review services, and additional current auditing topics. Auditing theories and practices are presented in a manner which enables the student to conceptualize the entire audit process. Prerequisite: Auditing (ACC-413). (Offered alternate years)  
 **ACC 472 Advanced Tax Accounting**  
A continuation of Tax Accounting (ACC-422) with an emphasis on taxation of corporations, “S” corporations, partnerships, estates, and trusts. Development of a basic understanding of tax research methodology. Prerequisite: Tax Accounting (BUS-445). (Offered alternate years)  

### Courses in Business

 **BUS 105 Colloquium in Business**  
A study of the dynamic world of business, with emphasis on the role of the individual as a consumer, a manager, an employee, and an investor. Such topics as the social responsibility of business, business environment, and the relationship of business to governments and to people are included.  
 **BUS 125 Computers in Business**  
An introduction to computers in business. Topics covered include the most commonly encountered software used for word processing, database management, and spreadsheets.  
 **BUS 145 Personal Financial Analysis & Plan**  
A study of important personal financial decisions made over an individual’s lifetime. This course provides the perspective and tools needed to make intelligent personal financial decisions. The course also challenges students to look at current events affecting personal finance from a public policy perspective, allowing them to develop informed opinions. Topics covered include understanding personal income taxes, buying a home, using credit wisely, and planning for retirement, among others. Open to all students. This course does not satisfy any of the requirements for a major in Business Administration.  
 **BUS 170 Bus Sustainability & Environment**  
Examines the global trend of the increasing attention organizations are giving to environmental and sustainability issues, including evaluation of successful business practices being pursued by leading corporations. Consideration is given to why and how corporations are embracing such trends. Topics covered include eco-labeling, corporate environmental strategies, NGO-business partnerships, and emerging markets for environmental goods and services. Significant attention is given to global warming concerns and the emerging strategies for measuring and reducing the carbon footprint of business.  
 **BUS 190 Statistical Analysis**  
Methods of statistical analysis and decision-making in business research and the behavioral sciences. Topics are selected from analysis of variance, regression analysis, factor analysis, time series analysis, and statistical decision theory. Prerequisite: The equivalent of three years of secondary school mathematics or consent of instructor.  
 **BUS 250 Principles of Management**  
A study of the general principles of management that are applicable to any organization with an established set of goals and objectives. This course analyzes the four major managerial functions of planning, organizing, leading, and controlling, and introduces the topics of international management and managerial ethics. Prerequisite: sophomore standing.  
 **BUS 255 Intro Management Science**  
The construction and use of mathematical models for making business decisions. Models studied include linear programming and related algorithms, project scheduling, waiting lines. Prerequisites: competency in algebra and junior standing or consent of instructor.  
 **BUS 280 Business Websites**  
An examination of the form, function, and creation of B2C (business-to-consumer) and B2B (business-to-business) websites. Students conduct research, develop a fictional business proposal, and build a basic website that promotes products and/or services to businesses or end-user consumers. This course does not, on its own or in combination with another 0.5 course, count as one of the two business electives required for a business major. (0.5 course credit)  
 **BUS 281 Social Media in Business**  
A survey of social media solutions utilized in the business environment with an emphasis on software usage. Learner-centered research and hands-on experience provide students with a solid understanding of current best practices. Applications explored include: LinkedIn, Skype, FaceTime, YouTube, Facebook, Yelp, Google+, Pinterest, Tumblr, Twitter, Instagram, and Kickstarter. This course does not, on its own or in combination with another 0.5 credit course, count as one of the two business electives required for a business major. (0.5 course credit)  
 **BUS 285 Computer Appl:Adv Top**  
Advanced computer applications courses on selected topics covered in business. Example topics: Management Science, Database Management, Marketing Publications. May be taken more than once for credit, provided the topics are substantially different. Prerequisites: Computers in Business (BUS-125) or consent of instructor. Some topics may require completion of or concurrent registration in relevant courses in the department. (0.5 course credit)  
 **BUS 300 Human Resource Management**  
A study of the theories, policies, and institutional forces that affect the human resource manager. This course analyzes managerial decisions regarding staffing, compensation, training, appraising, safety/ health, industrial relations, and the employment laws and environmental factors affecting human resource management. Prerequisite: sophomore standing.  
 **BUS 305 Production & Operations Mgmt**  
A study of the design, planning, and control of the factors that affect operations, including how to use labor, facilities, and equipment to manufacture finished goods or provide services. Prerequisites: competency in algebra and junior standing or consent of instructor.  
 **BUS 315 Business Law I**  
Introduction to law as an agency of control in the business world. Special attention to contracts, agencies, sales, negotiable instruments, and other types of contracts commonly used in the business world. Prerequisite: sophomore standing.  
 **ECO 315 Intermediate Macroeconomic Theory**  
See @sec-economics  
 **ECO 320 Public Finance**  
See @sec-economics  
 **ECO 325 Collectve Bargaining**  
See @sec-economics  
 **BUS 330 Principles of Marketing**  
A study of the basic principles of marketing including the analysis of market opportunities, market segmentation, and product positioning. Emphasis is placed on consumer markets and the development of marketing strategy using the variables of product, price, promotion, and distribution. Prerequisite: sophomore standing.  
 **BUS 340 Applied Regression Analysis**  
Introduction to the construction and use of regression models. Topics include estimation and inferential techniques in Simple and Multiple Regression; consequences of violations of the assumptions of the Classical Linear Regression model; regression with qualitative dependent variables.  
 **BUS 341 Introductory Business Analytics**  
A spreadsheet-based introductory course to business analytics. Emphasis is placed on fundamental knowledge and practical skills for applying data analysis to business decision making. Topics include data collection, statistical distributions, linear regression, forecasting, simulation, and optimization. Prerequisite: Statistical Analysis (BUS 240) or consent of instructor.  
 **BUS 345 Regulation of Business**  
Includes an examination of the social and economic impact of control legislation such as the Sherman Act, Clayton Act, Federal Trade Commission Act, Wagner Act, Securities Exchange Act, and many others. Prerequisites: Principles of Macroeconomics (ECO-205) and Principles of Microeconomics (ECO-215).  
 **ECO 345 Intermediate Price Theory**  
See @sec-economics  
 **BUS 350 Principles of Finance**  
A survey of securities markets and financial institutions and an introduction to finance and development in finance theory. Practices of personal and business finance decisions are also included. Prerequisites: Principles of Macroeconomics (ECO-205), Principles of Microeconomics (ECO-215), and Principles of Accounting II (BUS-215).  
 **BUS 352 Corporate Finance**  
A study of the major theories and models for planning and analyzing the working capital position, the financial structure, the cost of capital, and the capital budgeting of a business firm. Prerequisite: Principles of Finance (BUS-350).  
 **BUS 365 Principles of Insurance**  
Insurance as a method of dealing with business and personal hazards. Types of insurance in the life, fire, and casualty fields. Social Security measures and personal insurance programs. Social and economic significance of the insurance industry. Prerequisite: junior standing.  
 **BUS 375 Business Ethics**  
A study of some of the central ethical issues in the business world and some of the various ethical theories that might be employed in thinking about solutions to these problems. Topics likely to be covered include affirmative action, sexual harassment, whistleblowing, product safety standards, labor relations, advertising, and environmental issues. Prerequisite: sophomore standing or consent of instructor.  
 **ECO 375 Econometrics**  
See @sec-economics  
 **BUS 387 Adv Top:Human Res Mgt**  
Expands on some of the traditional material presented in the Human Resource Management course. Contemporary issues in the workplace which affect the nature of the relationship between the organization and the employee are discussed. Prerequisite: Human Resource Management (BUS-245).  
 **BUS 395 Organizational Behavior**  
Combines theory and practice to investigate human behavior in organizations. Topics at the macrolevel (history, culture, design, communications, total quality), human-level (perception, personality, attitudes, learning, stress), and group-level (team and organization development), and their influences on organizational effectiveness are examined. Prerequisite: Principles of Management (BUS-275).  
 **BUS 400 Legal Issues in Sports**  
A study of the legal aspects for the operations and administration of sports programs, competitive athletic programs, and community and commercial fitness programs. Topics such as risk management, gender equity, dipute resolution, and negotiation are included. Prerequisites: SMT-100: Introduction to Sports Management and BUS-315: Business Law I.  
 **BUS 410 Business Law II**  
An extended study of traditional business law subjects, with the addition of Federal Securities Regulation, secured transactions, suretyship, and accountant’s legal responsibility. Special attention is also given to agency, bankruptcy, and estates and trusts. Prerequisite: Business Law I (BUS-315).  
 **BUS 412 Entrepreneurship & New Business Frm**  
Analysis of the role of the entrepreneur in the capitalist economy. Development of the procedural system for establishing a new business. Establishment and operation of a “small business” by teams of students, including presentation of a business plan in order to secure financing with a local financial institution, acquisition of tax information necessary for start-up and continued operations, and analysis of problems confronting the new or small enterprise. Prerequisite: senior standing or consent of instructor.  
 **BUS 420 Sports Marketing and Communications**  
An introduction to the field of sports marketing and its role within sports organizations. Marketing mix, marketing research, and consumer behavior principles are used in studying topics such as sport sponsorships, branding, licensing, endorsements, naming rights, sales, fundraising, and public relations. Prerequisites: SMT-100: Introduction to Sports Management and BUS-330: Principles of Marketing.  
 **BUS 437 Strategic Compensation**  
A study of compensation systems used in organizations. This course looks at ways to develop, administer, and maintain compensation plans that attract and motivate employees while controlling labor costs. It covers such topics as the strategic importance of compensation; different types of compensation; designing competitive pay systems and employee benefits; and compensation for executives, expatriates, and contingent employees. Prerequisite: Human Resource Management (BUS-245).  
 **BUS 441 Advanced Business Analytics**  
A project-based, advanced study of buysiness analytics. The course offers training of coding with a computer programming language. No prior knowledge of coding is required. Topics learned in Introductory Business Analytics will be implemented in the context of computer coding. A term project with real-world applications is also required. Prerequisite: Introductory Business Analytics (BUS 341).  
 **BUS 444 Ind Study-Bus Admin**  
Independent studies under the direction of a faculty member in some area of business administration or economics. May be taken for an X status grade with consent of instructor prior to registration.  Prerequisite: consent of instructor.  
 **BUS 446 International Business Management**  
An introduction to the concepts of international business and the global economy. Topics include the impact of national and cultural differences on global business; cross-cultural communication, negotiation, and decision making; international human resource management; international trade theory; cross-border trade and investment; and global business strategy development. Prerequisite: Human Resource Management (BUS-300) or Principles of Management (BUS-335).  
 **ECO 446 International Econ**  
See @sec-economics  
 **BUS 454 Research in Business**  
The student works on a research program in business, independently or in participation with a business department faculty member. May be taken for an X status grade with consent of instructor prior to registration.  Prerequisites: junior standing and consent of instructor.  
 **BUS 457 Employment and Discrimination Law**  
Examines the legal regulation of the employment relationship. Extensive coverage of federal workplace discrimination statutes is featured, with particular consideration of Title VII, the ADEA, and the ADA. Significant attention placed on recent Supreme Court decisions and Congressional responses. Additional issues addressed may include employment-at-will and its exceptions, vicarious liability of employers for employee tort, and employee privacy concerns. 
Prerequisites: Human Resource Management (BUS-245) and Business Law I (BUS-315).  
 **BUS 460 Advertising**  
A study of the basic practices and concepts of advertising. Advertising is studied in the broader context of integrated marketing communications, including public relations and sales promotion. Topics to be covered include historical, legal, and ethical concepts of advertising and other forms of promotion, the management and planning of advertising, creativity in advertising, media planning, and advertising research. Prerequisite: Marketing (BUS-355).  
 **BUS 461 Marketing Decision Making/Analysis**  
A continuation of the study of marketing principles with special emphasis on understanding marketing as the basis for management decision-making. Topics to be covered include customer relationship management, market-oriented strategic planning, brand asset management, buyer behavior analysis, the use of marketing research to identify and target customers, and integrated marketing communications planning. Prerequisites: Marketing (BUS-355).  
 **BUS 464 Seminar in Management**  
Development of written and oral communication proficiency through an intensive study of one or more selected topics in management. Topics are studied through the use of readings, class discussions, writings, and presentations, and vary from term to term. May be taken more than once for credit, provided the topics are substantially different. Prerequisites: senior standing and at least one course in management [Principles of Management (BUS-250), Human Resource Management (BUS-300), or Organizational Behavior (BUS-395)], or consent of instructor.  
 **BUS 465 Advanced Topics in Marketing**  
An advanced study of a major topic in marketing. May be take more than once for credit, provided the topics are substantially different. Example topics: marketing research, international marketing, and sales management. Prerequisite: Marketing (BUS-355).  
 **BUS 466 Adv Top Mrktg:non-west persp**  
Same as Advanced Topics in Marketing (BUS-465), except the course focuses on topics related to non-Western cultures.  
 **BUS 467 Consumer Behavior**  
A study of the behavioral aspects of marketing with an emphasis on consumer markets. Various models of consumer decision-making are examined. Influences on consumer behavior are studied from both an individual perspective, including topics such as personality, perception, learning and attitudes, and a social perspective, including topics such as culture, social class, reference groups, and family. Prerequisite: Marketing (BUS-355).  
 **BUS 470 Strategic Management**  
A study of strategic management principles and the application of these principles to problems encountered by managers at all levels in large and small, for-profit and not-for-profit organizations. An advanced course in case studies to be taken near completion of the major. Prerequisite: junior standing.  
 **BUS 472 Advanced Topics in Finance**  
An advanced study of a major topic in finance. Example topics include quantitative methods in finance, behavioral finance, the evolution of financial thought, alternative investments, fixed income management, portfolio management, and derivatives. May be taken more than once for credit, with consent of department chair, provided the topics are substantially different. Prerequisite: Principles of Finance (BUS-350).  
 **BUS 475 Advanced Topics in Management**  
An advanced study of a major topic in management. Example topics: organizational theory, international management, negotiation, management information systems, and organizational change. May be taken more than once for credit, with consent of department chair, provided the topics are substantially different. Prerequisite: Principles of Management (BUS-275).  
 **BUS 476 Ad Top Mgmt:non-west persp**  
Same as Advanced Topics in Management (BUS-475), except the course focuses on topics related to non-Western cultures. Prerequisite: Principles of Management (BUS-275).  
 **BUS 485 Investment Fund Management**  
Examines financial asset portfolio construction and maintenance strategies used in the long-term management of an investment fund. Topics in this seminar include when to sell financial assets, how to evaluate mutual funds and exchange traded funds (ETFs), and the benefits of asset class diversification. Students will study the Birkey Investment Fund portfolio and make recommendations on rebalancing the portfolio through adjustments to its stock portfolio and its mutual fund and ETF holdings. Prerequisite: Research in Business (BUS-454) or permission of instructor. This course does not, on its own or in combination with another 0.5 credit course, count as one of the two business electives required for a business major. (0.5 course credit) (Offered Spring Term)  
 **ECO 485 Mathematical Economics**  
See @sec-economics  
 **BUS 494 Internship in Business**  
A work experience with a business organization involving opportunities, experiences, and personal growth which can be evaluated in equivalent terms to traditional course work. In most circumstances such experience shall count for one course credit. On-site work plus academic work must total a minimum of 160 hours (140 of which must be spent on-site.) In exceptional situations where an internship presents significant theoretical or practical ways to augment or extend traditional classroom experiences, two course credits are available. (See p. 17) S/U basis only. This course does not satisfy any of the requirements for a major in business administration. Prerequisites: Candidates must meet GPA and departmental residency requirements. All candidates must have the consent of a supervising faculty member of the department and consent of department chair. Students seeking more than one course credit must further have approval of the Department Internship Review Committee.  
 **BUS 495 Investment Analysis**  
A study of the fundamental principles underlying investment decisions. The course offers a basic understanding of the nature of risk and return considerations, the valuation framework for financial assets and derivatives, and introduction to the concepts of modern portfolio theory. Prerequisite: Principles of Finance (BUS-350).  
 **ECO 495 International Finance**  
See @sec-economics  
