## Art History

### Art History Major 

A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in art history.
An Art History major may also complete an Art minor, but only two courses may count toward both the major and the minor.


1. ARH 128 Introduction to Art History    
2. Two 200-level ARH courses  
3. Two additional courses approved by the department, chosen from the following:  
    - Courses in Art History (ARH-___)  
    - ANT 125 Art & Archaeology Classical World  
    - HIS 318 Topics in History :Div West Persp  
    - COM 161 Visual Rhetoric  
    - FLM 225 Film History  
    - COM 357 Sex, Race, & Gender in Media  
4. One of the following  
    - ARH 307 Modern and Contemporary Art  
    - ARH 310 Contemporary Art, Theory &Criticism  
5. ARH 464 Senior Seminar I  
6. ARH 474 Senior Seminar II   
7. One 100- ART course  
8. One 300-level ART course  

note: Scheduling may be planned to allow at least one term of study off-campus at one of the approved foreign or domestic programs. With departmental approval, up to three courses from these programs may count toward either the two 200-level courses in item 2 or the two additional courses in item 3.

Students interested in art history or visual culture at the graduate level should complete Intermediate French I (FRE-215).

### Art History Minor

A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in art history.


1. ARH 128 Introduction to Art History  
2. Three additional art history courses, one of which must be ARH-200 or above.  Can also include one of the following:  
   - ANT 125 Art & Archaeology Classical World  
   - HIS 318 Topics in History :Div West Persp  
   - COM 161 Visual Rhetoric  
   - FLM 225 Film History  
   - COM 357 Sex, Race, & Gender in Media  
3. One of the following  
   - ARH 307 Modern and Contemporary Art
   - ARH 310 Contemporary Art, Theory &Criticism  
4. One 100- or 300-level ART- course

### COURSES IN ART HISTORY

- ARH 106 World Art   
  Traces key themes in art from a global perpective, focusing on the ways that cultures and civilizations across time have visually expressed social, religious and political values. Cross-cultural themes may include: religion and spirituality, word and image, violence and death, power and propaganda, gender and society, parks and memorials, and ritual and body decoration.   
- ARH 107 Gender and Art   
  Explores of the ways in which visual culture reflects and projects cultural biases and issues related to gender from prehistory to the modern era. Analyzes how gender identities can be shaped by politics, religion, and culture, as well as the effect of an artist's sex and/or sexual preferences on subject choices, media, and market values.   
- ARH 128 Introduction to Art History   
  Examines Western art and architecture from prehistory to the later 19th century, with emphasis on the ways in which visual culture both reflects and shapes societies and civilizations. Explores how works of art create and sustain meaning for their original audiences, and how some objects or visual solutions transcend their historical moment and surface throughout time as familiar cultural icons or references.   
- ARH 191 Topics in Art History   
  See also +++MISSING INFO: c.art91.short +++   
  Focuses on a selected topic or theme in art history or visual culture. Topics vary. May be taken more than once for credit, provided the topics are substantially different.   
- ARH 201 Art of the Middle Ages  
  Explores the art and architecture of the medieval world both chronologically and thematically. The course examines issues such as patronage of the arts, pilgrimage, the cult of saints, the arts as a medium of cultural exchange, and the role of the artist in the Middle Ages. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.  
- ARH 218 The World of Renaissance Art  
  Explores the visual culture of Europe from the 14th through the 16th centuries, focusing on topics such as competition, display, devotion, portraits, the printing revolution, death, and gender issues. Prerequisite: Introduction to Art History (ART-128) or consent of instructor.  
- ARH 231 Romanticism, Realism, Impressionism  
  Focuses on the sweeping transformations in the creation, production and consumption of visual culture in the 19th century. The rapidly changing aesthetics of the dawning modern era generated passionate debates about the creation and reception of art during this period. This course uses these debates as a series of touchstones for understanding the visual and social landscape of the times. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.  
- ARH 248 Baroque, Rococo, and Neoclassicism  
  Focuses on a thematic exploration of the major art movements in the 17
th and 18th centuries, emphasizing the pendulum swings of artistic practice, exploration, and
institutional hierarchies. Inclusion of cultural phenomena—the Grand Tour, the
Enlightenment, revolutions, and the establishment of academies—factor heavily in this
course. Prerequisite: Introduction to Art History (ARH 128) or consent of instructor.  
- ARH 268 History of Architecture  
  Investigates major monuments of architectural history from prehistory to the present day, with an emphasis on formal and conceptual concepts. Key figures, theories, innovations, and functions (both original and altered throughout time) are also discussed.
Prerequisite: Introduction to Art History (ARH 128) or consent of instructor.  
- ARH 296 Topics in Art History:Global Persp  
  Focuses on a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.  
- ARH 297 Topics in Art History: US Pluralism  
  Examines a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.  
- ARH 298 Topics in Art History:Div West Pers  
  Studies a selected topic or theme in art history. Topics vary, and may include: Art and Cultural Property; Memory, Environment and Landscape. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.  
- ARH 307 Modern and Contemporary Art  
  Traces the development of major artistic movements in the 20th centrury to the more contemporary trends of the 21st century. Topics include: Post-Impressionism, Cubism, Futurism, Surrealism, German Expressionism, Dada, Pop Art, Minimalism, Conceptual Art, Postmodernism, installation, new media, performance, and digital production and distribution. Prerequisite: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.  
- ARH 310 Contemporary Art, Theory &Criticism  
  Investigates issues in contemporary art. Focuses on art of the late 20th and early 21st centuries, considering stylistic, historical and theoretical developments. Prerequisite: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.  
- ARH 391 Advanced Topics in Art History  
  See also ART 291  
  Focuses on an advanced study of a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisites: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.  
- ARH 394 Directed Learning  in Art History  
  Investigates topics in art history selected by the student and instructor to fit the student’s particular interests and educational needs. May be taken more than once for credit. Prerequisites: junior standing and consent of department chair.  
- ARH 444 Independent Study: Art History  
  Focuses on independent work on a selected project under the direction of a faculty member of the Art and Art History department. Prerequisite: consent of instructor.  
- ARH 464 Senior Seminar I  
  Introduces the research methods, theories, and curatorial practices affiliated with the discipline of art history. Additionally, students begin crafting their capstone projects in art history, which will be completed in Seminar II. Prerequisites: declared major in Art History, Introduction to Art History (ARH-128), one 200-level ARH course, and junior standing.  
- ARH 474 Senior Seminar II  
  Completes the capstone research project (i.e. research papers, exhibitions, or hybrid projects that involve making
art and contextualizing visual culture). Prerequisite: Successful completion of Seminar in Art History I.  
- ARH 494 Internship in Art History  
  Investigates an area of interest related to the major, through voluntary field placement supervised by a faculty member of the Art and Art History department. A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisites: declared major in art history, junior standing, and consent of department chair.  
