## Asian Studies {#sec-asian-studies}

Nordmann (Administrative Coordinator).

The Asian Studies program is designed to acquaint students with the great cultures of Asia, primarily those of China, India and Japan.

### Asian Studies Major

A major in Asian studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

The major is interdisciplinary and requires that the students take courses in the areas of art history, history, literature, and religion, and suggests that they also take courses in economics, music, and political science.

1. **One** of the following:

- ASC 186 Modern South Asia
- HIS 136 East Asian Civilization

2. Participation in one overseas study program in Asia:

- an ACM overseas study program (India Studies or Japan Study)
- a Coe foreign exchange program (Chiang Mai University of Thailand, Nagoya Gakuin University of Japan, or Sookmyung University in South Korea)
- Coe’s Asia Term (see @sec-asia-term)

3. **Four** courses, chosen from the following, in consultation with the Asian Studies administrative coordinator:

- ASC 106 May Term in Asia
- ASC 176 China and Japan
- ECO 436 Econ Development or ECO 446 International Econ
- HIS 217 American War in Vietnam
- HIS 246 History of Modern China
- HIS 256 History of Modern Japan
- HIS 316 Topics in History:Non-Western Persp (when appropriate)
- HIS 466 Seminar Modern East Asian History
- JPN 115 Elementary Japanese I
- JPN 125 Elementary Japanese II
- JPN 215 Intermediate Japanese I
- JPN 225 Intermediate Japanese II
- PHL/REL 206 Buddhist Thought (WE)
- POL 286 Asian Politics
- REL 106 Eastern Religions
- A second term of an overseas study program

### Asian Studies Minor

1. **One** of the following:

- HIS 316 Topics in History:Non-Western Persp
- ASC 186 Modern South Asia

2. **Five** courses, chosen from the following, in consultation with the Asian Studies administrative coordinator:

- ASC 176 China and Japan
- ECO 436 Econ Development or ECO 446 International Econ
- HIS 217 American War in Vietnam
- HIS 246 History of Modern China
- HIS 256 History of Modern Japan
- HIS 316 Topics in History:Non-Western Persp (when appropriate)
- HIS 466 Seminar Modern East Asian History
- JPN 115 Elementary Japanese I
- JPN 125 Elementary Japanese II
- JPN 215 Intermediate Japanese I
- JPN 225 Intermediate Japanese II
- PHL/REL 206 Buddhist Thought (WE)
- POL 286 Asian Politics
- REL 106 Eastern Religions 

### Courses in Asian Studies

 **ASC 106 May Term in Asia**  
Examines experientially the fast-changing nation of Vietnam through three weeks of study and travel in the country. Students will investigate and evaluate
the contemporary nation, as well as the history and memory of its wartime experiences, through readings, written work, class discussions, and visits to
important historical and cultural landmarks. Through these varied experiences, students will deepen their understandings of the cultural skills involved in
overseas travel, the cultural differences and commonalities that shape human experiences, and the specific knowledge of Vietnam's culture and history.  
 **ASC 176 China and Japan**  
An interdisciplinary examination of themes and ideas central to understanding the cultures of China and Japan. Materials used include primary texts in Taoism, Confucianism, and Buddhism, as well as works of poetry, fiction, and visual art.  
 **ASC 186 Modern South Asia**  
India, Pakistan, Bangladesh, and Sri Lanka from a modern perspective. The preoccupation with identity, the reemergence of caste and religious conflicts, the strengths and weaknesses of political and economic development, and the implication of trends for the future. Includes selected topics on culture and history that provide insights to understanding the present.  
 **ASC 216 History of Modern Korea (WE)**  
See @sec-history  
