## Biochemistry (Collateral Major) {#sec-biochemistry}

Stead (Administrative Coordinator).

### Collateral Major in Biochemistry

A major in biochemistry requires a minimum cumulative 2.0 GPA in all courses counted toward the major.
Concurrent completion of a primary major in chemistry, including Calculus II and two General Physics courses is required. Students choosing a collateral major in biochemistry may not select a collateral major in molecular biology

1.BIO 145/145L Cellular and Molecular Biology and Laboratory (WE)  
2.CHM 431/431L Biochemistry and Laboratory  
3.CHM 432/432L Protein Biochemistry and Laboratory  
4.**Two** of the following:

> BIO 325/325L Microbiology (WE) and Laboratory  
> BIO 345/345L Techniques in Molecular Biology and Laboratory  
> BIO 405 Current Topics in Molecular Biology  
> BIO 435/435L Cell Physiology and Laboratory  

Genetics (BIO-235) and Laboratory (BIO-235L) and all of the courses under #4 are strongly encouraged, especially for those planning graduate study.
