## Classical Studies (Minor Only)
Langseth, Ziskowski (Administrative Coordinator).

Classical Studies provides the student opportunity to examine the achievements of the ancient past — notably those of Greece and Rome — from a variety of distinct perspectives: literature, language, art, history, philosophy, and religion, and archaeology.  To allow for the integration of perspectives, some courses have been designed which offer an interdisciplinary approach to the study of the past; these are designated HUM (for Humanities) in the listings below.

### Classical Studies Minor
Six courses, chosen from the following, in consultation with the Classical Studies administrative coordinator.
	
- ANT 125 Art & Archaeology Classical World
- CLA 108 Images of Foreign Culture
- CLA 155 Latin/Greek Origins Med Terminology
- CLA 284 Topics in Classical Studies
- ENG 110 Ancient Mythology
- ENG 115 The Classical Tradition
- GRK 115 Basic Greek
- GRK 125 Selected Readings in Ancient Greek
- +++MISSING INFO: c.grk284_384.long +++
- HIS 275 Ancient Greek History
- HIS 285 History of Ancient Rome
- HIS 318 Topics in History :Div West Persp (when topic is appropriate, as determined by the Classical Studies administrative coordinator)
- CLA 120 Greek Civilization
- CLA 130 Roman Civilization
- LTN 115 Basic Latin
- LTN 125 Selected Readings in Latin
- +++MISSING INFO: c.ltn284_384.long +++
- PHL 220 Ancient Greek Philosophy

### COURSES IN CLASSICAL STUDIES
 **CLA 108 Images of Foreign Culture**  
  A course dealing with the picture of human activity and values given in freign short stores, novels, films, and other works of art, as well as in historical documents and the like. It celebrates and explores the special character of a national or ethnic identity with regerence to either the French-speaking world, Spain and/or Latin America, Germany, Asia, or the world of Greek and Roman antiquity. Topics vary from year to year. Taught in English.  
 **CLA 120 Greek Civilization**  
  An interdisciplinary examination of themes central to understanding the Ancient Greek World. Topics and
materials may change each time the course is offered. May include The Greek View of Hero, Man and His
Community, Religion, Mythology, and Philosophy.  
 **CLA 130 Roman Civilization**  
  An interdisciplinary examination of themes central to understanding the Ancient Roman World. Topics and
materials may change each time the course is offered. May include The Cult of the Emperor, Roman Law, Art, and Religion.  
 **CLA 155 Latin/Greek Origins Med Terminology**  
  Examines the origins of contemporary medical terminology, in part by studying the development of a distinct technical vocabulary, with historical roots in the Greco-Roman, Arabic, and Modern-European worlds, which developed as physicians discovered distinct ways of communicating both with their patients and with each other.  
 **CLA 284 Topics in Classical Studies**  
  A study of a selected theme or topic in Classical Studies. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different.  
