## Dance (Courses Only) {#sec-dance}
Rezabek, Wolverton.

### Courses in Dance

- **DAN 101 Dance - Jazz I**
  A beginning-level course designed to introduce the student to basic jazz dance techniques and skills. Emphasis on alignment and precise execution of jazz movements. Class includes functional kinesiology and injury prevention techniques, and presentations place jazz dance in socio-historical context. (0.2 course credit) 
- **DAN 102 Dance - Jazz II**
  An intermediate-level course designed to increase the student 2019s knowledge and skill in jazz dance techniques. May include Hatchett, Giordano, Luigi, and contemporary styles. Class continues functional kinesiology, and presentations place jazz dance in socio-historical context. Prerequisite: Jazz I (DAN-101). (0.2 course credit) 
- **DAN 111 Dance-Modern I**
  A beginning-level class focusing on fundamental modern dance techniques. Emphasis on placement of the spine and quality of movement. Features the techniques of Doris Humphrey, Jose Limon, and Erick Hawkins. Presentations discuss modernisms and postmodernism and place modern dance in socio-historical context. (0.2 course credit) 
- **DAN 112 Dance-Modern II**
  An intermediate-level class offering more complex modern dance styles and skills. May include Graham, Horton, and Cunningham techniques. Presentations continue the discussion of modernism and postmodernism and place modern dance in socio-historical context. Prerequisite: Modern I (DAN-111). (0.2 course credit) 
- **DAN 131 Dance-Ballet I**
  Classical ballet is based on traditional positions and movements of the body emphasizing harmonious lines in space. It is the technical basis of many forms of dance. This course offers a working vocabulary of basic ballet movement skills and terminology. Presentations discuss the history and theory of ballet. (0.2 course credit) 
- **DAN 132 Dance-Ballet II**
  This course continues Ballet I, offering more complex ballet movement skills and terminology. Prerequisite: Ballet I (DAN-131). (0.2 course credit) 
- **DAN 141 Dance - Tap I**
  Simple tap steps and combinations, including adequate background to survive an audition. The course progresses to more complicated movement sequences, with emphasis on speed and clarity. (0.2 course credit) 
- **DAN 142 Dance - Tap II**
  More complex steps, styles, and rhythms. Emphasis on speed, clarity, strength, and dexterity. Prerequisite: Tap I (DAN-141). (0.2 course credit) 
- **DAN 151 Dance-Choreography I**
  Introduction to the choreographic craft, concentrating on generating original movement through short studies focusing on body, space, and time. (0.2 course credit) 
- **DAN 152 Dance-Choreography II**
  Further exploration of choreographic techniques, culminating in a short performance of student 2019s work. Prerequisite: Choreography I (DAN-151). (0.2 course credit) 
