## Education {#sec-education}

N. Hayes, Haynes-Moore, Kigin (Placement Coordinator) Kress (Chair), Russell
Art: Rogers; Music: Carson, Shanley; Physical Education: Atwater.
Content Specialists (Part-time): Bakas, Christofferson, Dabroski, Gaylord Robertson, Hanson J., Hanson M., Hynek, Johnson,
Neilly, Zahn, Zrudsky

Student Teaching Supervisors: Bartlett, Lanich, Oberbroeckling

Coe College believes that the most effective preparation for teaching is one that combines a liberal arts education with courses in the theory and practice of teaching. The Education Department has the responsibility for coordinating the efforts of the College to provide such a program.  

Basic college requirements and those for a major area give students a well-rounded general education. Professional courses in education provide a foundation in principles and practices of teaching. Students gain practical experience in applying professional and general education through field experiences and, if pursuing licensure, through student teaching in area schools. 

Students who successfully complete Coe’s Teacher Education Program and student teaching are eligible to apply for an Iowa Initial Teacher License. Teaching licensure is governed by State of Iowa regulations. When changes in licensure requirements occur at the state level, they take precedence over College policies. For the most current policy information, students should consult the *Guide to Teacher Education*, available from the Education Department. The Education Department maintains records regarding Iowa licensure requirements. Students should consult a faculty member in the Education Department to arrange their respective courses of study. 

The Teacher Education Program at Coe College is approved by the Iowa Department of Education. Copies of the annual report filed with the Iowa Department of Education are available on request.


### Elementary Education Major
Teachers in elementary schools function as generalists who must draw upon a broad knowledge base from multiple disciplines. In recognition of this, the elementary teacher licensure program at Coe College consists of two components: content knowledge gained from the liberal arts classes and pedagogy learned in EDU courses. This program of undergraduate preparation to teach in elementary schools is intended to promote exploration and a balanced education drawn from a variety of fields. 

1. At least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities. **Iowa Distribution Requirements** - a “C” or better in the following courses:
	- **One** mathematics course with a prefix of MTH or STA
	- **One** American History course
	- **One** lab science in BIO or PHY-114 Modern Astronomy
	- **One** social science course with a prefix of ANT, ECO, POL, PSY, or SOC

2. A K–8 endorsement in Art, English/Language Arts, French, Spanish, Health, History, Mathematics, Music, Physical Education, Reading, Science, Social Studies, or Speech Communication and Theater.

3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- EDU 105 Foundations of Education
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- EDU 215 Practicum in Education
	- EDU 219 Educational Technology Lab
	- EDU 237 English Language Learners **OR** EDU 270 Read & Explore Childrens/Adol Lit
	- EDU 275 Math Comprehension for Teaching
	- EDU 300 Expressive Methods
	- EDU 305 Methods of Elementary Science
	- EDU 335 Methods of Elementary Mathematics
	- EDU 345 Methods of Elementary Language Arts
	- EDU 355 Methods of Elementary Reading
	- EDU 365 Methods of Elementary Social Studie
	- KIN 112 Health Educ for Elementary Tchr

**NOTE**: *As is true for all majors, elementary education students are responsible for completion of Coe’s general education requirements. Careful program planning may enable either greater breadth within the liberal arts or a deeper concentration within a specialty discipline. Programs containing such additional concentration may require more than four years of study.* 


### Secondary Education Minor
1. *Iowa Distribution Requirements*: a “C” or better in at least one course of the four fields of mathematics, natural sciences, social sciences, and humanities.
2. A grade of “C” or better must be earned in all courses counted toward a major or minor in education and in subject areas in which students intend to teach.
3. Completion of a major in one or more teaching fields with a GPA of 2.7 or higher. Teaching field(s) must be in subjects ordinarily taught in the secondary schools and for which Coe has approval by the Iowa Department of Education. Approved teaching fields include American Government, American History, Art, Basic Science, Biology, Business, Chemistry, Economics, English/Language Arts, French, Health, Math, Music, Physical Education, Physics, Psychology, Sociology, Spanish, Speech Communication and Theater, and World History.
4. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- EDU 105 Foundations of Education
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- EDU 215 Practicum in Education
	- EDU 219 Educational Technology Lab
5. **One or more** of the following Methods courses: 
	- ART 230 Art of Children & Adolescents
	- EDU 310 Meth Secondary Business Educ
	- EDU 311 Meth Secondary Language Arts
	- EDU 312 Meth Secondary Social Studies
	- EDU 313 Methods Secondary Mathematics
	- EDU 320 Methods of Secondary Science
	- EDU 321 Methods of World Language K-12
	- KIN 415 Meth Secondary School PE & Health
	- MU 361 Choral Music Methods **AND** MU 362 InstrMusMethChrlTeachr
	- MU 363 Instrumental Music Methods **AND** MU 364 ChrlMusMethInstTeach


### ADMISSION TO THE TEACHER EDUCATION PROGRAM
The Education Department offers a major in **elementary education**, a minor in **secondary education**, and courses leading to three types of teacher licensure: K-6 classroom (elementary education); 5–12 content area (secondary education) and K-12 “specials” content area (art, music, physical education). Students pursuing any of these options must be admitted to the Teacher Education Program before being allowed to enroll in a practicum course or methods course. Admission to Coe College does not guarantee admission to the Teacher Education Program. Information related to applying to the Teacher Education Program is found in the *Guide to Teacher Education* available from the Education Department. 

State of Iowa licensure requirements specify that a minimum of 80 hours of field experience be completed after admission to the Teacher Education Program and prior to student teaching. Teacher Education Program applications are available online; contact your Education advisor. 

The Teacher Education Committee has responsibility for review of the Teacher Education Program, including admission of students into the program. In reviewing applications for admission to the program, the committee considers the following: 

1. A “C” or better in two core EDU courses (EDU 105 Foundations of Education strongly recommended)
2. GPA (a minimum of 2.7 is required in education core courses, courses in the major and overall)
3. A grade of “C” or higher must be earned in all courses counted toward a major or minor in education and in subject areas in which students intend to teach. 
4. Performance in education courses taken. 
5. The essay included on the program application.
6. Other relevant information as provided by the faculty of the Education Department and comments from faculty in classes the student is enrolled in or has recently taken.

The Teacher Education Committee reviews applications at the conclusion of each semester. Students are notified in writing regarding the committee’s decision. Appeals may be made to the committee in writing. The committee evaluates such appeals on an individual basis, using its best judgment of the student’s suitability to enter the teaching profession. The process for further appeals is detailed in the *Guide to Teacher Education*.


### Graduates/Transfers from Other Institutions
Graduates/transfers from other institutions should submit transcripts and all other relevant materials for
review to the Education department chair. In most cases, applicants are required to take a minimum of four EDU courses at Coe, in which at least a 2.7 GPA or higher and a “C” or better is earned, prior to student teaching. 
Students who received the highest degree more than 10 years prior to application to the Teacher Education Program must complete two additional courses at Coe in the major area, with a grade of “C” or better, in addition to the required professional education courses. 


### Elementary Education/Non-Licensure
The majority of students who major in elementary education intend to become licensed K–6 classroom teachers and complete one term of full-time student teaching after completing the major requirements. Occasionally, however, a student may wish to work with young children in settings other than those for which certification is required. Such students may complete all of the required coursework for the elementary education major without student teaching and are advised on supplementary coursework to support their goals.


### REQUIREMENTS FOR STUDENTS PURSUING TEACHING LICENSES
To be recommended for licensure in any of the categories listed below, a student must have a baccalaureate degree, a cumulative GPA of at least 2.7, and at least a 2.7 GPA in each teaching field. The department can refuse to recommend for licensure a student who has been found to have violated the College’s Academic Integrity Policy.  


### Iowa Distribution Requirements for All Students Seeking Licensure
According to state regulations, all teachers in Iowa “shall acquire a core of liberal arts knowledge including, but not limited to, English composition, mathematics, natural sciences, social sciences, and humanities.” While the state’s distribution requirements are consistent with Coe’s general education requirements, they are not automatically met by these requirements. Education students should consult with their Education advisor to coordinate this mandate with the selection of courses for general education.



### Elementary Licensure
**Requirements:**

1. Students licensed at the elementary level, must have a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas.
2. **Iowa Distribution Requirements** - a “C” or better in the following courses:
	- **One** mathematics course with a prefix of MTH or STA
	- **One** American History course
	- **One** lab science in BIO or Modern Astronomy
	- **One** social science course
3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- EDU 105 Foundations of Education
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- EDU 215 Practicum in Education
	- EDU 219 Educational Technology Lab
	- EDU 237 English Language Learners **OR** EDU 270 Read & Explore Childrens/Adol Lit
	- EDU 275 Math Comprehension for Teaching
	- EDU 300 Expressive Methods
	- EDU 305 Methods of Elementary Science
	- EDU 335 Methods of Elementary Mathematics
	- EDU 345 Methods of Elementary Language Arts
	- EDU 355 Methods of Elementary Reading
	- EDU 365 Methods of Elementary Social Studie
	- KIN 112 Health Educ for Elementary Tchr
4. A K–6 Iowa teaching license must be accompanied by at least one K–8 endorsement (state approved specialization in a particular subject area) available at Coe. K–8 endorsements include: Art, English/Language Arts, French, Spanish, Health, History, Mathematics, Music, Physical Education, Reading, Science, Social Studies, or Speech Communication and Theater. Students should consult their Education advisor for assistance in adding these endorsements to their elementary teaching license.
5. Student Teaching (4 course credits):
	- EDU 492 Student Teaching K-3
	- EDU 491 Student Teaching 4-6
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Students seeking elementary licensure must have an advisor in the Education Department with whom they meet regularly (at least twice per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


### Secondary Licensure
Those interested in teaching at the secondary level must major in one or more teaching fields, minor in education, and meet the state requirements for a 5–12 endorsement (state-approved specialization in a particular subject area).  Teaching field(s) must be in subjects taught in the secondary schools and for which Coe has approval by the Iowa Department of Education.  
	**5–12 endorsements include**: American Government, American History, Art, Biology, Business, Chemistry, Coaching (see Kinesiology), Economics, English/Language Arts, French, Health, Math, Music, Physical Education, Physics, Psychology, Science, Social Studies, Sociology, Spanish, Speech Communication and Theater or World History. 

**Requirements:**

1. Students licensed at the secondary level, must have a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas.
2. Iowa Distribution Requirements: a “C” or better in at least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities.
3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- EDU 105 Foundations of Education
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- EDU 215 Practicum in Education
	- EDU 219 Educational Technology Lab
4. **One or more** of the following Methods courses:
	- EDU 310 Meth Secondary Business Educ
	- EDU 311 Meth Secondary Language Arts
	- EDU 312 Meth Secondary Social Studies
	- EDU 313 Methods Secondary Mathematics
	- EDU 320 Methods of Secondary Science
	- EDU 321 Methods of World Language K-12
5. Successful completion of Student Teaching:
	- EDU 489 Student Teaching Sr HS
	- EDU 490 Student Teaching Jr HS
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Not all Coe majors align perfectly with State of Iowa requirements for 5–12 endorsements. Students seeking secondary licensure should also have an advisor in the Education Department with whom they meet regularly (at least once per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


### Art, Music and Physical Education (K–12 licensure)
Preparation for teaching at the elementary (K–8) and secondary (5–12) levels in the subject areas of art, music, and physical education includes state licensure requirements, in addition to work students complete in their major.

**Requirements:**

1. Students licensed in art, music, or physical education must earn a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas (state approved specialization in a particular subject area).
2. Iowa Distribution Requirements: A “C” or better in at least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities.
3. GPA of 2.7 or higher and a “C” or better in the following professional educational courses: 
	- EDU 105 Foundations of Education
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- EDU 215 Practicum in Education
	- EDU 219 Educational Technology Lab
4. **One or more** of the following Methods courses:
	- ART 230 Art of Children & Adolescents
	- KIN 315 Methods Elementary Sch PE & Health
	- KIN 415 Meth Secondary School PE & Health
	- MU 360 Elementary & General Music Methods
	- MU 361 Choral Music Methods **AND** MU 362 InstrMusMethChrlTeachr 
	- MU 363 Instrumental Music Methods **AND** MU 364 ChrlMusMethInstTeach 
5. Successful completion of Student Teaching:
	- EDU 481 Stu Tchg Sec: ART
	- EDU 482 Stu Tchg Sec: Phys Education
	- EDU 483 Std Teaching Elem: ART
	- EDU 485 Std Teaching Elem: Phys Ed
	- MU 421 Student Teaching Elementary Music
	- MU 422 Student Teaching Secondary Music
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Not all Coe majors align perfectly with State of Iowa requirements for licensure. Students seeking licensure should also have an advisor in the Education Department with whom they meet regularly (at least once per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


### Student Teaching
Permission to student teach requires approval of the Teacher Education Committee. Applications are due by February 1 for student teaching the following Fall Term and by September 1 for student teaching the following Spring Term. Applications are available from the Education Office.
When an application to student teach is considered, the student’s standing in the Teacher Education Program is reviewed. The committee considers:

1. Recommendations of cooperating teacher(s) during the student’s field experience(s).
2. Consultation with student’s major department(s).
3. A grade of “C” or better must be earned in all courses counted toward a major or minor in education and in all endorsement areas.
4. GPA (a minimum of 2.7 is required in the professional education courses, courses in the major, and overall).
5. Review by Education Department faculty.

Student teaching is the culminating experience of the Teacher Education Program. It involves observation and active participation in directing learning experiences aligned with professional learning standards in a school classroom, under the supervision of a cooperating teacher and the college supervisor. A minimum of four course credits of student teaching is required. Student teaching in all subjects is available for one to four course credits for students earning both Elementary and Secondary licensure.

Normally, students complete two seven- to eight-week placements, with each placement worth two credits. Successful completion of the student teaching semester, including attendance at and participation in the student teaching seminar, earns four credits. Student teaching is a full-time obligation, must be completed in one term, and is evaluated on a P/NP basis.


**Student Teaching Requirements**

1. One or more of the following:
	- EDU 481 Stu Tchg Sec: ART
	- EDU 482 Stu Tchg Sec: Phys Education
	- EDU 483 Std Teaching Elem: ART
	- EDU 485 Std Teaching Elem: Phys Ed
	- EDU 489 Student Teaching Sr HS
	- EDU 490 Student Teaching Jr HS
	- EDU 491 Student Teaching 4-6
	- EDU 492 Student Teaching K-3
	- MU 421 Student Teaching Elementary Music
	- MU 422 Student Teaching Secondary Music
2. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
3. Satisfactory performance in the field as determined by the cooperating teacher and supervisor evaluations.


### Ninth-Term/Fifth-Year Programs
Students who want to include more coursework in their liberal arts and sciences curriculum in conjunction with completing requirements for elementary and/or secondary teacher licensure may apply for a Ninth-Term/Fifth-Year tuition reduction. Both options are open to all students who have been ***admitted*** to the Teacher Education Program and meet requirements for student teaching.
Students participating in the Ninth-Term/Fifth-Year Programs are eligible for a 60% discount on full-time tuition, if the following criteria are met:

1. The student must be in good standing with the college (not on academic probation);
2. The student must be registered as a full-time student;
3. The student must have completed 32 course credits, sixteen of which were taken at Coe; and
4. The student must not have previously received the age discount.
5. The student submits the application by the appropriate deadline:
	- Fall Term: April 1st
	- Spring Term: November 1st

Students who have satisfactorily completed four years of full-time registration at Coe may also apply for this reduction. Students continue to be eligible to apply for student loans and any available federal and state government grants. This reduction can only be given for a maximum of two terms and applies only to regular full-time tuition charges for undergraduate campus-based programs. Applications for tuition reduction are available from the Education Department.

Exemptions from these requirements may be granted in unusual circumstances with the approval of the Provost and Dean of the Faculty and the Education department chair. A written request for such consideration, detailing the circumstances and rationale, should be made to the Education department chair.


### Courses in Education

- **EDU 105 Foundations of Education**
  Explores the many facets of schooliing in the United States. Students will examine historical, political, legal, social, and philosophical issues related to education and public schooling in the United States. A second course component consists of an introduction to curricular and instructional planning. A ten-hour field experience in local schools is required.  
- **EDU 109 Field Experience**
  Conducted in the public schools at either the elementary or secondary level. Students spend at least 60 hours of supervised work in a school setting. Prerequisite: Foundations of Education (EDU-105) and consent of Education Department Chair. (0.5 course credit)  
- **EDU 117 Exceptional Learners**
  Addresses the nature and needs of students with exceptionalities in the general classroom. Topics include historical and legal foundations of special education; classroom teacher responsibilities under IDEA and Section 504 of the Vocational Rehabilitation Act, categories of exceptionality, appropriate instructional accommodations for students with exceptionalities, methods of instruction and assessment of students with special needs. The course addresses the different needs of all learners, including but not limited to gifted learners, learners with disabilities, English Language Learners, twice exceptional learners, and learners struggling with literacy.  
- **EDU 187 Human Relations**
  Examines the lifestyles, history, and contributions of various identifiable subgroups in our pluralistic society. Students explore and analyze issues related to such topics as: equity in the schools, multicultural education, sexism, racism, religious pluralism, sexuality, intercultural interaction, and sexual harassment. Coursework encourages students to build their capacities for recognizing, understanding, and respecting diversity of people and cultures in order to develop constructive interpersonal relationships and favorable learning experiences in the classroom. A 10-hour field experience is required.  
- **EDU 195 Educ Psychology & Development**
  Introduces theories that address teaching and learning processes. Special attention is given to the following topics: the cognitive and emotional development of children and adolescents; learning and memory; intelligence and creativity; academic motivation; assessment; and classroom management. The course connects theories to practice by exploring the nature of formal learning environments that best serve the cognitive and emotional growth of students.  
- **EDU 215 Practicum in Education**
  Integrates theory and pedagogical practice. Students spend a minimum of 60 hours of practical experience in an elementary or secondary school classroom assisting in a range of instructional activities. College classroom experience complements the field experience and focuses on instructional planning, differentiation, assessment, classroom management and reflective teacing practices. Prerequisites: Admission to the Teacher Education Program (approved or conditional).  
- **EDU 219 Educational Technology Lab**
  Focuses on strategies for integrating educational technology in K-12 classrooms. Through hands-on lab work, course readings, reflective writing, and exposure to professionals in the field (both local and afar) help students gain the knowledge, skills, and attitudes needed to select, implement, and manage technology. The goal of the course is to help students plan, implement, and evaluate educational technology for teaching and learning. Course projects focus on the use of instructional technology tools to develop materials that support teaching and learning. P/NP basis only. Corequisite: Practicum in Education (EDU-215) or Practicum in Music Education (MU-205). (0.0 course credit)  
- **EDU 220 Professional Writing for Teachers**
  Practical experience creating professional documents for a variety of educational purposes and for a range of educational constituents. This course provides intensive practice in composing and designing documents central to teachers' work lives. The goal of the course is to help students develop confidence and skill as teaching professionals who excel at written communication. Prerequisiites: Foundations of Education (EDU 105) or consent of instructor.  
- **EDU 237 English Language Learners**
  Introduces the issues of language and literacy acquisition for English Language Learners. This class includes a focus on oral communication and K-12 literature. It is appropriate for teachers of non-native English students and international teaching of English. Prerequisite: sophomore standing or consent of instructor. (Offered Spring Term)  
- **EDU 241 Foundations of Reading**
  Explores past and current theories of language acquisition and development. Attention to the history of reading complements a focus on current research related to the psychological, socio-cultural, and linguistic foundations of reading and writing. This is the first course in the sequence leading to the reading endorsement. Prerequisite: admission to the Education Program or consent of Education Department Chair. (Offered Spring Term)  
- **EDU 260 Content Area Reading**
  Explores research-based instructional strategies for facilitating students’ textual comprehension. Major topics include best practices in the teaching of vocabulary, meaning making, text structure, genre, and types of writing. Attention to instructional strategies especially helpful to English language learners, as well as technological tools for language and literacy instruction. This is the second course in the sequence leading to the reading endorsement. Prerequisites: admission to the Education Program and Foundations of Reading (EDU-247) or consent of Education Department Chair. (Offered Fall Term)  
- **EDU 270 Read & Explore Childrens/Adol Lit**
  Provides students pursuing literature-related studies with models of how teachers use literature to support various levels of readers and content areas in the classroom. The course focuses on the history of children’s literature, analyses of a variety of books for youths, creation of a functional bibliography, and using knowledge of child and adolescent development to assist in book selection for young readers. Includes study of the development of language skills, strategies to facilitate student learning of standard English, diversity issues, non-print materials, and technology tools. (Offered Fall Term)  
- **EDU 275 Math Comprehension for Teaching**
  Enhances understanding of the discipline of mathematics for elementary classroom teachers. Content is aligned with the NCTM curriculum standards of Number, Algebra, Geometry, Measurement, and Data Analysis and Probability. Substantial attention is given to discrete mathematics, reasoning and proof, active problem solving, technology, and connections within mathematics and to other disciplines studied in schools. The ability to communicate mathematically and provide justification or rationale for quantitative reasoning is fostered across mathematical applications. (Offered Fall Term)  
- **EDU 284 Topics in Education**
  Examines special topics in education. Content varies and is determined by the instructor. Example topics
include: Assessment in Education, Educational Law, Leadership in Education, Social-Emotional Teaching
and Learning, Current Events in Education. May be taken more than once provided the topics are
substantially different. Prerequisite: Educational Foundations (EDU 105) or consent of
instructor. (.5 course credit)  
- **EDU 300 Expressive Methods**
  Integrates art, music, and physical education into the regular elementary classroom. Students will study of instructional methods for incorporating visual, aesthetic, auditory, and kinesthetic teaching and learning strategies into the classroom. This course promotes the integration of art, music, and physical education into the regular elementary classroom. Topics include research on learning styles, development of lessons and classroom management strategies that incorporate movement and creative expression, and alternative assessment as it relates to these strategies. Diversity issues, non-print materials, and technology tools are integrated. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair. (0.5 course credit) (Offered Fall Term)  
- **EDU 305 Methods of Elementary Science**
  Helps future teachers develop an integrated set of perspectives, attitudes, and skills, enabling them to give positive support to their students’ natural inclination to be curious, manipulate, observe, and interpret. Multiiple instructional strategies and methods will be studied in an outside of class sessions. Integration of relevant children’s literature is included. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Fall Term)  
- **EDU 310 Meth Secondary Business Educ**
  Prepares students for student teaching placement in a secondary business classroom. Students explore and
examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson
design, classroom management and learner assessment. Students will be exposed to strategies for
teaching high school general business courses, including accounting, marketing, and economics. This course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair.  
- **EDU 311 Meth Secondary Language Arts**
  Prepares students for student teaching in a secondary language arts classroom. Students explore and
examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson
design, and learner assessment. Students also experience working with texts such as YA literature,
podcasts, novels, poetry, drama, etc.. The course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Ecducation Department Chair.  
- **EDU 312 Meth Secondary Social Studies**
  Prepares students for student teaching in a secondary social studies classroom. Students explore and
examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson
design, classroom management and learner assessment. This course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Fall Term)  
- **EDU 313 Methods Secondary Mathematics**
  Prepares students for student teaching in a secondary mathematics classroom. Students explore and examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson design, classroom management and learner assessment. This course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair.  
- **EDU 320 Methods of Secondary Science**
  Prepares students for student teaching in a secondary science classroom. Students explore and examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson design, classroom management and learner assessment. This course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Fall Term)  
- **EDU 321 Methods of World Language K-12**
  Prepares students for student teaching in a world language classroom. Students explore and examine approaches to teaching and learning. Among the topics studied are instructional strategies, lesson design, classroom management and learner assessment. This course includes a 30-hour field experience. Prerequisite: Practicum in Education (EDU-215) or consent of Education Department Chair.  
- **EDU 335 Methods of Elementary Mathematics**
  Examines basic concepts of curriculum and instruction for elementary school mathematics using the framework of the National Council of Teachers of Mathematics and the Iowa Core Curriculum, This course assists prospective teachers in developing effective instructional skills that foster problem solving abilities and the conceptual and procedural knowledge of mathematics. Instruction includes integration of math-related children’s literature. A field experience of 30 contact hours is included. Prerequisites: Mathematics Comprehension for Teaching (EDU-275), Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Spring Term)  
- **EDU 345 Methods of Elementary Language Arts**
  Examines strategies for teaching the interrelated aspects of reading, writing, listening, speaking, spelling, and creative drama as they apply to the functional language of elementary school children. Assessing student literacy competence and planning for instruction are explored. Prerequisites: Concurrent registration in Teaching Reading (K-6) (EDU-355) and Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Spring Term)  
- **EDU 355 Methods of Elementary Reading**
  Examines the five components of reading-phonological awareness, phonics, fluency, comprehension and vocabulary. Instruction is provided in the strategies for mastering pre-reading, decoding, and comprehension skills. Methods of organizing, maintaining, and evaluating reading programs are addressed. Substantial study of children’s literature is included. A field experience of 30 contact hours provides an opportunity to apply the content of the course. Prerequisites: Concurrent registration in Teaching Language Arts (K-6) (EDU-345). Practicum in Education (EDU-215) or consent of Education Department Chair. (Offered Spring Term)  
- **EDU 365 Methods of Elementary Social Studie**
  Examines the content and teaching strategies that collectively form the scope and sequence of elementary school social studies. Geography and ecological anthropology provide a framework for integrating social science disciplines with other subject matter fields, such as children’s literature and science. Social issues are investigated on three levels: in relation to self, one’s immediate environment, and the global ecosystem. Prerequisite: Practicum in Eduation (EDU-215) or consent of Education Department Chair. (Offered Fall Term)  
- **EDU 395 Diagnostic Reading & Tutorial**
  Intensively studies diagnostic and screening instruments as well as multiple strategies to improve reading and writing skills. This course includes direct application of assessment and instructional strategies with individual children through a supervised tutorial outside of regular class time.  Prerequisites: admission to the Education Program, Foundations of Reading (EDU-241), and Content Area Reading (EDU-260). (Offered Spring Term)  
- **EDU 444 Ind Study-Tchr Ed**
  Extensively studies selected problems in the teaching of elementary and secondary school subjects under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of Education Department Chair.  
- **EDU 454 Research Participation**
  Provides students engagement in educational research. Students should consult members of the department to determine projected programs. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of Education Department Chair.  
- **EDU 494 Internship in Education**
  Explores a career area related to schools supervised by a faculty member of the department. A minimum of 140 hours on-site experience is required. A reflective paper analyzing the experience is required. May be completed during any term in which schools are in session. May include teaching, administrative, and/or counseling duties. S/U basis only. This course does not satisfy any of the requirements of the Education Program. Prerequisites: Foundations of Education (EDU-105) and consent of Education Department Chair.  
