## Education {#sec-education}

N. Hayes, Haynes-Moore, Kigin (Placement Coordinator) Kress (Chair), Russell

Art: Rogers; Music: Carson, Shanley; Physical Education: Atwater.

Content Specialists (Part-time): Bakas, Christofferson, Dabroski, Gaylord Robertson, Hanson J., Hanson M., Hynek, Johnson,
Neilly, Zahn, Zrudsky

Student Teaching Supervisors: Bartlett, Lanich, Oberbroeckling

Coe College believes that the most effective preparation for teaching is one that combines a liberal arts education with courses in the theory and practice of teaching. The Education Department has the responsibility for coordinating the efforts of the College to provide such a program.  

Basic college requirements and those for a major area give students a well-rounded general education. Professional courses in education provide a foundation in principles and practices of teaching. Students gain practical experience in applying professional and general education through field experiences and, if pursuing licensure, through student teaching in area schools. 

Students who successfully complete Coe’s Teacher Education Program and student teaching are eligible to apply for an Iowa Initial Teacher License. Teaching licensure is governed by State of Iowa regulations. When changes in licensure requirements occur at the state level, they take precedence over College policies. For the most current policy information, students should consult the *Guide to Teacher Education*, available from the Education Department. The Education Department maintains records regarding Iowa licensure requirements. Students should consult a faculty member in the Education Department to arrange their respective courses of study. 

The Teacher Education Program at Coe College is approved by the Iowa Department of Education. Copies of the annual report filed with the Iowa Department of Education are available on request.


### Elementary Education Major
Teachers in elementary schools function as generalists who must draw upon a broad knowledge base from multiple disciplines. In recognition of this, the elementary teacher licensure program at Coe College consists of two components: content knowledge gained from the liberal arts classes and pedagogy learned in EDU courses. This program of undergraduate preparation to teach in elementary schools is intended to promote exploration and a balanced education drawn from a variety of fields. 

1. At least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities. **Iowa Distribution Requirements** - a “C” or better in the following courses:
	- **One** mathematics course with a prefix of MTH or STA
	- **One** American History course
	- **One** lab science in BIO or PHY-114 Modern Astronomy
	- **One** social science course with a prefix of ANT, ECO, POL, PSY, or SOC

2. A K–8 endorsement in Art, English/Language Arts, French, Spanish, Health, History, Mathematics, Music, Physical Education, Reading, Science, Social Studies, or Speech Communication and Theater.

3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- {{< var c.edu105.long >}}
	- {{< var c.edu117.long >}}
	- {{< var c.edu187.long >}}
	- {{< var c.edu195.long >}}
	- {{< var c.edu215.long >}}
	- {{< var c.edu219.long >}}
	- {{< var c.edu237.long >}} **OR** {{< var c.edu270.long >}}
	- {{< var c.edu275.long >}}
	- {{< var c.edu300.long >}}
	- {{< var c.edu305.long >}}
	- {{< var c.edu335.long >}}
	- {{< var c.edu345.long >}}
	- {{< var c.edu355.long >}}
	- {{< var c.edu365.long >}}
	- {{< var c.kin112.long >}}

**NOTE**: *As is true for all majors, elementary education students are responsible for completion of Coe’s general education requirements. Careful program planning may enable either greater breadth within the liberal arts or a deeper concentration within a specialty discipline. Programs containing such additional concentration may require more than four years of study.* 


### Secondary Education Minor
1. *Iowa Distribution Requirements*: a “C” or better in at least one course of the four fields of mathematics, natural sciences, social sciences, and humanities.
2. A grade of “C” or better must be earned in all courses counted toward a major or minor in education and in subject areas in which students intend to teach.
3. Completion of a major in one or more teaching fields with a GPA of 2.7 or higher. Teaching field(s) must be in subjects ordinarily taught in the secondary schools and for which Coe has approval by the Iowa Department of Education. Approved teaching fields include American Government, American History, Art, Basic Science, Biology, Business, Chemistry, Economics, English/Language Arts, French, Health, Math, Music, Physical Education, Physics, Psychology, Sociology, Spanish, Speech Communication and Theater, and World History.
4. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- {{< var c.edu105.long >}}
	- {{< var c.edu117.long >}}
	- {{< var c.edu187.long >}}
	- {{< var c.edu195.long >}}
	- {{< var c.edu215.long >}}
	- {{< var c.edu219.long >}}
5. **One or more** of the following Methods courses: 
	- {{< var c.art230.long >}}
	- {{< var c.edu310.long >}}
	- {{< var c.edu311.long >}}
	- {{< var c.edu312.long >}}
	- {{< var c.edu313.long >}}
	- {{< var c.edu320.long >}}
	- {{< var c.edu321.long >}}
	- {{< var c.kin415.long >}}
	- {{< var c.mu361.long >}} **AND** {{< var c.mu362.long >}}
	- {{< var c.mu363.long >}} **AND** {{< var c.mu364.long >}}


### ADMISSION TO THE TEACHER EDUCATION PROGRAM
The Education Department offers a major in **elementary education**, a minor in **secondary education**, and courses leading to three types of teacher licensure: K-6 classroom (elementary education); 5–12 content area (secondary education) and K-12 “specials” content area (art, music, physical education). Students pursuing any of these options must be admitted to the Teacher Education Program before being allowed to enroll in a practicum course or methods course. Admission to Coe College does not guarantee admission to the Teacher Education Program. Information related to applying to the Teacher Education Program is found in the *Guide to Teacher Education* available from the Education Department. 

State of Iowa licensure requirements specify that a minimum of 80 hours of field experience be completed after admission to the Teacher Education Program and prior to student teaching. Teacher Education Program applications are available online; contact your Education advisor. 

The Teacher Education Committee has responsibility for review of the Teacher Education Program, including admission of students into the program. In reviewing applications for admission to the program, the committee considers the following: 

1. A “C” or better in two core EDU courses ({{< var c.edu105.long >}} strongly recommended)
2. GPA (a minimum of 2.7 is required in education core courses, courses in the major and overall)
3. A grade of “C” or higher must be earned in all courses counted toward a major or minor in education and in subject areas in which students intend to teach. 
4. Performance in education courses taken. 
5. The essay included on the program application.
6. Other relevant information as provided by the faculty of the Education Department and comments from faculty in classes the student is enrolled in or has recently taken.

The Teacher Education Committee reviews applications at the conclusion of each semester. Students are notified in writing regarding the committee’s decision. Appeals may be made to the committee in writing. The committee evaluates such appeals on an individual basis, using its best judgment of the student’s suitability to enter the teaching profession. The process for further appeals is detailed in the *Guide to Teacher Education*.


### Graduates/Transfers from Other Institutions
Graduates/transfers from other institutions should submit transcripts and all other relevant materials for
review to the Education department chair. In most cases, applicants are required to take a minimum of four EDU courses at Coe, in which at least a 2.7 GPA or higher and a “C” or better is earned, prior to student teaching. 
Students who received the highest degree more than 10 years prior to application to the Teacher Education Program must complete two additional courses at Coe in the major area, with a grade of “C” or better, in addition to the required professional education courses. 


### Elementary Education/Non-Licensure
The majority of students who major in elementary education intend to become licensed K–6 classroom teachers and complete one term of full-time student teaching after completing the major requirements. Occasionally, however, a student may wish to work with young children in settings other than those for which certification is required. Such students may complete all of the required coursework for the elementary education major without student teaching and are advised on supplementary coursework to support their goals.


### REQUIREMENTS FOR STUDENTS PURSUING TEACHING LICENSES
To be recommended for licensure in any of the categories listed below, a student must have a baccalaureate degree, a cumulative GPA of at least 2.7, and at least a 2.7 GPA in each teaching field. The department can refuse to recommend for licensure a student who has been found to have violated the College’s Academic Integrity Policy.  


### Iowa Distribution Requirements for All Students Seeking Licensure
According to state regulations, all teachers in Iowa “shall acquire a core of liberal arts knowledge including, but not limited to, English composition, mathematics, natural sciences, social sciences, and humanities.” While the state’s distribution requirements are consistent with Coe’s general education requirements, they are not automatically met by these requirements. Education students should consult with their Education advisor to coordinate this mandate with the selection of courses for general education.



## Elementary Licensure
**Requirements:**

1. Students licensed at the elementary level, must have a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas.
2. **Iowa Distribution Requirements** - a “C” or better in the following courses:
	- **One** mathematics course with a prefix of MTH or STA
	- **One** American History course
	- **One** lab science in BIO or Modern Astronomy
	- **One** social science course
3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- {{< var c.edu105.long >}}
	- {{< var c.edu117.long >}}
	- {{< var c.edu187.long >}}
	- {{< var c.edu195.long >}}
	- {{< var c.edu215.long >}}
	- {{< var c.edu219.long >}}
	- {{< var c.edu237.long >}} **OR** {{< var c.edu270.long >}}
	- {{< var c.edu275.long >}}
	- {{< var c.edu300.long >}}
	- {{< var c.edu305.long >}}
	- {{< var c.edu335.long >}}
	- {{< var c.edu345.long >}}
	- {{< var c.edu355.long >}}
	- {{< var c.edu365.long >}}
	- {{< var c.kin112.long >}}
4. A K–6 Iowa teaching license must be accompanied by at least one K–8 endorsement (state approved specialization in a particular subject area) available at Coe. K–8 endorsements include: Art, English/Language Arts, French, Spanish, Health, History, Mathematics, Music, Physical Education, Reading, Science, Social Studies, or Speech Communication and Theater. Students should consult their Education advisor for assistance in adding these endorsements to their elementary teaching license.
5. Student Teaching (4 course credits):
	- {{< var c.edu492.long >}}
	- {{< var c.edu491.long >}}
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Students seeking elementary licensure must have an advisor in the Education Department with whom they meet regularly (at least twice per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


## Secondary Licensure
Those interested in teaching at the secondary level must major in one or more teaching fields, minor in education, and meet the state requirements for a 5–12 endorsement (state-approved specialization in a particular subject area).  Teaching field(s) must be in subjects taught in the secondary schools and for which Coe has approval by the Iowa Department of Education.  
	
>>**5–12 endorsements include**: American Government, American History, Art, Biology, Business, Chemistry, Coaching (see Kinesiology), Economics, English/Language Arts, French, Health, Math, Music, Physical Education, Physics, Psychology, Science, Social Studies, Sociology, Spanish, Speech Communication and Theater or World History. 

**Requirements:**

1. Students licensed at the secondary level, must have a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas.
2. Iowa Distribution Requirements: a “C” or better in at least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities.
3. GPA of 2.7 or higher and a “C” or better in the following professional education courses:
	- {{< var c.edu105.long >}}
	- {{< var c.edu117.long >}}
	- {{< var c.edu187.long >}}
	- {{< var c.edu195.long >}}
	- {{< var c.edu215.long >}}
	- {{< var c.edu219.long >}}
4. **One or more** of the following Methods courses:
	- {{< var c.edu310.long >}}
	- {{< var c.edu311.long >}}
	- {{< var c.edu312.long >}}
	- {{< var c.edu313.long >}}
	- {{< var c.edu320.long >}}
	- {{< var c.edu321.long >}}
5. Successful completion of Student Teaching:
	- {{< var c.edu489.long >}}
	- {{< var c.edu490.long >}}
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Not all Coe majors align perfectly with State of Iowa requirements for 5–12 endorsements. Students seeking secondary licensure should also have an advisor in the Education Department with whom they meet regularly (at least once per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


### Art, Music and Physical Education (K–12 licensure)
Preparation for teaching at the elementary (K–8) and secondary (5–12) levels in the subject areas of art, music, and physical education includes state licensure requirements, in addition to work students complete in their major.

**Requirements:**

1. Students licensed in art, music, or physical education must earn a 2.7 GPA or higher and a “C” or better in all courses in their major and in endorsement areas (state approved specialization in a particular subject area).
2. Iowa Distribution Requirements: A “C” or better in at least one course in each of the four fields of mathematics, natural sciences, social sciences, and humanities.
3. GPA of 2.7 or higher and a “C” or better in the following professional educational courses: 
	- {{< var c.edu105.long >}}
	- {{< var c.edu117.long >}}
	- {{< var c.edu187.long >}}
	- {{< var c.edu195.long >}}
	- {{< var c.edu215.long >}}
	- {{< var c.edu219.long >}}
4. **One or more** of the following Methods courses:
	- {{< var c.art230.long >}}
	- {{< var c.kin315.long >}}
	- {{< var c.kin415.long >}}
	- {{< var c.mu360.long >}}
	- {{< var c.mu361.long >}} **AND** {{< var c.mu362.long >}} 
	- {{< var c.mu363.long >}} **AND** {{< var c.mu364.long >}} 
5. Successful completion of Student Teaching:
	- {{< var c.edu481.long >}}
	- {{< var c.edu482.long >}}
	- {{< var c.edu483.long >}}
	- {{< var c.edu485.long >}}
	- {{< var c.mu421.long >}}
	- {{< var c.mu422.long >}}
6. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
7. Demonstrate content-area knowledge and pedagogical knowledge by successfully passing state-required Praxis II exams.

**NOTE:** ***Not all Coe majors align perfectly with State of Iowa requirements for licensure. Students seeking licensure should also have an advisor in the Education Department with whom they meet regularly (at least once per year) to ensure timely completion of all graduation, general education, and licensure requirements.***


### Student Teaching
Permission to student teach requires approval of the Teacher Education Committee. Applications are due by February 1 for student teaching the following Fall Term and by September 1 for student teaching the following Spring Term. Applications are available from the Education Office.
When an application to student teach is considered, the student’s standing in the Teacher Education Program is reviewed. The committee considers:

1. Recommendations of cooperating teacher(s) during the student’s field experience(s).
2. Consultation with student’s major department(s).
3. A grade of “C” or better must be earned in all courses counted toward a major or minor in education and in all endorsement areas.
4. GPA (a minimum of 2.7 is required in the professional education courses, courses in the major, and overall).
5. Review by Education Department faculty.

Student teaching is the culminating experience of the Teacher Education Program. It involves observation and active participation in directing learning experiences aligned with professional learning standards in a school classroom, under the supervision of a cooperating teacher and the college supervisor. A minimum of four course credits of student teaching is required. Student teaching in all subjects is available for one to four course credits for students earning both Elementary and Secondary licensure.

Normally, students complete two seven- to eight-week placements, with each placement worth two credits. Successful completion of the student teaching semester, including attendance at and participation in the student teaching seminar, earns four credits. Student teaching is a full-time obligation, must be completed in one term, and is evaluated on a P/NP basis.


**Student Teaching Requirements**

1. One or more of the following:
	- {{< var c.edu481.long >}}
	- {{< var c.edu482.long >}}
	- {{< var c.edu483.long >}}
	- {{< var c.edu485.long >}}
	- {{< var c.edu489.long >}}
	- {{< var c.edu490.long >}}
	- {{< var c.edu491.long >}}
	- {{< var c.edu492.long >}}
	- {{< var c.mu421.long >}}
	- {{< var c.mu422.long >}}
2. Successful completion of Student Teaching Seminar
	- Active engagement in and regular attendance in seminar
	- Dyslexia training
	- Ethics training
	- Mock evaluations
	- CPR card (PE and coaching candidates)
	- Successful completion and presentation of e-portfolio
3. Satisfactory performance in the field as determined by the cooperating teacher and supervisor evaluations.


### Ninth-Term/Fifth-Year Programs
Students who want to include more coursework in their liberal arts and sciences curriculum in conjunction with completing requirements for elementary and/or secondary teacher licensure may apply for a Ninth-Term/Fifth-Year tuition reduction. Both options are open to all students who have been ***admitted*** to the Teacher Education Program and meet requirements for student teaching.
Students participating in the Ninth-Term/Fifth-Year Programs are eligible for a 60% discount on full-time tuition, if the following criteria are met:

1. The student must be in good standing with the college (not on academic probation);
2. The student must be registered as a full-time student;
3. The student must have completed 32 course credits, sixteen of which were taken at Coe; and
4. The student must not have previously received the age discount.
5. The student submits the application by the appropriate deadline:
	- Fall Term: April 1st
	- Spring Term: November 1st

Students who have satisfactorily completed four years of full-time registration at Coe may also apply for this reduction. Students continue to be eligible to apply for student loans and any available federal and state government grants. This reduction can only be given for a maximum of two terms and applies only to regular full-time tuition charges for undergraduate campus-based programs. Applications for tuition reduction are available from the Education Department.

Exemptions from these requirements may be granted in unusual circumstances with the approval of the Provost and Dean of the Faculty and the Education department chair. A written request for such consideration, detailing the circumstances and rationale, should be made to the Education department chair.


### Courses in Education

 **{{< var c.edu105.long >}}**  
    {{< var c.edu105.desc >}}  
 **{{< var c.edu109.long >}}**  
    {{< var c.edu109.desc >}}  
**{{< var c.edu117.long >}}**  
    {{< var c.edu117.desc >}}  
 **{{< var c.edu187.long >}}**  
    {{< var c.edu187.desc >}}  
 **{{< var c.edu195.long >}}**  
    {{< var c.edu195.desc >}}  
 **{{< var c.edu215.long >}}**  
    {{< var c.edu215.desc >}}  
 **{{< var c.edu219.long >}}**  
    {{< var c.edu219.desc >}}  
 **{{< var c.edu220.long >}}**  
    {{< var c.edu220.desc >}}  
 **{{< var c.edu237.long >}}**  
    {{< var c.edu237.desc >}}  
 **{{< var c.edu241.long >}}**  
    {{< var c.edu241.desc >}}  
 **{{< var c.edu260.long >}}**  
    {{< var c.edu260.desc >}}  
 **{{< var c.edu270.long >}}**  
    {{< var c.edu270.desc >}}  
 **{{< var c.edu275.long >}}**  
    {{< var c.edu275.desc >}}  
 **{{< var c.edu284.long >}}**  
    {{< var c.edu284.desc >}}  
 **{{< var c.edu300.long >}}**  
    {{< var c.edu300.desc >}}  
 **{{< var c.edu305.long >}}**  
    {{< var c.edu305.desc >}}  
 **{{< var c.edu310.long >}}**  
    {{< var c.edu310.desc >}}  
 **{{< var c.edu311.long >}}**  
    {{< var c.edu311.desc >}}  
 **{{< var c.edu312.long >}}**    
    {{< var c.edu312.desc >}}  
 **{{< var c.edu313.long >}}**  
    {{< var c.edu313.desc >}}  
 **{{< var c.edu320.long >}}**  
    {{< var c.edu320.desc >}}  
 **{{< var c.edu321.long >}}**  
    {{< var c.edu321.desc >}}  
 **{{< var c.edu335.long >}}**  
    {{< var c.edu335.desc >}}  
 **{{< var c.edu345.long >}}**  
    {{< var c.edu345.desc >}}  
 **{{< var c.edu355.long >}}**  
    {{< var c.edu355.desc >}}  
 **{{< var c.edu365.long >}}**  
    {{< var c.edu365.desc >}}  
 **{{< var c.edu395.long >}}**  
    {{< var c.edu395.desc >}}  
 **{{< var c.edu444.long >}}**  
    {{< var c.edu444.desc >}}  
 **{{< var c.edu454.long >}}**  
    {{< var c.edu454.desc >}}  
 **{{< var c.edu494.long >}}**  
    {{< var c.edu494.desc >}}  
