## English {#sec-english}

Aspengren, Ferguson, Hausknecht, LeMay, McQueen, Shaw (Chair), Sodeman, Valderrama

The study of English allows students to explore a wide range of literary and cultural productions from varied parts of the world. Our courses develop habits of mind that are fundamental to liberal education, including the ability to read critically, to think creatively, and to write clearly and with verve.
In consultation with their advisors, English majors are able to design personalized programs of study that attend to the historical and geographical range of literatures in English.  Students considering graduate work in literature should consult with English faculty to plan a rigorous course of study that would typically include an honors thesis and coursework in a world language.


### English Major
A major in English requires a minimum cumulative 2.0 GPA in all courses counted toward the major.    
1. ENG 111 Introduction to Literary Studies    
2. ENG 281 Literatures in English to 1800    
3. ENG 291 Literatures in English after 1800    
4. ENG 301 The Art of Literary Research    
5. Three English courses numbered 305 or above, one of which must be in British literature before 1800.     
6. Two additional English course credits, one of which may be in Creative Writing or in French, or Spanish literature in translation (FRE 145 French Literature in Translation, FRE 146 French Literature Translation:NWP, FRE 148 French Literature Translation:DWP, SPA 148 Spanish Literature in Translation)    
7.ENG 464 Seminar in Literature _OR_ ENG 467 Seminar inLit:USPluralism  


### English Minor
The minor in English consists of five course credits, including ENG 111 Introduction to Literary Studies and _two_ English courses numbered 300 or above. One course in Creative Writing (CRW-) or in French, or Spanish literature in translation (FRE 145 French Literature in Translation, FRE 146 French Literature Translation:NWP, FRE 148 French Literature Translation:DWP, SPA 148 Spanish Literature in Translation) may count toward the five course credits.


### Courses in Literature {#sec-courses-in-english}

- **ENG105 Composition I**
  None  
- **ENG 107 Exploring Literature:US Pluralism**
  Explores works by writers from one or more subgroups in American culture with the purposes of stimulating the appreciation of literary art and considering the various functions of literature in the contemporary world.  
- **ENG105 Composition I**
  None  
- **ENG 108 Exp Lit:Diverse Western Perspective**
  Explores works by writers from one or more subgroups in Western Civilization outside the United States with the purposes of stimulating the appreciation of literary art and considering the various functions of literature in the contemporary world.  
- **ENG 110 Ancient Mythology**
  Study of the myths of the ancient Greeks and Romans, while briefly touching on their Near Eastern predecessors as a way of investigating the character of myth and the purpose it plays in society. We examine these myths not only through the ancient texts, but by studying theoretical models and approaches to mythology.  
- **ENG 111 Introduction to Literary Studies**
  The Art of Reading and Writing (WE). Study of selected works of fiction, poetry, and drama with an emphasis on close reading
and expository writing. This course introduces terms and skills necessary for further literary study.  
- **ENG 112 Environmental Humanities**
  Introduces fundamental issues, questions, and methods relating to humans and our environment. This course explores how human cultures may participate in the response to environmental challenges through an analysis of various literary works and other forms of cultural production.  
- **ENG 115 The Classical Tradition**
  Study of ancient Greek, Roman, or other classical literature, read in translation. This course focuses on the diverse genres of classical literature, including epic, lyric, and drama, while attending to its continuities with medieval continental literature.  
- **ENG 117 Asian American Literature**
  Reading and discussion of literature by Asian Americans and an introduction to its literary, cultural, and historical context.  
- **ENG 127 Social Justice and Literature**
  Study of literary works that represent and reimagine issues of human rights in the twentieth and twenty-first centuries.  
- **ENG 137 African American Literature**
  See also African American Studies (AAM-137), @sec-courses-in-african-american-studies
  Reading and discussion of the writings of African Americans, with emphasis on the twentieth century. May include some relevant writings on African Americans by other groups. Study of the artistic values and of the social and cultural significance of these writings. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different.  
- **ENG 146 Intro Postcolonial Literature**
  Study of twentieth-century prose and poetry arising out of the cultural, social, economic, and legal harms of imperialism and colonization.  
- **ENG 157 Latinx/Chicanx Literature**
  Explores the lived experiences and cultures of Latinx and Chicanx communities in the U.S. through fiction, poetry, and non-fiction by Latina/os and Chicana/os. This course examines cultural works from dominant U.S. sub-groups— such as Mexican-Americans—and from communities with roots in South America, Central America, and the Caribbean. It interprets these works in relation to cultural, historical, and sociopolitical contexts.  
- **ENG 175 Contemporary Literature**
  Study of American or British literature from 1945 to the present.  
- **ENG 206 Gender and Literature: NWP**
  Examination of a particular author, theme, region, or genre in the context of gender and sexuality studies. Course focuses on topics related to non-western perspectives, such as women in the global south and the role that African American literature plays within different regions of the world.  
- **ENG 207 Gender & Lit:US Pluralism**
  Examination of a particular author, theme, region, or genre in the context of gender and sexuality studies. Course focuses on topics related to United States pluralism, such as American Women Writers or Gender and Race in American Literature.  
- **ENG 208 Gender & Lit:DWP**
  Examination of a particular author, theme, region, or genre in the context of gender and sexuality studies. Course focuses on topics related to Western cultural diversity, such as Gender Identity in Literature, Renaissance Women Writers, Women’s Autobiography.  
- **ENG 281 Literatures in English to 1800**
  Charts literary developments and transformations before 1800 in relation to changing historical conditions, from the history of books and writing to the wider histories of social, political, and cultural movements. An excursion into the literary, social, and cultural histories of the English speaking world, this course may include works by Bristish, American, or Anglophone writers.  
- **ENG 291 Literatures in English after 1800**
  Charts literary developments and transformations after 1800 in relation to changing historical conditions, from history of books and writing to the wider histories of social, political, and cultural movements. An excursion into the literary, social, and cultural histories of the English speaking world, this course may include works by British, American, or Anglophone writers.  
- **ENG 301 The Art of Literary Research**
  Practice in literary research, with particular attention to the varied critical and theoretical approaches necessary for advanced study. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101).  
- **ENG 312 Studies in Environmental Humanities**
  Studies selected works by major environmental writers, filmmakers, philosophers, and activists. Students study environmental texts in their ecological, historical, and cultural contexts and uses the interdisciplinary, justice-oriented methods of the environmental humanities to analyze environmental challenges and our cultural responses to them. Specific topics vary from year to year.  
- **ENG 327 Literature of American Renaissance**
  Study of literature from 1830 to the Civil War or of an author, topic, or genre of the period. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 337 American Realism & Naturalism**
  Study of literature from the Civil War to World War I, or of an author, topic, or genre of the period. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 347 Study in Modern or Contemp Amer Lit**
  Study of novels, short fiction, and poetry by American writers of the twentieth and twenty-first centuries or of an author, topic, or genre of the period. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 357 Studies in Latinx/ChicanxLiterature**
  Reviews selected works of literature by Latina/os and Chicana/os. Students explore through reading and discussion methods and concepts relating to human rights, coloniality, diaspora, Latinidad and/or linguistic philosophy to better understand the lived experiences, identities, and cultures of Latinx and Chicanx communities in the U.S. Specific topics vary from year to year.  
- **ENG 367 Studies in African Am Literature**
  See Also African American Studies (AAM-367), @sec-courses-in-african-american-studies
  See also African American Studies (AAM-367), 
Course focuses on specific literary genres or time periods and functions as an intermediate course between the introductory African American Literature (AAM/ENG-267) and the advanced English seminar (particularly Seminar in Literature: United States Pluralism (ENG-707)). Students read and discuss both primary and secondary sources in an effort to gain a fuller understanding and appreciation of the artistic values and of the social and cultural significance of these writings. Specific topics vary from year to year. Possible topics include African American Historical Fiction, African American Speculative Fiction, Literature of the Civil Rights Era, and the African American Bildungsroman. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 375 Study in European Literature**
  Study of selected works in English or translation by major European writers. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 378 Studies in Transatlantic Literature**
  Study of selected works in English from the Atlantic world. This course examines the diverse literatures, politics, and trade relations of the Atlantic world and considers how transatlantic relations alter the ways we read and understand national literatures. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 380 The Age of Chaucer**
  Reading and discussion of literature of the later Middle Ages, with some emphasis on the work of Geoffrey Chaucer. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 382 Shakespeare:Com/Rom**
  Reading, viewing, and discussion of comedies and romances spanning Shakespeare’s career. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 383 Shakespeare:Tragedies & Histories**
  Reading, viewing, and discussion of history plays and tragedies, with some emphasis on the middle period of Shakespeare’s career, including the major tragedies. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 384 British Renaissance Literature**
  Study of the development of English literature in the sixteenth and seventeenth centuries. Typically the focus is on either poetry or drama. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 385 Restoration &18th Cntry British Lit**
  Study of major works from 1660 to the end of the eighteenth century or of an author, topic, or genre of the period. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 388 Romantic Literature**
  Study of major works from 1780 to 1830, with emphasis on writings by Blake, Wollstonecraft, Wordsworth, Coleridge, Austen, Byron, Keats, P. Shelley, and M. Shelley. This course may count toward the upper-level early British literature requirement for the English major. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 390 Victorian Literature**
  Study of poetry and prose of the Victorian era from 1832 through the fin-de-siècle, including such writers as Tennyson, Browning, Barrett Browning, Arnold, Mill, Ruskin, C. Rossetti, D. G. Rossetti, Swinburne, Hopkins, and Wilde. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 392 19th Century British Novel**
  Study of major British novelists such as Austen, Scott, Dickens, C. Brontë, E. Brontë, Eliot, Collins, and Hardy. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 393 Study in Cont/Mod British Fiction**
  Study of novels, short fiction, and poetry by British writers of the twentieth and twenty-first centuries, or of an author, topic, or genre of the period. Prerequisite: Introduction to Literary Studies: The Art of Reading and Writing (ENG-101) or consent of instructor.  
- **ENG 394 Directed Learning in English**
  Study of individually chosen topics in literature or execution of projects in writing under the direction of a faculty member of the department. Registration only after the instructor has approved a written proposal for the project. Prerequisite: three courses in literature.  

### ADVANCED STUDY IN ENGLISH
Students registering for these courses must fulfill the **prerequisites** first and should consult with English department faculty if they have questions. 

- **ENG 454 Honors Research**
  Development and completion of an honors thesis under the direction of a faculty member of the department. Normally taken in Fall Term of the senior year for an X status grade. Prerequisites: Seminar in Literature (ENG-464) or Seminar in Literature: United States Pluralism (ENG-467) and consent of instructor.  
- **ENG 464 Seminar in Literature**
  Advanced study of a specialized topic in literature. As a capstone experience, the seminar fosters student-driven inquiry and requires students to present their work-in-progress and to complete a culminating project (typically, an extensive research paper). To be taken at or near the end of the English major. May be counted toward the upper-level early British literature requirement for the English major when topic is appropriate. May be taken more than once for credit toward the English major. Prerequisites: junior standing, The Art of Literary Research (ENG-301), and an English course numbered 305 or above.
- **ENG 467 Seminar inLit:USPluralism**
  Advanced study of a specialized topic in literature. As a capstone experience, the seminar fosters student-driven inquiry and requires students to present their work-in-progress and to complete a culminating project (typically, an extensive research paper). To be taken at or near the end of the English major. May be taken more than once for credit toward the English major. Prerequisites: junior standing, The Art of Literary Research (ENG-301), and an English course numbered 305 or above.
- **ENG 494 Internship in English**
  Exploration of a career area related to English. Application and supervision through the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. This course does not satisfy any of the requirements for a major in English, but with consent of rhetoric department chair, one credit from an appropriate internship may satisfy the requirements for a minor in writing. Prerequisites: junior standing and consent of department chair.


