## Film Studies {#sec-film-studies}
Cohen (Co-Coordinator), Lausch, Rogers (Co-Coordinator).

The film studies major is an interdisciplinary major that allows a student to focus on the particular aspect of film studies that interests her or him most – for example, film writing, cinema studies, or digital production.

### Film Studies Major
A major in film requires a minimum cumulative 2.0 GPA in all courses counted toward the major. A major in film studies requires ten courses taken from each of the three disciplines represented in the major.  
1. ART 150 Time Based Media  
2. FLM 105 /FLM 105L Introduction to Film and Laboratory  
3. FLM 200 /FLM 200L Film Analysis and Laboratory (WE)  
4. FLM 225 /FLM 225L Film History and Laboratory (WE)  
5. FLM 464 Seminar in Film II: and FLM 474 Senior Seminar II in Film & Senior  
6. **Five** courses chosen from the following, in consultation with the Film Studies administrative coordinator.  At least two of the courses must be completed at the 300 level or above, and no more than two courses may be selected with the same prefix.  
	
>ART 145 Digital Studio  
	ART 155 Photography: Light Writing  
	ART 325 Contemporary Photographic Genres  
	ART 361 Documentary  
	ART 370 Video Art and Production  
	COM 151 Introduction to New Media Studies  
	COM 157 Introduction to Media Analysis  
	COM 161 Visual Rhetoric  
	COM 337 Persuasion  
	COM 341 Digital Storytelling  
	COM 357 Sex, Race, & Gender in Media  
	CRW 255 Playwriting Workshop I or THE 255 Playwriting Workshop I  
	CRW 350 Screenwriting  
	FLM 250 Film Topics  
	FLM 350 Advanced Topics in Film  
	FLM 442 Independent Study in Film  
	FLM 494 Internship in Film  
	MU 140 Film Music  
	MU 195 Music Production  
	RHE 137 Creative Nonfiction U.S.-Pluralism  
	RHE 146 Creative Nonfiction:Global Perspect  
	RHE 200 Rhetorical Theory and Practice  
	RHE 255 The Essay  
	RHE 257 Environmental Rhetoric  
	THE 130 Technical Production I  
	THE 140 Design for the Stage  
	THE 220 Tech Theatre Lab  
	THE 290 Directing I  


### Film Studies Minor
A minor in film studies requires six courses chosen in consultation with the Film Studies administrative coordinator.  
1. ART 150 Time Based Media  
2. FLM 105 /FLM 105L Introduction to Film and Laboratory  
3. FLM 200 /FLM 200L Film Analysis and Laboratory (WE)  
4. FLM 225 /FLM 225L Film History and Laboratory (WE)  
5. **One** of the following:  
	
>ART 145 Digital Studio  
	ART 155 Photography: Light Writing  
	ART 325 Contemporary Photographic Genres  
	ART 361 Documentary  
	ART 370 Video Art and Production  
	COM 151 Introduction to New Media Studies  
	COM 157 Introduction to Media Analysis  
	COM 161 Visual Rhetoric  
	CRW 255 Playwriting Workshop I or THE 255 Playwriting Workshop I  
	MU 140 Film Music  
	MU 195 Music Production  
	RHE 137 Creative Nonfiction U.S.-Pluralism  
	RHE 146 Creative Nonfiction:Global Perspect  
	RHE 200 Rhetorical Theory and Practice  
	RHE 255 The Essay  
	RHE 257 Environmental Rhetoric  
	THE 130 Technical Production I  
	THE 140 Design for the Stage  
	THE 220 Tech Theatre Lab  
	THE 290 Directing I  
6. **One** of the following:  
	
>CRW 350 Screenwriting  
	COM 337 Persuasion  
	COM 341 Digital Storytelling  
	COM 357 Sex, Race, & Gender in Media  
	FLM 350 Advanced Topics in Film  
	FLM 442 Independent Study in Film  
	FLM 494 Internship in Film  


### Courses in Film Studies
 **FLM 105 /FLM 105L Introduction to Film and Laboratory**  
  Provides an historical understanding of film art as well as a basic critical perspective. This course surveys basic technical elements of film as well as major genres and cultural themes. Students view a wide spectrum of film and are introduced to the special vocabulary associated with film. Three class meetings and one three-hour lab (0.0 course credit) each week. Lab is P/NP basis only.   
 **FLM 200 /FLM 200L Film Analysis and Laboratory (WE)**  
  Provides practice in the application of major film theories. Subject areas include auteur theory, genre theory, image and montage, narrative form, and digital technologies. Three class meetings and one three-hour lab (0.0 course credit) each week. Lab is P/NP basis only. Prerequisite: Introduction to Film (FLM-105) or consent of the Film Studies administrative coordinator.   
 **FLM 225 Film History**  
  Familiarizes students with the history of film from the beginning to the present. Additional viewing time outside of class is required.   
 **FLM 250 Film Topics**  
  Includes a brief introduction to film analysis, but focuses on a specific topic such as: adaptations, a genre, a period, an individual director, a studio. May be repeated, with consent of instructor, provided the topics are substantially different.   
 **FLM 350 Advanced Topics in Film**  
  Advanced study of a selected topic or method in cinematic production. Example topics: Documentary, Interactive Multimedia, Motion Graphics, Advanced Editing, Producing, and Directing. May be taken more than once for credit, provided the topics are substantially different. Prerequisities: FLM-105 Introduction to Film and ART-170 Time-Based Art I.   
 **FLM 442 Independent Study in Film**  
  Independent Study in Film Independent work on a selected project under the direction of a faculty member of the department. Prerequisites: Previous or concurrent enrollment in Movement (ART 170), Introduction to Film (FLM 105), Film Analysis (FLM 200), Film History (FLM 225). (Offered by arrangement)   
 **FLM 464 Seminar in Film II:**  
  Emphasis is on preparation of work toward the senior capstone project. Only film majors are admitted to this course. Prerequisite: successful completion of Senior Seminar I (FLM-444).   
 **FLM 474 Senior Seminar II in Film & Senior**  
  Emphasis is on preparation of work toward the senior capstone project. Only fillm majors are admitted to this course. Prerequisite: successful completion of Senior Seminar I (FLM-454).   
 **FLM 494 Internship in Film**  
  An internship with a focus on film production. A minimum of 140 hours on-site experience is required. S/U basis only. Prerequisite: junior standing and consent of the Film Studies administrative coordinator.   














