## French & Francophone Studies {#sec-french-and-francophone-studies}
Janca-Aji

The French & Francophone Studies program is an intercultural and interdisciplinary program featuring courses in language, cultural history, literature and cinema, translation and interpretation, and pre-professional studies. Students are strongly encouraged to pursue opportunities for immersive and experiential learning through study abroad, May Term courses, service learning, and community-based projects and to explore ways to incorporate French in and with other major(s).

### French & Francophone Studies Major
A grade of "C" (2.0) or higher must be earned in all courses counted toward a major in French & Francophone Studies. Students complete eight credits of 300- to 400-level courses in French. FRE 315 French Composition & Conversation is required. Up to three credits may be earned by successfully completing a study abroad program in France or a francophone country that is approved by the College and the department. Up to one credit may be earned from a list of approved courses taught in English. One credit from a course taught in French must be taken in the senior year. FRE 499 Exit Exam and Interview is required during the final term before graduation.
 
### French & Francophone Studies Minor
A grade of "C" (2.0) or higher must be earned in all courses counted toward a minor in French & Francophone Studies. Students complete a minimum of four credits of 300- to 400-level courses in French. FRE 315 French Composition & Conversationis required. Up to one credit may be earned from a list of approved courses taught in English. FRE 499 Exit Exam and Interview is required during the final term before graduation.

### Interdisciplinary French & Francophone Studies Major
A grade of "C" (2.0) or higher must be earned in all courses counted toward a major in Interdisciplinary French & Francophone Studies. Students complete 1) **four** credits of courses taught in French at any level, including FRE 315 French Composition & Conversation, 2) a departmentally approved term-long study abroad experience in France or a Francophone country, and 3) **four** credits from courses, taught in either French or English, from the list of approved courses which include at least two different prefixes and demonstrate thematic coherence. Courses not on this list may count for credit with approval of the program coordinator. FRE 499 Exit Exam and Interview is required during the final term before graduation. 

### Interdisciplinary French & Francophone Studies Minor
A grade of "C" (2.0) or higher must be earned in all courses counted toward a minor in Interdisciplinary French & Francophone Studies. Students complete 1) **four** credits of courses taught in French at any level, including FRE 315 French Composition & Conversation, and 2) **three** credits from courses, taught in either French or English, from the list of approved courses which include at least two different prefixes and demonstrate thematic coherence. Courses not on this list may count for credit with approval of the program coordinator. FRE 499 Exit Exam and Interview is required during the final term before graduation FRE 499 Exit Exam and Interview. 


### Courses Taught in English that can be used for credit in French & Francophone Studies

- ARH 201 Art of the Middle Ages
- ARH 218 The World of Renaissance Art
- ARH 231 Romanticism, Realism, Impressionism
- ARH 307 Modern and Contemporary Art
- COM 236 Intercultural Communication
- ENG 146 Intro Postcolonial Literature
- FRE 145 French Literature in Translation
- FRE 146 French Literature Translation:NWP
- FRE 148 French Literature Translation:DWP
- FRE 158 France & Francophone World
- HIS 238 Modern France
- HIS 248 The French Revolution
- HIS 272 History of Medieval Europe
- HIS 288 Renaissance & Reformation
- HIS 355 19th Century Europe
- HIS 365 20th Century Europe
- HIS 372 Early Modern Europe
- PHL 230 Medieval Philosophy
- PHL 240 Early Modern Philosophy
- PHL 255 Existentialism
- PHL 305 Contemporary Continental Philosophy
- PHL 345 Philosophy of Language
- POL 298 European Politics
- REL 148 Islam
- REL 178 Christianity


### Courses in French
- **FRE 115 Elementary French I**
  Designed for students with no previous knowledge of French. In the first term, emphasis is placed on oral practice and exposure to aspects of contemporary French culture. Activities in class are designed to develop the student's proficiency in understanding, speaking, writing, and reading the French language. In the second term, these skills are developed further in the context of class discussion and short compositions. Note: FRE-115 is not open to students with one or more full years of French in secondary school without consent of the instructor in consultation with the student's advisor. 
- **FRE 125 Elementary French II**
  Designed for students with no previous knowledge of French. In the first term, emphasis is placed on oral practice and exposure to aspects of contemporary French culture. Activities in class are designed to develop the student's proficiency in understanding, speaking, writing, and reading the French language. In the second term, these skills are developed further in the context of class discussion and short compositions. Note: FRE-115 is not open to students with one or more full years of French in secondary school without consent of the instructor in consultation with the student's advisor.
- **FRE 145 French Literature in Translation**
  Reading, in translation, of a selection of works centering on a theme, genre, time period, or author. Students preparing a French major or minor must write a paper in French. Taught in English.
- **FRE 146 French Literature Translation:NWP**
  Same as French Literature in Translation (FRE-145) except selected works focus on francophone writers from Africa, Asia, or the Caribbean.
- **FRE 148 French Literature Translation:DWP**
  Same as French Literature in Translation (FRE-145) except selected works focus on diverse Western perspectives: women’s writing, gay and lesbian literature, or Quebeçois literature.
- **FRE 158 France & Francophone World**
  An interdisciplinary survey of topics and issues central to an understanding of contemporary France:social, cultural, political, and economic. Films and speakers may be included in the format of this course. Taught in English.
- **+++MISSING INFO: c.fre199.long +++**
  +++MISSING INFO: c.fre199.desc +++
- **FRE 235 Intermediate French**
  Reviews French grammar and vocabulary thoroughly in the context of an introduction to French and Francophone culture. Includes short readings and compositions, films, discussions, and immersion activities to improve language skills. Designed for students who have completed two semesters of
French at Coe or with 2-4 years of high school French. Prerequisite: placement, Elementary French II (FRE-125) or consent of instructor.
- **FRE 315 French Composition & Conversation**
  Serves as the capstone of previous language courses, sharpens oral and written communication skills, and introduces students to the particular ways in which native speakers of French tend to express themselves through listening exercises, discussion, immersion activities, interviews, and compositions on cultural aspects of communication. This course is required of all students majoring or minoring in French. It is expected that this course be followed by Introduction to French Literature (FRE-335) or History of French: Language and Culture (FRE-3XX), in the following term. Prerequisite: Intermediate French II (FRE-225) or consent of instructor.
- **FRE 335 Introduction to French Literature**
  Close reading and critical analysis of different genres of literary texts through discussion, performance, and imitation. Students learn to use literary theory, to write, revise, and edit longer papers, and to develop their own creative voices in French. Prerequisite: French Composition and Conversation (FRE-315) or consent of instructor.
- **FRE 339 French for Health Care**
  Prepares students for using French in health and wellness contexts. Students learn essential vocabulary, improve written and oral communication skills, examine cultural differences, develop skills in translation and medical interpretation, and complete an independent project based on professional interests. May involve community engagement. Can be taken by arrangement. Prerequisite: Oral and Written Communication Skills (FRE-315) or consent of instructor.
- **FRE 340 French & Fracophone Cinema (WE)**
  Surveys some of the major genres, directors, and films of French and francophone cinema from the Lumière brothers to the present, as well as discussions of French film culture and cinema’s relations to history, literature, and other forms of visual and media arts. Students produce their own short films in French. Prerequisite: Oral and Written Communication Skills (FRE-315) or consent of instructor.
- **FRE 345 History of Fr: Language & Culture**
  None
- **FRE 394 Directed Learning  in French**
  For students wishing to investigate a particular aspect of French literature unavailable through the regular sequence of courses offered. Periodic conferences and papers are required. May be taken more than once for credit. Prerequisite: Introduction to French Literature (FRE-335) or consent of instructor.
- **FRE 400 Advanced Language Skills**
  Focuses on improving linguistic skills and deepening understanding of how French is used in a variety of contexts and media through intensive practice. Topics vary from term to term. May be taken more than once for credit for a maximum of 2.0 credits. Prerequisite: Oral and Written Communication Skills (FRE-315) or consent of instructor. (0.5 course credit)
- **FRE 444 Ind Study-French**
  Independent investigation of a selected project in French under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of department chair.
- **FRE 446 Colonial & Multicultural Narratives**
  A study of the history of "la francophonie" in terms of France's colonial experiments, and their literary legacies, and current issues of immigration and multiculturalism. Includes novels and films from France, Cameroon, Senegal, Canada, Morocco, and Martinique. Prerequisite: Introduction to French Literature (FRE- 335) or History of French: Language and Culture (FRE-345).
- **FRE 452 Adv Language Skills & Trnsltn Wkshp**
  Focus on improving linguistic skills and deepening understanding of how French is used in a variety of contexts and media through intensive practice translating from and into French May be taken more than once for credit for a maximum of 3.0 credits. Prerequisite: French Composition and Conversation (FRE-315) or consent of instructor.
- **FRE 494 Internship in French**
  Exploration of a career area related to French. Application and supervision through the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. This course does not satisfy any of the requirements for a major in French. Prerequisites: junior standing and consent of department chair.
- **FRE 495 Top in French/Francophone Lit & Clt**
  Literature and culture course centering on a theme, region, time period, or genre. Approach and content vary from term to term as determined by the instructor. Topics include: Writing and Painting in 19th-century Paris, Contemporary Writing in French, Postcolonial Lives. May be taken more than once for credit for a maximum of 3.0 credits. Prerequisite: Introduction to French Literature (FRE- 335), or History of French: Language and Culture (FRE-3XX).
- **FRE 499 Exit Exam and Interview**
  Evalutates the student's progress in French and experinece of the program. To be completed with faculty in French during the last semester before graduation. P/NP basis only. Prerequisite: consent of instructor. (0.0 course credit) 














