## Gender And Sexuality Studies (Minor Only) {#sec-gender-and-sexuality-studies}
Janca-Aji (Administrative Coordinator).

The Gender and Sexuality Studies program is an interdisciplinary inquiry into the ways in which gender and sexuality inform constructions of identity, societies, and ideologies across race, ethnicities, class, cultures, and historical periods.  Because core courses and electives are offered by faculty across the College, students are encouraged to meet with the Gender and Sexuality Studies administrative coordinator for informal advising as soon as they declare a minor.

### Gender and Sexuality Studies Minor
A minor in gender studies requires a minimum cumulative 2.0 GPA in all courses counted toward the minor.  
1. GS 107 Intro Gender & Sexuality Studies  
2. GS 327 Thry&Mthds/Gender &Sexuality Stdy  
3. **Four** electives from the lists below, with at least **three** from the list of core courses. Other courses may count as electives when topics are appropriate with the consent of the academic coordinator.   
	**Core Courses**  
		ARH 107 Gender and Art  
		COM 357 Sex, Race, & Gender in Media  
		ENG 206 Gender and Literature: NWP  
		ENG 207 Gender & Lit:US Pluralism  
		ENG 208 Gender & Lit:DWP  
		GS 127 Dress, Gender, and Identity  
		GS 136 Gender in Non-Western World  
		GS 247 Gender & Sexuality StudiesSymposium  
		GS 387 Topics: Gender & Sexuality Studies  
		HIS 297 Women in America  
		NUR 137 Human Sexuality or PSY 137 Human Sexuality  
		PHL 277 Philosophy of Gender & Race  
		POL 277 Women & Poltics in US  
		PSY 208 Gender Psychology  
		SOC 417 Sociology of Sex & Sexuality  
	**Component Courses  
		ANT 116 Cultural Anthropology  
		COM 236 Intercultural Communication  
		COM 357 Sex, Race, & Gender in Media  
		COM 361 Communication & Social Change  
		EDU 187 Human Relations  
		RHE 377 Cultural Studies  
		SCJ 350 Human Rights & Comparative Justice  
		SOC 207 Sociology of the Family  
		THE 288 History of Dress  

### Courses in Gender and Sexuality Studies
- **GS 107 Intro Gender & Sexuality Studies**
  An examination of the ways in which societies shape our notions of gender, including, but not limited to, how class, race, and sexual orientation influence this process. Topics for lecture, discussion, and readings are selected by the instructor and are drawn from a variety of academic fields. 
- **GS 127 Dress, Gender, and Identity**
  Explores the issues of personal adornment and dress related to the projection of gender and identity. Examples from contemporary cultures around the globe are analyzed and compared following a variety of themes. Those themes include: revealing and concealing gender and/or identity, dress codes as social markers, body image and gender, and group identity through dress and adornment. 
- **GS 136 Gender in Non-Western World**
  A study of gender rituals, family practices, sexuality, gendered work, and other aspects of gender in non-western cultures. 
- **GS 247 Gender & Sexuality StudiesSymposium**
  None 
- **GS 327 Thry&Mthds/Gender &Sexuality Stdy**
  Offers a thorough introduction to critical theories and methods in feminist and queer studies with particular emphasis on historical foundations, questions of power and discourse, intersectionalities, and global perspectives. A research project using feminist or queer theory is required. Prerequisite: Introduction to Gender and Sexuality Studies (GS-107) and completion of one elective that counts toward a Gender and Sexuality Studies major. (Offered Spring Term, alternate years) 
- **GS 387 Topics: Gender & Sexuality Studies**
  Focuses on specific authors, events, or issues in feminist, queer, and masculinity studies. May be taken more than once, provided the topics are substantially different. Prerequisites: Introduction to Gender and Sexuality Studies (GS-107) or consent of instructor. 
NOTE: Students are encouraged to complete Theory and Methods in Gender and Sexuality (GS-327) before enrolling in GS-387. 
**NOTE:** *Students are encouraged to complete GS 327 Thry&Mthds/Gender &Sexuality Stdy before enrolling in GS 387 Topics: Gender & Sexuality Studies. *











