## History {#sec-history}
Swenson Arnold, Buckaloo, Keenan (Chair), Nordmann, Ziskowski. 

The history department allows students the opportunity to study history broadly, while also focusing on specific interests. Students learn how to express themselves, both orally and in writing, and, in the liberal arts tradition, are taught to learn quickly, communicate clearly, and build a rewarding career and life in their chosen field.

### History Major
A major in history requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. **Four** courses in one of these two combinations:
	- HIS 115 History of Europe to 1500
	- HIS 125 History of Europe Since 1500
	- HIS 145 History of United States to 1865 **or** HIS 155 History of United States since 1865
	- One additional U.S. History course

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **or**

	- HIS 145 History of United States to 1865
	- HIS 155 History of United States since 1865
	- HIS 115 History of Europe to 1500 **or** HIS 125 History of Europe Since 1500
	- One additional European History course

2. HIS 205 Historians Craft
3. **One** of the following:
	- HIS 136 East Asian Civilization
	- HIS 246 History of Modern China
	- HIS 256 History of Modern Japan

4. **One** of the following:
	- HIS 465 Seminar in Ancient History
	- HIS 466 Seminar Modern East Asian History
	- HIS 472 Seminar American History I
	- HIS 473 Seminar American History II
	- HIS 474 Seminar Modern European History

5. **Three** additional history courses

**NOTE:** *With departmental approval, successful completion of the ACM Newberry Seminar: Research in the Humanities Program off-campus study experience may be used to satisfy #4 above.*


### History Minor

**One** of the following combinations:

- HIS 115 History of Europe to 1500
- HIS 125 History of Europe Since 1500
- **One** course in United States history
- **One** course in Asian history
- **Two** additional history courses approved by the department

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **or**

- HIS 145 History of United States to 1865
- HIS 155 History of United States since 1865
- **One** course in European history
- **One** course in Asian history
- **Two** additional history courses approved by the department

### Courses in History by Content Area

*Asian History*  
        - HIS 136 East Asian Civilization  
        - HIS 216 History of Modern Korea (WE)  
        - HIS 246 History of Modern China  
        - HIS 256 History of Modern Japan  
        - HIS 316 Topics in History:Non-Western Persp  

*European History*  
        - HIS 115 History of Europe to 1500  
        - HIS 125 History of Europe Since 1500  
        - HIS 238 Modern France  
        - HIS 248 The French Revolution  
        - HIS 272 History of Medieval Europe  
        - HIS 275 Ancient Greek History  
        - HIS 285 History of Ancient Rome  
        - HIS 288 Renaissance & Reformation  
        - HIS 292 History of Modern England  
        - HIS 318 Topics in History :Div West Persp  
        - HIS 355 19th Century Europe  
        - HIS 365 20th Century Europe  
        - HIS 372 Early Modern Europe  

*U.S. History*  
        - HIS 145 History of United States to 1865  
        - HIS 155 History of United States since 1865  
        - HIS 217 American War in Vietnam  
        - HIS 227 American Civil War  
        - HIS 257 Native American History  
        - HIS 297 Women in America  
        - HIS 317 Topics in History:US Pluralism  
        - HIS 325 Recent American History I  
        - HIS 335 Recent American History II  
        - HIS 347 African American History  
        - HIS 387 American Colonial History  
        - HIS 395 United States Diplomatic History  

*Methods and Research*  
        - HIS 205 Historians Craft  
        - HIS 465 Seminar in Ancient History  
        - HIS 466 Seminar Modern East Asian History  
        - HIS 472 Seminar American History I  
        - HIS 473 Seminar American History II  
        - HIS 474 Seminar Modern European History  

*Other History Courses*  
        - HIS 208 The First World War (WE)  
        - HIS 218 The Second World War (WE)  
        - HIS 268 Latin America  
        - HIS 276 The "Discovery" of America: Clash  
        - HIS 278 History of the Holocaust (WE)  
        - HIS 286 Modern Middle East  
        - HIS 300 Public History  
        - HIS 306 Revolution, Social Struggle, Testim  
        - HIS 308 Legacies of the Cold War inLatin Am  
        - HIS 328 Modern France  
        - HIS 444 Ind Study-History  
        - HIS 494 Internship in History  

### Courses in History
 **HIS 115 History of Europe to 1500**    
  The development of Western civilization from the earliest times to 1500, with primary emphasis on the culture and thought of the Ancient, Medieval, and Renaissance eras.  
 **HIS 125 History of Europe Since 1500**  
  The development of Western civilization from 1500 to modern times, with emphasis on the cultural and intellectual development of the West and such topics as the Reformation, the Enlightenment, the Industrial Revolution, Imperialism, and the rise of Totalitarianism.  
 **HIS 136 East Asian Civilization**  
  A survey of East Asian civilization with emphasis on China from its origins to 1700. Particular attention is paid to cultural and political factors.  
 **HIS 145 History of United States to 1865**  
  A survey of relations between indigenous, European, and African peoples in places that would become the United States from the colonial era through the Civil War. Topics include European colonization; indigenous resistance; racial slavery; the American Revolution and creation of the United States; westward territorial expansion; and the Civil War.  
 **HIS 155 History of United States since 1865**  
  A survey of American history from the Reconstruction to the present. Topics include the changing American economy, the inclusion and exclusion of various Americans defined by race, class, and gender, and the emergence of the United States as a world power.  
 **HIS 205 Historians Craft**  
  Introduction to the nature and craft of history. Emphases include use of sources, historiography, philosophy of history, and various forms of historical writing. The capstone assignment is a research paper. Prerequisite: sophomore standing.  
 **HIS 208 The First World War (WE)**  
  Introduces students to the global history of the First World War and the start of the interwar period. The class focuses on the political, cultural, and social effects of the war through a study of historical documents, period literature, and film. Through class discussion, short compositions, response papers, and digital humanities work students will: critically analyze historical documents; identify and evaluate the significance of key actors, events, and ideas of the First World War; and synthesize evidence from to produce effective written and oral arguments.  
 **HIS 216 History of Modern Korea (WE)**  
  Introduces students to modern Korean history by examining Korea’s transition from a politically isolated rural state to, in the South, an industrialized country electing its own government and, in the North, a totalitarian state capable of producing nuclear weapons. Students will examine historical documents, literature and film and use class discussion and formal papers to analyze key events such as: Korea’s colonization under Japan; the Korean War; South Korea’s economic and democratic “miracles;” North Korean communism and nuclear brinksmanship; and South Korea’s emergence as a major producer of exported entertainment like K-Pop and K-Drama.  
 **HIS 217 American War in Vietnam**  
  Examines the American war in Vietnam from its earliest roots to its latest ramifications and from multiple perspectives. Emphases include the French Indochina War, American policy debate, the sources of American policy, Vietnamese perspectives, and the war in fiction and film.  
 **HIS 218 The Second World War (WE)**  
  Introduces students to the global history of the Second World War, beginning with the interwar period and moving into the start of the Cold War. The course will focus on both the European and Pacific battle and home fronts, including the Holocaust, through a study of historical documents, period literature, and film. Through class discussion, short compositions, response papers, and digital humanities work students will: critically analyze historical documents; identify and evaluate the significance of key actors, events, and ideas of the Second World War; and synthesize evidence from to produce effective written and oral arguments.  
 **HIS 227 American Civil War**  
  A study of events, issues, ideas, and forces leading to the American Civil War and the resulting Reconstruction. Topics emphasized include slavery, social, economic, and political events leading to the war, the political and military strategies of the war, the efforts of Americans on the homefront, and the trials and triumphs during Reconstruction.  
 **HIS 238 Modern France**   
  An examination of the major political, cultural, and social developments in France from the end of the French Revolution to present day, with an emphasis on the changes and shifts in French national identity and global relations.  
 **HIS 246 History of Modern China**  
  A history of modern China since 1700. Chinese states and society from the height of Qing culture, through the impact of the West and Japan, the rise of Chinese Republicanism and Marxism, the Liberation of 1949, the Great Leap Forward, the death of Mao Zedong, and rule of Deng Xiaoping, up to the present day.  
 **HIS 248 The French Revolution**   
  An investigation of the origins and course of the French Revolution from the Ancien Regime to 1815. The course covers the Enlightenment, the collapse of the Ancien Regime, the opening of the Revolution, the Terror, and Napoleon.  
 **HIS 256 History of Modern Japan**  
  A history of modern Japan since 1700. Historical analysis of Edo period culture, politics and society, rapid Meiji era changes, constitutionalism and imperialism, Japan’s expansion in Asia, World War II, the post-war social change, and economic recovery and rise to international leadership, up to the present.  
 **HIS 257 Native American History**  
  Examines the history of Native Americans and their relationships to Europe and Anglo-America from pre- Columbian times to the present. Emphases include understanding Native cultures, early Anglo-Indian relations, the western “Indian wars,” and the Red Power movement of the 1970s.  
 **HIS 268 Latin America**  
  Survey of the social, political, economic, and cultural factors of Latin America from the colonial era to the present, with an emphasis on how these factors influence present day Latin America.  
 **HIS 272 History of Medieval Europe**  
  A survey of Medieval Europe focusing on the intellectual, cultural, religious, artistic, and literary achievements of the High Middle Ages from roughly 1000 A.D. to 1300 A.D.  
 **HIS 275 Ancient Greek History**  
  An examination of the evolution of certain key institutions and traditions in the ancient Greek world—political, constitutional, military, social, and economic—with particular emphasis on the revolutionary changes experienced during the Classical Age, i.e., the fifth and fourth centuries B.C.  
 **HIS 276 The "Discovery" of America: Clash**  
  Focuses on the biggest empires in the Americas (Maya, Aztec, and Inca) and the process of conquest and colonization after Christopher Columbus’ arrival. The students will read accounts written during the 15th-17th centuries and consider how to critically engage them. The class aims to reflect not only on the stories of the conquistadores, but also on those of the conquered people through historical accounts that attempt to give a voice to the voiceless, analyze the challenges of facing a completely unknown culture, and the ethical implications of imposing your values and traditions on others. By the end of the class, the student will be able to provide an overview of the Spanish Conquest, its history, and controversies. Students also will develop
skills to analyze primary and secondary sources and write small response papers as well as a small essay that demonstrates an understanding of the time period and the ability to support an argument.  
 **HIS 278 History of the Holocaust (WE)**  
  Introduces students to the examination of the causes, experiences, and legacy of the Holocaust, studying viewpoints of victims, perpetrators, and bystanders. Students will study historical documents and literature as well as audiovisual sources in course discussions and written work as they cover social, cultural, and political history from pre-war Germany through World War II, and evaluate memory of the Holocaust in the time period since 1945. Through written work and course discussions, students will: identify and evaluate the significance of key actors, events, and ideas connected to the Holocaust; analyze primary and secondary sources; synthesize evidence to produce cogent written and oral arguments; and critically examine understanding of the Holocaust.  
 **HIS 285 History of Ancient Rome**  
  An examination of the evolution of certain key institutions and traditions—political, constitutional, military, social, and economic—in the ancient Roman world, with emphasis on the revolutionary changes during the transition from the Republic to the Empire, i.e., the first centuries B.C. and A.D.  
 **HIS 286 Modern Middle East**  
  A survey of recent history of the Middle East, from the 1800's to the present with an emphasis on the 20th century. Course focuses on the Middle East and its global interactions.  
 **HIS 288 Renaissance & Reformation**  
  The European experience from the waning of the Middle Ages through the period of the religious wars, with the emphasis on art, the rise of nation states, overseas expansionism, the scientific revolution, and the Protestant and Catholic Reformations.  
 **HIS 292 History of Modern England**  
  A survey of the major constitutional, political, and social developments in England from The Glorious Revolution to the present. Particular attention is paid to the growth of Empire, the Industrial Revolution, the rise of labor, and the effects of The Great War and World War II.  
 **HIS 297 Women in America**  
  A survey of the role and power of a variety of women in America’s history from colonial times to the present, with an emphasis on understanding the place of women today.  
 **HIS 300 Public History**  
  Introduces students to the methods and practices of public history. Public history refers to the many ways history is utilized and applied outside traditional academic research and college classroom settings. Through readings, discussions, site visits, guest speakers, and writing assignments, students will learn about the many ways history is applied, interpreted, and used by museums, historical sites, non-historians, and other publics. They will be introduced to career opportunities in public history and will engage with the cultural and historical resources of Cedar Rapids. Students will analyze primary and secondary sources, refine written and verbal communication skills, and demonstrate an understanding of and ability to use historical research techniques. The course culminates in the production of a hands-on, research-based, collaborative class history project (e.g., exhibit, website, historical markers, etc.) that will serve a public beyond the classroom.  
 **HIS 306 Revolution, Social Struggle, Testim**  
  Revolution, Social Struggle, and Testimonio in Latin America 20th Century

Introduces students to the testimonial literature in Latin America, a genre capable of allowing the oppressed to bring forward their perceptions, world view, and experience of a specific historical moment. This class includes narratives from Guatemala, Nicaragua, El Salvador, México, and Bolivia, among others. It will also include a theoretical segment that will reflect on
the advantages and shortcomings of this genre. At the end of the class, students understand and describe major social problems during specific time frames in the 20th century of the nations studied, articulate the characteristics of this genre, and use a testimonio to gain an insight into a sociohistorical event. Through written assignments and discussions students will analyze the experience of marginalized communities in relation to specific institutional policies. The course ends with a testimonio project where students explore the genre using personal experience, family history, or by interviewing an acquaintance that can offer a special insight regarding a social problem.  
 **HIS 308 Legacies of the Cold War inLatin Am**  
  Legacies of the Cold War in Argentina, Peru, Colombia, and Chile Is an interdisciplinary class centered on the relation between the Cold War and the internal violence that several South American nations lived through during the second half of the 20th century. The influence of anti-imperialist ideas throughout Latin America, the development of the guerrilla movement and its revolutions, and the militarized counter-revolution served as the
political basis for moments of crisis that each nation endured: The National Reorganization Process in Argentina (1976-1982), the Civil War in Peru (1980-2000), the Military Dictatorship in Chile (1973-1990), and the long-term war in Colombia (1948-present). The classwork with historical and anthropological accounts, testimonios, art, film, and theory to give a more diverse image of experiences and implications of these events for different sectors of the communities. At the end of the course, the student will understand major Latin American historical trends in relation to the Cold War, as well as the specificities of the conflict in each one of these nations. They also will be able to analyze one of the factors that play a role in the development of these
crises through a small research project that is developed by written assignments.  
 **HIS 316 Topics in History:Non-Western Persp**  
  An intensive study of a selected topic (or topics) in history related to non-Western cultures through lectures or group discussion or directed learning or research and writing. (Offered on an occasional basis)  
 **HIS 317 Topics in History:US Pluralism**  
  An intensive study of a selected topic (or topics) in history related to United States Pluralism through lectures or group discussion or directed learning, or research and writing. (Offered on an occasional basis)  
 **HIS 318 Topics in History :Div West Persp**  
  An intensive study of a selected topic (or topics) in history related to Diverse Western Perspectives through lectures or group discussion or directed learning or research and writing. (Offered on an occasional basis)  
 **HIS 325 Recent American History I**  
  An examination of American domestic development from the last quarter of the 19th century to the present. Topics include immigration, workers in a changing economy, the World Wars, the Cold War, civil rights, the changing role of women in society, and the contested post-1960’s move to the political right. Prerequisite: History of the United States Since 1865 (HIS-155) or consent of instructor.  
 **HIS 328 Modern France**  
  An examination of the major political, cultural, and social developments in France from the end of the French Revolution to present day, with an emphasis on the changes and shifts in French national identity and global relations.  
 **HIS 335 Recent American History II**  
  An examination of American foreign relations from the 1890s to the present, including the World Wars, the Cold War, and the post-9/11 world. Prerequisite: History of the United States Since 1865 (HIS-155) or consent of instructor.  
 **HIS 347 African American History**  
  An examination of changes and continuities in the lives of African Americans from the colonial era to the present. Emphases include the origins and evolving nature of slavery, race, and racism; development of African-American culture, individual struggles for freedom and civil rights; migrations; segregation; and large-scale movements for social and political change.  
 **HIS 355 19th Century Europe**  
  The evolution of Europe from the French Revolution to World War I, with an emphasis on such topics as Liberalism, the Industrial Revolution, Nationalism, Marxian Socialism, Imperialism, and Great Power diplomacy.  
 **HIS 365 20th Century Europe**  
  A historical survey of modern Europe from 1900 to the present. Emphases are on World War I, the Russian Revolution, the rise of Fascism, Hitler, Nazi Germany, Stalin and Soviet Communism, World War II and the Cold War, as well as the emergence of the European Community (EC) and the collapse of Communism and the Soviet Union.  
 **HIS 372 Early Modern Europe**  
  The history of Europe from 1603-1815 with emphasis on the English Revolutions, the age of Absolute Monarchy, the Enlightenment, the decline of the Ancien Regime, the French Revolution, the Napoleonic era, and concluding with the Congress of Vienna.  
 **HIS 387 American Colonial History**  
  The history of the American colonies from their founding through the American Revolution, focusing on the diverse perspectives of people varying in religion, ethnicity, and gender, as well as economic and political backgrounds.  
 **HIS 395 United States Diplomatic History**  
  Begins with an examination of the relations of the colonies to international affairs. The course focuses attention on topics in American diplomatic history which provide a background for an understanding of the nation’s present status as a world power.  
 **HIS 444 Ind Study-History**  
  Independent work on a selected project under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of instructor.  
 **HIS 465 Seminar in Ancient History**  
  An intensive reading and research seminar on a selected topic in the history of the ancient world. Prerequisite: The Historian's Craft (WE) (HIS-205) and junior standing.  
 **HIS 466 Seminar Modern East Asian History**  
  An intensive reading and research seminar on selected topics in the 19th- and 20th-century history of China, Japan and Korea. Prerequisite: The Historian’s Craft (HIS-205) and junior standing.  
 **HIS 472 Seminar American History I**  
  An introduction to historical research in earlier American history (prior to 1865). Critical inquiry is emphasized in detailed examination of specific topics. Prerequisite: The Historian’s Craft (HIS-205) and junior standing.  
 **HIS 473 Seminar American History II**  
  An introduction to historical research in later American history since 1865. Critical inquiry is emphasized in detailed examination of specific topics. Prerequisite: The Historian’s Craft (HIS-205) and junior standing.  
 **HIS 474 Seminar Modern European History**  
  An intensive reading and research seminar on selected topics in 19th- and 20th-century European political, diplomatic, and intellectual history. Prerequisite: The Historian’s Craft (HIS-205) and junior standing.  
 **HIS 494 Internship in History**  
  Part-time work experience for one term in a history-related field supervised by a faculty member of the department in cooperation with the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. This course does not satisfy any of the requirements for a major or minor in history. Prerequisites: junior standing and consent of department chair.  


