## Health and Society Studies (Minor Only) {#sec-health-and-society-studies}
Kelly, LeMay (Administrative Coordinators).

The Health and Society Studies program is an interdisciplinary cluster of courses that allows students to examine the breadth of issues impacting health and healthcare from the perspectives of natural sciences, social sciences, and humanities.  This Health and Society Studies minor broadens students understanding of the impact of health and healthcare delivery issues, personally, professionally, and within our society.  In addition, the minor will provide a strong interdisciplinary foundation for students interested in graduate studies related to health professions.   Because required and elective courses are offered by faculty across the College, students are encouraged to meet with a Health and Society Studies administrative coordinator for informal advising before choosing the Health and Society minor.

### Health and Society Studies Minor
A minor in Health and Society Studies requires a minimum cumulative 2.0 GPA in all courses counted toward the minor. In addition, only (1) one course from a student's major or collateral major can count towards the Health and Society Studies Minor.

**Required Courses**

1. PHL 165 Bio-medical Ethics
2. SOC 107 Introductory Sociology
3. **One** of the following Biology courses:
	- BIO 103 Anatomy & Physiology
	- BIO 120 Biology, Health, & Society
	- BIO 155 Organismal & Ecological Biology

4. **Three** elective courses from the list below, only (1) one of which may be a 100-level course.
	- ANT 116 Cultural Anthropology
	- CLA 155 Latin/Greek Origins Med Terminology
	- COM 236 Intercultural Communication
	- COM 237 Interpersonal Communication
	- COM 332 Health Communication (WE)
	- KIN 115 Fundamentals:Exercise & Nutrition
	- KIN 125 Public and Consumer Health
	- KIN 155 Substance Abuse
	- PHL 128 Morality & Moral Controversies
	- ECO 221 Health Economics
	- PHY 321 Health Physics
	- PSY 205 Developmental Psychology
	- PSY 235 Abnormal Psychology
	- PSY 325 Health Psychology
	- PSY 350 Drugs & Behavior
	- SPA 339 Spanish for Health Care
	- HSS 494 Health Professions Externship

**NOTE:** *additional health-related courses may be approved as an elective with administrative coordinator approval.*

### Courses in Health and Society Studies
- **HSS 100 Exploration in Health & Society**
  Allows students interested in health-related careers to explore various career options (e.g., medicine, dentistry, physical therapy, occupational therapy, nursing, psychological counseling); to assess and reflect on their own values, abilities, and motivations; and to develop some of the applied knowledge and skills necessary for entry into these occupations. Appropriate for first and second year students. (0.5 course credit) 











