## International Economics {#sec-international-economics}
Students majoring in economics have two options: the **ECONOMICS** major (see @sec-economics) and the **INTERNATIONAL ECONOMICS** major. The international economics major is designed to allow students who are interested in international studies to explore issues of development, growth, and international finance, using the tools of economic analysis. Because of significant overlap in the economics and the international economics requirements, only one of the two majors may be elected by a student. Students majoring in economics or international economics may not minor in either economics or international economics.

### International Economics Major
1. ECO 175 Principles of Macroeconomics
2. ECO 215 Prin Microeconomics
3. ECO 315 Intermediate Macroeconomic Theory
4. ECO 336 Divergent Economic Growth
5. ECO 345 Intermediate Price Theory
6. ECO 375 Econometrics
7. ECO 436 Econ Development
8. ECO 446 International Econ
9. ECO 495 International Finance
10. Two courses in world language numbered 115 or above
11. **One** of the following:
	- A semester abroad
	- A May Term abroad
	- A capstone project in international economics, supervised by a member of the economics faculty

**NOTE:** *International economics majors intending to do graduate work in international studies or intending to pursue a career with a governmental or non-governmental agency are strongly encouraged to consider a minor or major in political science or one of the International Studies tracks to complement the international economics major. Students are also encouraged to work closely with a member of the department to select complementary general education courses. *


### International Economics Minor
1. ECO 175 Principles of Macroeconomics
2. ECO 215 Prin Microeconomics
3. ECO 336 Divergent Economic Growth
4. ECO 436 Econ Development
5. ECO 446 International Econ
6. ECO 495 International Finance














