## International Studies {#sec-international-studies}
Chaimov (Administrative Coordinator).

### International Studies Major
A major in international studies, in any track, requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

### International Studies Core Courses (required of students completing a major in international studies): 
1. IS 116 Intro to International Studies
2. ANT 116 Cultural Anthropology
3. POL 258 World Politics
4. ECO 175 Principles of Macroeconomics
5. **Two** world language courses, numbered 125 or above in Spanish or French, 115 or above in another language. 
6. A term-long study abroad experience, subject to prior approval by the International Studies program committee.
7. IS 464 International Studies Colloquium

**NOTE:** *International Studies majors select one of the following tracks: The Global South, International Relations, or Global Cultural Studies.  (Students who plan to pursue a graduate program that requires a strong foundation in economics should consider the International Economics major offered by the Business and Economics Department.)*

### International Studies Major — The Global South track
The Global South examines the characteristics of regions in what has come to be called the “Global South,” especially Latin America, Africa, and Asia.  It investigates how the evolution of these regions relates to social, political and economic systems.  Students are introduced to a variety of disciplinary and theoretical approaches to the study of international development; graduates better understand the history and legacy of colonialism, the conditions that create or resolve poverty, and relations between the Global South and North.
1. **Seven** international studies core courses (See above.)
2. 












### Courses in Interdisciplinary Studies
- **INT 494 Internship**
  An internship related to the student’s field of interdisciplinary study supervised by the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. Prerequisites: junior standing and approval of an interdisciplinary major. 












