## International Business {#sec-international-business}

Students majoring in business administration have two options: the BUSINESS ADMINISTRATION major (see @sec-business-administration-and-economics) and the INTERNATIONAL BUSINESS major. The international business major is designed to prepare students for specific challenges related to operating an organization in an international context. Because of significant overlap in the business administration and the international business requirements, only one of the two majors may be elected by a student.  

### International Business Major
A major in international business requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.acc171.long >}}
2. {{< var c.eco175.long >}}
3. {{< var c.eco215.long >}}
4. {{< var c.bus190.long >}}
5. **One** of the following:

	-{{< var c.bus250.long >}}
	-{{< var c.bus300.long >}}

6. {{< var c.bus315.long >}}
7. {{< var c.bus446.long >}}
8. **One** of the following:

	-{{< var c.bus466.long >}}
	-{{< var c.eco336.long >}}
	-{{< var c.eco436.long >}}
	-{{< var c.eco446.long >}}

9. {{< var c.eco495.long >}}
10. Two courses in world language numbered 115 or above
11. One of the following:

	-A semester abroad

	-A May Term abroad

	-A capstone project in international business, supervised by a member of the business faculty
















