## International Business {#sec-international-business}

Students majoring in business administration have two options: the BUSINESS ADMINISTRATION major (see @sec-business-administration-and-economics) and the INTERNATIONAL BUSINESS major. The international business major is designed to prepare students for specific challenges related to operating an organization in an international context. Because of significant overlap in the business administration and the international business requirements, only one of the two majors may be elected by a student.  

### International Business Major
A major in international business requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. ACC 171 Principles of Accounting I
2. ECO 175 Principles of Macroeconomics
3. ECO 215 Prin Microeconomics
4. BUS 190 Statistical Analysis
5. **One** of the following:
	-BUS 250 Principles of Management
	-BUS 300 Human Resource Management

6. BUS 315 Business Law I
7. BUS 446 International Business Management
8. **One** of the following:
	-BUS 466 Adv Top Mrktg:non-west persp
	-ECO 336 Divergent Economic Growth
	-ECO 436 Econ Development
	-ECO 446 International Econ

9. ECO 495 International Finance
10. Two courses in world language numbered 115 or above
11. One of the following:
	-A semester abroad
	-A May Term abroad
	-A capstone project in international business, supervised by a member of the business faculty

















