## Interdisciplinary Studies {#sec-interdisciplinary-studies} 

The interdisciplinary major is a rigorous academic program in which the individual student assumes primary responsibility for designing her or his own academic program. Since the interdisciplinary major is structured by the student to serve individual needs, the primary courses selected for the major invariably cross traditional departmental boundaries. In all instances, the interdisciplinary major must display internal topical coherence. Assisting the student in developing a coherent interdisciplinary major will be the supervising faculty member, the student’s academic advisor (if the advisor is not the supervising faculty member), faculty from those departments in which the student is taking primary courses, and the Academic Policies Committee. This committee is responsible for approving student-initiated majors and for offering, where necessary, constructive advice on student proposals. Further guidelines for interdisciplinary majors may be obtained from the Office of the Registrar. The decision to undertake and to seek approval of an interdisciplinary major should be made after the student has had sufficient consultation with the appropriate persons within the College. Normally, this decision is made in the sophomore year, but in no case is an interdisciplinary major approved after the student has embarked upon the final eight courses leading to graduation. Application for an interdisciplinary major must contain the following: 1) a list of the nine to 11 primary courses which constitute the major; 2) a list of secondary or supportive courses which are tangentially related to the major; and 3) a three- to four-page typewritten statement of the rationale for the proposal, indicating, among other things, the internal coherence of the major. 

### Additional guidelines and requirements: 
1. Courses for the major are selected from three or more academic disciplines. At least 40% of the courses in a proposed major must be taken at Coe. 
2. A student’s program of study must include, among the primary and secondary courses listed on the proposal, at least five upper division classes within a single discipline or within two closely related disciplines. Students may consider an established, departmental minor when a minor appropriate to the proposed major is available. Students should not propose a major that simply recombines courses from majors and minors that will already be recognized on the student’s transcript. An interdisciplinary major should be substantially distinct from the student’s other majors and minors. 
3. Students must complete an integrative senior project which demonstrates competence in bringing together at least two disciplines within the major. A student develops a project in consultation with the student’s academic advisor and at least one other faculty consultant from an appropriate department other than that of the academic advisor. The senior project must be reviewed. The form of the review, which may be similar to the defense of an honors project, is determined by the project advisor in consultation with the student. The project must also be reviewed by at least one other faculty member from a department other than that of the faculty advisor. Students may undertake the project with or without academic credit. Registration for credit may take one of two forms. Students may register for regular catalog courses in individualized instruction (e.g., directed readings or directed writing classes) or they may apply for an independent study which requires approval by the Chair of the Academic Policies Committee (Provost). 
4. An interdisciplinary major may include an internship. 


### Courses in Interdisciplinary Studies
- **{{< var c.int494.long >}}**
  {{< var c.int494.desc >}} 












