## Japanese (Courses Only) {#sec-japanese}
Potter.

### Courses in Japanese
- **JPN 106 Images Foreign Culture**
  A course dealing with the picture of human activity and values given in foreign short stores, novels, films, and other works of art, as well as in historical documents and the like. It celebrates and explores the special character of a national or ethnic identity. Topics vary from year to year. Taught in English. 
- **JPN 115 Elementary Japanese I**
  Beginning Japanese phonology, structure, and vocabulary. Study of hiragana and katakana syllabaries with introduction of some kanji. 
- **JPN 125 Elementary Japanese II**
  Continuing study of Japanese phonology, structure and vocabulary. Study of hiragana and katakana syllabaries with introduction of some kanji. Prerequisite: Elementary Japanese I (JPN-115) or consent of instructor. 
- **JPN 215 Intermediate Japanese I**
  Reading and discussion of selected Japanese texts, with continued work on grammatical structures. Increased emphasis on kanji. Prerequisite: Elementary Japanese II (JPN-165) or consent of instructor. 
- **JPN 225 Intermediate Japanese II**
  Reading and discussion of selected Japanese texts, with continued work on grammatical structures. Increased emphasis on kanji. Prerequisite: Intermediate Japanese I (JPN-215) or consent of instructor. 
- **JPN 305 Topics in Japanese Language**
  An advanced study of the Japanese language. May be taken more than once. Prerequisite: Intermediate Japanese II (JPN-225) or consent of instructor. 






