## Literature {#sec-literature}
Sodeman (Administrative Coordinator). 

The following requirements are designed to provide a framework within which the student can shape a program to suit individual interests: 

1. ENG 301 The Art of Literary Research
2. **One** of the following:
	- LIT 464 Seminar in World Literature
	- A course by arrangement chosen in consultation with Literature Administrative Coordinator
3. **Two** world language courses in the same language, intermediate or advanced, taken at Coe College with permission of Literature Administrative Coordinator.  
4. **At least** one literature course taught in a world language
5. **Six** courses to be chosen in consultation with the Literature Administrative Coordinator as indicated from the two lists below.  No more than three from the English department can be counted in the six courses. 

	a) **At least** four courses from the following list: 
		- courses in literature in translation
		- courses in English and American literature and in creative writing offered by the English department 
		- literature courses taught in a world language
		- linguistics courses offered by the English or world language departments
		- Independent Study

	b) **One or more** courses from the following list of core courses to bring the total number of elective courses to six:
		- AAM 137 African American Literature or ENG 137 African American Literature
		- ENG 110 Ancient Mythology
		- ENG 207 Gender & Lit:US Pluralism

### Senior Seminar Course
 **LIT 464 Seminar in World Literature**  
  Required of all literature majors in the senior year. While the subject changes from year to year, the seminar explores how literature from different countries relates to other human activities and disciplines. Thus, the emphasis may be on a historical period (literature and politics in the Renaissance); on an interdisciplinary topic (literature and Freudian analysis); or on a cross-cultural mix (literature, games and play). When the number of senior majors is too small to justify offering the seminar, other arrangements are made for majors to satisfy this requirement: either independent study or participation in an English department seminar, with the stipulation that the term paper be on a topic in comparative literature.   





