## Latin (Courses Only) {#sec-latin}
Langseth.

### Courses in Latin
 **CLA 155 Latin/Greek Origins Med Terminology**  
  Examines the origins of contemporary medical terminology, in part by studying the development of a distinct technical vocabulary, with historical roots in the Greco-Roman, Arabic, and Modern-European worlds, which developed as physicians discovered distinct ways of communicating both with their patients and with each other.  
 **LTN 115 Basic Latin**  
  An intensive examination and analysis of Latin grammar and syntax. Selected readings from the great literary works of the Republic and Empire. A combination of lecture, drill work, and discussion. Prerequisite: no prior instruction in Latin or fewer than two terms of secondary school Latin and consent of instructor.  
 **LTN 125 Selected Readings in Latin**  
  Review of basic grammar and syntax and examination of more advanced grammar and syntax. In-depth readings from selected authors. Combination of lecture, drill work, and class discussion. Prerequisite: Basic Latin (LTN-115) or two or more terms of secondary school Latin and consent of instructor.  
 **LTN 284/384 Topics in Latin**  
  Close textual reading and analysis of major Roman writers. Concern with stylistic differences, translating facility, and Roman culture. Combination of lecture, discussion, and translating. Prerequisite: selected Readings in Latin (LTN125) or four or more terms of secondary school Latin and consent of instructor.  




