## Molecular Biology (Collateral Major) {#sec-molecular-biology}
Leonardo (Administrative Coordinator).

This major might be considered by students interested in finding technical positions in academia or industry after graduation or those planning to pursue a graduate program in molecular biology, cell biology, or microbiology. 

### Collateral Major in Molecular Biology
A major in molecular biology requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

Concurrent completion of a primary major in biology is required (see @sec-biology). Students choosing a collateral major in Molecular Biology may not select the collateral major in Biochemistry. 

1. {{< var c.chm221.long >}}
2. {{< var c.chm321.long >}}
3. {{< var c.chm322.long >}}
4. {{< var c.bio345_345l.long >}}
5. {{< var c.bio405.long >}}
6. One of the following:
	- {{< var c.chm431_431l.long >}}
	- {{< var c.chm432_432l.long >}}
7. One of the following sequences:
	- {{< var c.bio325_325l.long >}}
	- {{< var c.bio415_415l.long >}}
	- {{< var c.bio435_435l.long >}}
	- {{< var c.bio455_455l.long >}}

Strongly recommended:
	
- One of the following sequences:
	- {{< var c.phy165_165l.long >}} and {{< var c.phy175_175l.long >}}
	- {{< var c.phy185_185l.long >}} and {{< var c.phy195_195l.long >}}
