## Molecular Biology (Collateral Major) {#sec-molecular-biology}
Leonardo (Administrative Coordinator).

This major might be considered by students interested in finding technical positions in academia or industry after graduation or those planning to pursue a graduate program in molecular biology, cell biology, or microbiology. 

### Collateral Major in Molecular Biology
A major in molecular biology requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

Concurrent completion of a primary major in biology is required (see @sec-biology). Students choosing a collateral major in Molecular Biology may not select the collateral major in Biochemistry. 

1. CHM 221 Organic Chemistry I
2. CHM 321 Organic Chemistry II
3. CHM 322 Organic Laboratory
4. BIO 345/345L Techniques in Molecular Biology and Laboratory
5. BIO 405 Current Topics in Molecular Biology
6. One of the following:
	- CHM 431/431L Biochemistry and Laboratory
	- CHM 432/432L Protein Biochemistry and Laboratory
7. One of the following sequences:
	- BIO 325/325L Microbiology (WE) and Laboratory
	- BIO 415/415L Developmental Biology and Laboratory
	- BIO 435/435L Cell Physiology and Laboratory
	- BIO 455/455L Molecular Neurobiology and Laboratory

Strongly recommended:
	
- One of the following sequences:
	- PHY 165/165L Basic Physics I & Laboratory and PHY 175/175L Basic Physics II & Laboratory
	- PHY 185/185L General Physics I & Laboratory and PHY 195/195L General Physics II & Laboratory
