## Music {#sec-music}
Benson, Brewer, Carson (Chair), Falk, Hanisch, Lawrence, Lovegood, Shanley, Weiler, B. Wolgast, Zeidieh

Teaching Artists: Altfillisch, Bishop, Brumwell, Capistran, Farley, Fleer, Hall, Harris, Holmes-Bendixen, Marrs, Morton, Nagel, Nothnagle, Phelps, Reznicow, Rothrock, Schamberger, Sentman, Terrell, Wissenberg, M. Wolgast

All Coe students are encouraged to participate in music as part of their liberal arts education. Choral and instrumental ensembles, private lessons in applied music, and academic courses are open to non-music majors. 

The *Coe College Music Department Faculty/Student Handbook* supplements the descriptions of courses and requirements for music majors and outlines departmental policies and procedures. Copies of the *Handbook* are available in the Music Office, Marquis Hall 103 or online at www.coe.edu/academics/majors-areas-study/music.

Students who major in music may select either the Bachelor of Arts degree or the Bachelor of Music degree. 

## Bachelor of Music
Candidates for the **BACHELOR OF MUSIC** degree must successfully complete:

1. **Six** theory and history courses with a grade of “C” (2.0) or higher:
	- MU 109 Theory of Music I/MU 109L Aural Skills Lab I
	- MU 209 Theory of Music II/MU 209L Aural Skills Lab II
	- MU 309 Theory of Music III/MU 309L Aural Skills Lab III
	- MU 255 Music History & Literature I
	- MU 355 Music History & Literature II
	- MU 458 Music History & Literature III
2. MU 285 Conducting I
3. First-Year Experience requirements (see @sec-first-year-experience)
4. The writing emphasis requirement of the general education requirements for the B.A. degree (see @sec-writing-emphasis-courses)
5. The *Keyboard Fundamentals Examination* by the end of the sophomore year. Exceptions must be approved by a majority vote of the music faculty. After successful completion of this examination, credits may be accumulated toward a secondary performance area in piano.
**NOTE:** *A description of this examination is given in the Coe College Music Department Faculty/Student Handbook at `https://www.coe.edu/academics/majors-areas-study/music`*
6. The Bachelor of Music Advanced Standing Assessment (BMASA), an audition evaluation whereby the music faculty assesses the suitability of a student for student teaching or for the presentation of a senior recital. Students performing at the approved level are permitted to register for lessons and classes at the Advanced Level, leading to student teaching or the presentation of a senior recital. Students who are not recommended for study at the Advanced Level are required to select a degree program other than the Bachelor of Music program, or to reapply in a later term.  
7. The Senior Assessment Examination in the final term prior to graduation. 
8. **One** of the four areas of study applicable towards the Bachelor of Music degree: 
	
	**Composition**

	1. MU 195 Music Production
	2. MU 409 Theory of Music IV/MU 409L Aural Skills Lab IV
	3. MUA 413 Orchestration
	4. MUA 423 Saxophone (Adv Std)
	5. **Eight** terms of participation in the Applied Music Course, which must include four terms each of MUA-202C and MUA-303C
	6. **One** course each from the social sciences, natural sciences, and humanities. (New York Term may be used to satisfy the humanities requirements, but the two required language courses described below may not.) 
	7. **Two** courses in French in consecutive terms (may not be used to satisfy the humanities requirement of #6) 
	8. **Two** additional non-music courses 
	9. MUA 490 Senior Recital
	
	**Keyboard and Instrumental Performance**

	1. MU 409 Theory of Music IV/MU 409L Aural Skills Lab IV
	2. **Four** of the following:
		- MU 140 Film Music
		- MU 151 Record Label
		- MU 157 Introduction to Jazz History
		- MU 195 Music Production
		- MU 270 Musical Theatre Acting
		- MU 166/284 Topics in Music
		- MU 385 Conducting II
		- MU 444 Ind Study-Music
		- MUA 133V Vocal Literature
		- MUA 134V Vocal Pedagogy
		- MUA 413 Orchestration
		- MUA 423 Saxophone (Adv Std)
		- One course credit in MUA-courses beyond those required in the Applied Music Course.
	3. **Eight** terms of participation in the Applied Music Course. 
	4. **One** course each from the social sciences, natural sciences, and humanities. (New York Term may be used to satisfy the humanities requirements.) 
	5. **Two** courses in French in consecutive terms (may not be used to satisfy the humanities requirement of #4)
	6. MUA 490 Senior Recital

	**Vocal Performance**

	1. MUA 133V Vocal Literature
	2. MUA 134V Vocal Pedagogy
	3. MU 409 Theory of Music IV/MU 409L Aural Skills Lab IV
	4. **Four** of the following:
		- MU 140 Film Music
		- MU 151 Record Label
		- MU 157 Introduction to Jazz History
		- MU 195 Music Production
		- MU 270 Musical Theatre Acting
		- MU 166/284 Topics in Music
		- MU 385 Conducting II
		- MU 444 Ind Study-Music
		- MUA 133V Vocal Literature
		- MUA 413 Orchestration
		- MUA 423 Saxophone (Adv Std)
		- One course credit in MUA-courses beyond those required in the Applied Music Course. 
	5. **Eight** terms of participation in the Applied Music Course. 
	6. **One** course each from the social sciences, natural sciences, and humanities. (New York Term may be used to satisfy the humanities requirements.) 
	7. **Two** courses in French in consecutive terms (may not be used to satisfy the humanities requirement of #6) 
	8. MUA 490 Senior Recital

	**Music Education (Vocal or Instrumental)**
		
	To complete the Vocal or Instrumental Music Education area of study in four years, a student must begin the sequence of courses during the first year. A student entering either area of study as a sophomore should anticipate spending a fifth year to complete all degree requirements. 
	
	In addition to the following requirements, according to state regulations, all teachers in Iowa “shall acquire a core of liberal arts knowledge including, but not limited to, mathematics, natural sciences, social sciences, and humanities.”  The Mathematics and Natural Science course requirements may be met through coursework at Coe, comparable courses from an accredited college, or a score of 4 or higher on AP examinations in mathematics or science.  Social Science and Humanities core are met with the required EDU courses and MU Music History and Literature courses.

	1. EDU 105 Foundations of Education
	2. EDU 117 Exceptional Learners
	3. EDU 187 Human Relations
	4. EDU 195 Educ Psychology & Development
	5. EDU 219 Educational Technology Lab
	6. MU 205 Practicum in Music Education
	7. MU 360 Elementary & General Music Methods
	8. **One** of the following:
		- MU 361 Choral Music Methods, MU 362 InstrMusMethChrlTeachr, and MUA 134V Vocal Pedagogy (for Vocal Music Education majors)
		- MU 363 Instrumental Music Methods and MU 364 ChrlMusMethInstTeach (for Instrumental Music Education majors)
	9. MU 385 Conducting II
	10. MU 421 Student Teaching Elementary Music
	11. MU 422 Student Teaching Secondary Music
	12. **Seven** terms of participation in the Applied Music Course.
	13. Fulfillment of the general licensure grade point requirement (minimum 2.7 cumulative and in the major) 
		
**NOTE:** *A recital is not required to complete the music education area of study but may be given with the approval of the studio instructor. *

## Bachelor of Arts: Music Major
Candidates for the **BACHELOR OF ARTS** degree with a major in music must successfully complete:

1. MU 109 Theory of Music I/MU 109L Aural Skills Lab I
2. MU 209 Theory of Music II/MU 209L Aural Skills Lab II
3. MU 309 Theory of Music III/MU 309L Aural Skills Lab III
4. MU 458 Music History & Literature III
5. **Four** terms of participation in the Applied Music Course with piano as the primary or secondary performing area. (See @sec-MUA-classes)
6. **One** of the following: 
	- MU 255 Music History & Literature I
	- MU 355 Music History & Literature II
7. **One** of the following (if not used to satisfy #6):
	- MUA 131V Song Interpretation Workshop
	- MU 140 Film Music
	- MU 151 Record Label
	- MU 157 Introduction to Jazz History
	- MU 195 Music Production
	- MU 255 Music History & Literature I
	- MU 270 Musical Theatre Acting
	- MU 166/284 Topics in Music
	- MU 285 Conducting I
	- MU 355 Music History & Literature II
	- MU 409 Theory of Music IV
	- MUA 133V Vocal Literature
	- MUA 134V Vocal Pedagogy
8. The Senior Assessment Examination in the final term prior to graduation 

### Jazz Emphasis
Students completing a **BACHELOR OF ARTS** degree may choose to supplement their music major with an Emphasis in Jazz.  Concurrent completion of a major in music is required.  A minimum of 6.1 course credits must be taken that do not count toward a major in music.

1. MU 157 Introduction to Jazz History
2. MU 409 Theory of Music IV/MU 409L Aural Skills Lab IV
3. **Five** terms of MUA 102 Jazz & Improvisation Lab
4. **Seven** terms of MUA 101 Jazz Ensemble
5. **Two** terms of MUA 102K Piano Arranging Lessons
6. **Two** terms of MUA 103K Piano: Jazz
7. AAM 107 Intro to African American Studies

### Music Industry Emphasis
Students completing a **BACHELOR OF ARTS** degree may choose to supplement their music major with an Emphasis in Music Industry.  Concurrent completion of a major in music is required.  A minimum of 6.5 course credits must be taken that do not count toward a major in music.

1. MU 195 Music Production
2. MU 202 Arts Administration
3. **One** of the following:
	- PR 205 Public Relations
	- RHE 265 Professional Writing
4. **One** of the following:
	- BUS 250 Principles of Management
	- BUS 330 Principles of Marketing
5. **Three** terms of MU 151 Record Label
6. **Two** terms of MU 251 Record Label Seminar

### Musical Theatre Emphasis
Students completing a **BACHELOR OF ARTS** degree may choose to supplement their music major with an Emphasis in Musical Theatre.  Concurrent completion of a major in music with voice as the primary instrument is required.  A minimum of 6.4 course credits must be taken that do not count toward a major in music.

1. THE 150 Acting I
2. THE 170 Voice & Diction
3. THE 270 Musical Theatre Acting
4. **Two** terms of MUA 202V Voice with musical theatre repertoire (may not be used to satisfy the requirement of #1) 
5. **One** additional course credit in practical musical theatre chosen from a combination of the following:
	- MUA 130V MusicalTheatreProductionExperience
	- MUA 131V Song Interpretation Workshop
	- A musical theatre internship approved by the music or theatre arts department
6. **Six** seven-week dance courses (DAN-101 through DAN-142) (0.2 cc)

### Pre-Music Therapy Emphasis
Students completing a **BACHELOR OF ARTS** degree may choose to supplement their music major with an Emphasis in Pre-Music Therapy.  Concurrent completion of a major in music is required.  
The Bachelor of Arts in Music, Pre-Music Therapy Emphasis, is designed to prepare students to apply to a Music Therapy certification program. It is not a free-standing major, and it does not include music therapy courses. Rather, the courses listed below are intended to better prepare Bachelor of Arts in Music students for future study in Music Therapy at an academic program approved by the American Music Therapy Association. Students must complete all requirements for a Bachelor of Arts in Music, in addition to the courses listed below. These include 5 non-music course credits and 2 additional music course credits for a minimum total of 7 course credits that must be taken that do not count toward a major in music.  
Courses taken to satisfy requirements in the Bachelor of Arts in Music may NOT also be used to satisfy the requirements of the Pre-Music Therapy Emphasis below, but all courses MAY be used towards general education requirements.

1. PSY 100 Introductory Psychology
2. BIO 103 Anatomy & Physiology
3. BIO 155 Organismal & Ecological Biology & BIO 155L Organismal & Ecological Biology Lab (concurrent with BIO-155)
4. **One** of the following:
	- EDU 117 Exceptional Learners
	- EDU 187 Human Relations
	- EDU 195 Educ Psychology & Development
	- PSY 235 Abnormal Psychology
	- PSY 315 Learning & Behavior
5. **One** of the following:
	- THE 100 Introduction to Theatre
	- THE 150 Acting I
	- THE 160 Movement for the Stage
	- THE 170 Voice & Diction
	- THE 270 Musical Theatre Acting
6. **Two** credits (or more) from the following:
	- MU 195 Music Production
	- MU 285 Conducting I
	- MU 409 Theory of Music IV
	- MUA 102K Piano Arranging Lessons
	- Additional terms of ensemble participation, beyond those required for the Bachelor of Arts in Music: 
		* Concert Band (0.3 each), Jazz Band (0.2 each), Concert Choir (0.3 each), Chorale (0.2 each), Orchestra (0.3 each), or Handbells (0.2 each) 
	- Additional terms of hour lessons, beyond those required for the Bachelor of Arts in Music, on your primary instrument (0.6 each):  
		* MUA 104K Piano for Music Teachers
		* MUA 151S Guitar
		* MUA 300A Alexander Technique

Strongly recommended:

- MU 255 Music History & Literature I **or** MU 355 Music History & Literature II (whichever is not taken to fulfill the BA in Music requirement) 
- MU 285 Conducting I and MU 385 Conducting II
- Additional music performance courses (ensembles and lessons) 
- Additional theatre, art, biology, business, education, psychology, sociology, and statistics courses 
- Fulfill the academic practicum requirement with a music therapy-related internship 

### Music Minor
The minor in music consists of six course credits. At least four of these credits must be MU courses. MUA credits (lessons and ensembles) must be taken as the Applied Music Course if they are to apply to the music minor. Individual partial credit courses may not accumulate toward credit for a minor in music. 

### Departmental Notes
- Private music lessons are available for credit only. Declared music majors who have achieved junior status (see @sec-class-designation) and who perform in a major ensemble are not charged for lessons. Other Coe students are charged by term according to the total registered lesson credit (see @sec-financial-information). Students who have not attended three lessons by the end of the third week of classes are dropped from music lessons and may be reinstated only by petition. After the third week of lessons, students will be charged for the full term, even if they choose to drop.
- Attendance at the numerous musical events on campus throughout the year is an essential part of the student’s musical training. Students taking lessons for 0.6 credit must attend a specific number of these events each term and the weekly Recital Hour. They must also perform in Recital Hour once each term, except for the first term of the first year of study.

### APPLIED MUSIC
### The Applied Music Course
Intensive studies in performance and repertoire through lessons, ensembles, pedagogy, and techniques. The applied music course requirements are:

1. An hour lesson each week, as specified in the *Coe College Music Department Faculty/Student Handbook* for each major, along with participation and attendance at the weekly Recital Hour and concerts as described above in *Departmental Notes*. (0.6 course credit)
2. Participation in one of the following ensembles, as assigned by audition: Concert Band, Concert Choir, Orchestra, Chorale.
3. Additional ensembles, lessons, or courses in pedagogy, techniques, and literature (0.1-0.6 course credit) that are required for any of the areas of study that lead to one of the music degrees. The *Coe College Music Department Faculty/Student Handbook* (see above) contains descriptions and additional information about these ensembles and courses.
**Prerequisite:** an audition; consent of department chair.

### APPLIED MUSIC CLASSES {#sec-MUA-classes}
Artist teachers in violin, viola, cello, string and electric bass, piano, piano accompanying\*, harpsichord\*, organ\*, flute, oboe, clarinet, saxophone, bassoon, trumpet, horn, trombone, low brass, percussion, guitar, harp, composition\*, and voice are available to all students who wish to study applied music. 

**\*Prerequisite:** proficiency in piano and consent of instructor. 

Composition lessons and classes in keyboard, brass, woodwind, and string literature are also available. Credit for applied music study is granted after the student has satisfactorily passed an examination by a faculty committee (jury exam) at the close of each term. Two hours daily practice per weekly hour lesson are expected of all students taking applied music. 

### APPLIED BRASSES--LESSONS
- MUA 101B Trumpet
- MUA 202B Trumpet
- MUA 303B Trumpet (Adv Std)
- MUA 111B French Horn
- MUA 212B French Horn
- MUA 313B French Horn (Adv Std)
- MUA 121B Trombone
- MUA 222B Trombone
- MUA 323B Trombone (Advanced Standing)
- MUA 131B Low Brass
- MUA 232B Low Brass
- MUA 333B Low Brass (Ad Std)

### APPLIED COMPOSITION--LESSONS
- MUA 101C Composition
- MUA 202C Composition
- MUA 303C Composition (Advanced Standing)
- MUA 413 Orchestration
- MUA 423 Saxophone (Adv Std)

### APPLIED KEYBOARD--LESSONS
- MUA 100K Group Piano
- MUA 102K Piano Arranging Lessons
- MUA 103K Piano: Jazz
- MUA 202K Piano Lessons
- MUA 303K Piano (Adv Standing)
- MUA 304K Piano Accompanying
- MUA 111K Organ
- MUA 212K Organ
- MUA 313K Organ (Adv Standing)
- MUA 121K Harpsichord Lessons
- MUA 222K Harpsichord Lessons
- MUA 323K Harpsichord Lessons(Adv Standing)

### APPLIED PERCUSSION--LESSONS
- MUA 101P Percussion
- MUA 202P Percussion
- MUA 303P Percussion (Adv Std)

### APPLIED STRINGS--LESSONS
- MUA 101S Violin
- MUA 202S Violin
- MUA 303S Violin (Adv Standing)
- MUA 111S Viola
- MUA 212S Viola
- MUA 313S Viola (Adv Standing)
- MUA 121S Cello
- MUA 222S Cello
- MUA 323S Cello (Adv Standing)
- MUA 131S String Bass
- MUA 232S String Bass
- MUA 333S String Bass (Advanced Standing)
- MUA 141S Harp
- MUA 242S Harp
- MUA 343S Harp (Adv Standing)
- MUA 151S Guitar
- MUA 252S Guitar
- MUA 353S Guitar (Adv Std)

### APPLIED VOICE--LESSONS
(Offerings vary each term and include sight singing and/or Alexander Technique.)

- MUA 101V Voice
- MUA 110V Voice Sight Singing Lessons
- MUA 202V Voice
- MUA 303V Voice (Adv Standing)
- MUA 300A Alexander Technique

### APPLIED WOODWINDS--LESSONS
- MUA 101W Flute
- MUA 202W Flute
- MUA 303W Flute (Adv Standing)
- MUA 111W Oboe
- MUA 212W Oboe
- MUA 313W Oboe (Adv Standing)
- MUA 121W Clarinet
- MUA 222W Clarinet
- MUA 323W Clarinet (Adv Std)
- MUA 131W Saxophone
- MUA 232W Saxophone
- MUA 333W Saxophone (Adv Std)
- MUA 141W Bassoon
- MUA 242W Bassoon
- MUA 343W Bassoon (Adv Std)

### APPLIED PEDAGOGY/ ENSEMBLE AND LITERATURE
- MUA 133B Brass Ensemble & Lit
- MUA 134B Brass Pedagogy
- MUA 133K Keyboard Ensemble & Literature
- MUA 134K Keyboard Pedagogy
- MUA 133P Percussion Ens/Lit
- MUA 134P Percussion Pedagogy
- MUA 133S String Ens & Lit
- MUA 134S Strings Pedagogy
- MUA 133W Woodwind Ensemble & Literature
- MUA 134W Woodwind Pedagogy
- MUA 134V Vocal Pedagogy

### APPLIED TECHNIQUES
- MUA 143 Instrumental Techniques:Strings
- MUA 153 Instr Tech:Single Reeds & Flute
- MUA 163 Instr Tech: Double Reeds
- MUA 173 Instr Tech: High Brass
- MUA 183 Instr Tech: Low Brass
- MUA 193 Instr Tech: Percussion

### COURSES IN MUSIC BY CATEGORY
### ENSEMBLES
Ensembles are open, by audition, to all Coe students, as well as being required of all students pursuing a degree in music. 
Credit for participation in these regularly-offered ensembles is available under the following schedule.  Students are encouraged to participate in these ensembles as often as possible. Additional ensembles, offered on a periodic basis, are listed in the *Coe College Music Department Faculty/Student Handbook*.

- MUA 100 Concert Band
- MUA 101 Jazz Ensemble
- MUA 102 Jazz & Improvisation Lab
- MUA 103 Symphony Orchestra
- MUA 104 Concert Choir
- MUA 105 Crimson Singers
- MUA 110 Vocal Jazz Ensemble
- MUA 111 Coe Handbell Ensemble
- MUA 130V MusicalTheatreProductionExperience
- MUA 131V Song Interpretation Workshop
- MUA 284 Applied Music: Special Topics

### GENERAL SURVEY COURSES
- MU 100 Experiencing Music
- MU 101 Music Fundamentals
- MU 140 Film Music
- MU 151 Record Label
- MU 251 Record Label Seminar
- MU 157 Introduction to Jazz History
- MU 161 Hip Hop Workshop
- MU 166 Topics in Music:Non-Western Perspct
- MU 270 Musical Theatre Acting
- MU 284 Topics in Music
- MUA 133V Vocal Literature
- MUA 134V Vocal Pedagogy

### THEORY COURSES 
- MU 109 Theory of Music I
- MU 109L Aural Skills Lab I
- MU 209 Theory of Music II
- MU 209L Aural Skills Lab II
- MUA 211 Group Sight-Singing Lessons
- MU 309 Theory of Music III
- MU 309L Aural Skills Lab III
- MU 409 Theory of Music IV
- MU 409L Aural Skills Lab IV

### COMPOSITION COURSES 
- MU 195 Music Production
- MUA 413 Orchestration
- MUA 423 Saxophone (Adv Std)

### CONDUCTING COURSES 
- MU 285 Conducting I
- MU 385 Conducting II

### HISTORY COURSES 
- MU 255 Music History & Literature I
- MU 355 Music History & Literature II
- MU 458 Music History & Literature III

### MUSIC EDUCATION COURSES 
- MU 205 Practicum in Music Education
- MU 360 Elementary & General Music Methods
- MU 361 Choral Music Methods
- MU 362 InstrMusMethChrlTeachr
- MU 363 Instrumental Music Methods
- MU 364 ChrlMusMethInstTeach
- MU 421 Student Teaching Elementary Music
- MU 422 Student Teaching Secondary Music
- MUA 104K Piano for Music Teachers

### ADVANCED STUDY IN MUSIC 
- MUA 490 Senior Recital
- MU 444 Ind Study-Music

### Courses in Music {#sec-courses-in-music}
**MU Prefix**

 **MU 100 Experiencing Music**  
  Provides a framework for informed music listening and for developing an appreciation for a diverse variety of musical styles. Emphasis is on traditional classical music, with some attention to jazz, electronic, and avant-garde styles. Attendance at live concerts is an integral part of the course. This course does not satisfy any of the requirements for a major in music.  
 **MU 101 Music Fundamentals**  
  An introduction to the materials of music and an understanding of the musical system. The course includes basic keyboard knowledge as well as beginning song writing.  
 **MU 109 Theory of Music I**  
  For students majoring in music and other students with background in music. Develops keyboard harmony, melodic and harmonic dictation, improvisation, four-part writing up to and including dominant seventh chords, and introduction to music notation software. Students seeking a BA in Music or one of the Bachelor Music degrees must also register for an appropriate Aural Skills Lab course. Prerequisite: Music Theory Placement exam or consent of the instructor.  
 **MU 109L Aural Skills Lab I**  
  Provides a focused setting for working on and perfecting the musicianship skills of sight singing, ear training, and musical dictation, all essential skills for musicians. The Aural Skills Labs function in coordination with the Theory of Music sequence of courses. The labs, required of all music majors, incorporate strategies and drills for learning and honing these musicianship skills through in-class individual and group work, as well as guided, independent work online. P/NP basis only. 
Prerequisite: Music Theory Placement exam. Corequisite: Theory of Music I (MU-109). (0.2 course credit)  
 **MU 140 Film Music**  
  An introduction to the history, principles, and techniques of music in film. In addition to lecture, film viewing and analysis, critical reading and response, student presentation, and short film-music projects elucidate the genre.  
 **MU 151 Record Label**  
  Team-oriented class environment offering students practical experience operating 399 Records, a student-run record label. Students make all business and creative decisions, including discovering and developing performing artists on campus, recording, promoting and distributing a finished music product each term. May be taken more than once. (0.5 course credit)  
 **MU 157 Introduction to Jazz History**  
  Surveys many styles of jazz by studying them in a historical perspective. Listening, discussion, and lecture components are emphasized. (Offered May Term only)  
 **MU 161 Hip Hop Workshop**  
  Blend of seminar and studio sessions focusing on hip-hop repertoire, beat arrangement, and lyrical structure. Additional emphasis on vocal recording and editing proficiency, as well as active listening exercises to better apply music production techniques to original student works. Participation in the creative process is required, and collaboration among students is encouraged.  
 **MU 166 Topics in Music:Non-Western Perspct**  
  A topics course that explores the music of one of more non-Western cultures, largely from a musicological viewpoint. Topics could include survey courses, such as World Music, or courses focused on the music of one particular continent, country, or sub-group. Prerequisite: consent of instructor. (Offered on an occasional basis)  
 **MU 195 Music Production**  
  Exploration of audio engineering and recording practices, with special attention to electronic and popular music. Overview of intellectual property in the arts, the evolution of audio technology, and cultural movements that influenced new forms of experimental and commercial music. Students are introduced to the fundamentals of acoustics and sound design through audio production software, with hands-on projects detailing methods for producing music in a variety of genres.  
 **MU 202 Arts Administration**  
  Introduces principles and the development of skills associated with the management of arts organizations. Financial and program planning, audience engagement, marketing and publicity. Supplemental guest lectures by professionals highlight arts advocacy and specific challenges facing nonprofits.  
 **MU 205 Practicum in Music Education**  
  For students considering the teaching profession. Class discussions and reading assignments explore the purpose of music education in the public schools, requisites of good teachers and good teaching, and basic philosophies and methods of music education. Students spend a minimum of 60 hours observing and assisting public school music teachers in a range of activities. Prerequisites: Educational Foundations (EDU-205) and admission to the Teacher Education Program, or consent of Department Chair. (Offered Spring Term)  
 **MU 209 Theory of Music II**  
  Continuation of Theory of Music I. Prerequisite: Theory of Music I (MU-109) or consent of instructor.  
 **MU 209L Aural Skills Lab II**  
  Provides a focused setting for working on and perfecting the musicianship skills of sight singing, ear training, and musical dictation--essential skills for musicians. The Aural Skills Labs function in coordination with the Theory of Music sequence of courses. The labs, required of all music majors, incorporate strategies and drills for learning and honing these musicianship skills through in-class individual and group work, as well as guided, independent work online. P/NP basis only. Prerequisite: Aural Skills Lab I (MU-109L). Corequisite: Theory of Music II (MU-209). (0.2 course credit)  
 **MU 251 Record Label Seminar**  
  Same as MU-151, but at an advanced level. In addition to a weekly seminar providing intensive discussion of music industry topics, students oversee recording sessions and lead development meetings for 399 Records, as well as conduct independent research suitable to career aspirations. Students may not register for both MU-151 and MU-251 in the same term. May be taken more than once for credit for a maximum of 2.0 credits. Prerequisites: junior standing and MU-151 Record Label. (0.5 course credit)  
 **MU 255 Music History & Literature I**  
  Study of the evolution of western music and musical systems, forms, styles, and media from ancient Near East, Greece, and Rome through the first half of the 18th century. Prerequisite: Theory of Music II (MU- 125) or consent of instructor.  
 **MU 270 Musical Theatre Acting**  
  See also Theatre Arts (THE 270), @sec-courses-in-theatre-arts  
  A performance-based studio course focusing on the development of basic skills necessary for musical theatre
performance. Students become familiar with the specialized requirements necessary for the merging of singing
with dramatic action. Periodic performance projects (solos, duets, and ensemble numbers—some including
dialogue) are supplemented by student research projects. The course is also designed to introduce students to a
wide-ranging repertoire of available audition material. Additional rehearsal time outside of class is required.  
 **MU 284 Topics in Music**  
  A course of selected focus that centers on a particular musical issue, problem, theory, or methodology. Topics vary, and they include, but are not limited to, Advanced Form and Analysis, Rock and Roll History, Music of the 1960’s, and Modern Musical Theatre. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: consent of instructor. (Offered on an occasional basis)  
 **MU 285 Conducting I**  
  Basic conducting techniques: reading, analysis, and interpretation of choral, band, and orchestral literature. Laboratory experience with college ensembles. Prerequisite: Theory of Music III (MU-215) or consent of instructor.  
 **MU 309 Theory of Music III**  
  Continuation of Theory of Music II, including musicianship training, form and analysis, chromatic harmony, and the basic compositional tools of the 18th and 19th centuries. Prerequisite: Theory of Music II (MU-209) or consent of instructor.  
 **MU 309L Aural Skills Lab III**  
  Provides a focused setting for working on and perfecting the musicianship skills of sight singing, ear training, and musical dictation, all essential skills for musicians. The Aural Skills Labs function in coordination with the Theory of Music sequence of courses. Aural Skills Lab III is a continuation course for Labs I and II. Required of all music majors, the labs incorporate strategies and drills for learning and honing these musicianship skills through in-class individual and group work as well as guided, independent work online. P/NP basis only. Prerequisite: Aural Skills Lab II (MU-209L). Corequisite: Theory of Music III (MU-309). (0.2 course credit)  
 **MU 355 Music History & Literature II**  
  Study of western music of the 18th and 19th centuries in Europe and America. Prerequisite: Theory of Music II (MU-125) or consent of instructor.  
 **MU 360 Elementary & General Music Methods**  
  Objectives, problems, and methods of teaching elementary music and general music in the schools. Course surveys elementary and general music curricula and develops a functional knowledge of: organization and management; fretted and classroom instruments; methods of teaching singing, rhythmic, and listening activities expected. Directed observation in elementary schools required. Prerequisite: Practicum in Music Education (MU-205). (0.5 course credit) (Offered Spring Term)  
 **MU 361 Choral Music Methods**  
  Objectives, problems, and methods of teaching choral music in the schools. General survey of elementary and secondary choral music curricula and develops a functional knowledge of: organization and management; the changing voice; beginning, intermediate, and advanced choral techniques. Directed observation in elementary and secondary schools required. Credit is given for Choral Music Methods (MU-361) or Choral Music Methods for the Instrumental Teacher (MU-364), not both. Prerequisite: Practicum in Music Education (MU-205) (Offered Spring Term)  
 **MU 362 InstrMusMethChrlTeachr**  
  Objectives, problems, and methods of teaching instrumental music in the schools. General survey of elementary and secondary instrumental music curricula. Students are introduced to: concert band and orchestral techniques; jazz band techniques; marching band techniques; beginning, intermediate, and advanced band and orchestral techniques. Credit is given for Instrumental Music Methods for the Choral Teacher (MU-362) or Instrumental Music Methods (MU-363), not both. Prerequisite: Practicum in Music Education (MU-205) (0.5 course credit) (Offered Spring Term)  
 **MU 363 Instrumental Music Methods**  
  Objectives, problems, and methods of teaching instrumental music in the schools. General survey of elementary and secondary instrumental music curricula and develops a functional knowledge of: organization and management; concert band and orchestral techniques; jazz band techniques; marching band techniques; beginning, intermediate, and advanced band and orchestral techniques. Directed observation in elementary and secondary schools required. Credit is given for Instrumental Music Methods for the Choral Teacher (MU-362) or Instrumental Music Methods (MU-363), not both. Prerequisite: Practicum in Music Education (MU-205). (Offered Spring Term)  
 **MU 364 ChrlMusMethInstTeach**  
  Objectives, problems, and methods of teaching choral music in the schools. General survey of elementary and secondary choral music curricula. Students are introduced to the changing voice and to beginning, intermediate, and advanced choral techniques. Credit is given for Choral Music Methods (MU-361) or Choral Music Methods for the Instrumental Teacher (MU-364), not both. Prerequisite: Practicum in Music Education (MU-205). (0.5 course credit) (Offered Spring Term)  
 **MU 385 Conducting II**  
  Continuation of Conducting I. Prerequisite: Conducting I (MU-285).  
 **MU 409 Theory of Music IV**  
  Further investigation of tonal music, including jazz harmony, harmonic and formal analysis, the rudiments of 18th-century counterpoint, and an introduction to contemporary music. Prerequisite: Theory of Music III (MU-309) or consent of instructor.  
 **MU 409L Aural Skills Lab IV**  
  Aural Skills Lab IV  
 **MU 421 Student Teaching Elementary Music**  
  Directed observation and student teaching in the first six grades. Scheduled daily for seven weeks, approximately six hours per day. Prerequisite: satisfactory completion of all other requirements for the Bachelor of Music in Music Education. (2.0 course credits) (Offered Fall Term)  
 **MU 422 Student Teaching Secondary Music**  
  Directed observation and student teaching in middle school and high school. Scheduled for seven weeks, approximately six hours per day. Prerequisite: satisfactory completion of all other requirements for the Bachelor of Music in Music Education. (2.0 course credits) (Offered Fall Term)  
 **MU 444 Ind Study-Music**  
  Independent work on a selected project in music under the direction of a faculty member of the department. May be taken for an X status grade with consent of instructor prior to registration.  Prerequisites: background courses and consent of department chair.  
 **MU 458 Music History & Literature III**  
  Study of the composers and musical developments in Europe and America in the 20th and 21st centuries, together with the influences of music from other world cultures. Prerequisite: Theory of Music II (MU-209) or consent of instructor.  

**MUA Prefix**

 **MUA 100 Concert Band**  
  Open to all woodwind, brass, and percussion players. The ensemble offers students the opportunity to perform some of the great band repertoire of the 20th and 21st centuries, as well as carefully selected transcriptions of orchestral repertoire. A select Wind Ensemble within the Concert Band occasionally performs additional selections from the contemporary repertoire. The Concert Band tours on a regular basis. (0.3 course credit)  
 **MUA 101 Jazz Ensemble**  
  Membership determined by an audition of interested saxophone, trombone, trumpet, piano, bass, guitar, drum set, and auxiliary percussion players. The ensemble offers students the opportunity to perform varied selections from the jazz repertoire of the 20th and 21st centuries, as well as the opportunity to improvise in the jazz idiom. The Jazz Ensemble tours on a regular basis and performs with three to five guest artists each year. (0.2 course credit)  
 **MUA 102 Jazz & Improvisation Lab**  
  Open to all interested musicians. The ensemble offers students the opportunity to perform varied selections from the jazz repertoire of the 20th and 21st centuries, as well as the opportunity to improvise in the jazz idiom. The Lab gives students an outlet to practice a secondary instrument and also allows music education majors the opportunity to rehearse and conduct a jazz ensemble. (0.1 course credit)  
 **MUA 103 Symphony Orchestra**  
  Membership determined by an audition of interested string, woodwind, brass, and percussion players. The ensemble offers students the opportunity to perform varied selections from the symphonic repertoire of the 18th through the 21st centuries, in both full orchestra and string orchestra formats. The Symphony Orchestra also occasionally performs works that feature soloists or combines with the Concert Choir to present masterworks. (0.3 course credit)  
 **MUA 104 Concert Choir**  
  Membership determined by audition. The ensemble offers students the opportunity to perform a wide variety of repertoire covering many styles from the Renaissance through the 21st centuries. The Concert Choir also occasionally combines with the Symphony Orchestra to present large masterworks, and tours on a regular basis. (0.3 course credit)  
 **MUA 105 Crimson Singers**  
  Presents concerts each term, on and off campus. Open to all interested musicians who sing. The Crimson Singers is a small auditioned, mixed singing ensemble focusing on Broadway, jazz, and popular music styles. Some selections will be choreographed. Participants will gain experience in show choir, jazz, and a cappella singing and performing styles. Previous show choir is preferable; it is not required. Students in the Crimson Singers are also encouraged to enroll in the Concert Choir. Registration for this course is by audition and the consent of the instructor. (0.3 course credit)  
 **MUA 110 Vocal Jazz Ensemble**  
  Membership determined by audition. The Vocal Jazz Ensemble offers students the opportunity to perform in a wide variety of vocal and choral styles, with an emphasis on repertoire for smaller vocal ensemble including vocal jazz, madrigals, pop, and music of other cultures. The Vocal Jazz Ensemble may perform either on or off campus and tours on an occasional basis. (0.2 course credit)  
 **MUA 111 Coe Handbell Ensemble**  
  Provides students the unique opportunity to play English Handbells in a team-ensemble experience. The course focuses on basic through advanced ringing techniques, music-reading skills, rhythmic skills, and coordination skills. Prerequisites: Music Fundamentals (MU-055) or Theory of Music I (MU-115), prior experience in a handbell or other music ensemble, or consent of instructor. (0.20 course credit)  
 **MUA 130V MusicalTheatreProductionExperience**  
  Practical involvement in a mainstage production of a musical as a vocal or instrumental performer, accompanist,
or vocal coach stage manager, assistant director, dramaturge, or in another capacity as approved by the faculty.
May be taken more than once. Prerequisite: an audition. (0.5 course credit)  
 **MUA 131V Song Interpretation Workshop**  
  Open to all vocal musicians. Students will develop performance skills as a solo singer. They will study and interpret stage acting, movement, musicality, and character development. Students will rehearse songs from varied repertoire and perform them in front of an audience. (0.2 course credit)  
 **MUA 133V Vocal Literature**  
  Broad overview of vocal literature (art song, opera, oratorio) from Western Europe and the Americas. Prerequisite: Music History and Literature II (MU-355) or consent of instructor. (0.2 course credit)  
 **MUA 134V Vocal Pedagogy**  
  Credit for applied music study is granted after the student has satisfactorily passed an examination by a faculty committee (jury exam) at the close of each term. Two hours daily practice per weekly hour lesson are expected of all students taking applied music.  
 **MUA 211 Group Sight-Singing Lessons**  
  Study of aural skills in a group setting. Develops ear training and sight-singing proficiencies. Prerequisite: Theory of Music II (MU-209). (0.2 course credit)  
 **MUA 284 Applied Music: Special Topics**  
  Private study in Applied Music topics not offered in MUA course listings for music majors or other interested and qualified students. The course provides extended, yet tangible, instruction and/or research pertaining to the student's specific applied music specialty or related music interest area. Prerequisites: consent of instructor and department chair. (0.3 and 0.6 course credit)  
 **MUA 413 Orchestration**  
  None  
 **MUA 423 Saxophone (Adv Std)**  
  None  
 **MUA 490 Senior Recital**  
  A full-length senior recital in composition or performance area. S/U basis only. Prerequisite: consent of instructor.  

