## Nursing

Bursch (Chair), Dehner, Guthrie, Kittrell, Siems, Umbarger-Mackey 

A description of policies unique to the nursing department is in the *Nursing Department Student Policies Manual*. Copies of the manual are available in the Nursing Department Office, Stuart Hall 415, and online.

### The Bachelor of Science in Nursing Program

The baccalaureate nursing program is designed to prepare students for practice as professional nurses in a variety of settings. The upper division nursing courses draw upon broad and diverse knowledge gained from the liberal arts foundation to support the educational outcomes. 

Clinical experiences in the program include working with clients across the age span in a wide spectrum of practice sites. Nurse preceptors are utilized at clinical sites to provide the maximum amount of individual supervision and educational opportunity to students. Coe College nursing faculty provide clinical expertise and education by overseeing student clinical experiences, evaluating and promoting preceptor performance, and engaging in ongoing dialogue with students regarding the application of theory into practice. 

Graduates of the Bachelor of Science in Nursing degree program are eligible to take the state board licensing examination for Registered Nurses. They are also eligible for admission to graduate programs in nursing and to advanced nurse practitioner programs. The Coe College nursing program is approved by the Iowa Board of Nursing and accredited by the Commission on Collegiate Nursing Education (CCNE). 

Coe College offers two paths to enter the nursing program.  Standard entry is for sophomore level (or higher) college students and direct entry is for selected high school seniors.  Details for both plans are found in the *Nursing Department Student Policies Manual*.  Copies of the manual are available in the Nursing Department Office.  At the end of the sophomore year, a student must possess valid licensure, e.g. Licensed Practical Nurse (LPN) or Certified Nursing Assistant (Direct Care Worker). A student with a revoked license from any state will NOT be admitted into the nursing program. In addition, a clinical component may not be taken by a person: a) who had been denied licensure by the State Board of Nursing, b) whose licensure is currently suspended, surrendered or revoked in any United States jurisdiction, c) whose licensure/ registration is currently suspended, surrendered or revoked in another country due to disciplinary action.

The nursing department Admission, Promotion, and Retention committee reviews applications and selects candidates who are best qualified to meet the standards of the nursing profession. Admission to the BSN degree program is competitive. Those applicants who appear to be the most qualified will be admitted. Standard and direct entry students are expected to maintain the eligibility requirements as outlined in the *Nursing Department Student Policies Manual*. 

### Departmental Notes: 

In order to successfully complete a course and be promoted to successive courses, students must:
	
- Achieve a minimum grade of C (2.0) in all nursing courses; a grade of C- (1.7) or lower requires the student to repeat the course.
- Achieve a cumulative average of 72% on all exams in a given course.

Candidates for the **Bachelor of Science in Nursing** degree must satisfactorily complete: 

1. The general education requirements (see @sec-general-education-courses ).

2. **Eight** required supporting courses:

:::: {.columns}

::: {.column width="20%"}
Biology

Chemistry

Psychology

Sociology

Statistics 
:::

::: {.column width="10%"}

:::

::: {.column width="70%"}

BIO 145 Cellular & Molecular Biology
BIO 195 Introduction to Microbiology
+++MISSING INFO: c.bio215_215l.long +++
BIO 225 Human Physiology

+++MISSING INFO: c.bio111_111l.long +++

PSY 100 Introductory Psychology

SOC 107 Introductory Sociology

+++MISSING INFO: c.sta300.long +++ **or**
STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 110 Stats IIA: Inferential Reasoning
:::

::::

Biology         BIO 145 Cellular & Molecular Biology
		BIO 195 Introduction to Microbiology
		+++MISSING INFO: c.bio215_215l.long +++
		BIO 225 Human Physiology
		
Chemistry	+++MISSING INFO: c.bio111_111l.long +++

Psychology 	PSY 100 Introductory Psychology

Sociology	SOC 107 Introductory Sociology

Statistics 	PSY 300 Stat Methods and Data Analysis **or**
		STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 110 Stats IIA: Inferential Reasoning

3. NUR 100 Nursing Issues (0.2 course credit) (Pre-nursing students must enroll each term of the first year.  A maximum of two seminars may be counted for credit toward graduation.)

4. NUR 200 Nursing Issues II (0.2 course credit) (Pre-nursing students must enroll each term of the sophomore year. A maximum of two seminars may be counted for credit toward graduation.)

5. **Nine** non-clinical theory course credits: 
	- NUR 300 Art & Science of Nursing 
	- NUR 305 Information Literacy & Management
	- +++MISSING INFO: c.nur345_345l.long +++
	- NUR 360 Pharmacological Principles
	- NUR 375 Legal & Ethical Issues in Nursing
	- NUR 425 Nursing Research
	- NUR 430 Community & Population Oriented Nur
	- NUR 431 Wellness in Aging & Chronicity
	- NUR 495 Maternal Newborn Nursing

6. **Four** two-course-credit clinical courses: 
	- +++MISSING INFO: c.nur315_315l.long +++
	- +++MISSING INFO: c.nur355_355l.long +++
	- +++MISSING INFO: c.nur415_415l.long +++
	- +++MISSING INFO: c.nur455_455l.long +++

7. A formal NCLEX review course (at the student’s expense)

8. All required supporting courses and required nursing courses listed above, with no one specific course repeated more than once and with no more than two different courses repeated.


### Courses in Nursing

 **NUR 100 Nursing Issues**  
  An introduction to the nursing degree program. The seminar provides an opportunity for pre-nursing students to interact with nursing students and faculty to explore the process of becoming a nurse. Topics include professional role development and current issues in clinical nursing practice. Pre-nursing students must enroll each term. May be taken for credit a maximum of two times. Prerequisite: first-year student. (0.2 course credit)  
 **NUR 137 Human Sexuality**  
See also PSY 137 Human Sexuality , @sec-psychology  
  See also Psychology (PSY-137), p. 170
Examines human sexuality from the psychosocial, biophysiological, and cultural perspective. Topics include, but are not limited to, cultural and historical influences on our current understanding and attitudes toward the human sexual experience; the development of gender roles as they impact upon political, work, and social relationships; cultural aspects of sexuality including intimacy, courtship, marriage, and procreation; and sexuality during developmental changes and alterations in health such as infertility, pregnancy, abortion, cancer, AIDS, and others. Prerequisite: sophomore standing.  
 **NUR 200 Nursing Issues II**  
  An introduction to the nursing profession. The seminar provides an opportunity for pre-nursing students to explore the profession of nursing through discussions regarding the domains of nursing knowledge, nursing roles, and nursing skills. May be taken for credit twice. Prerequisite: Nursing Issues (NUR-100) or sophomore standing. (0.2 course credits)  
 **NUR 215 Devel Relationship**  
  Investigates theories for successful relationships. The emphasis is on self learning and application of principles involved in healthy and dysfunctional relationships. The students critically review popular literature versus scientific research related to relationship theory. Prerequisite: sophomore standing.  
 **NUR 268 Cult Diver & Health**  
  A study of the health practices of diverse cultures within the United States. Culture guides problem solving with regard to life choices, including health. This course examines how culture affects decisions about health and health care. Prerequisite: sophomore standing.  
 **NUR 297 Parent Child Relationships**  
  A study of the historical, cultural, ethnic, and religious perspectives on parenting in America, the effects of stress and change on parenting ability, and the challenges and rewards of parenting as children and parents move across the lifespan and experience changes in family composition (blended, single-parent, gay and lesbian), health (sandwich generation and aging), and lifestyle. Prerequisite: sophomore standing.  
 **NUR 300 Art & Science of Nursing**  
  Introduces the nursing student to the nursing profession. The concepts of . professional responsibility, accountability, human development, spirituality, values and beliefs, diversity, and death and dying are discussed. Students learn to apply the nursing process, principles of teaching/learning, and therapeutic communication in the practice of individualized nursing care. Preventative nursing strategies in caring for individuals with reduced mobility are introduced. Prerequisite: admission to the Bachelor of Science in Nursing degree.  
 **NUR 305 Information Literacy & Management**  
  Introduces the student to the intellectual language, vocabulary, and expectations used in making nursing decisions in practice. Discusses concepts such as data gathering using search methods, organizing, synthesizing and critical evaluation Data information, knowledge, and standardized nursing language are discussed. Prerequisite: acceptance into the Bachelor of Science Nursing degree or consent of instructor. (0.5 course credits)  
 **+++MISSING INFO: c.nur315_315l_315c.long +++**  
  Provides the foundation for the integration of assessment data and pathophysiological concepts in the application of the nursing process. Focuses on comprehensive health assessment of diverse individuals across the lifespan. Assessment skills, health histories, and physical exams are practiced.  Clinical component provides an opportunity to reinforce health assessment skills with diverse individuals across the lifespan as well as implementing safe, basic patient-centered care. Prerequisites: admission to the Bachelor of Science in Nursing degree; previous or concurrent registration in Art and Science of Nursing (NUR-300). (2.0 course credits)  
 **NUR 345 Mental Health Nursing**  
  Introduces the nursing student to the care of persons with at-risk behavioral responses to life processes. The student analyzes theoretical and empirical knowledge from liberal arts and sciences as it applies to diagnosing and treating at-risk behavioral responses to life processes. The students study such topics as alterations in cognition and thought processes, coping responses, self-perception and violence toward self and others. A major component is the use of therapeutic communication skills to provide support that reduce risk, promote positive coping, and reinforce accurate perceptions in patients with alterations in mental health. Prerequisite: Art and Science of Nursing (NUR-300).  
 **+++MISSING INFO: c.nur355_335l_335c.long +++**  
  Focuses on holistic care of diverse individuals and families across the life span. Applies the nursing process, emphasizing primary, secondary, and tertiary nursing interventions. in the care of individuals experiencing actual or risk for alterations in renal, gastrointestinal, and musculoskeletal systems. Surgical, dietary, and pharmacological management is integrated. Clinical components reinforce application of the nursing process in the delivery of safe, evidence-based, holistic care.. Prerequisites: Art and Science of Nursing (NUR-300); Pathophysiology and Assessment/Clinical Application (NUR-315); Information Management and Patient Care Technology (NUR-305). (2.0 course credits)  
 **NUR 360 Pharmacological Principles**  
  Basic concepts and principles of administration, pharmacokinetics, pharmacodynamics, and application to basic biophysical concepts for specific pharmacological interventions. A brief overview of the mechanisms of action of select classifications of drugs is included. Prerequisite: acceptance into the Bachelor of Science in Nursing Degree or consent of instructor. (0.5 course credits)  
 **NUR 375 Legal & Ethical Issues in Nursing**  
  Focuses on the complexity of moral, legal, and ethical issues in health care. Topics include the legislative and regulatory processes governing healthcare, appraisal of legal risks, ethical principles, current ethical debates in healthcare, and developing trends and ethical conflicts. Students examine and explore one topic in depth. Prerequisite:acceptance into the Bachelor of Science Nursing Degree or consent of instructor .  
 **NUR 387 Alternative Therapies for Hlth/Heal**  
  Examines available alternative and complimentary therapies. Risks and benefits of these modalities are assessed to determine if there are solid, scientific rationales for them. Therapies include dietary supplements, mind-body interventions (e.g., meditation), body based methods (e.g., massage), and energy therapies (e.g., Reiki). Prerequisite: sophomore standing.  
 **+++MISSING INFO: c.nur415_415l_415c.long +++**  
  Advances and continues the focus of holistic care for diverse individuals, families, groups, and populations across the life span. Applies the nursing process, emphasizing primary, secondary and tertiary nursing interventions, in care of individuals experiencing actual or risk for alterations in integumentary, pulmonary, cardiovascular, endocrine, sensory/neurological, and immune systems. Surgical, dietary and pharmacological management is integrated. Clinical components reinforce application of the nursing process in the delivery of safe, evidence-based, holistic, patient-centered care. Prerequisites: Introductory Concepts in Nursing/Clinical Application (NUR-355). (2.0 course credits)  
 **NUR 425 Nursing Research**  
  Study of the research process, the language of research, hypothesis formulation and testing, data collection, and analysis as they relate to the profession of nursing. Discussion of the nurse as a consumer of research with critical evaluation of selected research endeavors. Nursing research project required. The intent of this learning experience is to expose the student to the basic steps of the research process and their relationship to nursing. Prerequisites: R.N., junior, or senior standing in the nursing program, and Statistical Methods in the Behavioral Sciences (PSY-215) or Statistical Reasoning-Statistical Foundations (STA-100) (7 weeks) and Statistical Reasoning IIA (STA-110) (7 weeks).  
 **NUR 430 Community & Population Oriented Nur**  
  Focuses on community and population health promotion, and disease/injury prevention. Community oriented nursing roles are discussed. Topics include levels of prevention, risk analyses, harm reduction, causality, epidemiology, biostatistics, study designs, and sources of data applied to population health. Current issues related to disease control and surveillance, screening programs, clinical decision-making, health planning, and evaluation are addressed. Clinical application includes community observation experiences. Prerequisite: previous or concurrent registration in Nursing Research (NUR-425).  
 **NUR 431 Wellness in Aging & Chronicity**  
  Examines normal versus abnormal aspects of the aging process. Common health problems of the elderly are discussed. Addresses evidence-based strategies to promote wellness and to assist those living with chronic illnesses. Explores community resources to meet the holistic health needs of diverse individuals, groups, and families. Topics include the impact of culture, gender, stigma, and socioeconomic status on communication and care. Clinical application includes well elderly visits in the community. Prerequisite: Advanced Concepts in Nursing: Clinical Application (NUR-415) or Community and Population Oriented Nursing (NUR-430).  
 **NUR 444 Ind Study-Nursing**  
  Guided study of individually chosen topic in nursing with a nursing department faculty member. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: junior standing and consent of instructor.  
 **NUR 455 Leadership & Cont Issues in Nursing**  
  +++MISSING INFO: c.nur455_445c.desc +++  
 **NUR 494 Internship in Nursing**  
  A clinical practicum on an inpatient health care unit supervised by a faculty member of the department and a professionally prepared R.N. preceptor. A minimum of 140 hours on-site experience is required. S/U basis only. Prerequisite: Introductory Concepts in Nursing/Clinical Applications (NUR-355/-355L) and consent of department chair.  
 **NUR 495 Maternal Newborn Nursing**  
  Analyzes previously learned nursing knowledge and skills to provide safe, holistic patient-centered care for diverse individuals and families during normal and high risk pregnancy, labor, delivery, and the postpartum-neonatal period of life. Includes concepts and issues in reproductive health of men and women using a developmental framework. Surgical, dietary, and pharmacological management are integrated. Clinical component includes patient simulation experiences. Prerequisite: Advanced Concepts in Nursing/Clinical Application (NUR-415).  



