## Organizational Science (Collateral Major) {#sec-organizational-science} 

Farrell (Administrative Coordinator)

The Organizational Science major is a collateral and interdisciplinary program of study designed to acquaint students with human behavior in organizations from both theoretical and applied perspectives. The program aims to prepare students to carry out various human resources, organizational development, customer service, and institutional research functions in a variety of organizational settings. It also prepares students for graduate study in the fields of Industrial/Organizational (I/O) Psychology, Human Resources, Quantitative Methods, and other similar fields. Required courses in quantitative methods form the core of the major, complemented by required and elective coursework on relevant topics within the disciplines of Psychology and Business Administration that are central to the field. An internship or research experience is also required. 

### Collateral Major in Organizational Science

A major in organizational science requires a minimum cumulative 2.0 GPA in all courses counted toward the major.
 
Concurrent completion of a primary major in psychology is required. 
 
1. **All** of the following quantitative/methodological core courses:
	BUS 340 Applied Regression Analysis
	PSY 475 Testing & Measurement	
2. **All** of the following organizational core courses: 
	BUS 300 Human Resource Management
	BUS 315 Business Law I
	PSY 245 Organizational Psychology
	PSY 465 Industrial Psychology

3. **Four** elective courses to be chosen as indicated from the two lists below. 
 
a. **At least two** of the following courses:
	BUS 250 Principles of Management
	BUS 375 Business Ethics
	BUS 387 Adv Top:Human Res Mgt
	BUS 395 Organizational Behavior
	BUS 410 Business Law II 
	BUS 437 Strategic Compensation
	BUS 457 Employment and Discrimination Law
	BUS 464 Seminar in Management

b. **No more than two** of the following courses:
	PSY 255 Social Psychology
	PSY 315 Learning & Behavior
	+++MISSING INFO: c.psy355_355l.long +++
	PSY 464 Seminar in Psychology (if topic is appropriate)
	
4. **One** of the following, subject to prior approval by the Organizational Science administrative coordinator:
	BUS 454 Research in Business (with business administration departmental approval)
	BUS 494 Internship in Business (with business administration departmental approval)
	PSY 455 Advanced Experimental Psychology 
	PSY 494 Internship in Psychology