## Physics 
Affatigato (Chair), Akgun, Baehr, Bragatto, Duru, Feller, Wetzel

The physics department serves a variety of students with a balanced program, giving equal emphasis to the needs of the technically and the non-technically oriented. 

### Physics Major

A major in physics requires a minimum cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.phy185_185l.long >}}
 
2. {{< var c.phy195_195l.long >}} 

3. {{< var c.phy231.long >}} 

4. {{< var c.phy235_235l.long >}} 

5. {{< var c.phy265.long >}} 

6. **Two** of the following courses:
	- {{< var c.phy275.long >}}
	- {{< var c.phy315.long >}}
	- {{< var c.phy335.long >}}
	- {{< var c.phy425.long >}}

7. **Four** additional physics courses, all of which must be numbered 150 or above.

8.	Comprehensive evaluation
	Satisfactory completion of written and oral examinations

***Recommended:***
	- {{< var c.cs125.long >}}
	- {{< var c.chm121_121l.long >}}

### Physics Minor
A minor in Physics requires a cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.phy185_185l.long >}} or {{< var c.phy165_165l.long >}}

2. {{< var c.phy195_195l.long >}} or {{< var c.phy175_175l.long >}}

3. {{< var c.phy235_235l.long >}}

4. {{< var c.phy265.long >}} 

5. **Two** additional physics course approved by the department, both of which must be numbered 150 and above. 

### Courses in Physics 
 **{{< var c.phy105.long >}}**  
  {{< var c.phy105.desc >}}  
 **{{< var c.phy114_114l.long >}}**  
  {{< var c.phy114_114l.desc >}}  
 **{{< var c.phy121.long >}}**  
  {{< var c.phy121.desc >}}  
 **{{< var c.phy155_155l.long >}}**  
  {{< var c.phy155_155l.desc >}}  
 **{{< var c.phy161.long >}}**  
  {{< var c.phy161.desc >}}  
 **{{< var c.phy165_165l.long >}}**  
  {{< var c.phy165_165l.desc >}}  
 **{{< var c.phy175_175l.long >}}**  
  {{< var c.phy175_175l.desc >}}  
 **{{< var c.phy181.long >}}**  
  {{< var c.phy181.desc >}}  
 **{{< var c.phy185_185l.long >}}**  
  {{< var c.phy185_185l.desc >}}  
 **{{< var c.phy195_195l.long >}}**  
  {{< var c.phy195__195l.desc >}}  
 **{{< var c.phy201.long >}}**  
  {{< var c.phy201.desc >}}  
 **{{< var c.phy211.long >}}**  
  {{< var c.phy211.desc >}}  
 **{{< var c.phy221.long >}}**  
  {{< var c.phy221.desc >}}  
 **{{< var c.phy231.long >}}**  
  {{< var c.phy231.desc >}}  
 **{{< var c.phy235.long >}}**  
  {{< var c.phy235.desc >}}  
 **{{< var c.phy235l.long >}}**  
  {{< var c.phy235l.desc >}}  
 **{{< var c.phy241.long >}}**  
  {{< var c.phy241.desc >}}  
 **{{< var c.phy251.long >}}**  
  {{< var c.phy251.desc >}}  
 **{{< var c.phy255_355.long >}}**  
  {{< var c.phy255_355.desc >}}  
 **{{< var c.phy265.long >}}**  
  {{< var c.phy265.desc >}}  
 **{{< var c.phy275.long >}}**  
  {{< var c.phy275.desc >}}  
 **{{< var c.phy301.long >}}**  
  {{< var c.phy301.desc >}}  
 **{{< var c.phy311.long >}}**  
  {{< var c.phy311.desc >}}  
 **{{< var c.phy315.long >}}**  
  {{< var c.phy315.desc >}}  
 **{{< var c.phy321.long >}}**  
  {{< var c.phy321.desc >}}  
 **{{< var c.phy335.long >}}**  
  {{< var c.phy335.desc >}}  
 **{{< var c.phy341.long >}}**  
  {{< var c.phy341.desc >}}  
 **{{< var c.phy411.long >}}**  
  {{< var c.phy411.desc >}}  
 **{{< var c.phy425.long >}}**  
  {{< var c.phy425.desc >}}  
 **{{< var c.phy441.long >}}**  
  {{< var c.phy441.desc >}}  
 **{{< var c.phy444.long >}}**  
  {{< var c.phy444.desc >}}  
 **{{< var c.phy451.long >}}**  
  {{< var c.phy451.desc >}}  
 **{{< var c.phy454.long >}}**  
  {{< var c.phy454.desc >}}  
 **{{< var c.phy464/phy474.long >}}**  
  {{< var c.phy464/phy474.desc >}}  
 **{{< var c.phy484.long >}}**  
  {{< var c.phy484.desc >}}  
 **{{< var c.phy494.long >}}**  
  {{< var c.phy494.desc >}}  
 **{{< var c.occ365.long >}}**  
See description, @sec-ACM-and-international-programs
