## Political Science
Barrow, Lanegran (Chair), B. Nesmith.

The department of political science emphasizes the breadth of political science and presents politics as a worldwide phenomenon. The department nurtures active and responsible habits of citizenship, encouraging service learning and the development of political values, while offering students a variety of opportunities to study politics outside the classroom.

### Political Science Major
A major in political science requires a cumulative 2.0 GPA in all courses counted toward the major.

A major in political science requires ten courses, including at least three 300- or 400-level courses. 

1. POL 108 Introduction to Politics
 
2. POL 115 American National Gov & Pol

3. **One** political theory course:
	- POL 405 Contemporary Political Theory
	- POL 435 Ancient & Medieval Pol Thry
	- POL 445 Modern Political Theory 

4. **One** additional American government course:
	- POL 207 Religion & American Politics 
	- POL 245 Political Parties & Elections
	- POL 277 Women & Poltics in US
	- POL 325 The American Congress
	- POL 345 American Presidency
	- POL 350 US Social Policy Process

5. **Two** comparative or international politics courses:
	- POL 248 Political Violence and the Violent
	- POL 258 World Politics
	- POL 266 Latin American Politics
	- POL 276 African Politics
	- POL 286 Asian Politics
	- POL 298 European Politics
	- POL 305 Terrorism
	- POL 310 International Organizations         
	- POL 365 American Foreign Policy
	- POL 386 International Development
	- POL 398 Religion & World Politics

6. **Four** additional political science courses

Satisfactory work in Topics in Political Science (POL-284/-296) may be used, with consent of department chair, to satisfy any departmental requirement. 

### Political Science Minor

A minor in political science requires six courses, including at least two 300- or 400-level courses. 

1. POL 108 Introduction to Politics

2. POL 115 American National Gov & Pol

3. **One** political theory course:
	- POL 405 Contemporary Political Theory
	- POL 435 Ancient & Medieval Pol Thry
	- POL 445 Modern Political Theory
 	 
4. **One** additional American government course: 
	- POL 207 Religion & American Politics 
	- POL 245 Political Parties & Elections
	- POL 277 Women & Poltics in US
	- POL 325 The American Congress
	- POL 345 American Presidency
	- POL 350 US Social Policy Process

5. **One** comparative or international politics course:
	- POL 248 Political Violence and the Violent
	- POL 258 World Politics
	- POL 266 Latin American Politics
	- POL 276 African Politics
	- POL 286 Asian Politics
	- POL 298 European Politics
	- POL 305 Terrorism
	- POL 310 International Organizations
	- POL 365 American Foreign Policy
	- POL 386 International Development
	- POL 398 Religion & World Politics
		
6. **One** additional political science course

Satisfactory work in Topics in Political Science (POL-284/-296) may be used, with consent of department chair, to satisfy any departmental requirement. 

### Courses in Political Science

 **POL 108 Introduction to Politics**  
  Compares societies and states across regions, cultures, and time spans, in an attempt to understand what governments have in common, how they differ, and why. Includes such specific topics as democracy and fascism, nationalism, human rights, post-communist states, and post-cold war international politics. Challenges students to look beyond the day’s headlines, learn from other peoples’ politics, and develop political self-awareness.  
 **POL 115 American National Gov & Pol**  
  Constitutional, institutional, and political dimensions, and principal contemporary problems of the government of the United States.  
 **POL 207 Religion & American Politics**  
  Examines several points of tension at the intersection of the religious and political spheres. Explores the connections between religious movements and political beliefs in American history, evolving understandings of the Constitution’s religious freedom clauses, and the complicating effects on politics of America’s increasing religious and cultural diversity.  
 **POL 210 Environmental Politics**  
  Brings multiple perspectives to bear and provides a solid foundation for understanding the politics and complexities of environmental issues. Examines actors and issues in environmental policy-making at various levels of government, from the local to the national to the global. Analyzes the reasons for and hindrances to collective action. Students will acquire some tools of “practical politics,” including political communications. No prerequisites, but Introduction to Politics (POL-108) is recommended.  
 **POL 245 Political Parties & Elections**  
  The development and nature of political parties; state, local, and national party organizations; parties in government; voting behavior; campaigns and nominations. The course includes an introduction to election data sets and original research using quantitative research methods. Prerequisite: American National Government and Politics (POL-115) or consent of instructor. (Offered alternate years)  
 **POL 248 Political Violence and the Violent**  
  Focuses on politically motivated violence by and against states, groups, and individuals, with attention to theories that explain the persistence of such violence. Examines such phenomena as traditional warfare, guerrilla warfare, coups d’état, rebellions, torture, and terrorism and the people, politics, ideals, and ideologies behind them. Prerequisite: Introduction to Politics (POL-108) or consent of the instructor. (Offered alternate years)  
 **POL 258 World Politics**  
  Survey of the basic factors of international politics, including the character of the state system and international economic relations, the role of force, the role of diplomacy and negotiation, and an examination of the formulation of foreign policy within domestic political systems.  
 **POL 266 Latin American Politics**  
  Focuses on two of the most exciting and dynamic features of contemporary Latin American politics: the “wave” of democratization that is washing over the region and the changing relationship between religion and politics. Topics include political culture, political economy, political violence, the impact of U.S. policies, the Catholic church’s role in politics, and how the rise of Protestantism affects church-state relations. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 276 African Politics**  
  An introductory survey of post-independence political patterns and processes in Africa. Similarities and differences across the continent are highlighted while a small number of select countries are studied indepth. Attention is given to the legacy of the colonial period, democratization, the challenges of violence and illegitimate governance, and the impact of the modern global economy on life in Africa. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 277 Women & Poltics in US**  
  Examines three aspects of the dynamic between women and the US political process: women as political leaders, women as voters and activists, and the impact of policies on women and their everyday lives. The course addresses general theories of elections, feminist politics, and political behavior and discusses a number of specific policy issues such as reproductive health and international affairs. Prerequisite: American National Government and Politics (POL-115) or consent of instructor. (Offered alternate years)  
 **POL 284 Topics in Political Science**  
  Intensive reading, study, writing, and discussion dealing with various political science subjects. Examples of recent topics include political violence, environmental politics, and Mexican politics. This course may count toward a political science major, depending on course content, as either an American government course or as a comparative or international politics course. May be taken more than once for credit, provided the topics are substantially different.  
 **POL 286 Asian Politics**  
  Examines the broad variety of Asian political systems through case studies of selected countries that are authoritarian, communist, transitioning, or established democracies. Issues confronted include: the East Asian economic miracle, the character of Asian democracies, and the role of ethnicity and religion in politics. The tension in the region between economic growth and political control receives particular attention. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 296 Topics Pol Sci: Non-West Persp**  
  Same as Topics in Political Science (POL-284) except the course focuses on topics related to non-Western cultures.  
 **POL 298 European Politics**  
  Addresses political and economic continuities, changes, and challenges in modern Europe. The course examines the political structures and policy challenges of select states in the region including Great Britain, Germany and France. Other topics are the political dynamics of the expanding European Union as well as transitions to democracy and capitalism in Russia and Central and Eastern European states. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 305 Terrorism**  
  An advanced-level examination of terrorism and global responses to it. Topics include the history of terrorism, a variety of domestic and international terrorist groups, and how terrorism is changing in the post-Cold War era. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 310 International Organizations**  
  Examines the role of international organizations in international relations. The central question is whether organizations like the United Nations and the European Union are tools of their member states or actors that rival the power of nation-states in international relations. Students participate in simulations of international organizations. Prerequisite: Introduction to Politics (POL-108) or consent of instructor.  
 **POL 325 The American Congress**  
  Examines the American legislative process at the national level, with special attention to the constitutional origins of Congress, consideration of legislation by Congress, and the relationship of Congress to other political actors, as well as current policy issues. Prerequisite: American National Government and Politics (POL-115) or consent of instructor.  
 **POL 335 Constitution & Roles of Govt**  
  Examination of original court opinions and political writings focusing on the nature and sources of Supreme Court authority; the structure of government; judicial review; commerce, taxing, spending, and war powers; with special emphasis upon separation of powers: the President, Congress, and the Court. Prerequisite: junior standing or consent of instructor. (Offered alternate years)  
 **POL 345 American Presidency**  
  The President as chief executive, commander-inchief, chief diplomat, chief legislator, party leader, head of state; the institutionalized presidency. The course includes doing original research using historical case studies. Prerequisite: American National Government and Politics (POL-115) or consent of instructor.  
 **POL 350 US Social Policy Process**  
  Familiarizes students with the bureaucratic process through which national-level public policy is formulated in the United States, and gives students expertise in the challenges, history, successes, and shortcomings of select social policies. Policies examined may include education, public health, social security and welfare. Students participate in primary research examining the implementation of national policies in Iowa. Prerequisite: American National Government and Politics (POL-115) or consent of instructor. (Offered alternate years)  
 **POL 365 American Foreign Policy**  
  Examination of the institutional setting in which foreign policy is formulated, the political dynamics of policy formulation, and case studies of American foreign policy since World War II. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 375 Constitution & Individual Liberties**  
  Examination of original court opinions and political writings focusing upon the procedural contents of due process, equal protection under the law, post-Civil War amendments, and civil rights legislation, with special emphasis upon freedoms of religion and expression. Prerequisite: junior standing or consent of instructor. (Offered alternate years)  
 **POL 386 International Development**  
  Addresses controversies in international development, such as what is to be developed, for whom, and whether development means Westernization. Topics include how we measure development; foreign aid and debt; the roles of the World Bank, International Monetary Fund and USAID, as well as non-governmental organizations; and conflicting theories of development. Readings and discussions also touch on pressing ethical issues, most basically whether citizens have any moral responsibility to people who live beyond the nation’s borders. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 398 Religion & World Politics**  
  Seminar addressing such issues as the ways in which religion enters world politics (and vice versa), when and where religion has been a force for peacemaking or for conflict, and why religion is so often ignored or misunderstood by Western foreign policy theorists and practitioners. Includes student research projects. Prerequisite: Introduction to Politics (POL-108) or consent of instructor. (Offered alternate years)  
 **POL 405 Contemporary Political Theory**  
  Survey and argumentative analysis of the ideas of major political thinkers since 1900. Selections are made from such authors as Hannah Arendt, John Dewey, Sigmund Freud, Martin Luther King Jr., Robert Nozick, John Rawls, and Jean-Paul Sartre. Prerequisites: Introduction to Politics (POL-108) and junior standing, or consent of instructor.  
 **POL 435 Ancient & Medieval Pol Thry**  
  Historical survey and argumentative analysis of the ideas of great political thinkers from the 5th century B.C.E. to the 15th century C.E. Selections are made from such authors as Plato, Aristotle, Confucius, the Biblical writers, Augustine, and Thomas Aquinas. Prerequisites: Introduction to Politics (POL-108) and junior standing, or consent of instructor.  
 **POL 444 Ind Study-Pol Sci**  
  Independent study and research, under the direction of a faculty member of the department, in some area of political science. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: two completed courses in the relevant area at the 300- or 400-level and consent of department chair.  
 **POL 445 Modern Political Theory**  
  Historical survey and argumentative analysis of the ideas of the most important political thinkers from the 16th to the 19th centuries. Selections are made from such authors as Machiavelli, Hobbes, Locke, Rousseau, Marx, and Mill. Prerequisites: Introduction to Politics (POL-108) and junior standing, or consent of instructor.  
 **POL 494 Internship in Political Science**  
  Substantial work or participation in an office, organization, or activity concerned with government and politics, such as a congressional, federal, state, or local government office, a political campaign, or an active interest group. A minimum of 140 hours on-site experience is required. S/U basis only. One course credit toward a political science major for successful completion, unless The Washington Experience (WSH-494) is completed for credit toward a major. Prerequisite: consent of department chair.  
 **WSH 284 Topics in Washington DC**  
See description, @washington-term  
 **WSH 286 Topics in Washington, D.C:NWP**  
See description, @washington-term  
 **WSH 464 Internship Seminar**  
See description, @washington-term  
 **WSH 494 Washington Experience**  
See description, @washington-term  
