## Religion {#sec-religion}
Chaplin, Hatchell (Chair), Kensky. 

The philosophy and religion department offer courses designed to lead students to reflect on their views concerning fundamental issues in life and thought. Since both the philosophical and religious traditions have had a central place in and an enormous influence upon the development of human culture, any student seeking a liberal education, whatever the major discipline, will profit from the departmental offerings. 

### Religion Major 
A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in religion. 

1. **One** of the following:
	* REL 101 Introduction to Religion
	* REL 103 Belief & Unbelief

2. REL 106 Eastern Religions

3. REL 108 Western Religions

4. **One** of the following:
	* REL 105 Introduction to Hebrew Bible
	* REL 115 Introduction to New Testament 

5. **One** of the following:
	* REL 116 Buddhism 
	* REL 136 Religions of China 
	* REL 196 Hinduism 

6. **Five** additional religion courses, at least three of which are numbered 300 or above 

### Religion Minor 

1. **One** of the following:
	* REL 106 Eastern Religions
	* REL 108 Western Religions

2. **Four** additional religion courses 

### Courses in Religion by Content Area 
Special attention should be given to the numerical ordering of the courses listed below: 

1. Courses numbered between 100 and 199 include general introductions to religion (REL 101 Introduction to Religion , REL 103 Belief & Unbelief , REL 106 Eastern Religions , and REL 108 Western Religions as well as introductory courses focused on specific traditions.

2. Courses numbered 200-299 are topical courses especially suitable for sophomore level and above.

3. Courses numbered 300-399 are advanced courses with prerequisites. 

Recommended beginning courses for those contemplating a major in religion are: REL 101 Introduction to Religion , REL 103 Belief & Unbelief , REL 106 Eastern Religions , or REL 108 Western Religionsm. However, other courses numbered below 200 are also suitable introductory courses.

:::: {.columns}

::: {.column width="45%"}
* **Survey courses**	
	- REL 101 Introduction to Religion
	- REL 103 Belief & Unbelief
	- REL 106 Eastern Religions
	- REL 108 Western Religions

* **Individual traditions**
	- REL 116 Buddhism
	- REL 128 Judaism
	- REL 136 Religions of China
	- REL 138 Modern Judaism
	- REL 148 Islam
	- REL 178 Christianity
	- REL 196 Hinduism
	- REL 206 Buddhist Thought
	- REL 215 The Rise of Christianity
	- REL 226 Religions of China:Daoism
	- REL 236 Zen Buddhism
	- REL 336 Tibetan Buddhist Cultrue
:::

::: {.column width="10%"}

:::

::: {.column width="45%"}
* **Judeo-Christian scriptures**
	- REL 105 Introduction to Hebrew Bible
	- REL 115 Introduction to New Testament
	- REL 310 Early Christian Gospels
	- REL 330 Topics in Hebrew Bible
	- REL 365 The Letter of Paul

* **Topical courses**
	- REL 217 Religion in America
	- REL 295 Topics in Religion
	- REL 296 Topics in Religion NWP
	- REL 338 Modern Religious Thought
	- REL 385 Advanced Topics in Religion
	- REL 386 Advanced Topics in Religion: Non-Western Perspectives (WE)
	- REL 394 Directed Learning in Religion
	- REL 444 Ind Study-Relig
	- REL 494 Internship in Religion 
:::

::::

* **Survey courses**	
	- REL 101 Introduction to Religion
	- REL 103 Belief & Unbelief
	- REL 106 Eastern Religions
	- REL 108 Western Religions

* **Individual traditions**
	- REL 116 Buddhism
	- REL 128 Judaism
	- REL 136 Religions of China
	- REL 138 Modern Judaism
	- REL 148 Islam
	- REL 178 Christianity
	- REL 196 Hinduism
	- REL 206 Buddhist Thought
	- REL 215 The Rise of Christianity
	- REL 226 Religions of China:Daoism
	- REL 236 Zen Buddhism
	- REL 336 Tibetan Buddhist Cultrue
 
* **Judeo-Christian scriptures**
	- REL 105 Introduction to Hebrew Bible
	- REL 115 Introduction to New Testament
	- REL 310 Early Christian Gospels
	- REL 330 Topics in Hebrew Bible
	- REL 365 The Letter of Paul

* **Topical courses**
	- REL 217 Religion in America
	- REL 295 Topics in Religion
	- REL 296 Topics in Religion NWP
	- REL 338 Modern Religious Thought
	- REL 385 Advanced Topics in Religion
	- REL 386 Advanced Topics in Religion: Non-Western Perspectives (WE)
	- REL 394 Directed Learning in Religion
	- REL 444 Ind Study-Relig
	- REL 494 Internship in Religion 
 
### Courses in Religion
 **REL 101 Introduction to Religion**  
  Introduces students to thinking about religion as a category of human experience, both in terms of foundational beliefs and how those beliefs are situated in practice. The course examines methods of studying religion as well as essential questions regarding the nature of religion.  
 **REL 103 Belief & Unbelief**  
  Discussion oriented course focusing on the dynamics of faith and of atheism. Special attention to traditional proofs for God’s existence, the problems of evil and the afterlife, and the nature of religious experience.  
 **REL 105 Introduction to Hebrew Bible**  
  A literary and theological overview of the first five books of the Hebrew Bible (the Pentateuch or Torah) in the context of their historical development and their formative impact on the rest of Israelite scripture (the Prophets and Writings). It is recommended that this course be taken prior to other Biblical studies courses.  
 **REL 106 Eastern Religions**  
  An introductory survey of some of the major religions of the Indian subcontinent and the Far East. Religions to be discussed include Hinduism, Buddhism, Confucianism and Taoism.  
 **REL 108 Western Religions**  
  An introductory survey of the three major Abrahamic religions (Judaism, Christianity and Islam), both in their historical development and their contemporary expressions.  
 **REL 115 Introduction to New Testament**  
  A literary and theological overview of the Christian scriptures (the Gospels and Acts, the Pauline, Johannine and catholic epistles, and the Apocalypse of John) in the context of the origins and early historical development of Christianity.  
 **REL 116 Buddhism**  
  An introduction to the Buddhist religion, including its history, philosophy, ritual, meditation, and popular practice. Course materials include Buddhist histories and religious texts, as well as contemporary anthropological materials and film.  
 **REL 128 Judaism**  
  The basic beliefs and practices of Judaism, from the prophetic period to the present. This course and the Modern Judaism course form a program in Jewish Studies which is supported by The Sinaiko Endowment.  
 **REL 136 Religions of China**  
  An introduction to religion in China, with particular focus on the three major traditions of Confucianism, Taoism, and Buddhism. Course materials include readings from major texts of each tradition, as well as histories, anthropological studies, literature, and film.  
 **REL 138 Modern Judaism**  
  A study of selected issues in Enlightenment or post Enlightenment Judaism as reflected, for example, in the history of the Jewish people, rabbinic teachings and Jewish theological scholarship, or Jewish literature. This course and the Judaism course form a program in Jewish Studies which is supported by The Sinaiko Endowment.  
 **REL 148 Islam**  
  An introductory overview of Islam as an Abrahamic faith, a global civilization, and an integral facet of the American religious experience.  
 **REL 178 Christianity**  
  A study of the beliefs and practices of Christianity from its earliest formulations to the modern world. Special attention is paid to essential tenets of Christian faith, elements of Christian practice, and divergences between Catholic, Protestant, and Orthodox Christianities.  
 **REL 196 Hinduism**  
  An introduction to the Hindu religion, including its history, philosophy, ritual, meditation, and popular practice. Course materials include Hindu histories and religious texts, as well as contemporary anthropological materials, literature, and film.  
 **REL 206 Buddhist Thought**  
  A survey of major issues in Buddhist philosophy, including ethics, emptiness, idealism, the nature of mind, and the nature of reality. The course focuses on Indian Buddhist philosophical schools and also explores distinctive philosophical ideas from Buddhist traditions in China, Japan, and Tibet. Prerequisite: Eastern Religions (REL-036), or Buddhism (REL-116), or consent of instructor.  
 **REL 215 The Rise of Christianity**  
  An examination of how Christianity grew from a small band of Jewish followers of Jesus to the dominant religion in the Roman Empire. Attention is paid to crucial figures such as Paul of Tarsus, Irenaeus of Lyons, and Augustine of Hippo, among others.  
 **REL 217 Religion in America**  
  Examines the varieties of American religious experience, from the religion of the Puritans to the 21st century. Attention is paid both to normative and minority traditions, with a look at the growing Evangelical and Muslim communities in America today.  
 **REL 226 Religions of China:Daoism**  
  An introduction to China's Daoist tradition of Buddhism, beginning with its early literature like the Dao-de-jing and the Zhuang-zi and examining several later Daoist movements in China. The course also examines other Chinese religions and intellectual traditions that have influenced Daoism, including Confucianism and Buddhism. Course materials include histories, translations of Daoist literature, accounts of contemporary Daoists, and film.  
 **REL 236 Zen Buddhism**  
  An introduction to the Zen tradition of Buddhism beginning with its origins in China and also examining its traditions in Japan. The course examines other Chineses religious and intellectual traditions that helped shape the Zen tradition, with particular influence on Daoism. Course materials include histories, translations of Zen literature, autobiography, and film.  
 **REL 295 Topics in Religion**  
  An examination of a selected topic in religious studies. Content varies from year to year. May be taken for credit more than once.  
 **REL 296 Topics in Religion NWP**  
  Same as Topics in Religion REL295, except the course focuses on topics related to non-western cultures. Content varies from year to year. May be taken for credit more than once.  
 **REL 310 Early Christian Gospels**  
  An examination of the literary genre in early Christianity, focusing on both canonical (Mark, Matthew, Luke, John) and non-canonical Gospels, including the Gospel of Truth and the Gospel of Thomas.  Why did early Christians utilize this genre to communicate traditions about Jesus of Nazareth? Prerequisite: Introduction to Hebrew Bible (REL-105) or Introduction to New Testament (REL-115) or consent of instructor.  
 **REL 330 Topics in Hebrew Bible**  
  An advanced course in an aspect of critical study of the Hebrew Bible. Potential topics include Prophecy, Wisdom Literature, and Women in the Bible. Prerequisite: Introduction to Hebrew Bible (REL-105) or consent of instructor.  
 **REL 336 Tibetan Buddhist Cultrue**  
  Introduces students to the lived experience of Buddhists on the Tibetan plateau and in Nepal. THe course discusses the history of religion in Tibet, as well as the major doctrines of Tibetan Buddhism. Particular attention is also paid toTibetan religious culture and popular religious practices. Course materials include Tibetan literature, histories, biographies, and film, as well as anthropological studies of Tibetan societies.  
 **REL 338 Modern Religious Thought**  
  A survey of the religious thinkers and themes of the 20th century. Various religious outlooks, ranging from conservative to radical, are explored, as are alternative conceptions of God, religion, and salvation. Prerequisite: one course in religion or consent of instructor.  
 **REL 365 The Letter of Paul**    
  An examination of the 13 letters attributed to Paul of Tarsus in the New Testament as well as biblical and extra-biblical sources for the life of this crucial figure who spread Christianity around the Roman Empire. Prerequisite: Introduction to Hebrew Bible (REL-105) or Introduction to New Testament (REL-115) or consent of instructor.  
 **REL 385 Advanced Topics in Religion**  
  Seminar examining a selected topic in religious studies. Content varies from year to year. May be taken for credit more than once. Prerequisite: one course in religion or consent of instructor.  
 **REL 386 Advanced Topics in Religion: Non-Western Perspectives (WE)**  
  Same as Advanced Topics in Religion (REL-385) except the course focuses on topics related to non-Western cultures. Content varies from year to year. May be taken more than once for credit. Prerequisite: one course in religion or consent of instructor.  
 **REL 394 Directed Learning in Religion**  
  A course of directed learning designed by the student and instructor to fit the individual student’s particular interests and educational needs. Prerequisite: consent of instructor.  
 **REL 444 Ind Study-Relig**  
  Independent study under the direction of a faculty member of the department in an area selected by the student. May be taken for an X status grade with consent of instructor prior to registration. Prerequisite: consent of instructor.  
 **REL 494 Internship in Religion**  
  Exploration of a career area related to the student’s interest in religion supervised by a Religion faculty member in cooperation with the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. This course does not satisfy any of the requirements for a major in Religion. Prerequisites: declared major in Religion, junior standing, and consent of department chair.  
