## Rhetoric
Carr (Chair), Donofrio, Harmsen, J. Nesmith, Opayemi, Spikes 

The Rhetoric Department offers a major and a minor in both **Communication Studies** (see @sec-communication-studies ) and **Writing** (see @sec-writing ) and is responsible for offering courses in the study and practice of academic prose, non-fiction writing, journalism, and communication studies.  

### Writing {#sec-writing}
The writing major (within the Rhetoric department) is designed to help students become skilled, reflective writers capable of composing texts in a variety of genres, responding effectively to diverse rhetorical situations. 

#### Writing Major
A major in Writing requires a cumulative 2.0 GPA in all courses counted toward the major.

1. {{< var c.rhe200.long >}}

2. **One** of the following:
   - {{< var c.rhe225.long >}} 
   - {{< var c.rhe255.long >}} 

3. **One** of the following:
	- {{< var c.rhe377.long >}}
	- {{< var c.com382.long >}} **or** {{< var c.rhe382.long >}}

4. **Six** credits, including any course with an RHE prefix not already fulfilling another requirement, or any of the courses from the list below. No more than two courses with the CRW or COM prefix may count toward the major.

	- {{< var c.com241.long >}}
	- {{< var c.com341.long >}}
	- {{< var c.com361.long >}}
	- {{< var c.com362.long >}}
	- {{< var c.com382.long >}} or {{< var c.rhe382.long >}} (if not used to fulfill requirement #3)
	- {{< var c.com462.long >}}
	- {{< var c.crw115.long >}}
	- {{< var c.crw255.long >}}
	- {{< var c.crw280.long >}}
	- {{< var c.crw290.long >}}
	- {{< var c.crw355.long >}}
	- {{< var c.crw380.long >}}
	- {{< var c.crw390.long >}}

5. **One** of the following:
	- {{< var c.rhe415.long >}} (If not used to satisfy requirement #4)
	- {{< var c.rhe425.long >}} (if not used to satisfy requirement #4)
	- {{< var c.rhe444.long >}}
	- An Honors Thesis 

6. A portfolio of works completed in the major (minimum 3, maximum 4), preceded by a preface that synthesizes major threads/themes of learning, and reflects on programmatic learning outcomes and on what takeaways from the major the student anticipates being most important as they prepare for their post-baccalaureate life. The portfolio should be submitted by the end of the term prior to the student’s intended graduation date, unless circumstances suggest it should be submitted later (confer with advisor and department chair).

#### Writing Minor
A minor in Writing requires five credits, including {{< var c.rhe200.long >}} and one RHE course numbered 300 or above. Any course with an RHE prefix or chosen from the list below may count toward the five credits; no more than two courses with CRW or COM prefix may count toward the minor. A cumulative 2.0 GPA is required in all courses counted toward the minor.

	- {{< var c.com241.long >}}
	- {{< var c.com341.long >}}
	- {{< var c.com361.long >}}
	- {{< var c.com362.long >}}
	- {{< var c.com382.long >}} **or** {{< var c.rhe382.long >}}
	- {{< var c.com462.long >}}
	- {{< var c.crw115.long >}}
	- {{< var c.crw255.long >}}
	- {{< var c.crw280.long >}}
	- {{< var c.crw290.long >}}
	- {{< var c.crw355.long >}}
	- {{< var c.crw380.long >}}
	- {{< var c.crw390.long >}}

### Courses in Rhetoric {#sec-courses-in-rhetoric}
- **{{< var c.rhe100.long >}}**
  {{< var c.rhe100.desc >}}  
- **{{< var c.rhe112.long >}}**
  {{< var c.rhe112.desc >}}
- **{{< var c.rhe135.long >}}**
  {{< var c.rhe135.desc >}}  
- **{{< var c.rhe137.long >}}**
  {{< var c.rhe137.desc >}}
- **{{< var c.rhe146.long >}}**
  {{< var c.rhe146.desc >}}  
- **{{< var c.rhe175.long >}}**
  {{< var c.rhe175.desc >}}
- **{{< var c.rhe200.long >}}**
  {{< var c.rhe200.desc >}}  
- **{{< var c.rhe210.long >}}**
  {{< var c.rhe210.desc >}}
- **{{< var c.rhe225.long >}}**
  {{< var c.rhe225.desc >}}  
- **{{< var c.rhe230.long >}}**
  {{< var c.rhe230.desc >}}
- **{{< var c.rhe255.long >}}**
  {{< var c.rhe255.desc >}}  
- **{{< var c.rhe257.long >}}**
  {{< var c.rhe257.desc >}}
- **{{< var c.rhe265.long >}}**
  {{< var c.rhe265.desc >}}  
- **{{< var c.rhe275.long >}}**
  {{< var c.rhe275.desc >}}
- **{{< var c.rhe284.long >}}**
  {{< var c.rhe284.desc >}}  
- **{{< var c.rhe285.long >}}**
  {{< var c.rhe285.desc >}}
- **{{< var c.rhe312.long >}}**
  {{< var c.rhe312.desc >}}  
- **{{< var c.rhe345.long >}}**
  {{< var c.rhe345.desc >}}
- **{{< var c.rhe377.long >}}**
  {{< var c.rhe377.desc >}}  
- **{{< var c.rhe382.long >}}**
  {{< var c.rhe382.desc >}}
- **{{< var c.rhe394.long >}}**
  {{< var c.rhe394.desc >}}
- **{{< var c.rhe415.long >}}**
  {{< var c.rhe415.desc >}}  
- **{{< var c.rhe425.long >}}**
  {{< var c.rhe425.desc >}}
- **{{< var c.rhe444.long >}}**
  {{< var c.rhe444.desc >}}  
- **{{< var c.rhe490.long >}}**
  {{< var c.rhe490.desc >}}
- **{{< var c.rhe494.long >}}**
  {{< var c.rhe494.desc >}} 
