## Social & Criminal Justice
L. Barnett, J. Christensen, Lemos, McNabb (Administrative Coordinator).

The Social & Criminal Justice Program offers students an opportunity to immerse themselves in an interdisciplinary major that draws from Coe’s rich tradition in the liberal arts, as well as the pre-professional opportunities at the college. Core courses in the major address multifaceted questions surrounding restorative, retributive, procedural, and distributive justice. While many programs addressing such issues are housed in the field of criminal justice studies, the SCJ faculty teach topics within the major from varying perspectives and disciplines, introducing students to the ways in which matters of justice are at work in — and essential to — many areas of study.

The major is both local and global in nature, exhibiting the possibilities and limitations of social and criminal justice initiatives in the Cedar Rapids community, while also navigating matters of human rights and comparative justice systems that reveal our connections to the broader world.

Through interdisciplinary engagement and a required practicum, the SCJ program demonstrates for students how a multiplicity of voices and viewpoints can help to shape new ideas about the impact of social justice initiatives upon the criminal justice system, and the foundations of individual and collective community engagement.

### Social & Criminal Justice Major
A major in Social & Criminal Justice requires a cumulative 2.0 GPA in all courses counted toward the major.

1. SCJ 101 Intro to Social & Criminal Justice 

2. SCJ 201 Law Enforcement & Corrections 

3. +++MISSING INFO: c.scj235.long +++ 

4. PHL 285 Law, Morality & Punishment 

5. SCJ 350 Human Rights & Comparative Justice 

6. SOC 351 Criminology
 
7. **One** of the following:
	- STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 110 Stats IIA: Inferential Reasoning (7 weeks)
	- STA 100 Statistical Reasoning I-Foundations (7 weeks) **and** STA 130 Stats IIB: Experimental Design (7 weeks)
	- +++MISSING INFO: c.sta190.long +++
	- PSY 300 Stat Methods and Data Analysis

8. **Three** courses, chosen from the following, in consultation with the student’s advisor and/or the Social & Criminal Justice administrative coordinator. No more than two courses may be selected from the same prefix.
	- ACC 313 Fraud Examination
	- ARH 107 Gender and Art
	- COM 237 Interpersonal Communication
	- COM 357 Sex, Race, & Gender in Media
	- COM 361 Communication & Social Change
	- COM 362 U.S. Public Address
	- ECO 115 Intro Political Econ
	- EDU 187 Human Relations
	- ENG 127 Social Justice and Literature
	- ENG 146 Intro Postcolonial Literature
	- GS 107 Intro Gender & Sexuality Studies
	- HIS 145 History of United States to 1865
	- HIS 155 History of United States since 1865
	- HIS 347 African American History
	- HIS 257 Native American History
	- HIS 297 Women in America
	- HIS 325 Recent American History I
	- IS 126 HumanRightsBurmeseMigrant
	- PHL 128 Morality & Moral Controversies
	- PHL 205 Environmental Ethics
	- PHL 265 Political Philosophy
	- PHL 270 Ethical Theory
	- PHL 277 Philosophy of Gender & Race
	- POL 305 Terrorism
	- POL 350 US Social Policy Process
	- POL 375 Constitution & Individual Liberties
	- PSY 235 Abnormal Psychology
	- PSY 245 Organizational Psychology
	- PSY 255 Social Psychology
	- PSY 315 Learning & Behavior
	- PSY 350 Drugs & Behavior
	- PSY 415 Counseling Psychology
	- REL 217 Religion in America
	- SCJ 190 Topics in Social & Criminal Justice
	- SCJ 220 Juvenile Delinq & the Justice Sys
	- SCJ 301 Criminal Law & the 4th, 5th & 6th
	- SCJ 390 Adv Topics in Soc & Crim Just
	- SOC 207 Sociology of the Family
	- SOC 247 Sociology of Race
	- SOC 207 Sociology of the Family
	- SOC 247 Sociology of Race
	- SOC 328 Urban Sociology
	- SOC 338 Political Sociology
	- SOC 355 Deviant Behavior
	- SOC 425 Social Change
	- A course approved by the Social & Criminal Justice administrative coordinator

9. **One** of the following capstone projects:
	- SCJ 444 Independent Study in Social and Cri
	- SCJ 494 Internship in Social and Criminal J
	- OCC 323 OCC Chicago: Urban Studies (if internship/independent study has SCJ focus)
	- WSH 464 Internship Seminar (if internship has SCJ focus)
	- As a capstone experience, it is expected that students will carry out the project during the junior or senior year, after completing the majority of the required coursework. Students are expected to consult with the SCJ administrative coordinator prior to beginning their projects. 

10. SCJ 490 Social & Criminal Just Colloquium -- Non-Credit Bearing

### Courses Social & Criminal Justice

- **SCJ 101 Intro to Social & Criminal Justice**
  Explores components of justice. Focus is on understanding the nature and goals of social and criminal justice issues and policies including an analysis of globalization, consumer culture, and social privilege. Considers the history, structure, functions, and philosophy of justice. This course includes a required civic engagement component.  
- **SCJ 190 Topics in Social & Criminal Justice**
  A focused examination of an issue, problem, theory, or methodology related to social and criminal justice. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different (0.5 or 1.0 course credit).
- **SCJ 201 Law Enforcement & Corrections**
  Examines the structure and function of law enforcement policies and techniques along with practices, policies, and agencies involved in corrections systems. Review the histrical development of law enforcement and corrections, including challenges facing correctional populations. Explores the principles and practices of treatment accorded to suspects and offenders in various settings. Prerequisite: Introduction to Social and Criminal Justice (SCJ-101).  
- **SCJ 220 Juvenile Delinq & the Justice Sys**
  Overview of delinquent behavior and juvenile justice system responses to delinquency. Addresses historical precedents and philosophical reasons for treating juveniles differently from adults. Also considers methodological problems and theoretical controversies in delinquency research, and the goals and effectiveness of juvenile justice systems. Prerequisite: Introduction to Social and Criminal Justice (SCJ-101).
- **SCJ 301 Criminal Law & the 4th, 5th & 6th**
  Study of criminal law including the general elements of crime, the specific criminal offenses, legal justification defenses, and conspiracy. Additionally, the course offers a general understanding of accused rights under the Fourth, Fifth, Sixth Amendments of the U.S. Constitution. Prerequisite: junior standing or consent of instructor.  
- **SCJ 350 Human Rights & Comparative Justice**
  Introduces philosophical and legal questions surrounding "human rights", analyzing the ways that the language of human rights permeates questions of civil rights and social justice in both international and domestic settings.
- **SCJ 390 Adv Topics in Soc & Crim Just**
  Advanced study of an issue, problem, theory, or methodology related to social and criminal justice. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantally different. Prerequisite: Introduction to Social and Criminal Justice (SCJ-101) and Methods of Sociological Research (SOC-235). 0.5 or 1.0 course credit.  
- **SCJ 444 Independent Study in Social and Cri**
  Independent study under faculty guidance of a research problem chosen by the student. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: Methods of Sociological Research (SOC-235), junior standing, and declared major in Social & Criminal Justice.
- **SCJ 490 Social & Criminal Just Colloquium**
  Majors discuss and present their work that is a requirement of their capstone projects. It is expected that Colloquium is taken during or following the completing of the capstone internship/independent study. Satisfactory completion of the Colloquium is required for graduation with a major in Social & Criminal Justice. S/U basis only. (0.0 course credit)
- **SCJ 494 Internship in Social and Criminal J**
  Investigation of a career area related to the student’s interest in social and criminal justice supervised by a faculty member in cooperation with the Center for Creativity and Careers. A minimum 140 hours of on-site experience is required. S/U basis only. Prerequisites: junior standing, declared major in Social & Criminal Justice, and consent of Social & Criminal Justice administrative coordinator.  
