## Sports Management (Courses Only)

See Sports Management Concentration in Business, @sec-sports-management-concentration

### Courses in Sports Management

- **SMT 100 Introduction to Sports Management**
  An introductory course in sports management. This course provides an overview of the historical, legal, economic, political, and social-cultural issues that shape the field of sports management. The skills needed for managing sports organizations, from recreational to collegiate and professional, are also introduced. The course will look at the key functional areas of sport management such as marketing, communication, finance and economics and facility and event management.  
- **SMT 300 Sport/Recreation Event Management**
  An introduction to the principles and procedures for preparing, planning, operating, managing, and evaluating events and venues in sports settings. Students will gain a greater understanding of event and venue management and the total operation of sports organizations. Prerequisite: SMT-100: Introduction to Sports Management
- **SMT 454 Seminar in Sports Management**
  A lecture/discussion-based course in which relevant and current research and industry trends are thoroughtly reviewed and analyzed. Students are encouraged to take this course near the end of their careers as undergraduate students in the sports management concentration.
- **SMT 494 Internship in Sports Management**
  An internship with a focus on sports management supervised by a faculty member teaching within the sports management concentration. A minimum of 140 hours on-site experience is required. Students must document and analyze the experience through a journal and final report or through other written work as assigned by the faculty supervisor. S/U basis only. A maximum of one credit may count toward the concentration with the approval of the administrative coordinator(s) of the concentration. Prerequisites: junior standing and consent of administrative coordinator(s).


