## Sociology
L. Barnett, Boguslaw, Fairbanks (Chair, Fall), K. Rodgers (Chair, Spring).

The sociology department, which also offers a minor in anthropology, offers a rigorous curriculum in support of Coe’s mission of providing students with a high-quality liberal arts education and preparing students intellectually, professionally, and socially to lead productive and satisfying lives in the global society of the 21^st^ century. The department serves this mission through an integrated series of courses designed to promote students’ awareness and understanding 21^st^ century social problems, including the enduring presence of social inequality.

### Sociology Major
A major in Sociology requires a cumulative 2.0 GPA in all courses counted toward the major.

1. SOC 107 Introductory Sociology 

2. SOC 235 Methods of Sociological Research
 
3. SOC 450 Sociological Theory
 
4. SOC 464 Capstone Seminar in Sociology 

5. **Five** additional sociology courses, including at least one course numbered 400–449 (not including SOC-444 Independent Study, which does not count towards the major)

6. **One** of the following:
	- STA 100 Statistical Reasoning I-Foundations (7weeks) and STA 110 Stats IIA: Inferential Reasoning (7 weeks)
	- STA 100 Statistical Reasoning I-Foundations (7weeks) and STA 130 Stats IIB: Experimental Design (7 weeks)

### Sociology Minor
1. SOC 107 Introductory Sociology
 
2. SOC 235 Methods of Sociological Research 

3. SOC 450 Sociological Theory

4. **Three** additional sociology courses, including at least one course numbered 400–449 (not including SOC 444 Ind Study-Soc , which does not count towards the major)

The following courses do not satisfy any of the requirements for a major or minor in sociology:
	- SOC 275 Directed Readings in Sociology
	- SOC 365 Research Participation I or SOC 375 Research Participation II
	- SOC 444 Ind Study-Soc
	- SOC 494 Internship in Sociology
	- SOC 499 Career Related Independent Invest

### Courses in Sociology 

 **SOC 107 Introductory Sociology**
  An introduction to sociology, the scientific study of human social behavior. The course explores the place of the discipline in the social sciences and the interplay of theory and empirical evidence in building an understanding of society, and it provides exposure to a wide range of research topics and results from different areas of study in the field.  
 **SOC 207 Sociology of the Family**
  Sociological description and analysis of the family as a major social institution. Topics covered may include, but are not limited to: the various ways in which “families” are defined, and the different forms that families take; the relationship of family life to social processes such as socialization, stratification, and modernization, and the role of families in the interdependent network of social institutions. Prerequisite: Introductory Sociology (SOC-107) or consent of instructor.
 **SOC 217 Sociology of Religion**
  Examines the ways in which religion affects—and is affected by—the social context in which it occurs. Although the primary emphasis is on religion in the contemporary United States, considerable cross-cultural and historical material is included as well. The concept of secularization (that both the public and private impact of religion decline as societies modernize) is examined in light of empirical evidence. Prerequisite: Introductory Sociology (SOC-107) or consent of instructor. (Offered on an occasional basis)  
 **SOC 226 Gender and Globalizaton**
  Examines processes of globalization through a gendered lens. Focus on the ways global issues such as labor, intimacy, poverty, pop culture, and environmental degradation affect people of different genders in various ways. Also notes how people respond to the forces of globalization and addresses the effects of globalization on the lives of people in the non-Western world. Prerequisite: Introductory Sociology (SOC-107), or consent of instructor.
 **SOC 235 Methods of Sociological Research**
  An exploration of the various strategies researchers employ to gather information and test hypotheses about the social world. Topics include data collection, sampling, conceptualization and measurement, and both qualitative and quantitative methods of analysis. Prerequisite: Introductory Sociology (SOC-107), sophomore standing or consent of instructor.  
 **SOC 236 Topics in Sociology NWP**
  Same as Topics in Sociology (SOC-237) except topic(s) relate to non-Western cultures. Prerequisite: Introductory Sociology (SOC-107) or consent of instructor.
 **SOC 237 Topics in Sociology:U S Pluralism**
  A course of selected focus that centers on a particular sociological issue, problem, theory, or methodology related to United States Pluralism. Content varies and is determined by the instructor. May be repeated for credit, provided the topics are substantially different. Prerequisite: Introductory Sociology (SOC-107) or consent of instructor. (Offered on an occasional basis)  
 **SOC 238 Topics in Soc Div West Perspectives**
  Same as Topics in Sociology (SOC-237) except topic(s) relate to diverse Western cultures.
Prerequisite: Introductory Sociology (SOC 107)
 **SOC 247 Sociology of Race**
  The purpose of this course is twofold: first, students will develop an understanding of the social, political, and economic pressures shaping definitions of ‘race’ over time; second, we will explore the intersections of ‘race’ with ethnicity, gender, class, and sexuality. Students will examine these via in-depth evaluations of the following topics: the historical emergence of ‘race,’ contemporary and historical whiteness, harmonious and discordant inter-racial interactions, stereotyping, discrimination, racism, race and crime, economic inequality, and changing racial demographics. Efforts will be made throughout the course to make the material relevant to students’ lives.
 **SOC 275 Directed Readings in Sociology**
  Study of major literature on a selected topic in sociology directed by a sociology department faculty member. This course does not satisfy any of the requirements for a major or minor in sociology. Prerequisites: declared sociology major, minor, or elementary education emphasis, sophomore standing, or consent of department.  
 **SOC 328 Urban Sociology**
  Analysis of cities as they affect social behavior, and the study of the urban form as it is produced and modified by wider changes in the world economy. Emphasis is theoretical, historical, and comparative. Problems addressed include restructuring, poverty, and underdevelopment. Prerequisites: Introductory Sociology (SOC-107), sophomore standing or consent of instructor.
 **SOC 338 Political Sociology**
  Examines the interconnections between politics and society. Emphasis is on the relationship between the state and social structures of capatalist societies. Theoretical, historical, and comparative materials are considered. Topics may include polititcal power, the polititcs of the welfare state, policy-making, and political participation.
Prerequisite: Introductory Sociology (SOC 107) or consent of the instructor.  
 **SOC 351 Criminology**
  Examines the social meaning of criminal behavior. Looks at the relationship between crime and society - in particular, how the production and destribution of economic, political, and cultural resources shape the construction of "law" and "crime". Includes a comparison of different types of crime, criminals, and victims, as well as at efforts to understand and control them. Prerequisite: Introductory Sociology (SOC-107).
 **SOC 355 Deviant Behavior**
  Emphasis on theories and research in understanding deviant behaviors and deviant careers. Approaches include learning, strain, conflict, and labeling theories. Prerequisite: Introductory Sociology (SOC-107), consent of instructor.
 **SOC 365 Research Participation I**
  Individual or group investigation with a sociology department faculty member on a research topic or topics of mutual interest. The student must obtain approval for a specific project and make necessary arrangements prior to the term of registration for the course. This course does not satisfy any of the requirements for a major or minor in sociology. Prerequisites: Introductory Sociology (SOC-107) and consent of instructor. (Offered by arrangement)  
 **SOC 375 Research Participation II**
  A continuation of Research Participation I. The student must obtain approval for a specific project and make necessary arrangements prior to the term of registration for the course. This course does not satisfy any of the requirements for a major or minor in sociology. Prerequisites: Research Participation I (SOC-365) and consent of instructor. (Offered by arrangement)
 **SOC 417 Sociology of Sex & Sexuality**
  Examines how social contexts in the United States shape sexuality. Gender is a significant theme throughout the course, with a focus on topics such as past and current research about sexual behavior and identities; the social construction of sexual orientations; connections among thnicity, race, and sexulaity; domestic and international sex work; sexual violence. 
Prerequisite: Methods of Sociological Research (SOC 235) or consent of instructor.  
 **SOC 425 Social Change**
  Theories of change applied to substantive areas (for example, modernization, economic development or restructuring, social values, and social definitions), selected by the instructor. The course addresses the differential experiences of the consequences of change among various social groups. Prerequisite: Methods of Social Research (SOC-235) or consent of instructor. (Offered alternate years)
 **SOC 435 Advanced Topics in Sociology**
  Examines a particular sociological issue, problem, theory, or methodology. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Methods of Sociological Research (SOC-235) or consent of instructor.
 **SOC 444 Ind Study-Soc**
  None  
 **SOC 445 Small Groups**
  Theory and research on the processes of social interaction and social psychology with special application to studies of groups. Prerequisite: Methods of Social Research (SOC-235) or consent of instructor.
 **SOC 450 Sociological Theory**
  Examines the major paradigms and theories in contemporary sociology. The course places particular emphasis on the ways in which those paradigms and theories affect—and are affected by—the process of empirical research. Prerequisites: Methods of Sociological Research (SOC-235) and three other sociology courses above the introductory level or consent of instructor.  
 **SOC 464 Capstone Seminar in Sociology**
  Concepts, theories, and methodologies learned in previous sociology courses are applied to the intensive study of a topic selected by the instructor. Prerequisite: Sociological Theory (SOC-450), and senior standing, or consent of department chair.
 **SOC 494 Internship in Sociology**
  A field placement with a career-related organization. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major or minor in sociology. Prerequisite: declared major in sociology, junior standing, or consent of department chair.

