## Theatre Arts

D. Barnett, Charipar, Ganfield, Hahn, Rezabek, Schmidt, Steffens, Wolverton (Chair)

The Theatre Arts program is designed to provide a balance between academic and experiential learning for all interested students. The goal is to offer opportunities for student participation in all aspects of theatre, on stage and in the classroom, and to enrich the cultural and academic life of the College. 

The program accommodates both majors and minors through courses focused on theatrical history, theory and literature, as well as through training in acting, directing, design, and theatrical production. This foundation prepares students for graduate study and for any field that values high-level communication skills, as well as for careers in theatre as teachers, artists, technicians, or managers. 

As a means of helping students prepare for graduate study and/or a professional career, all majors are required to present an audition piece or a portfolio for annual review beginning in their second year. The senior seminar provides a capstone experience, giving students an opportunity to reflect on their development as theatre artists, and to examine theatre as a collaborative art form. 

For the campus community at large, as audience members or as occasional participants, the program offers a wide range of drama selected both to educate and to entertain. 

### Theatre Arts Major {#sec-theatre-arts-major}

A major in Theatre Arts requires a cumulative 2.0 GPA in all courses counted toward the major.

**Theatre Arts Core Courses** (required of all students majoring in theatre arts):

1. {{< var c.the102.long >}} 

2. {{< var c.the130.long >}}
 
3. {{< var c.the140.long >}} 

4. {{< var c.the150.long >}} 

5. {{< var c.the228.long >}}
 
6. {{< var c.the238.long >}} 

7. {{< var c.the290.long >}} 

8. {{< var c.the464.long >}} 

### Theatre Arts Minor 
The minor in Theatre Arts consists of six course credits of Theatre Arts. 

Theatre Arts students select one of the following **emphases**: general, acting, directing, musical theatre, and technical theatre/design.

**General**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. **Three** additional course credits of Theatre Arts, chosen with departmental approval. 

**Acting**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. {{< var c.the170.long >}} 
 
3. {{< var c.the250.long >}} 

4. **One** of the following:
	- {{< var c.the160.long >}} 
	- {{< var c.the260.long >}} 
	- {{< var c.the270.long >}} 
	- {{< var c.the350.long >}}
 
*Strongly recommended:*

- Any dance course (DAN-101 through DAN-152)
- {{< var c.the162.long >}} 
- {{< var c.the452.long >}} 
- {{< var c.phl105.long >}} 
- {{< var c.psy100.long >}} 

**Directing**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. {{< var c.the250.long >}} 

3. {{< var c.the390.long >}} 

4. **One** additional course in acting or design

*Strongly recommended:*
	- {{< var c.arh118.long >}} 
	- {{< var c.com237.long >}}
	- {{< var c.the220.long >}}  
	- {{< var c.the242.long >}} 
	- {{< var c.the280.long >}} 
	- {{< var c.the350.long >}} 
	- {{< var c.the462.long >}}
	- Any other art history course 

**Musical Theatre**

1. **Eight** core courses (See @sec-theatre-arts-major )

2. {{< var c.mu109.long >}} 

3. {{< var c.the170.long >}} 

4. {{< var c.the270.long >}} 

5. **Four** terms of {{< var c.mua202v.long >}} (0.6 cc) 

6. **One** additional course credit in practical musical theatre chosen from a combination of the following:
	- {{< var c.mua130v.long >}} (0.5 cc)
	- {{< var c.mua131v.long >}} (0.2 cc)
	- A musical theatre internship approved by the Music or Theatre Arts department

7. **Six** seven-week dance courses (DAN-101 through DAN-142) (0.2 cc)

**Technical Theatre/Design** 

1. **Eight** core courses (see @sec-theatre-arts-major )

2. **Three*** of the following: 
	- {{< var c.the220.long >}} 
	- {{< var c.the230.long >}} 
	- {{< var c.the232.long >}} 
	- {{< var c.the242.long >}} 
	- {{< var c.the280.long >}}
	- {{< var c.the288.long >}} 

*Strongly recommended:* 
	- {{< var c.arh118.long >}} 
	- Any other Art History course 
	- {{< var c.art115.long >}} 
	- {{< var c.art145.long >}} 
	- {{< var c.art364.long >}} 
	- {{< var c.phy155.long >}} and {{< var c.phy155l.long >}}  
	- {{< var c.the442.long >}} 

### Courses in Theatre Arts {#sec-courses-in-theatre-arts}

 **{{< var c.the100.long >}}**  
  {{< var c.the100.desc >}}  
 **{{< var c.the102.long >}}**  
  {{< var c.the102.desc >}}  
 **{{< var c.the112.long >}}**  
  {{< var c.the112.desc >}}  
 **{{< var c.the118.long >}}**  
  {{< var c.the118.desc >}}  
 **{{< var c.the130.long >}}**  
  {{< var c.the130.desc >}}  
 **{{< var c.the140.long >}}**  
  {{< var c.the140.desc >}}  
 **{{< var c.the145.long >}}**  
  {{< var c.the145.desc >}}  
 **{{< var c.the150.long >}}**  
  {{< var c.the150.desc >}}  
 **{{< var c.the160.long >}}**  
  {{< var c.the160.desc >}}  
 **{{< var c.the162.long >}}**  
  {{< var c.the162.desc >}}  
 **{{< var c.the170.long >}}**  
  {{< var c.the170.desc >}}  
 **{{< var c.the185.long >}}**  
  {{< var c.the185.desc >}}  
 **{{< var c.the220.long >}}**  
  {{< var c.the220.desc >}}  
 **{{< var c.the228.long >}}**  
  {{< var c.the228.desc >}}  
 **{{< var c.the230.long >}}**  
  {{< var c.the230.desc >}}  
 **{{< var c.the232.long >}}**  
  {{< var c.the232.desc >}}  
 **{{< var c.the238.long >}}**  
  {{< var c.the238.desc >}}  
 **{{< var c.the242.long >}}**  
  {{< var c.the242.desc >}}  
 **{{< var c.the250.long >}}**  
  {{< var c.the250.desc >}}  
 **{{< var c.the255.long >}}**  
See {{< var c.crw255.long >}} , @sec-courses-in-creative-writing  
  {{< var c.the255.desc >}}  
 **{{< var c.the260.long >}}**  
  {{< var c.the260.desc >}}  
 **{{< var c.the270.long >}}**  
See {{< var c.mu270.long >}} , @sec-courses-in-music  
  {{< var c.the270.desc >}}  
 **{{< var c.the280.long >}}**  
  {{< var c.the280.desc >}}  
 **{{< var c.the288.long >}}**  
  {{< var c.the288.desc >}}  
 **{{< var c.the290.long >}}**  
  {{< var c.the290.desc >}}  
 **{{< var c.the350.long >}}**  
  {{< var c.the350.desc >}}  
 **{{< var c.the355.long >}}**  
See also {{< var c.crw355.long >}} , @sec-courses-in-creative-writing  
  {{< var c.the355.desc >}}  
 **{{< var c.the390.long >}}**  
  {{< var c.the390.desc >}}  
 **{{< var c.the442.long >}}**  
  {{< var c.the442.desc >}}  
 **{{< var c.the444.long >}}**  
  {{< var c.the444.desc >}}  
 **{{< var c.the452.long >}}**  
  {{< var c.the452.desc >}}  
 **{{< var c.the455.long >}}**  
See also {{< var c.crw455.long >}} , @sec-courses-in-creative-writing  
  {{< var c.the455.desc >}}  
 **{{< var c.the462.long >}}**  
  {{< var c.the462.desc >}}  
 **{{< var c.the464.long >}}**  
  {{< var c.the464.desc >}}  
 **{{< var c.the486.long >}}**  
  {{< var c.the486.desc >}}  
 **{{< var c.the488.long >}}**  
  {{< var c.the488.desc >}}  
 **{{< var c.the494.long >}}**  
  {{< var c.the494.desc >}}  

