## Theatre Arts

D. Barnett, Charipar, Ganfield, Hahn, Rezabek, Schmidt, Steffens, Wolverton (Chair)

The Theatre Arts program is designed to provide a balance between academic and experiential learning for all interested students. The goal is to offer opportunities for student participation in all aspects of theatre, on stage and in the classroom, and to enrich the cultural and academic life of the College. 

The program accommodates both majors and minors through courses focused on theatrical history, theory and literature, as well as through training in acting, directing, design, and theatrical production. This foundation prepares students for graduate study and for any field that values high-level communication skills, as well as for careers in theatre as teachers, artists, technicians, or managers. 

As a means of helping students prepare for graduate study and/or a professional career, all majors are required to present an audition piece or a portfolio for annual review beginning in their second year. The senior seminar provides a capstone experience, giving students an opportunity to reflect on their development as theatre artists, and to examine theatre as a collaborative art form. 

For the campus community at large, as audience members or as occasional participants, the program offers a wide range of drama selected both to educate and to entertain. 

### Theatre Arts Major {#sec-theatre-arts-major}

A major in Theatre Arts requires a cumulative 2.0 GPA in all courses counted toward the major.

**Theatre Arts Core Courses** (required of all students majoring in theatre arts):

1. THE 102 Theatre Production Lab 

2. THE 130 Technical Production I
 
3. THE 140 Design for the Stage 

4. THE 150 Acting I 

5. THE 228 History of Theatre and Drama I
 
6. THE 238 History of Theatre and Drama II 

7. THE 290 Directing I 

8. THE 464 Senior Seminar 

### Theatre Arts Minor 
The minor in Theatre Arts consists of six course credits of Theatre Arts. 

Theatre Arts students select one of the following **emphases**: general, acting, directing, musical theatre, and technical theatre/design.

**General**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. **Three** additional course credits of Theatre Arts, chosen with departmental approval. 

**Acting**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. THE 170 Voice & Diction 
 
3. THE 250 Acting II 

4. **One** of the following:
	- THE 160 Movement for the Stage 
	- THE 260 Acting for the Camera 
	- THE 270 Musical Theatre Acting 
	- THE 350 Advanced Acting:Shakespeare
 
*Strongly recommended:*

- Any dance course (DAN-101 through DAN-152)
- THE 162 Stage Make-Up 
- THE 452 Advanced Projects in Acting 
- PHL 105 Introduction to Philosophy: 
- PSY 100 Introductory Psychology 

**Directing**

1. **Eight** core courses (see @sec-theatre-arts-major )

2. THE 250 Acting II 

3. THE 390 Directing II  WE 

4. **One** additional course in acting or design

*Strongly recommended:*
	- ARH 118 History of Western Architecture 
	- COM 237 Interpersonal Communication
	- THE 220 Tech Theatre Lab  
	- THE 242 Scene Design 
	- THE 280 Costume Design 
	- THE 350 Advanced Acting:Shakespeare 
	- THE 462 Advanced Projects in Directing
	- Any other art history course 

**Musical Theatre**

1. **Eight** core courses (See @sec-theatre-arts-major )

2. MU 109 Theory of Music I 

3. THE 170 Voice & Diction 

4. THE 270 Musical Theatre Acting 

5. **Four** terms of MUA 202V Voice (0.6 cc) 

6. **One** additional course credit in practical musical theatre chosen from a combination of the following:
	- MUA 130V MusicalTheatreProductionExperience (0.5 cc)
	- MUA 131V Song Interpretation Workshop (0.2 cc)
	- A musical theatre internship approved by the Music or Theatre Arts department

7. **Six** seven-week dance courses (DAN-101 through DAN-142) (0.2 cc)

**Technical Theatre/Design** 

1. **Eight** core courses (see @sec-theatre-arts-major )

2. **Three*** of the following: 
	- THE 220 Tech Theatre Lab 
	- THE 230 Technical Production II 
	- THE 232 Computer Aided Drafting and Design 
	- THE 242 Scene Design 
	- THE 280 Costume Design
	- THE 288 History of Dress 

*Strongly recommended:* 
	- ARH 118 History of Western Architecture 
	- Any other Art History course 
	- ART 115 Drawing 
	- ART 145 Digital Studio 
	- ART 364 The Human Form 
	- PHY 155 Electronics and PHY 155L Electronics Lab  
	- THE 442 Adv Proj-Design/Tech Production 

### Courses in Theatre Arts {#sec-courses-in-theatre-arts}

- **THE 100 Introduction to Theatre**
  A study of the art of theatre, emphasizing theatre’s place among the humanities; its relationship to the other arts; and its cultural and social influences in our society. Students derive a foundation for discriminating theatregoing through analysis of dramatic form and of selected playtexts; consideration of the methods and techniques employed by theatre artists and crafts persons; and a brief survey of theatre and drama, both in their historical context and as they have been manifested through related media. As part of the study, students are required to attend some evening events. This course does not satisfy any of the requirements for a major in theatre arts.  
- **THE 102 Theatre Production Lab**
  Applied skills in one of the theatre production crews. Students assist with set construction, costuming, lighting, painting, publicity, sound, or run-crew positions for productions during a term. No previous experience is required. Lab meets four hours per week. Theatre arts majors are required to take four labs. (0.25 course credit)
- **THE 112 Production Experience**
  Practical involvement in a mainstage production as an actor (in a leading or secondary role), stage manager, assistant director, dramaturge, technical crew head (property master, master electrician, wardrobe master, etc.), or in another capacity as approved by the faculty (excluding run-crew positions). May be taken more than once. Prerequisite: consent of department chair. (0.5 course credit)  
- **THE 118 Theatre & Arts in Serbia**
  Explores the recent history and political realities of Belgrade, Serbia, through the lens of Theatre and other art forms, as well as visits to multiple cultural formations: museums, churches, monuments and schools. Offered May Term only. Prerequisite: consent of instructor.
- **THE 130 Technical Production I**
  An introduction to the technical aspects of theatre production. Topics covered include safety, mechanical drawing, stage carpentry, craft techniques, stage lighting and electricity, costume construction, scene painting, and production organization. Class includes lecture-demonstration and practical application. Additional time outside of class is necessary to complete projects. (Offered Fall Term)  
- **THE 140 Design for the Stage**
  Examines the design process for all aspects of theatre design (costume, scenery, and lighting). Specific topics include the design elements, script analysis, research, basic drawing, basic drafting, and presentation techniques. A series of projects and readings introduce students to the basic language of visual story telling. Additional time outside of class is necessary to complete projects. (Offered Spring Term)
- **THE 145 Viewpoints Ensemble Work**
  A course designed to provide students with a comprehensive understanding of Viewpoints Technique for actors. Viewpoints is a "philosophy translated into a technique for training performers, building ensemble and creating movement for the stage." Students working within a group dynamic learn to access acutely their centers of awareness and intensify their ability to work in the "here and now." Hands-on training is supplemented by readings, quizzes and journal writing. (Offered Fall Term, alternate years)  
- **THE 150 Acting I**
  Stanislavsky-based, comprehensive introduction to the elements of acting for the stage. Through theatre games, improvisations, exercises, and partnered work on scenes grounded in realism, students learn to identify and personalize a character’s “objectives” and the “obstacles” that stand in the way of attaining them, and to engage themselves (via voice, body, mind, and spirit) in specific “actions” undertaken in pursuit of those identified goals. Emphasis is placed on “interactive” skills and on character-specific listening. Additional rehearsal time outside of class is required.
- **THE 160 Movement for the Stage**
  Designed to help students learn the effective use of the body as a component of the acting process. Physical expression in movement and gesture is developed by way of in-class exercises and improvisations, leading to the solo and collaborative creation of movement pieces for performance. Skills of concentration, breath control, partner awareness, and physical characterization are also fostered in this work.  
- **THE 162 Stage Make-Up**
  The theory and practice of designing and creating make-up for the stage actor. Lecture/demonstration plus laboratory experience.
- **THE 170 Voice & Diction**
  Designed to help students learn how to use the voice as a component of the acting process. The mechanics of vocal production and of speech are examined, along with various approaches for their improvement. A number of performance projects supplement a wide range of vocal exercises and drills. Students are introduced to the International Phonetic Alphabet (IPA) as the basis for determining correct pronunciation, both in standard speech and in preparing dialects and accents. Additional rehearsal time outside of class is required.  
- **THE 185 Production and Performance**
  A “theatre company” consisting of actors, designers, a stage manager, costume, set, and lighting crew (plus an accompanist and choreographer, if needed). The company has as its goal the mounting of the chosen production in a fully-collaborative atmosphere. In addition to fulfilling their various creative functions, company members may be asked to take on, under the supervision of a faculty member of the department, dramaturgical assignments designed to provide research and study on selected aspects of the play or musical. This material is presented to the Coe community in the form of public displays throughout the campus. Company members need to audition prior to spring registration. The basis for student evaluation is completion of assigned duties and quality of work. May be taken more than once for credit. A maximum of two course credits may be counted toward a major or minor in theatre arts. (Offered Spring Term)
- **THE 220 Tech Theatre Lab**
  A study of the equipment, mechanics, and theories used by lighting designers to produce lighting for theatre, dance, concerts, and architecture. Specific topics include design research and conceptualization, color, angle, cueing, and methods of presentation (sketches, storyboards, light plots, and associated paperwork). Class includes lecture/demonstration and practical application. Additional time outside of class is necessary to complete projects. Prerequisites: Design for the Stage (THE-140) and Technical Production I (THE-130) or consent of instructor. (Offered Spring Term, alternate years)  
- **THE 228 History of Theatre and Drama I**
  A writing intensive course that provides students with an overview of World Theatre and Drama from cultures where oral traditions were the dominant forms of communication through and including those wherein the written word presented a new paradigm. The course provides a practical investigation of current critical discourses that examine dramatic literature and performance traditions from around the world. (Offered Fall Term in rotation with History of Theatre and Drama II (THE-238))
- **THE 230 Technical Production II**
  A full-term study of the techniques and practical applications in a specific area of technical theatre. Possible course topics include stage management, drafting, sketching and rendering, scene painting, millinery, costume crafts, or fabric design. Prerequisite: Technical Production I (THE-130) or consent of instructor. (Offered by arrangement)  
- **THE 232 Computer Aided Drafting and Design**
  An introduction to the use of the computer as a drafting and design tool. Using theatre-related examples and projects, students create two- and three-dimensional drawings. Further work involves 3-D modeling and creating perspective images of virtual stage settings. Class includes lecture/demonstration and laboratory. Additional time outside of class is necessary to complete projects. (Offered Spring Term, alternate years)
- **THE 238 History of Theatre and Drama II**
  A writing intensive course that provides students with an overview of World Theatre and Drama, focusing primarily on cultures and periods wherein new forms of technology, from the camera to the computer, have become determining factors in systems of communication. The course provides a practical investigation of current critical discourses that examine dramatic literature from around the world. (Offered Fall Term in rotation with History of Theatre and Drama I (THE-228))  
- **THE 242 Scene Design**
  A study of the aesthetic, historical, and technical aspects of stage design. Projects emphasize research, drawing, drafting, problem solving, model building, and rendering. Class includes lecture/demonstration and practical application. Additional time outside of class is necessary to complete projects. Prerequisites: Technical Production I (THE-130) and Design for the Stage (THE-140) or consent of instructor.
- **THE 250 Acting II**
  A performance-based studio course designed to expand upon the work begun in Acting I by assisting students in the development of intermediate-level acting skills. Scenes and monologues progress beyond realism with an introduction to a number of other styles. Significant emphasis is placed on character development and on detailed analysis of dramatic action. Additional rehearsal time outside of class is required. Prerequisite: Acting I (THE-150). (Offered Spring Term)  
- **THE 255 Playwriting Workshop I**
See CRW 255 Playwriting Workshop I , @sec-courses-in-creative-writing
  Explores the basics of playwriting through the study of dramatic structure, creative exercises, and reading and analysis of existing play scripts, with emphasis on the one-act play. Students complete a one-act play script of their own creation.
- **THE 260 Acting for the Camera**
  Development of basic acting techniques essential for work in film and television. The course is designed to help students become comfortable in front of the camera by way of breaking down their physical and internal inhibitions. The instructor helps the student find the most effective personal resources for the creation of truthful characters, given the unique pressures of a film or television shoot. The course also focuses on audition techniques and culminates in the shooting of a scripted scene. Additional rehearsal time outside of class is required. Prerequisite: Acting I (THE-150).  
- **THE 270 Musical Theatre Acting**
See MU 270 Musical Theatre Acting , @sec-courses-in-music
  A performance-based studio course focusing on the development of basic skills necessary for musical theatre performance. Students become familiar with the specialized requirements necessary for the merging of singing with dramatic action. Periodic performance projects (solos, duets, and ensemble numbers—some including dialogue) are supplemented by student research projects. The course is also designed to introduce students to a wide-ranging repertoire of available audition material. Additional rehearsal time outside of class is required.
- **THE 280 Costume Design**
  A study of the aesthetic, historical, and technical aspects of costume design. Projects emphasize research, character analysis, figure drawing, textile selection, and rendering. Class includes lecture-demonstration and practical application. Additional time outside of class is necessary to complete projects. Prerequisites: Technical Production I (THE-130) and Design for the Stage (THE-140) or consent of instructor.  
- **THE 288 History of Dress**
  Traces the history of dress from ancient to modern times, with a special emphasis on dress as it relates to gender roles, social issues, cultural practices and beliefs, politics, and economic patterns within an historical context.
- **THE 290 Directing I**
  Offers students an introduction to the fundamental tools of directing plays for the stage. Analysis of playtexts is undertaken to demonstrate how a director develops the vision of a play that serves as an interpretive guide throughout the production process. In-class exercises, improvisations, and staged “image” pieces focus on the acquisition of skills for communicating effectively with actors. Scene projects are rehearsed outside of class for in-class presentation, and comprehensive promptbooks are prepared in conjunction with each. Additional rehearsal time outside of class is required. Prerequisite: Acting I (THE-150). (Offered Spring Term)  
- **THE 350 Advanced Acting:Shakespeare**
  A performance-based studio course aimed at the development of advanced-level acting skills specifi- cally related to performing the playtexts of William Shakespeare. An eclectic approach to this complex material is offered, with emphasis divided between its verbal, physical, and psychological demands. Students prepare and perform several scenes and monologues throughout the term. Exercises and improvisations related to characterization and written character analyses are also components of this course. Additional rehearsal time outside of class is required. Prerequisite: Acting I (THE-150).
- **THE 355 Playwriting Workshop 2**
See also CRW 355 Playwriting Workshop 2 , @sec-courses-in-creative-writing
  Focuses on the analysis and creation of play scripts of two acts or more. Emphasis is placed on the writing and marketing of the student’s own creative work, culminating in the completion and public reading of a full-length script. Prerequisite: Beginning Playwriting (CRW/THE-255).  
- **THE 390 Directing II  WE**
  An intermediate-level course or independent study expanding upon the work begun in Directing I by developing more complex analytical tools and deepening the work of conceptualization for production. Assigned readings guide the directing student to knowledge and understanding of a wide variety of 20th-century and contemporary directing theories and methodologies. The course culminates in the analysis and preparation with actors of a short one-act play or an extended scene from a full-length play that allows the student director to work in a non-realist style. Prerequisite: Directing I (THE-290). (Offered by arrangement)
- **THE 442 Adv Proj-Design/Tech Production**
  Individual work in a specific aspect of theatrical production: lighting design, costume design, scene design, sound design, technical direction, or stage management. A written proposal, conceptual statement, documentation of process, and self-evaluation are components of this upper-level course. May involve actual work for a departmental production. May be taken more than once, provided the emphasis varies. Prerequisite: consent of department chair. (Offered by arrangement)  
- **THE 444 Ind Study-Theatre**
  The faculty-supervised staging of an extended one-act or a full-length play as an advanced project. The production is staged in the Mills Experimental Theatre and may receive modest technical and design support, when appropriate. Comprehensive playtext analysis and documentation of process are components of this course. Prerequisite: Design for the Stage (THE-140), Directing II (THE-390), or consent of department chair. (Offered by arrangement)
- **THE 452 Advanced Projects in Acting**
  A senior acting recital designed to demonstrate the proficiency level of majors with an acting emphasis. The recital may take the form of a one-person performance or a selection of scenes, monologues, and /or musical numbers demonstrating the student’s range and versatility. The project requires conceptualization, organization and selection of performance material, and adherence to a pre-arranged rehearsal process. Written components include a detailed proposal, a comprehensive statement of concept, thorough documentation of process, and analytical self-evaluation. Prerequisites: senior standing and consent of department chair. (Offered by arrangement)  
- **THE 455 Playwriting Workshop 3**
See also CRW 455 Playwriting Workshop 3 , @sec-courses-in-creative-writing
  Continued advanced writing, with an emphasis on producing finished poems. Prerequisite: Poetry Workshop 2 (CRW-380).
- **THE 462 Advanced Projects in Directing**
  The faculty-supervised staging of an extended one-act or a full-length play as an advanced project. The production is staged in the Mills Experimental Theatre and may receive modest technical and design support, when appropriate. Comprehensive playtext analysis and documentation of process are components of this course. Prerequisite: Design for the Stage (THE-140), Directing II (THE-390), or consent of department chair. (Offered by arrangement)  
- **THE 464 Senior Seminar**
  Capstone course for theatre arts majors that requires students to synthesize their study of dramatic theory and literature and their experiences in theatre performance and production. Assignments center on dramaturgy, dramatic theory and criticism, and on the current state of the art. Required of theatre arts majors in their senior year. (Offered Fall Term)
- **THE 486 Spc Top Theatre or Film: NWP**
  None  
- **THE 488 Special Topics in THE/ FLM**
  Focuses on specific aspects of theatre or film. Possible topics include: Eastern European Theatre, Post-War Eastern European Cinema, Queer Cinema, Feminist Theatre. May be taken more than once, provided the topics are substantially different. With departmental approval, this course may be used to satisfy the requirements for a major in theatre arts.
- **THE 494 Internship in Theatre Arts**
  An experience in professional or community theatre under the direction of an on-site supervisor in cooperation with a faculty member of the department and the Internship Specialist. A minimum of 140 hours on-site experience is required. S/U basis only. One internship credit may be used to satisfy the requirements for a major in theatre arts. Prerequisites: junior standing, declared major in theatre arts, and consent of department chair. 

