## Workshops (Courses Only)

Hughes, Rogers.

Workshops (0.25 and 0.5 course credit) are designed to allow hands-on, experiential learning in a practice-based context.  WKS courses can be interdisciplinary explorations, or offer opportunities to learn, refine, or apply a skill set within a specific discipline. 

- **WKS 201 Workshop: Studio Lighting/Portrait**
  An introduction to studio lighting for photography. Following a review of the history of the photographic portrait, students learn the basics of studio lighting for expressive portraits. (0.5 course credit).  
- **WKS 202 Workshop: Encaustic Painting**
  An introduction to encaustic painting. Encaustic, one of the oldest painting mediums, is pigment suspended in wax. Projects help students learn the technical process and explore the expressive potential of the medium. (0.5 course credit).
- **WKS 203 Workshop: Egg Tempera Painting**
  An introduction to egg tempera painting. Egg tempera was the most common painting medium before the introduction of oil paint. Projects help students learn the technical process and explore the expressive potential of the medium. (0.5 course credit).  
- **WKS 204 Workshop: Digital Toolbox**
  An introduction to Adobe Photoshop as an art-making tool through a series of self-directed creative projects (not tutorials). Students learn through hands on experience, guided with interactive demonstrations and assignments. (0.5 course credit).
- **WKS 211 Workshop: Design Thinking Project**
  Learn to solve real world problems using design thinking processes. (0.5 course credit).  
- **WKS 212 Workshop: 3D Modeling & Output**
  An introduction to 3D modeling software. Course culminates in outputting the final project by means of a 3D printer or other means appropriate to the project. (0.5 course credit).
- **WKS 213 Workshop: Vector Graphics**
  An introduction to vector graphics programs such as Adobe Illustrator as art-making tools though a series of self-directed creative projects (not tutorials). Students learn through hands on experience, guided with interactive demonstrations and assignments. (0.5 course credit).  
- **WKS 214 Workshop: Stop Motion**
  An introduction to stop-motion animation as an art-making tool, through a series of self-directed creative projects (not tutorials). Students learn through hands on experience, guided with interactive demonstration and assignments. (0.5 course credit).
- **WKS 221 Innovation Lab I**
  A workshop for students to engage in collaborative, innovative projects in the Center for Creativity. Students can work on smaller initiatives for 7 weeks (Innovation Lab I) or tackle more complex problems for an entire semester (Innovation Lab I and II)  
- **WKS 241 Workshop: Topics**
  Investigates specific topics and/or tools in art-making. (0.5 course credit).
- **WKS 251 Workshop: Sound**
  An introduction to sound as an art medium, using recording devices, software and installation, through a series of self-directed creative projects (not tutorials). Students learn through hands on experience, guided with interactive demonstrations and assignments. Prerequisite: Illuminated Pixels (ART-145), or Movement (ART-170), or Narratives (ART-251), or SpaceTime (ART-203). (0.5 course credit).  
- **WKS 252 Workshop: Motion Graphics**
  An introduction to digital kinetic graphics programs, specifically Adobe AfterEffects among others, as art-making tools, through a series of self-directed creative projects (not tutorials). Students learn through hands on experience, guided with interactive demonstrations and assignments. Prerequisite: Illuminated Pixels (ART-145), or Movement (ART-170), or Narratives (ART-251), or SpaceTime (ART-203), or Vector Graphics (WKS-213). (0.5 course credit).
- **WKS 253 Workshop: Competitions**
  This 7-week workshop is designed to prepare artists for submission, be that galleries, grants, festivals or graduate schools. Learn about what makes submissions attractive and improve your submission materials, including artist resumes, proposals, statements, etc. To be most successful, students should have a project in mind or already near completion. Prequisite: at least two ART- courses or consent of instructor.
- **WKS 291 Workshop: Advanced Topics**
  This course will investigate specific topics and/or tools in art-making. Prerequisite: at least two ART- courses or consent of instructor. (0.5 course credit).  