## French & Francophone Studies
Janca-Aji

The French & Francophone Studies program is an intercultural and interdisciplinary program featuring courses in language, cultural history, literature and cinema, translation and interpretation, and pre-professional studies. Students are strongly encouraged to pursue opportunities for immersive and experiential learning through study abroad, May Term courses, service learning, and community-based projects and to explore ways to incorporate French in and with other major(s).

### French & Francophone Studies Major
A grade of "C" (2.0) or higher must be earned in all courses counted toward a major in French & Francophone Studies. Students complete eight credits of 300- to 400-level courses in French. FRE-315 Oral and Written Communication Skills (WE) is required. Up to three credits may be earned by successfully completing a study abroad program in France or a francophone country that is approved by the College and the department. Up to one credit may be earned from a list of approved courses taught in English. One credit from a course taught in French must be taken in the senior year. FRE-499 Exit Exam and Interview is required during the final term before graduation.
 
### French & Francophone Studies Minor
A grade of "C" (2.0) or higher must be earned in all courses counted toward a minor in French & Francophone Studies. Students complete a minimum of four credits of 300- to 400-level courses in French. FRE-315 Oral and Written Communication Skills (WE) is required. Up to one credit may be earned from a list of approved courses taught in English. FRE-499 Exit Exam and Interview is required during the final term before graduation.

### Interdisciplinary French & Francophone Studies Major
A grade of "C" (2.0) or higher must be earned in all courses counted toward a major in Interdisciplinary French & Francophone Studies. Students complete 1) **four** credits of courses taught in French at any level, including FRE-315 Oral and Written Communication Skills (WE), 2) a departmentally approved term-long study abroad experience in France or a Francophone country, and 3) **four** credits from courses, taught in either French or English, from the list of approved courses which include at least two different prefixes and demonstrate thematic coherence. Courses not on this list may count for credit with approval of the program coordinator. FRE-499 Exit Exam and Interview is required during the final term before graduation. 

### Interdisciplinary French & Francophone Studies Minor
A grade of "C" (2.0) or higher must be earned in all courses counted toward a minor in Interdisciplinary French & Francophone Studies. Students complete 1) **four** credits of courses taught in French at any level, including FRE-315 Oral and Written Communication Skills (WE), and 2) **three** credits from courses, taught in either French or English, from the list of approved courses which include at least two different prefixes and demonstrate thematic coherence. Courses not on this list may count for credit with approval of the program coordinator. FRE-499 Exit Exam and Interview is required during the final term before graduation. 


### Courses Taught in English that can be used for credit in French & Francophone Studies
	{{< var c.arh201.long >}}
	{{< var c.arh218.long >}}
	{{< var c.arh231.long >}}
	{{< var c.arh307.long >}}
	{{< var c.com236.long >}}
	{{< var c.eng146.long >}}
	{{< var c.fre145.long >}}
	{{< var c.fre146.long >}}
	{{< var c.fre148.long >}}
	{{< var c.fre158.long >}}
	{{< var c.his238.long >}}
	{{< var c.his248.long >}}
	{{< var c.his272.long >}}
	{{< var c.his288.long >}}
	{{< var c.his355.long >}}
	{{< var c.his365.long >}}
	{{< var c.his372.long >}}
	{{< var c.phl230.long >}}
	{{< var c.phl240.long >}}
	{{< var c.phl255.long >}}
	{{< var c.phl305.long >}}
	{{< var c.phl345.long >}}
	{{< var c.pol298.long >}}
	{{< var c.rel148.long >}}
	{{< var c.phl178.long >}}


### Courses in French
- **{{< var c.fre115.long >}}**
  {{< var c.fre115.desc >}} 
- **{{< var c.fre125.long >}}**
  {{< var c.fre125.desc >}}
- **{{< var c.fre145.long >}}**
  {{< var c.fre145.desc >}}
- **{{< var c.fre146.long >}}**
  {{< var c.fre146.desc >}}
- **{{< var c.fre148.long >}}**
  {{< var c.fre148.desc >}}
- **{{< var c.fre158.long >}}**
  {{< var c.fre158.desc >}}
- **{{< var c.fre199.long >}}**
  {{< var c.fre199.desc >}}
- **{{< var c.fre235.long >}}**
  {{< var c.fre235.desc >}}
- **{{< var c.fre315.long >}}**
  {{< var c.fre315.desc >}}
- **{{< var c.fre335.long >}}**
  {{< var c.fre335.desc >}}
- **{{< var c.fre339.long >}}**
  {{< var c.fre339.desc >}}
- **{{< var c.fre340.long >}}**
  {{< var c.fre340.desc >}}
- **{{< var c.fre345.long >}}**
  {{< var c.fre345.desc >}}
- **{{< var c.fre394.long >}}**
  {{< var c.fre394.desc >}}
- **{{< var c.fre400.long >}}**
  {{< var c.fre400.desc >}}
- **{{< var c.fre444.long >}}**
  {{< var c.fre444.desc >}}
- **{{< var c.fre446.long >}}**
  {{< var c.fre446.desc >}}
- **{{< var c.fre452.long >}}**
  {{< var c.fre452.desc >}}
- **{{< var c.fre494.long >}}**
  {{< var c.fre494.desc >}}
- **{{< var c.fre495.long >}}**
  {{< var c.fre495.desc >}}
- **{{< var c.fre499.long >}}**
  {{< var c.fre499.desc >}} 














