## International Economics {#sec-international-economics}
Students majoring in economics have two options: the ECONOMICS major (see @sec-economics) and the INTERNATIONAL ECONOMICS major. The international economics major is designed to allow students who are interested in international studies to explore issues of development, growth, and international finance, using the tools of economic analysis. Because of significant overlap in the economics and the international economics requirements, only one of the two majors may be elected by a student. Students majoring in economics or international economics may not minor in either economics or international economics.

### International Economics Major
1. {{< var c.eco175.long >}}
2. {{< var c.eco215.long >}}
3. {{< var c.eco315.long >}}
4. {{< var c.eco336.long >}}
5. {{< var c.eco345.long >}}
6. {{< var c.eco375.long >}}
7. {{< var c.eco436.long >}}
8. {{< var c.eco446.long >}}
9. {{< var c.eco495.long >}}
10. Two courses in world language numbered 115 or above
11. **One** of the following:
	A semester abroad
	A May Term abroad
	A capstone project in international economics, supervised by a member of the economics faculty

**NOTE:** *International economics majors intending to do graduate work in international studies or intending to pursue a career with a governmental or non-governmental agency are strongly encouraged to consider a minor or major in political science or one of the International Studies tracks to complement the international economics major. Students are also encouraged to work closely with a member of the department to select complementary general education courses. *


### International Economics Minor
1. {{< var c.eco175.long >}}
2. {{< var c.eco215.long >}}
3. {{< var c.eco336.long >}}
4. {{< var c.eco436.long >}}
5. {{< var c.eco446.long >}}
6. {{< var c.eco495.long >}}














