### Nursing

Bursch (Chair), Dehner, Guthrie, Kittrell, Siems, Umbarger-Mackey 
A description of policies unique to the nursing department is in the *Nursing Department Student Policies Manual*. Copies of the manual are available in the Nursing Department Office, Stuart Hall 415, and online.

#### The Bachelor of Science in Nursing Program

The baccalaureate nursing program is designed to prepare students for practice as professional nurses in a variety of settings. The upper division nursing courses draw upon broad and diverse knowledge gained from the liberal arts foundation to support the educational outcomes. 

Clinical experiences in the program include working with clients across the age span in a wide spectrum of practice sites. Nurse preceptors are utilized at clinical sites to provide the maximum amount of individual supervision and educational opportunity to students. Coe College nursing faculty provide clinical expertise and education by overseeing student clinical experiences, evaluating and promoting preceptor performance, and engaging in ongoing dialogue with students regarding the application of theory into practice. 

Graduates of the Bachelor of Science in Nursing degree program are eligible to take the state board licensing examination for Registered Nurses. They are also eligible for admission to graduate programs in nursing and to advanced nurse practitioner programs. The Coe College nursing program is approved by the Iowa Board of Nursing and accredited by the Commission on Collegiate Nursing Education (CCNE). 

Coe College offers two paths to enter the nursing program.  Standard entry is for sophomore level (or higher) college students and direct entry is for selected high school seniors.  Details for both plans are found in the *Nursing Department Student Policies Manual*.  Copies of the manual are available in the Nursing Department Office.  At the end of the sophomore year, a student must possess valid licensure, e.g. Licensed Practical Nurse (LPN) or Certified Nursing Assistant (Direct Care Worker).   A student with a revoked license from any state will NOT be admitted into the nursing program.  In addition, a clinical component may not be taken by a person: a) who had been denied licensure by the State Board of Nursing, b) whose licensure is currently suspended, surrendered or revoked in any United States jurisdiction, c) whose licensure/ registration is currently suspended, surrendered or revoked in another country due to disciplinary action.

The nursing department Admission, Promotion, and Retention committee reviews applications and selects candidates who are best qualified to meet the standards of the nursing profession. Admission to the BSN degree program is competitive. Those applicants who appear to be the most qualified will be admitted. Standard and direct entry students are expected to maintain the eligibility requirements as outlined in the *Nursing Department Student Policies Manual*. 

#### Departmental Notes: 
In order to successfully complete a course and be promoted to successive courses, students must 
- Achieve a minimum grade of C (2.0) in all nursing courses; a grade of C- (1.7) or lower requires the student to repeat the course.
- Achieve a cumulative average of 72% on all exams in a given course.

Candidates for the **Bachelor of Science in Nursing** degree must satisfactorily complete: 
1. The general education requirements (see p. ).
2. [Eight] required supporting courses:
Biology		BIO-145 Cellular and Molecular Biology 
		BIO-195 Introduction to Microbiology 
		BIO-215/ -215L Human Anatomy and Laboratory 
		BIO-225 Human Physiology
Chemistry	CHM-111/ -111L Introduction to Organic and Biological Chemistry and Laboratory
Psychology 	PSY-100 Introductory Psychology 
Sociology	SOC-107 Introductory Sociology
Statistics 	PSY-300 Statistical Methods and Data Analysis **[or]**
		STA-100 Statistical Foundations (7 weeks) **and** STA-110 Inferential Statistics (7 weeks)
3. NUR-100 Nursing Issues (0.2 course credit) (Pre-nursing students must enroll each term of the first year.  A maximum of two seminars may be counted for credit toward graduation.)
4. NUR-200 Nursing Issues II (0.2 course credit) (Pre-nursing students must enroll each term of the sophomore year. A maximum of two seminars may be counted for credit toward graduation.)
5.   Nine non-clinical theory course credits: 
NUR-300 Art and Science of Nursing 
NUR-305 Information Literacy and Management (WE) (0.5 cc)  
NUR-345/-345L Mental Health Nursing and Laboratory
NUR-360 Pharmacological Principles (0.5 cc)  
NUR-375 Legal and Ethical Issues in Nursing (WE)
NUR-425 Nursing Research (WE) 
NUR-430 Community and Population Oriented Nursing (WE)
NUR-431 Maintaining Wellness in Aging and Chronicity
NUR-495 Maternal Newborn Nursing
6.   Four two-course-credit clinical courses: 
NUR-315/ -315L Pathophysiology and Assessment/Clinical Application 
NUR-355/-355L Introductory Concepts in Nursing/Clinical Application
NUR-415/ -415L Advanced Concepts in Nursing/Clinical Application 
NUR-455/-455L Leadership and Contemporary Issues in Nursing/Clinical Application (WE)
7. A formal NCLEX review course (at the student’s expense)
8. All required supporting courses and required nursing courses listed above, with no one specific course repeated more than once and with no more than two different courses repeated.


#### Courses in Nursing

- **{{< var c.nur100.long >}}**
  {{< var c.dsnur100.desc >}}  
- **{{< var c.nur137.long >}}**
  {{< var c.nur137.desc >}} 
- **{{< var c.nur200.long >}}**
  {{< var c.nur200.desc >}}
- **{{< var c.nur215.long >}}**
  {{< var c.nur215.desc >}}  
- **{{< var c.nur268.long >}}**
  {{< var c.nur268.desc >}} 
- **{{< var c.nur297.long >}}**
  {{< var c.nur297.desc >}} 
- **{{< var c.nur300.long >}}**
  {{< var c.nur300.desc >}}
- **{{< var c.nur305.long >}}**
  {{< var c.nur305.desc >}}
- **{{< var c.nur315.long >}}**
  {{< var c.nur315.desc >}} 
- **{{< var c.nur345.long >}}**
  {{< var c.nur345.desc >}}  
- **{{< var c.nur355.long >}}**
  {{< var c.nur355.desc >}} 
- **{{< var c.nur360.long >}}**
  {{< var c.nur360.desc >}}  
- **{{< var c.nur375.long >}}**
  {{< var c.nur375.desc >}} 
- **{{< var c.nur387.long >}}**
  {{< var c.nur387.desc >}} 
- **{{< var c.nur415.long >}}**
  {{< var c.nur415.desc >}} 
- **{{< var c.nur425.long >}}**
  {{< var c.nur425.desc >}} 
- **{{< var c.nur430.long >}}**
  {{< var c.nur430.desc >}} 
- **{{< var c.nur431.long >}}**
  {{< var c.nur431.desc >}} 
- **{{< var c.nur444.long >}}**
  {{< var c.nur444.desc >}} 
- **{{< var c.nur455.long >}}**
  {{< var c.nur455.desc >}} 
- **{{< var c.nur494.long >}}**
  {{< var c.nur494.desc >}} 
- **{{< var c.nur495.long >}}**
  {{< var c.nur495.desc >}} 



