### Physics 
Affatigato (Chair), Akgun, Baehr, Bragatto, Duru, Feller, Wetzel
The physics department serves a variety of students with a balanced program, giving equal emphasis to the needs of the technically and the non-technically oriented. 

####Physics Major
A major in physics requires a minimum cumulative 2.0 GPA in all courses counted toward the major.
1. PHY-185/ -185L General Physics I & Laboratory
2. PHY-195/ -195L General Physics II & Laboratory 
3. PHY-231 Mathematical Methods for Physicists
4. PHY-235/ -235L Modern Physics & Laboratory (WE)
5. PHY-265 Electromagnetism 
6. [Two] of the following courses:
   PHY-275 Classical Mechanics
   PHY-315 Thermodynamics and Statistical Mechanics
   PHY-335 Quantum Physics
   PHY-425 Solid State Physics 
7. Four additional physics courses, all of which must be numbered 150 or above. 
8. Comprehensive evaluation
   Satisfactory completion of written and oral examinations
***Recommended:***
   CS-125 Introduction to Programming 
   CHM-121/-121L General Chemistry I and Laboratory

####Physics Major
A minor in Physics requires a cumulative 2.0 GPA in all courses counted toward the major.
1. PHY-185/-185L General Physics I & Laboratory or PHY-165/-165L Basic Physics I & Laboratory 
2. PHY-195/-195L General Physics II & Laboratory or PHY-175/-175L Basic Physics II & Laboratory 
3. PHY-235/-235L Modern Physics & Laboratory (WE)
4. PHY-265 Electromagnetism
6. Two additional physics course approved by the department, both of which must be numbered 150 and above. 

#### Courses in Physics 
- **{{< var c.phy105.long >}}**
  {{< var c.phy105.desc >}} 
- **{{< var c.phy114.long >}}**
  {{< var c.phy114.desc >}}  
- **{{< var c.phy121.long >}}**
  {{< var c.phy121.desc >}}
- **{{< var c.phy155.long >}}**
  {{< var c.phy155.desc >}} 
- **{{< var c.phy161.long >}}**
  {{< var c.phy161.desc >}}  
- **{{< var c.phy165.long >}}**
  {{< var c.phy165.desc >}}
- **{{< var c.phy175.long >}}**
  {{< var c.phy175.desc >}}
- **{{< var c.phy181.long >}}**
  {{< var c.phy181.desc >}} 
- **{{< var c.phy185.long >}}**
  {{< var c.phy185.desc >}}  
- **{{< var c.phy195.long >}}**
  {{< var c.phy195.desc >}}
- **{{< var c.phy201.long >}}**
  {{< var c.phy201.desc >}}
- **{{< var c.phy211.long >}}**
  {{< var c.phy211.desc >}} 
- **{{< var c.phy221.long >}}**
  {{< var c.phy221.desc >}}  
- **{{< var c.phy231.long >}}**
  {{< var c.phy231.desc >}}
- **{{< var c.phy235.long >}}**
  {{< var c.phy235.desc >}}
- **{{< var c.phy235lab.long >}}**
  {{< var c.phy235lab.desc >}}
- **{{< var c.phy241.long >}}**
  {{< var c.phy241.desc >}}
- **{{< var c.phy251.long >}}**
  {{< var c.phy251.desc >}}
- **{{< var c.phy255.long >}}**
  {{< var c.phy255.desc >}}
- **{{< var c.phy355.long >}}**
  {{< var c.phy355.desc >}}
- **{{< var c.phy265.long >}}**
  {{< var c.phy265.desc >}}
- **{{< var c.phy275.long >}}**
  {{< var c.phy275.desc >}}
- **{{< var c.phy301.long >}}**
  {{< var c.phy301.desc >}}
- **{{< var c.phy311.long >}}**
  {{< var c.phy311.desc >}}
- **{{< var c.phy315.long >}}**
  {{< var c.phy315.desc >}}
- **{{< var c.phy321.long >}}**
  {{< var c.phy321.desc >}}
- **{{< var c.phy335.long >}}**
  {{< var c.phy335.desc >}}
- **{{< var c.phy341.long >}}**
  {{< var c.phy341.desc >}}
- **{{< var c.phy411.long >}}**
  {{< var c.phy411.desc >}}
- **{{< var c.phy425.long >}}**
  {{< var c.phy425.desc >}}
- **{{< var c.phy441.long >}}**
  {{< var c.phy441.desc >}}
- **{{< var c.phy444.long >}}**
  {{< var c.phy444.desc >}}
- **{{< var c.phy451.long >}}**
  {{< var c.phy451.desc >}}
- **{{< var c.phy454.long >}}**
  {{< var c.phy454.desc >}}
- **{{< var c.phy464.long >}}**
  {{< var c.phy464.desc >}}
- **{{< var c.phy484.long >}}**
  {{< var c.phy484.desc >}}
- **{{< var c.occ365.long >}}**
  {{< var c.occ365.desc >}}






