### Public Relations
Carstens (Administrative Coordinator). 
The Public Relations major prepares students for a career in public relations and related communication fields. The major integrates course work in business administration, professional writing, graphic arts, and other disciplines relevant to public relations. The curriculum encourages the development of skills and perspectives desirable for learning to manage the successful communication between an organization and its publics. 
Students wishing to complete this major must consult with the Public Relations administrative coordinator no later than the first term of their junior year. Students wishing to register for any of the art courses that count toward this major should consult with the art and art history department prior to course registration. 

#### Collateral Major in Public Relations
A major in Public Relations requires a cumulative 2.0 GPA in all courses counted toward the major.
Concurrent completion of any of the majors listed on p.  of the Catalog is required.  
1. [One] of the following:
   ART-101 Works on Paper: Two-Dimensional Design
   ART-145 Digital Studio
   ART-155 Photography: Light Writing
   ART-363 Graphic Design Studio
2. PR-205 Public Relations (WE)
3. BUS-330 Principles of Marketing (WE)
4. BUS-460 Advertising (WE)
5. [One] of the following:
   COM-241 Introduction to Multimedia Journalism (WE)
   RHE-225 Journalism and Media Writing Workshop (WE)
6. [One] of the following (producing a portfolio of writings related to the field of public relations):
   BUS-461 Marketing Decision-Making & Strategy (WE)
   RHE-415 Advanced Writing Workshop (WE)
7. [One] of the following: 
   BUS-494 Internship in Business (with public relations or advertising as a major component) 
   INT-499 Summer Internship (0.0 credit) (with public relations as a major component)
   PR-494 Internship in Public Relations 
8. [Three] of the following.  No more than two courses may be selected from within any one department. (Students majoring in Business Administration may select no more than one course with either a BUS or an ACC prefix. Students majoring in Communication Studies or in Writing may select no more than one course with either a COM or an RHE prefix.)
    ACC-171 Principles of Accounting I
    ART-101 Works on Paper: Two-Dimensional Design (if not used to satisfy #1)
    ART-145 Digital Studio (if not used to satisfy #1) 
    ART-155 Photography: Light Writing (if not used to satisfy #1)  
    ART-363 Graphic Design Studio (if not used to satisfy #1)
    BUS-250 Principles of Management 
    BUS-375 Business Ethics (WE)
    BUS-461 Marketing Decision-Making & Strategy (WE) (if not used to satisfy #6)
    BUS-464 Seminar in Management (WE), subject to topic approval by PR administrative coordinator
   BUS-465 Advanced Topics in Marketing, subject to topic approval by PR administrative coordinator
   COM-125 Fundamentals of Public Speaking
   COM-157 Introduction to Media Analysis (WE)
   COM-337 Persuasion
   COM-341 Digital Storytelling (WE)
   RHE-225 Journalism and Media Writing Workshop (WE) (if not used to satisfy #5) 
   RHE-265 Professional Writing (WE)
   RHE-415 Advanced Writing Workshop (WE) (if not used to satisfy #6)

#### Courses in Public Relations 
- **{{< var c.pr205.long >}}**
  {{< var c.pr205.desc >}}  
- **{{< var c.pr494.long >}}**
  {{< var c.pr494.desc >}}



