### Data Science
Peach, Muñoz Pérez, Rodríguez Moreno (Program Coordinator).

##### Spanish Major 
A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in Spanish. 
Students who major in Spanish complete a minimum of eight courses in Spanish beyond Intermediate Spanish II (SPA-225), though Spanish Literature in Translation (SPA-148) may be taken as one of the eight. Elementary Spanish (SPA-115/125), Spanish Review and Preparation (SPA-135), and Intermediate Spanish (SPA-215/225) are regarded as skill-building courses, and do not count toward the major in Spanish. Spanish students are urged to substitute study abroad in a program approved by the College and the department for up to three courses for the major. One Hispanic literature course (SPA-336 or above) must be taken in the senior year. 
SPA-464 Capstone in Spanish is required during the final spring term before graduation. Students selecting Spanish as a second teaching field should complete a minimum of four Spanish courses numbered 315 or above. Any advanced courses taken for the second teaching field should include Spanish Composition and Conversation (WE) (SPA-315). 

#### Spanish Minor
A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in Spanish. 
The minor in Spanish requires the completion of four courses beyond Intermediate Spanish II (SPA-225), though with the consent of department chair, Spanish Literature in Translation (SPA-148) may be taken as one of the four. Elementary Spanish (SPA-115/125), Spanish Review and Preparation (SPA-135), and Intermediate Spanish (SPA-215/225) are regarded as skill-building courses, and do not count toward the minor in Spanish. 

#### Spanish Studies Major 
A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in Spanish Studies. 
The Spanish Studies major requires: 1) successful completion of four courses beyond Intermediate Spanish II (SPA-225), with Hispanic Life and Culture (SPA-336/ -338) recommended as one of the four; and 2) successful completion of a departmentally approved list of five courses proposed by the student which exhibits both internal coherence and relevance to the course work in Spanish. Typically, application to the department for the approval of the interdisciplinary elected courses is to be made no later than the Spring Term of the junior year. Elementary Spanish (SPA-115/125), Spanish Review and Preparation (SPA-135), and Intermediate Spanish (SPA-215/225) are regarded as skill-building courses, and do not count toward the major in Spanish Studies.

#### Courses in Spanish
- **{{< var c.spa115.long >}}**
  {{< var c.spa115.desc >}}  
- **{{< var c.spa129.long >}}**
  {{< var c.spa129.desc >}}
- **{{< var c.spa135.long >}}**
  {{< var c.spa135.desc >}}  
- **{{< var c.spa148.long >}}**
  {{< var c.spa148.desc >}}
- **{{< var c.spa215.long >}}**
  {{< var c.spa215.desc >}}  
- **{{< var c.spa258.long >}}**
  {{< var c.spa258.desc >}}
- **{{< var c.spa315.long >}}**
  {{< var c.spa315.desc >}}  
- **{{< var c.spa325.long >}}**
  {{< var c.spa325.desc >}}
- **{{< var c.spa330.long >}}**
  {{< var c.spa330.desc >}}  
- **{{< var c.spa336.long >}}**
  {{< var c.spa336.desc >}}
- **{{< var c.spa338.long >}}**
  {{< var c.spa338.desc >}}  
- **{{< var c.spa339.long >}}**
  {{< var c.spa339.desc >}}
- **{{< var c.spa345.long >}}**
  {{< var c.spa345.desc >}}  
- **{{< var c.spa349.long >}}**
  {{< var c.spa349.desc >}}
- **{{< var c.spa394.long >}}**
  {{< var c.spa394.desc >}}  
- **{{< var c.spa412.long >}}**
  {{< var c.spa412.desc >}}
- **{{< var c.spa418.long >}}**
  {{< var c.spa418.desc >}}
- **{{< var c.spa421.long >}}**
  {{< var c.spa421.desc >}}
- **{{< var c.spa428.long >}}**
  {{< var c.spa428.desc >}}
- **{{< var c.spa431.long >}}**
  {{< var c.spa431.desc >}}
- **{{< var c.spa432.long >}}**
  {{< var c.spa432.desc >}}
- **{{< var c.spa442.long >}}**
  {{< var c.spa442.desc >}}
- **{{< var c.spa443.long >}}**
  {{< var c.spa443.desc >}}  
- **{{< var c.spa444.long >}}**
  {{< var c.spa444.desc >}}
- **{{< var c.spa446.long >}}**
  {{< var c.spa446.desc >}}
- **{{< var c.spa451.long >}}**
  {{< var c.spa451.desc >}}
- **{{< var c.spa455.long >}}**
  {{< var c.spa455.desc >}}
- **{{< var c.spa457.long >}}**
  {{< var c.spa457.desc >}}
- **{{< var c.spa458.long >}}**
  {{< var c.spa458.desc >}}
- **{{< var c.spa475.long >}}**
  {{< var c.spa475.desc >}}
- **{{< var c.spa476.long >}}**
  {{< var c.spa476.desc >}}
- **{{< var c.spa464.long >}}**
  {{< var c.spa464.desc >}}
- **{{< var c.spa494.long >}}**
  {{< var c.spa494.desc >}}
