<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Course Catalog 2022-2023 – 25&nbsp; DEPARTMENTAL PROGRAMS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../catalog_sections/28_reserve_officer_training_corps_rendered.html" rel="next">
<link href="../catalog_sections/26_academic_programs.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../catalog_sections/26_academic_programs.html">COURSES OF INSTRUCTION</a></li><li class="breadcrumb-item"><a href="../catalog_sections/27_departmental_programs_rendered.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DEPARTMENTAL PROGRAMS</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">
      Course Catalog 2022-2023
      </a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PREFACE</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">INTRODUCTORY RESOURCES</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/01_mission_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">MISSION STATEMENT OF THE COLLEGE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/02_fast_facts_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">FAST FACTS</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">ACADEMIC RESOURCES</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/03_academic_calendar_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">2022–2023 ACADEMIC CALENDAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/04_education_program_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">THE ACADEMIC CALENDAR</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/05_may_term_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">MAY TERM (OPTIONAL)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/06_coe_plan_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">COE PLAN</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/07_graduation_requirements_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">GRADUATION REQUIREMENTS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/08_areas_of_study_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">AREAS OF STUDY</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/09_academic_advising_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">ACADEMIC ADVISING</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/10_first_year_experience_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">FIRST-YEAR EXPERIENCE</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/11_writing_emphasis_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">WRITING EMPHASIS COURSES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/12_general_education_courses_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">GENERAL EDUCATION COURSES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/13_special_programs_and_opportunities_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">SPECIAL PROGRAMS AND OPPORTUNITIES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/14_off_campus_study_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">OFF-CAMPUS STUDY</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">CAMPUS RESOURCES</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/15_campus_resources_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">CAMPUS RESOURCES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/16_student_life_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">STUDENT LIFE</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">COLLEGE REGULATIONS</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/17_effective_catalog_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">EFFECTIVE CATALOG</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/19_class_designation_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">CLASS DESIGNATION</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/20_registration_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">REGISTRATION</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/21_academic_integrity_policy_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">ACADEMIC INTEGRITY POLICY</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/22_academic_standing_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">ACADEMIC STANDING</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/23_transcript_evaluation_policies_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">TRANSCRIPT EVALUATION POLICIES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/24_ferpa_rights_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">STUDENT NOTIFICATION OF RIGHTS UNDER FERPA</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">COURSES OF INSTRUCTION</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/26_academic_programs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">ACADEMIC PROGRAMS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/27_departmental_programs_rendered.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DEPARTMENTAL PROGRAMS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/28_reserve_officer_training_corps_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">RESERVE OFFICER TRAINING CORPS</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">FINANCIAL RESOURCES</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/29_financial_information_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">FINANCIAL INFORMATION</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/30_financial_aid_and_scholarship_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">FINANCIAL AID AND SCHOLARSHIPS</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">ADDITIONAL RESOURCES</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/31_directories_rendered.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">DIRECTORIES</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../catalog_sections/32_campus_map.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">CAMPUS MAP</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#accounting-managerial" id="toc-accounting-managerial" class="nav-link active" data-scroll-target="#accounting-managerial"><span class="header-section-number">25.1</span> ACCOUNTING, MANAGERIAL</a></li>
  <li><a href="#accounting-public" id="toc-accounting-public" class="nav-link" data-scroll-target="#accounting-public"><span class="header-section-number">25.2</span> ACCOUNTING, PUBLIC</a></li>
  <li><a href="#african-american-studies" id="toc-african-american-studies" class="nav-link" data-scroll-target="#african-american-studies"><span class="header-section-number">25.3</span> African American Studies</a></li>
  <li><a href="#anthropology-minor-only" id="toc-anthropology-minor-only" class="nav-link" data-scroll-target="#anthropology-minor-only"><span class="header-section-number">25.4</span> ANTHROPOLOGY (Minor Only)</a></li>
  <li><a href="#art-and-art-history" id="toc-art-and-art-history" class="nav-link" data-scroll-target="#art-and-art-history"><span class="header-section-number">25.5</span> ART AND ART HISTORY</a></li>
  <li><a href="#art-history" id="toc-art-history" class="nav-link" data-scroll-target="#art-history"><span class="header-section-number">25.6</span> Art History</a></li>
  <li><a href="#sec-asian-studies" id="toc-sec-asian-studies" class="nav-link" data-scroll-target="#sec-asian-studies"><span class="header-section-number">25.7</span> Asian Studies</a></li>
  <li><a href="#athletic-training" id="toc-athletic-training" class="nav-link" data-scroll-target="#athletic-training"><span class="header-section-number">25.8</span> Athletic Training</a></li>
  <li><a href="#biochemistry-collateral-major" id="toc-biochemistry-collateral-major" class="nav-link" data-scroll-target="#biochemistry-collateral-major"><span class="header-section-number">25.9</span> Biochemistry (Collateral Major)</a></li>
  <li><a href="#biology" id="toc-biology" class="nav-link" data-scroll-target="#biology"><span class="header-section-number">25.10</span> Biology</a></li>
  <li><a href="#business-administration-and-economics" id="toc-business-administration-and-economics" class="nav-link" data-scroll-target="#business-administration-and-economics"><span class="header-section-number">25.11</span> Business Administration and Economics</a></li>
  <li><a href="#sec-accounting" id="toc-sec-accounting" class="nav-link" data-scroll-target="#sec-accounting"><span class="header-section-number">25.12</span> Accounting</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../catalog_sections/26_academic_programs.html">COURSES OF INSTRUCTION</a></li><li class="breadcrumb-item"><a href="../catalog_sections/27_departmental_programs_rendered.html"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DEPARTMENTAL PROGRAMS</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DEPARTMENTAL PROGRAMS</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="accounting-managerial" class="level2" data-number="25.1">
<h2 data-number="25.1" class="anchored" data-anchor-id="accounting-managerial"><span class="header-section-number">25.1</span> ACCOUNTING, MANAGERIAL</h2>
<p>See <a href="#sec-accounting" class="quarto-xref"><span>Section 25.12</span></a></p>
</section>
<section id="accounting-public" class="level2" data-number="25.2">
<h2 data-number="25.2" class="anchored" data-anchor-id="accounting-public"><span class="header-section-number">25.2</span> ACCOUNTING, PUBLIC</h2>
<p>See <a href="#sec-accounting" class="quarto-xref"><span>Section 25.12</span></a></p>
</section>
<section id="african-american-studies" class="level2" data-number="25.3">
<h2 data-number="25.3" class="anchored" data-anchor-id="african-american-studies"><span class="header-section-number">25.3</span> African American Studies</h2>
<p>Rodgers (Administrative Coordinator).</p>
<p>The African American Studies major offers students the opportunity to study African American culture through an interdisciplinary approach. Students take courses in areas such as literature, history, and sociology in order to gain a more complete understanding of the major figures and movements that helped define the culture.</p>
<section id="african-american-studies-major" class="level3" data-number="25.3.1">
<h3 data-number="25.3.1" class="anchored" data-anchor-id="african-american-studies-major"><span class="header-section-number">25.3.1</span> African American Studies Major</h3>
<p>A major in African American studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.</p>
<ol type="1">
<li>AAM 107 Intro to African American Studies</li>
<li>+++MISSING INFO: c.aam/eng137.long +++</li>
<li>HIS 347 African American History</li>
<li>One of the following:</li>
</ol>
<ul>
<li>HIS 145 History of United States to 1865</li>
<li>HIS 155 History of United States since 1865</li>
<li>HIS 227 American Civil War</li>
</ul>
<ol start="5" type="1">
<li>Five additional courses, at least three of which are numbered 200 or above, chosen from the following: -<strong>(a)</strong> Elective courses:
<ul>
<li>AAM 217 Sport and Black Culture</li>
<li>AAM 287 Topics in African American Studies</li>
<li>AAM 367 Topics in AfricanAmericanLiterature</li>
<li>AAM 387 Adv Topics in African American Stud</li>
<li>+++MISSING INFO: c.aam447/457.long +++</li>
<li>AAM 467 Seminar in African American Lit</li>
<li>AAM 494 Internship in African American Stds</li>
<li>COM 236 Intercultural Communication</li>
<li>COM 357 Sex, Race, &amp; Gender in Media</li>
<li>EDU 187 Human Relations</li>
<li>HIS 145 History of United States to 1865</li>
<li>HIS 155 History of United States since 1865</li>
<li>HIS 227 American Civil War</li>
<li>MU 157 Introduction to Jazz History</li>
<li>SOC 247 Sociology of Race</li>
</ul></li>
</ol>
<p>-<strong>(b)</strong> Elective courses (when topic is appropriate): These courses can count toward the major or minor as determined by the African American Studies administrative coordinator. - ARH 297 Topics in Art History: US Pluralism - COM 157 Introduction to Media Analysis - COM 161 Visual Rhetoric - COM 361 Communication &amp; Social Change - ENG 107 Exploring Literature:US Pluralism - ENG 207 Gender &amp; Lit:US Pluralism - ENG 347 Study in Modern or Contemp Amer Lit - ENG 394 Directed Learning in English - HIS 297 Women in America - HIS 444 Ind Study-History - HIS 472 Seminar American History I - HIS 473 Seminar American History II - SOC 237 Topics in Sociology:U S Pluralism - SOC 464 Capstone Seminar in Sociology - THE 488 Special Topics in THE/ FLM</p>
<ol start="6" type="1">
<li>AAM 444 Ind Study-Afr-Am St (completed during the senior year)</li>
</ol>
</section>
<section id="african-american-studies-minor" class="level3" data-number="25.3.2">
<h3 data-number="25.3.2" class="anchored" data-anchor-id="african-american-studies-minor"><span class="header-section-number">25.3.2</span> African American Studies Minor</h3>
<ol type="1">
<li>AAM 107 Intro to African American Studies<br>
</li>
<li>+++MISSING INFO: c.aam/eng137.long +++</li>
<li>HIS 347 African American History<br>
</li>
<li>One of the following:</li>
</ol>
<ul>
<li>HIS 145 History of United States to 1865</li>
<li>HIS 155 History of United States since 1865</li>
<li>HIS 227 American Civil War</li>
</ul>
<ol start="5" type="1">
<li>Two additional courses from either list <strong>5a</strong> or, when appropriate, <strong>5b</strong> as listed above for the major</li>
</ol>
</section>
<section id="courses-in-african-american-studies" class="level3" data-number="25.3.3">
<h3 data-number="25.3.3" class="anchored" data-anchor-id="courses-in-african-american-studies"><span class="header-section-number">25.3.3</span> COURSES IN AFRICAN AMERICAN STUDIES</h3>
<ul>
<li><strong>AAM 107 Intro to African American Studies</strong> What is African American culture, and what accounts for its cultural distinctions? This course introduces students to the study of African American culture and the field of African American Studies. through an interdiciplinary approach (literature, history, music, art and film) students will examine central themes and key debates pertinent to African American culture and history from its beginning to present.</li>
<li><strong>AAM 137 African American Literature</strong> Reading and discussion of the writings of African Americans, with emphasis on the 20th century. May include some relevant writings on African Americans by other groups. Study of the artistic values and of the social and cultural significance of these writings. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different.</li>
<li><strong>AAM 217 Sport and Black Culture</strong> Examines through cultural analysis the complex relationships between sport and Black culture.&nbsp; This course addresses the way sport has evolved from being merely a physical activity to a cultural expression in Black communities.&nbsp; This course emphasizes the historical patterns and current conditions of Blacks; participation in sport through various articles, videos, and books.&nbsp; The course also examines how many Black people have used sport as a means of resistance, survival, and social mobility. Students learn to analyze cultural expression, to understand race and its continuing impact in American life, and to understand how various sports pursuits by Black athletes are invested with multiple meanings.&nbsp;Major topics and themes covered include: the concept of race, Black culture, the historical presence of Black athletes in sport, their current impact, and their dominance in certain sports.</li>
<li><strong>AAM 227 Blackness &amp; Identity in America</strong> Gathers a wide range of scholarship about race and identity to explore what race is, why it matters, racial dynamics in organizations, and how best to address them. Students will explore questions of identity, privilege, ethnicity, gender, and class. In this course, “race” is reviewed as a shorthand for the interconnected complexity of race, ethnicity, culture, and color, and will be carefully analyzed to distinguish among such terms and ideas. Students will critically analyze the social construct and the popular understandings of race and identity as reinforced through cultural institutions. Students will understand and evaluate the foundational concepts and theories of race and identity and synthesize their knowledge through research, presentation, and writing.</li>
<li><strong>AAM 287 Topics in African American Studies</strong> Examines an important theme or subject specific to African American experiences and culture. Content varies and is determined by the instructor. Students learn to understand African American experiences in context, to analyze texts and events from multiple disciplinary perspectives, and to write in clear, analytical prose. May be taken more than once for credit, provided the topics are substantially different.</li>
<li><strong>AAM 367 Topics in AfricanAmericanLiterature</strong> None</li>
<li><strong>AAM 387 Adv Topics in African American Stud</strong> Examines an important theme or subject specific to African American experiences and culture. Content varies and is determined by the instructor. Students learn to understand African American experiences in context, to analyze texts and events from multiple disciplinary perspectives, and to write in clear, analytical prose. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to African American Studies (AAM-107) or consent of instructor.</li>
<li><strong>AAM 444 Ind Study-Afr-Am St</strong> Study of individually chosen research topics in African American studies under the direction of a faculty member in the area. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: Introduction to African American Studies (AAM-107) or African American Literature (AAM-137); consent of African American Studies administrative coordinator and submission of a written proposal for a project.</li>
<li><strong>+++MISSING INFO: c.aam447/457.long +++</strong> +++MISSING INFO: c.aam447/457.desc +++</li>
<li><strong>AAM 467 Seminar in African American Lit</strong> Intensive study of selected works and subjects in African American literature. May be taken more than once, with consent of African American Studies administrative coordinator, provided the topics are substantially different. Prerequisites: junior standing and The Art of Literary Research (ENG-301). May be taken more than once.</li>
<li><strong>AAM 494 Internship in African American Stds</strong> None</li>
</ul>
</section>
</section>
<section id="anthropology-minor-only" class="level2" data-number="25.4">
<h2 data-number="25.4" class="anchored" data-anchor-id="anthropology-minor-only"><span class="header-section-number">25.4</span> ANTHROPOLOGY (Minor Only)</h2>
<p>Fairbanks, Ziskowski</p>
<section id="anthropology-minor" class="level3" data-number="25.4.1">
<h3 data-number="25.4.1" class="anchored" data-anchor-id="anthropology-minor"><span class="header-section-number">25.4.1</span> Anthropology Minor</h3>
<ol type="1">
<li><strong>One</strong> of the following:</li>
</ol>
<ul>
<li>ANT 109 Intro to Archaeology:Method &amp; Thry</li>
<li>ANT 116 Cultural Anthropology</li>
</ul>
<ol start="2" type="1">
<li>ANT 215 Ethnographic Methods</li>
<li><strong>One</strong> of the following:</li>
</ol>
<ul>
<li>ANT 284 Topics in Anthropology/Archaeology</li>
<li>ANT 286 Topics in Anthropology:NWP</li>
<li>ANT 288 Topics Anthropology/Archaeology:DWP</li>
</ul>
<ol start="4" type="1">
<li>ANT 450 Anthropological Theory</li>
<li><strong>One</strong> of the following:</li>
</ol>
<ul>
<li>ANT 484 AdvTop: Anthropology or Archaeology</li>
<li>ANT 486 Advanced Topics in Anthropology:NWP</li>
<li>ANT 488 Adv Top Anthro/Archaeo:DWP</li>
</ul>
<ol start="6" type="1">
<li>One additional anthropology course Students must take at least one course focused on archaeology and one focused on anthropology. The following courses do <strong>not</strong> satisfy any of the requirements for a minor in anthropology:</li>
</ol>
<ul>
<li>ANT 444 Independent Study: Anthropology</li>
<li>ANT 474 Research Participation:Anthropology</li>
<li>ANT 494 Internship in Anthropolgy</li>
</ul>
</section>
<section id="courses-in-anthropology" class="level3" data-number="25.4.2">
<h3 data-number="25.4.2" class="anchored" data-anchor-id="courses-in-anthropology"><span class="header-section-number">25.4.2</span> Courses in Anthropology</h3>
<ul>
<li><strong>ANT 109 Intro to Archaeology:Method &amp; Thry</strong> An introduction to the theoretical approaches and field methodologies of archaeology. The goal of this class is to familiarize the student with the history and theoretical frameworks of archaeology, in addition to the scientific methods with which material culture is collected, investigated, and evaluated. Major topics and themes covered in this class include: archaeological theory, excavation and survey, artifact analysis, death, social systems, economy, religion, and ethical practices in cultural heritage management.</li>
<li><strong>ANT 115 Ancient Greece:Hist as Archaeology</strong> Explores the various ways in which archaeology can inform our understanding of ancient Greek history by visiting the monuments, museums, and archaeological sites in modern Greece. The course emphasizes the combination of the historical textual evidence and the ancient physical evidence to enrich our understanding of Greek social, political, and cultural history. THe course also involves an examination of the evolution of ancient institutions and practices that range from the rise of the Athenian democracy, to the first theatrical productions of comedy and tragedy, to the establishment of the ancient Olympics. Archaeological theory, archaeiligical practice, and historical process constitute the nexus around which the course revolves. (Offered May Term only)</li>
<li><strong>ANT 116 Cultural Anthropology</strong> An introduction to cultural anthropology, presenting its place within the broader discipline of anthropology and outlining its characteristic methodological and theoretical approaches to the study of human life. The course emphasizes the diversity of approaches to common human experiences in a variety of cultural contexts.</li>
<li><strong>ANT 125 Art &amp; Archaeology Classical World</strong> A survey of the art, architecture, and archaeological remains of the Greek and Roman civilizations from early Aegean Bronze Age cultures to the fall of the Roman empire.</li>
<li><strong>ANT 215 Ethnographic Methods</strong> An introduction to ethnographic research methods, presenting a number of tools for collecting and analyzing ethnographic data. The course emphasizes the relationship between research questions and the methodological tools used by anthropologists to study those questions. Prerequisite: Cultural Anthropology (ANT-116) or consent of instructor.</li>
<li><strong>ANT 284 Topics in Anthropology/Archaeology</strong> A focused examination of an anthropological theme, theory or research method. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different.</li>
<li><strong>ANT 286 Topics in Anthropology:NWP</strong> A focused examination of an anthropological theme, theory or research method. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different.</li>
<li><strong>ANT 288 Topics Anthropology/Archaeology:DWP</strong> A focused examination of an archaeological theme, theory or research method. Content varies and is determined by the instructor. May be taken more than once for credit, provided the topics are substantially different.</li>
<li><strong>ANT 415 Ancient Greek Pottery Studies</strong> Considers Greek ceramics from both scientific and iconological perspectives. Students study issues of production, construction and distribution and then look at Greek pottery iconographically, focusing on the major stylistic periods but emphasizing regional variations through Greece. Discussions of connoisseurship and themes prevalent in Greek vase-painting such as death, myth, and gender round out the course’s survey of evidence. Prerequisite: consent of instructor.</li>
<li><strong>ANT 444 Independent Study: Anthropology</strong> Independent study under faculty guidance of a research problem chosen by the student. May be taken for an X status grade with consent of instructor prior to registration. This course does not satisfy any of the requirements for a minor in anthropology. Prerequisites: Previous or concurrent enrollment in Anthropology Theory (ANT-450) and consent of department chair. (Offered by arrangement)</li>
<li><strong>ANT 450 Anthropological Theory</strong> An examination of the historical development of anthropological theory, emphasizing American, British and French traditions from the 19th century through the present. Prerequisite: Cultural Anthropology (ANT-116) or consent of instructor.</li>
<li><strong>ANT 474 Research Participation:Anthropology</strong> Individual or group investigation with a faculty member on a research topic or topics of mutual interest. The student must obtain approval for a specific project and make necessary arrangements prior to the term of registration for the course. May be taken for an X status grade with consent of instructor prior to registration. This course does not satisfy any of the requirements for a minor in anthropology. Prerequisites: Cultural Anthropology (ANT-116) and consent of the instructor. (Offered by arrangement)</li>
<li><strong>ANT 484 AdvTop: Anthropology or Archaeology</strong> Same as ANT-284, except at an advanced level. Prerequisite: Introduction to Archaeology (ANT-109) or Cultural Anthropology (ANT-116) or consent of instructor.</li>
<li><strong>ANT 486 Advanced Topics in Anthropology:NWP</strong> Same as ANT-286, except at an advanced level. Prerequisite: Cultural Anthropology (ANT-116) or consent of instructor.</li>
<li><strong>ANT 488 Adv Top Anthro/Archaeo:DWP</strong> Same as ANT-228, except at an advanced level. Prerequisite: Introduction to Archaeology (ANT-109) or Cultural Anthropology (ANT-116) or consent of instructor.</li>
<li><strong>ANT 494 Internship in Anthropolgy</strong> Placement with a career-related organization. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a minor in anthropology. Prerequisites: declared minor in anthropology, junior standing and consent of department chair. (Offered by arrangement)</li>
</ul>
</section>
</section>
<section id="art-and-art-history" class="level2" data-number="25.5">
<h2 data-number="25.5" class="anchored" data-anchor-id="art-and-art-history"><span class="header-section-number">25.5</span> ART AND ART HISTORY</h2>
<p>Cohen, Goodson, Knight-Lueth, Rogers (Chair), Thompson.</p>
<p>A major in art or art history is designed to provide a foundation in theory and practice. Students focus on making and meaning, and gain an understanding of visual and contextual history and analysis. In studying the formal, technical and conceptual aspects of art and art history, students learn to communicate effectively to broad and diverse audiences.</p>
<p>An art major may also complete an art history minor, but only two courses may count toward both the major and the minor.</p>
<section id="art-major" class="level3" data-number="25.5.1">
<h3 data-number="25.5.1" class="anchored" data-anchor-id="art-major"><span class="header-section-number">25.5.1</span> Art Major</h3>
<p>A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in art.</p>
<ol type="1">
<li>ARH-128 Introduction to Art History</li>
<li>Two 100-level ART- courses</li>
<li>Four of the following:
<ul>
<li>ART 201 Focus Course: Creative Process</li>
<li>ART 202 Focus Course: Portfolio Development</li>
<li>ART 203 Focus: ContemporaryArtisticPractice</li>
<li>ART 211 Focus:ArtistStatements</li>
<li>ART 212 Focus Course: Artist Websites</li>
<li>ART 213 Focus Course: Critique</li>
<li>ART 291 Focus Course: Topics in Studio Art</li>
</ul></li>
</ol>
<p>The Focus Course requirement is considered a coherent set of experiences that can be tailored to student needs. The completion of four Focus Courses is considered as a single course credit with respect to Graduation Requirements (see <a href="07_graduation_requirements_rendered.html" class="quarto-xref"><span>Chapter 7</span></a> ).</p>
<ol start="4" type="1">
<li>Two 300-level ART- Courses</li>
<li>One additional 200-level Art History course</li>
<li>One of the following:
<ul>
<li>ARH 307 Modern and Contemporary Art</li>
<li>ARH 310 Contemporary Art, Theory &amp;Criticism</li>
</ul></li>
<li>Junior Review</li>
</ol>
<p>A studio portfolio presentation for art majors that is assessed by the art and art history faculty. Students must complete 20 course credits to be eligible for the junior review, and it must be completed prior to enrolling in ART-464 Senior Seminar I.</p>
<ol start="8" type="1">
<li>ART 464 Senior Seminar I</li>
<li>ART 474 Senior Seminar II &amp; Senior Exhibit</li>
</ol>
<p>In addition to the course requirements, a student must participate in a Junior Review with the art and art history department’s faculty. This must be completed no later than April of the junior year. The material submitted at the Review will be related to the senior graduation requirement, which is a demonstration of proficiency through a public exhibition of artwork, including portfolio of slides, exhibit announcement, and résumé.</p>
<p><strong>NOTE</strong>: Scheduling may be planned to allow at least one term of study off-campus at one of the approved foreign or domestic programs. With departmental approval, courses from these programs may count as 100 or 200 level courses.</p>
</section>
<section id="art-minor" class="level3" data-number="25.5.2">
<h3 data-number="25.5.2" class="anchored" data-anchor-id="art-minor"><span class="header-section-number">25.5.2</span> Art Minor</h3>
<p>A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in art.</p>
<ol type="1">
<li>ARH 128 Introduction to Art History</li>
<li>Two 100-level ART- courses</li>
<li>Two 300-level ART- courses</li>
<li>One 200-level ARH- course</li>
</ol>
<p>Further information for all these requirements and programs is available from the Art and Art History Department.</p>
</section>
<section id="courses-in-art" class="level3" data-number="25.5.3">
<h3 data-number="25.5.3" class="anchored" data-anchor-id="courses-in-art"><span class="header-section-number">25.5.3</span> Courses in Art</h3>
<p><strong>100-level courses</strong> (<em>except ART-130, see below</em>) are open to any student and may offer the opportunity to explore two or more areas of art making in a studio environment. ART-130 Art in the Elementary Classroom does not satisfy any of the requirements for a major or minor in Art or Art History. It also does not count as a 100-level art course needed for some courses as a prerequisite.</p>
<ul>
<li><strong>ART101 Art Appreciation</strong> None</li>
<li><strong>ART 102 Sculpture: Material Investigations</strong> Focuses on how material choices inform meaning. Students will use a variety of traditional and non-traditional materials to make sculptural art objects.</li>
<li><strong>ART 103 Ceramic Sculpture</strong> Provides instruction on the creation of hand-built ceramic sculptures. Projects will utilize pinch, coil building, soft and stiff slab construction, and additive and subtractive processes.</li>
<li><strong>ART 105 Narrative Ceramics</strong> Studies the history and evolution of ceramics as a storytelling medium. Projects will include tile-making, coil-building, surface decoration, and sculptural techniques as a means to explore how artists have used clay to create compelling narratives.</li>
<li><strong>ART 115 Drawing</strong> Introduces a variety of drawing media, including graphite, charcoal, brush and ink, pastels, and collage. Students are challenged to observe the visual world around them and to respond to that observation with interpretive choices in mark-making and composition to produce visual expression. Media may include graphite, charcoal, brush and ink, pastels, and collage.</li>
<li><strong>ART 125 Painting</strong> Introduces paint media to represent, amplify, and interpret the world. Students are also encouraged to discover the possibilities of color, shape, texture and mark-making.</li>
<li><strong>ART 130 Art in the Elementary Classroom</strong> Provides an overview of the role of art in the elementary curriculum. Students learn to incorporate art activities into other content areas and gain an understanding of the objective of elementary classes taught by elementary art specialist teachers. This course does not satisfy the College’s general education fine arts core group requirement nor does it satisfy major or minor requirements or prerequisites for Art or Art History. Prerequisite: admission to the Education Program or approval of the education department. (0.5 course credit)</li>
<li><strong>ART 131 Scultpure: Do, Undo, Redo</strong> Practices the inherent creative aspects of making, unmaking and remaking in response to these various states of transformation. Artworks are made using clay and other sculptural materials while documenting the exploratory processes through drawing, photography and more.</li>
<li><strong>ART 135 Ceramics: Form, Function &amp; Meaning</strong> Focuses on the creation of wheel thrown and handbuilt objects within the context of a social and cultural lens. Explores the relationship between making and meaning in the 21st century. Projects focus on fuctional work and its uses.</li>
<li><strong>ART 145 Digital Studio</strong> Explores contemporary digital imaging and design. Students produce a series of studio projects ranging from digital photography, collage, gif animation, vector graphics, and two-dimensional design. Includes introductory-level instruction of digital cameras and Adobe Creative Suite: Lightroom, Photoshop, Illustrator.</li>
<li><strong>ART 150 Time Based Media</strong> Explores the aesthetic and experiential qualities of time. The course includes readings, discussions, and screenings of historical and contemporary works plus hands-on studio projects using video, sound, performance, installation, and more. Includes introductory-level instruction in digital cameras and Adobe Lightroom and Premiere Pro. Through media production, students cultivate a range of technical skills plus a critical understanding of media culture.</li>
<li><strong>ART 151 Layers of Meaning</strong> Pursues meaning through multiplicity of imagery. Some work may be done in collage, but other materials and techniques, such as drawing, painting, and digital art, are used to juxtapose and layer imagery and meaning.</li>
<li><strong>ART 155 Photography: Light Writing</strong> Examines the ways that a photographic image can be viewed and interpreted. The course includes readings and research on the masters of photography. Technical skills include historic black and white analog photography including manual camera controls, film and print processing.</li>
<li><strong>ART 175 Printmaking</strong> Focuses on traditional and contemporary printmaking techniques, introducing students to the fundamentals of materials including paper, ink, presses, and image processing. This course explores the development of technical, compositional, and conceptual skills through the evolution of printmaking’s history of multiplicity.</li>
<li><strong>ART 191 Topics in Studio Art</strong> Focuses on a specific theme or topic. Topics vary. May be taken more than once for credit, provided the topics are substantially different.</li>
</ul>
<p><strong>Focus Courses</strong></p>
<p>Focus Courses are seven-week courses designed to prepare the student for a serious artistic practice.</p>
<ul>
<li><strong>ART-201 Focus Course: Creative Process</strong> Applies the tools and methods of creative processes. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Students propose, iterate, and produce an object or set of objects in an exploration of their own creative process. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-202 Focus Course: Portfolio Development</strong> Prepares students for developing a portfolio that reflects the breadth and skills of their own artistic practice and production. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-203 Focus Course: Contemporary Artistic Practice</strong> Highlights the art, writings, routines and habits of contemporary artists and practitioners. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-211 Focus Course: Artist Statements/Artist Talks</strong> Guides students through the construction of artist statements and artist talks to present their work to a wider public. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-212 Focus Course: Artist Websites</strong> Guides students through best practices in the process of developing and maintaining a professional website. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-213 Focus Course: Critique</strong> Offers students the opportunity to practice and improve critique skills. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
<li><strong>ART-291 Focus Course: Topics in Studio Art</strong> Focuses on a specific theme or topic. An abbreviated course offered seven weeks of a term designed to prepare the student for a serious artistic practice. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: two ART- courses (each 1.0 course credit) or consent of instructor. (0.25 course credit)</li>
</ul>
<p><strong>300-level courses</strong> offer students the opportunity to expand their technical and conceptual skills at a more advanced level. Courses numbered ART 300–349 are offered without prerequisite and open to any student. Courses numbered ART 350–399 have one or more prerequisites.</p>
<ul>
<li><strong>ART-301 Socially Engaged Art</strong> Invites collaboration with individuals, communities, and institutions in the creation of participatory art. The genre explores social forms such as dinner parties, conversations, and projects that intervene or intersect with real-world systems. Coursework is done collaboratively and independently on projects that critically engage with contemporary issues and explore a variety of contexts. A variety of media will be used as a means to define interests and inform social interventions.</li>
<li><strong>ART-313 Color and Design</strong> Examines the theory and practice of color, with emphasis on the use of color as a compositional element.</li>
<li><strong>ART-315 Installation Art</strong> Creates art environments that offer a unique experience for the viewer. Projects will include research, planning, drafting, and exhibiting artistic creations in spaces across campus and throughout the local community.</li>
<li><strong>ART- 325 Contemporary Photographic Genres</strong> Creates, researches, and analyzes contemporary digital photography. Readings and writings support the weekly production of imagery. Technical skills include camera functions, Adobe Photoshop, and Adobe Lightroom. Cameras and software provided.</li>
<li><strong>ART-328 Art and Industry</strong> Explores the relationship between art, mass production and the steady, habitual effort of making. Topics of inquiry include the Arts and Crafts Movement, the birth of industry and technology, and how 20th and 21st-century artists have responded to the frenzy of mass production and consumerism. Artworks are created using varying methods of mass production such as tile making, mold making and surface decoration techniques as a way to explore repetitive modes of making.</li>
<li><strong>ART-330 Methods of Teaching Art K–12</strong> Includes discussion, lecture, and studio work on campus, as well as experience in public school classes off campus. This course does not satisfy the College’s general education fine arts core group requirement nor does it satisfy major or minor requirements or prerequisites for Art of Art History. Prerequisite: art major or minor and admission to the Education Program.</li>
<li><strong>ART-331 Open Studio</strong> Provides an opportunity for independent work in the studio with a midterm and final critique. P/NP basis only. May be taken more than once. This course does not satisfy any of the requirements for a major or minor in art. Prerequisites: Ceramics: Form, Function, &amp; Meaning (ART-135) or consent of instructor.</li>
<li><strong>ART-352 Mark Making</strong> Offers instruction on materials and techniques that involve mark making. These may include painting and drawing on various surfaces, or digital painting. Through guided projects and independent work, students explore the connections between form and expression, with the aim of developing a visual language that is uniquely their own. Prerequisite: any 100-level ART- course.</li>
<li><strong>ART 360 Advanced 3D</strong> Focuses on the conceptual, aesthetic, and technical skills necessary to create more advanced and sophisticated artworks. Designed to build upon the foundations provided in beginning-level Ceramics and Sculpture classes. Prerequisite: any 100-level ART course.</li>
<li><strong>ART-361 Documentary</strong> Explores theory and practice of documentary filmmaking through readings, research projects, screenings, and in-class discussions. Students produce studio projects ranging from short-form documentaries, podcasts, still photography portfolios, and more. Prerequisite: Digital Studio (ART-145), Time-Based Media (ART-150), or with permission by instructor.</li>
<li><strong>ART-363 Graphic Design Studio</strong> Focuses on graphic design and the communication arts industry. Projects use traditional and digital tools, materials and procedures with a focus on finding creative visual solutions to communication problems. Prerequisite: Digital Studio (ART-145), or Workshop: Digital Toolbox (WKS-204), or Workshop: Vector Graphics (WKS-213), or consent of instructor.</li>
<li><strong>ART-364 The Human Form</strong> Focuses on the observation and interpretation of the human form. Working from life, students develop skills in capturing the gesture and form of the body and use those skills to create interpretive and expressive artworks, principally using drawing materials, but also exploring with paint and other materials. Prerequisite any 100-level ART- course.</li>
<li><strong>ART-370 Video Art and Production</strong> Explores the theoretical and technical foundations of video as a visual art medium. Students produce a series of short video projects that are presented during formal critiques, enabling students to cultivate meaningful dialogue about their work. Through production, students develop the technical and professional experience needed to enter the media industry. Prerequisite: Digital Studio (ART-145), Time-Based Media (ART-150), or with permission by instructor.</li>
<li><strong>ART-371 Typography and Design</strong> Investigates the history, theory and practice of letterforms and typography in graphics, advertising, design and visual communication. Projects address principles of typography, letter structure, typeface selection, fundamentals of computer typesetting, and typographic layout. Prerequisite: Digital Studio (ART-145), or Workshop: Digital Toolbox (WKS-204), or Workshop: Vector Graphics (WKS-213), or consent of instructor.</li>
<li><strong>ART-373 Screen Printing</strong> Utilizes silkscreen printing as a medium that can be integrated with photography, digital imagery, and three-dimensional objects. Course offers an exploration of the formal elements of design with an emphasis on the use of color. Coursework includes studio production, lectures, demonstrations and critiques. Prerequisite any 100-level ART- course.</li>
<li><strong>ART-374 Multiples in Printmaking</strong> Utilizes intaglio and lithography as a medium to explore artistic vision, personal imagery and design. Using the process of intaglio, students investigate the states of development of an image by printing multiple variations of the plate. Using the process of lithography, students learn how to create a limited edition of prints. Prerequisite any 100-level studio ART- course.</li>
<li><strong>ART-391 Advanced Topics in Studio Art</strong> See also Art History (ARH-391), p.&nbsp;92 Focuses on a specific advanced studio art theme or topic. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: any 100- or 200-level ART- course or consent of instructor.</li>
<li><strong>ART-394 Directed Studies in Art</strong> Investigates a topic in studio art selected by the student and instructor to fit the student’s particular interests and educational needs. May be taken more than once for credit. Prerequisites: junior standing and consent of department chair.</li>
</ul>
<p><strong>400-level courses</strong></p>
<ul>
<li><strong>ART-444 Independent Study</strong> Focuses on a topic for independent work on a selected project under the direction of a faculty member of the department. Prerequisite: consent of instructor.</li>
<li><strong>ART-464 Senior Seminar I</strong> Prepares students for advanced research in studio art. Emphasis is on preparation of work toward the senior exhibit. Only art majors are admitted to this course. Materials fee (where applicable) should be discussed with instructor. Prerequisite: declared major in art and successful completion of Junior Review.</li>
<li><strong>ART-474 Senior Seminar II &amp; Senior Exhibition</strong> Prepares students for advanced research in studio art. Emphasis is on preparation of work toward the senior exhibit. Only art majors are admitted to this course. Materials fee (where applicable) should be discussed with instructor. Prerequisite: successful completion of Senior Seminar I (ART-464).</li>
<li><strong>ART-494 Internship in Art</strong> Investigates an area of interest related to the major, through voluntary field placement supervised by a faculty member of the art and art history department. A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisites: declared major in art, junior standing, and consent of department chair.</li>
</ul>
</section>
</section>
<section id="art-history" class="level2" data-number="25.6">
<h2 data-number="25.6" class="anchored" data-anchor-id="art-history"><span class="header-section-number">25.6</span> Art History</h2>
<section id="art-history-major" class="level3" data-number="25.6.1">
<h3 data-number="25.6.1" class="anchored" data-anchor-id="art-history-major"><span class="header-section-number">25.6.1</span> Art History Major</h3>
<p>A grade of “C” (2.0) or higher must be earned in all courses counted toward a major in art history. An Art History major may also complete an Art minor, but only two courses may count toward both the major and the minor.</p>
<ol type="1">
<li>ARH 128 Introduction to Art History<br>
</li>
<li>Two 200-level ARH courses<br>
</li>
<li>Two additional courses approved by the department, chosen from the following:
<ul>
<li>Courses in Art History (ARH-___)<br>
</li>
<li>ANT 125 Art &amp; Archaeology Classical World<br>
</li>
<li>HIS 318 Topics in History :Div West Persp<br>
</li>
<li>COM 161 Visual Rhetoric<br>
</li>
<li>FLM 225 Film History<br>
</li>
<li>COM 357 Sex, Race, &amp; Gender in Media<br>
</li>
</ul></li>
<li>One of the following
<ul>
<li>ARH 307 Modern and Contemporary Art<br>
</li>
<li>ARH 310 Contemporary Art, Theory &amp;Criticism<br>
</li>
</ul></li>
<li>ARH 464 Senior Seminar I<br>
</li>
<li>ARH 474 Senior Seminar II<br>
</li>
<li>One 100- ART course<br>
</li>
<li>One 300-level ART course</li>
</ol>
<p>note: Scheduling may be planned to allow at least one term of study off-campus at one of the approved foreign or domestic programs. With departmental approval, up to three courses from these programs may count toward either the two 200-level courses in item 2 or the two additional courses in item 3.</p>
<p>Students interested in art history or visual culture at the graduate level should complete Intermediate French I (FRE-215).</p>
</section>
<section id="art-history-minor" class="level3" data-number="25.6.2">
<h3 data-number="25.6.2" class="anchored" data-anchor-id="art-history-minor"><span class="header-section-number">25.6.2</span> Art History Minor</h3>
<p>A grade of “C” (2.0) or higher must be earned in all courses counted toward a minor in art history.</p>
<ol type="1">
<li>ARH 128 Introduction to Art History<br>
</li>
<li>Three additional art history courses, one of which must be ARH-200 or above. Can also include one of the following:
<ul>
<li>ANT 125 Art &amp; Archaeology Classical World<br>
</li>
<li>HIS 318 Topics in History :Div West Persp<br>
</li>
<li>COM 161 Visual Rhetoric<br>
</li>
<li>FLM 225 Film History<br>
</li>
<li>COM 357 Sex, Race, &amp; Gender in Media<br>
</li>
</ul></li>
<li>One of the following
<ul>
<li>ARH 307 Modern and Contemporary Art</li>
<li>ARH 310 Contemporary Art, Theory &amp;Criticism<br>
</li>
</ul></li>
<li>One 100- or 300-level ART- course</li>
</ol>
</section>
<section id="courses-in-art-history" class="level3" data-number="25.6.3">
<h3 data-number="25.6.3" class="anchored" data-anchor-id="courses-in-art-history"><span class="header-section-number">25.6.3</span> COURSES IN ART HISTORY</h3>
<ul>
<li>ARH 106 World Art<br>
Traces key themes in art from a global perpective, focusing on the ways that cultures and civilizations across time have visually expressed social, religious and political values. Cross-cultural themes may include: religion and spirituality, word and image, violence and death, power and propaganda, gender and society, parks and memorials, and ritual and body decoration.<br>
</li>
<li>ARH 107 Gender and Art<br>
Explores of the ways in which visual culture reflects and projects cultural biases and issues related to gender from prehistory to the modern era. Analyzes how gender identities can be shaped by politics, religion, and culture, as well as the effect of an artist’s sex and/or sexual preferences on subject choices, media, and market values.<br>
</li>
<li>ARH 128 Introduction to Art History<br>
Examines Western art and architecture from prehistory to the later 19th century, with emphasis on the ways in which visual culture both reflects and shapes societies and civilizations. Explores how works of art create and sustain meaning for their original audiences, and how some objects or visual solutions transcend their historical moment and surface throughout time as familiar cultural icons or references.<br>
</li>
<li>ARH 191 Topics in Art History<br>
See also +++MISSING INFO: c.art91.short +++<br>
Focuses on a selected topic or theme in art history or visual culture. Topics vary. May be taken more than once for credit, provided the topics are substantially different.<br>
</li>
<li>ARH 201 Art of the Middle Ages<br>
Explores the art and architecture of the medieval world both chronologically and thematically. The course examines issues such as patronage of the arts, pilgrimage, the cult of saints, the arts as a medium of cultural exchange, and the role of the artist in the Middle Ages. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.<br>
</li>
<li>ARH 218 The World of Renaissance Art<br>
Explores the visual culture of Europe from the 14th through the 16th centuries, focusing on topics such as competition, display, devotion, portraits, the printing revolution, death, and gender issues. Prerequisite: Introduction to Art History (ART-128) or consent of instructor.<br>
</li>
<li>ARH 231 Romanticism, Realism, Impressionism<br>
Focuses on the sweeping transformations in the creation, production and consumption of visual culture in the 19th century. The rapidly changing aesthetics of the dawning modern era generated passionate debates about the creation and reception of art during this period. This course uses these debates as a series of touchstones for understanding the visual and social landscape of the times. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.<br>
</li>
<li>ARH 248 Baroque, Rococo, and Neoclassicism<br>
Focuses on a thematic exploration of the major art movements in the 17 th and 18th centuries, emphasizing the pendulum swings of artistic practice, exploration, and institutional hierarchies. Inclusion of cultural phenomena—the Grand Tour, the Enlightenment, revolutions, and the establishment of academies—factor heavily in this course. Prerequisite: Introduction to Art History (ARH 128) or consent of instructor.<br>
</li>
<li>ARH 268 History of Architecture<br>
Investigates major monuments of architectural history from prehistory to the present day, with an emphasis on formal and conceptual concepts. Key figures, theories, innovations, and functions (both original and altered throughout time) are also discussed. Prerequisite: Introduction to Art History (ARH 128) or consent of instructor.<br>
</li>
<li>ARH 296 Topics in Art History:Global Persp<br>
Focuses on a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.<br>
</li>
<li>ARH 297 Topics in Art History: US Pluralism<br>
Examines a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.<br>
</li>
<li>ARH 298 Topics in Art History:Div West Pers<br>
Studies a selected topic or theme in art history. Topics vary, and may include: Art and Cultural Property; Memory, Environment and Landscape. May be taken more than once for credit, provided the topics are substantially different. Prerequisite: Introduction to Art History (ARH-128) or consent of instructor.<br>
</li>
<li>ARH 307 Modern and Contemporary Art<br>
Traces the development of major artistic movements in the 20th centrury to the more contemporary trends of the 21st century. Topics include: Post-Impressionism, Cubism, Futurism, Surrealism, German Expressionism, Dada, Pop Art, Minimalism, Conceptual Art, Postmodernism, installation, new media, performance, and digital production and distribution. Prerequisite: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.<br>
</li>
<li>ARH 310 Contemporary Art, Theory &amp;Criticism<br>
Investigates issues in contemporary art. Focuses on art of the late 20th and early 21st centuries, considering stylistic, historical and theoretical developments. Prerequisite: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.<br>
</li>
<li>ARH 391 Advanced Topics in Art History<br>
See also {{&lt; var.art291.short  &gt;}}<br>
Focuses on an advanced study of a selected topic or theme in art history. Topics vary. May be taken more than once for credit, provided the topics are substantially different. Prerequisites: Introduction to Art History (ARH-128) and a 200-level ARH- course or consent of instructor.<br>
</li>
<li>ARH 394 Directed Learning in Art History<br>
Investigates topics in art history selected by the student and instructor to fit the student’s particular interests and educational needs. May be taken more than once for credit. Prerequisites: junior standing and consent of department chair.<br>
</li>
<li>ARH 444 Independent Study: Art History<br>
Focuses on independent work on a selected project under the direction of a faculty member of the Art and Art History department. Prerequisite: consent of instructor.<br>
</li>
<li>ARH 464 Senior Seminar I<br>
Introduces the research methods, theories, and curatorial practices affiliated with the discipline of art history. Additionally, students begin crafting their capstone projects in art history, which will be completed in Seminar II. Prerequisites: declared major in Art History, Introduction to Art History (ARH-128), one 200-level ARH course, and junior standing.<br>
</li>
<li>ARH 474 Senior Seminar II<br>
Completes the capstone research project (i.e.&nbsp;research papers, exhibitions, or hybrid projects that involve making art and contextualizing visual culture). Prerequisite: Successful completion of Seminar in Art History I.<br>
</li>
<li>ARH 494 Internship in Art History<br>
Investigates an area of interest related to the major, through voluntary field placement supervised by a faculty member of the Art and Art History department. A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisites: declared major in art history, junior standing, and consent of department chair.</li>
</ul>
</section>
</section>
<section id="sec-asian-studies" class="level2" data-number="25.7">
<h2 data-number="25.7" class="anchored" data-anchor-id="sec-asian-studies"><span class="header-section-number">25.7</span> Asian Studies</h2>
<p>Nordmann (Administrative Coordinator).</p>
<p>The Asian Studies program is designed to acquaint students with the great cultures of Asia, primarily those of China, India and Japan.</p>
<section id="asian-studies-major" class="level3" data-number="25.7.1">
<h3 data-number="25.7.1" class="anchored" data-anchor-id="asian-studies-major"><span class="header-section-number">25.7.1</span> Asian Studies Major</h3>
<p>A major in Asian studies requires a minimum cumulative 2.0 GPA in all courses counted toward the major.</p>
<p>The major is interdisciplinary and requires that the students take courses in the areas of art history, history, literature, and religion, and suggests that they also take courses in economics, music, and political science.</p>
<p>1.<strong>One</strong> of the following:</p>
<pre><code>-ASC 186 Modern South Asia
-HIS 136 East Asian Civilization</code></pre>
<p>2.Participation in one overseas study program in Asia:</p>
<pre><code>-an ACM overseas study program (India Studies or Japan Study)
-a Coe foreign exchange program (Chiang Mai University of Thailand, Nagoya Gakuin University of Japan, or Sookmyung University in South Korea)
-Coe’s Asia Term (see p. 30)</code></pre>
<p>3.<strong>Four</strong> courses, chosen from the following, in consultation with the Asian Studies administrative coordinator:</p>
<pre><code>-ASC 106 May Term in Asia
-ASC 176 China and Japan
-ECO 436 Econ Development or ECO 446 International Econ
-HIS 217 American War in Vietnam
-HIS 246 History of Modern China
-HIS 256 History of Modern Japan
-HIS 316 Topics in History:Non-Western Persp (when appropriate)
-HIS 466 Seminar Modern East Asian History
-JPN 115 Elementary Japanese I
-JPN 125 Elementary Japanese II
-JPN 215 Intermediate Japanese I
-JPN 225 Intermediate Japanese II
-+++MISSING INFO: c.phl/rel206.long +++
-POL 286 Asian Politics
-REL 106 Eastern Religions
-A second term of an overseas study program</code></pre>
</section>
<section id="asian-studies-minor" class="level3" data-number="25.7.2">
<h3 data-number="25.7.2" class="anchored" data-anchor-id="asian-studies-minor"><span class="header-section-number">25.7.2</span> Asian Studies Minor</h3>
<p>1.<strong>One</strong> of the following:</p>
<pre><code>-HIS 316 Topics in History:Non-Western Persp
-ASC 186 Modern South Asia</code></pre>
<p>2.<strong>Five</strong> courses, chosen from the following, in consultation with the Asian Studies administrative coordinator:</p>
<pre><code>-ASC 176 China and Japan
-ECO 436 Econ Development or ECO 446 International Econ
-HIS 217 American War in Vietnam
-HIS 246 History of Modern China
-HIS 256 History of Modern Japan
-HIS 316 Topics in History:Non-Western Persp (when appropriate)
-HIS 466 Seminar Modern East Asian History
-JPN 115 Elementary Japanese I
-JPN 125 Elementary Japanese II
-JPN 215 Intermediate Japanese I
-JPN 225 Intermediate Japanese II
-+++MISSING INFO: c.phl/rel206.long +++
-POL 286 Asian Politics
-REL 106 Eastern Religions</code></pre>
</section>
<section id="courses-in-asian-studies" class="level3" data-number="25.7.3">
<h3 data-number="25.7.3" class="anchored" data-anchor-id="courses-in-asian-studies"><span class="header-section-number">25.7.3</span> Courses in Asian Studies</h3>
<p>-<strong>ASC 106 May Term in Asia</strong> Examines experientially the fast-changing nation of Vietnam through three weeks of study and travel in the country. Students will investigate and evaluate the contemporary nation, as well as the history and memory of its wartime experiences, through readings, written work, class discussions, and visits to important historical and cultural landmarks. Through these varied experiences, students will deepen their understandings of the cultural skills involved in overseas travel, the cultural differences and commonalities that shape human experiences, and the specific knowledge of Vietnam’s culture and history. -<strong>ASC 176 China and Japan</strong> An interdisciplinary examination of themes and ideas central to understanding the cultures of China and Japan. Materials used include primary texts in Taoism, Confucianism, and Buddhism, as well as works of poetry, fiction, and visual art. -<strong>ASC 186 Modern South Asia</strong> India, Pakistan, Bangladesh, and Sri Lanka from a modern perspective. The preoccupation with identity, the reemergence of caste and religious conflicts, the strengths and weaknesses of political and economic development, and the implication of trends for the future. Includes selected topics on culture and history that provide insights to understanding the present. -<strong>+++MISSING INFO: c.asc216.long +++</strong> See <span class="quarto-unresolved-ref">?sec-history</span></p>
</section>
</section>
<section id="athletic-training" class="level2" data-number="25.8">
<h2 data-number="25.8" class="anchored" data-anchor-id="athletic-training"><span class="header-section-number">25.8</span> Athletic Training</h2>
<p>Chandler, Libby (Chair).</p>
<p>No students will be admitted to the Athletic Training Education Program after December 8, 2017</p>
<section id="courses-in-athletic-training" class="level3" data-number="25.8.1">
<h3 data-number="25.8.1" class="anchored" data-anchor-id="courses-in-athletic-training"><span class="header-section-number">25.8.1</span> Courses in Athletic Training</h3>
<p>-<strong>AT 100 Basic Athletic Training</strong> An overview of the athletic training profession designed to lead student’s knowledge of the profession from the general foundations to specific educational competencies. Included in this course are laboratory sessions used to instruct and practice athletic training competencies and proficiencies. Credit is given for Prevention and Care of Athletic Injuries &amp; Laboratory (PE 175 OR Basic Athletic Training (AT-100), not both.</p>
<p>Prerequisite: Application to the Athletic Training Education Program -<strong>+++MISSING INFO: c.at20_/30_/40_.long +++</strong> +++MISSING INFO: c.at20_/30_/40_.desc +++ -<strong>+++MISSING INFO: c.at225/220.long +++</strong> +++MISSING INFO: c.at225/220.desc +++ -<strong>+++MISSING INFO: c.at235/230.long +++</strong> +++MISSING INFO: c.at235/230.desc +++ -<strong>AT 375 General Medical Conditions</strong> Study of the etiology, clinical manifestations and management of common diseases/conditions that affect athletes and others involved in physical activity. Additional topics include pharmacology, counseling and psychosocial interventions. Prerequisites: Human Anatomy (BIO-215), Human Physiology (BIO-225), and admission to Athletic Training Education Program. -<strong>AT 385 Therapeutic Modalities</strong> Investigation into the concepts, indications/contraindications, physiological effects, and clinical implications of physical modalities used in a therapeutic setting. Prerequisite: Human Physiology (BIO-225). -<strong>+++MISSING INFO: c.at395/390.long +++</strong> +++MISSING INFO: c.at395/390.desc +++ -<strong>AT 425 Administration of Athletic Training</strong> Introduction to the organization and administration of an athletic training program including facility planning/design, information/resource management, legal/ethical considerations, risk management, insurance systems, and professional development. Prerequisite: senior standing in the Athletic Training Education Program. -<strong>AT 494 Internship in Athletic Training</strong> Comprehensive experience in athletic training through voluntary field placement supervised by a certified athletic trainer (ATC®). A minimum of 140 hours on-site experience is required. P/NP basis only. Prerequisite: senior standing in the Athletic Training Education Program.</p>
</section>
</section>
<section id="biochemistry-collateral-major" class="level2" data-number="25.9">
<h2 data-number="25.9" class="anchored" data-anchor-id="biochemistry-collateral-major"><span class="header-section-number">25.9</span> Biochemistry (Collateral Major)</h2>
<p>Stead (Administrative Coordinator).</p>
<section id="collateral-major-in-biochemistry" class="level3" data-number="25.9.1">
<h3 data-number="25.9.1" class="anchored" data-anchor-id="collateral-major-in-biochemistry"><span class="header-section-number">25.9.1</span> Collateral Major in Biochemistry</h3>
<p>A major in biochemistry requires a minimum cumulative 2.0 GPA in all courses counted toward the major. Concurrent completion of a primary major in chemistry, including Calculus II and two General Physics courses is required. Students choosing a collateral major in biochemistry may not select a collateral major in molecular biology</p>
<p>1.+++MISSING INFO: c.bio145/145L.long +++ 2.+++MISSING INFO: c.chm431/431L.long +++ 3.+++MISSING INFO: c.chm432/432L.long +++ 4.<strong>Two</strong> of the following:</p>
<pre><code>-+++MISSING INFO: c.bio325/325L.long +++
-+++MISSING INFO: c.bio345/345L.long +++
-BIO 405 Current Topics in Molecular Biology
-+++MISSING INFO: c.bio435/435L.long +++</code></pre>
<p>Genetics (BIO-235) and Laboratory (BIO-235L) and all of the courses under #4 are strongly encouraged, especially for those planning graduate study.</p>
</section>
</section>
<section id="biology" class="level2" data-number="25.10">
<h2 data-number="25.10" class="anchored" data-anchor-id="biology"><span class="header-section-number">25.10</span> Biology</h2>
<p>R. Christensen, Cozine (Chair), Ellis, Hughes, Keyes, Leonardo, Leveille, Luttinger, Mommer, Sanchini, Storer (Co-Chair).</p>
<p>In addition to a major in biology, the college also offers collateral majors in ENVIRONMENTAL SCIENCE (see p.&nbsp;115), MOLECULAR BIOLOGY (see p.&nbsp;144), and NEUROSCIENCE (see p.&nbsp;156). The biology program provides students with an early introduction to experimental design and use of instrumentation to investigate properties of cells and organisms. Opportunities to work one-on-one with faculty, in honors and independent study work or in research participation, is also available to students.</p>
<section id="biology-major" class="level3" data-number="25.10.1">
<h3 data-number="25.10.1" class="anchored" data-anchor-id="biology-major"><span class="header-section-number">25.10.1</span> Biology Major</h3>
<p>A major in biology requires a minimum cumulative 2.0 GPA over courses counted toward the major.</p>
<p>1.+++MISSING INFO: c.bio145/145L.long +++ 2.+++MISSING INFO: c.bio155/155L.long +++ 3.BIO 202 Topics in Evolution 4.+++MISSING INFO: c.bio205/205L.long +++ 5.+++MISSING INFO: c.bio235/235L.long +++ 6.<strong>One</strong> of the following:</p>
<pre><code>-+++MISSING INFO: c.bio355/355L.long +++
-+++MISSING INFO: c.bio375/375L.long +++</code></pre>
<p>7.<strong>Three</strong> biology electives with the associated laboratories 8.+++MISSING INFO: c.chm121/121L.long +++ 9.+++MISSING INFO: c.chm122/122L.long +++ 10.<strong>One</strong> of the following:</p>
<pre><code>-+++MISSING INFO: c.mth132.long +++ (strongly recommended for students considering attending graduate school)
-STA 100 Statistical Reasoning I-Foundations and STA 110 Stats IIA: Inferential Reasoning
-STA 100 Statistical Reasoning I-Foundations and STA 130 Stats IIB: Experimental Design</code></pre>
<p>11.Attendance at research seminars in junior and senior years</p>
<p><em>Strongly recommended:</em> <strong>One</strong> of the following sequences: -+++MISSING INFO: c.phy165/165L.long +++ and +++MISSING INFO: c.phy175/175L.long +++ -+++MISSING INFO: c.phy185/185L.long +++ and +++MISSING INFO: c.phy195/195L.long +++</p>
<p>With consent of the department chair, other chemistry or mathematics courses may be substituted.</p>
</section>
<section id="laboratory-study-in-biology" class="level3" data-number="25.10.2">
<h3 data-number="25.10.2" class="anchored" data-anchor-id="laboratory-study-in-biology"><span class="header-section-number">25.10.2</span> Laboratory Study in Biology</h3>
<p>Laboratory and field experiences are essential to scientific understanding. They offer an introduction to the processes of science, emphasizing student participation in hypothesis formulation, experimental design, data collection, data analysis, and the composition of papers in a format conventional to science. Biology majors must complete the requisite laboratory courses for the major. Students not majoring in biology should enroll in a laboratory section of any course they plan to apply to the laboratory science requirement in general education.</p>
</section>
<section id="courses-in-biology" class="level3" data-number="25.10.3">
<h3 data-number="25.10.3" class="anchored" data-anchor-id="courses-in-biology"><span class="header-section-number">25.10.3</span> Courses in Biology</h3>
<p>-<strong>BIO 100 Human Biology</strong> A study of Homo sapiens applying the same tools biologists use to study other organisms. Topics may include an overview of human evolution, reproduction, genetics, population genetics, adaptations of selected organs and organ systems, humans’ relationship to and impact on their environment, and other contemporary issues in human biology. Includes lecture and laboratory. This course does not satisfy any of the requirements for a major in biology. -<strong>+++MISSING INFO: c.bio100L.long +++</strong> +++MISSING INFO: c.bio100L.desc +++ -<strong>BIO 103 Anatomy &amp; Physiology</strong> Introduces the student to the structure, function, and organization of the human body. Designed for non-majors as well as students with health-related career interests. This course does not satisfy any of the requirements for a major in biology or nursing. -<strong>+++MISSING INFO: c.bio103L.long +++</strong> +++MISSING INFO: c.bio103L.desc +++ -<strong>BIO105 Introductory Biology</strong> None -<strong>BIO 111 Urban Ecology</strong> Introduces the ecology of urban systems, investigating how humans and their built environments interact with and form ecosystems. Two main points of view will be represented: the city as an ecological system, and the responses and adaptations of organisms to this ecosystem. We will also investigate how humans respond to and interact with this biotic and abiotic environment. Labs will visit relevant areas of Cedar Rapids. One three hour workshop and one four-hour lab per week. (Offered alternate years.) -<strong>+++MISSING INFO: c.bio111L.long +++</strong> +++MISSING INFO: c.bio111L.desc +++ -<strong>BIO 115 Marine Biology</strong> Surveys marine organisms and communities with emphasis on tropical coral reef systems. The primary field analyses focus on the dynamics of coral reefs, tidal regions, and turtle grass meadows. An off campus course taught at an appropriate site and involving extensive field work. Includes lecture and laboratory. Prerequisite: consent of instructor. (Offered May Term only) -<strong>BIO 120 Biology, Health, &amp; Society</strong> Introduces the basic principles, terms, and technologies needed to understand the role of biology in our lives. This course centers around answering questions in healthcare and in contemporary society, using the application of biological knowledge. Study skills for mastering college biology are also taught. Three lectures and one co-curricular skills workshop per week. Counts as a non-lab science course. This course does not satisfy any of the requirements for a major in biology. -<strong>BIO 145 Cellular &amp; Molecular Biology</strong> A study of biology at the cellular and molecular level, including cytology, metabolic, and genetic processes. Three lectures per week. -<strong>+++MISSING INFO: c.bio145L.long +++</strong> +++MISSING INFO: c.bio145L.desc +++ -<strong>BIO 155 Organismal &amp; Ecological Biology</strong> The study of organ systems, reproduction, and embryology, with an emphasis on human biology. Principles of evolution, ecology, and animal behavior are also studied. Three lectures per week. -<strong>+++MISSING INFO: c.bio155L.long +++</strong> +++MISSING INFO: c.bio155L.desc +++ -<strong>BIO 165 Ecology and Biology of Birds</strong> An introduction to the behavior, ecology and biology of birds, emphasizing identification of local species and such species’ adaptations to their biotic and abiotic environments. Binoculars furnished. This course satisfies the lab science course requirement. Offered Spring Term on campus and Summer at the Wilderness Field Station. -<strong>+++MISSING INFO: c.bio165L.long +++</strong> +++MISSING INFO: c.bio165L.desc +++ -<strong>BIO 175 Field Botany</strong> Investigates tree and wildflower species encountered in Iowa’s forests, fields and prairies. Emphasizes hands-on description of structural characteristics, identification of species using a dichotomous key and characteristics of flowering plant families. A basic understanding of the distribution of plants within communities is also developed. A collection of local plants is required. (Offered in May Term) -<strong>BIO 185 Entomology</strong> Introduces the biology of insects and related arthropods, focusing on how homeostatic problems common to all organisms have been solved. Topics include physiology, morphology, systematics, and the relationship among insects, plants, and humans. -<strong>+++MISSING INFO: c.bio185L.long +++</strong> +++MISSING INFO: c.bio185L.desc +++ -<strong>BIO 195 Introduction to Microbiology</strong> An elementary-level study of the principles of microbiology. Special attention is given to the medical aspect of the subject. Three lectures and one three hour laboratory per week. Designed for students with allied health career interests. This course does not satisfy any of the requirements for a major in biology. Prerequisite: Human Biology (BIO-100) or Cellular and Molecular Biology (BIO-145). -<strong>+++MISSING INFO: c.bio195L.long +++</strong> +++MISSING INFO: c.bio195L.desc +++ -<strong>BIO 202 Topics in Evolution</strong> Investigates the roles of selective and non-selective evolutionary mechanisms, especially as they affect adaptation, speciation, and extinction. Selected aspects of the fossil record and current theories of hominid evolution are also part of the course. Counts as a non-lab science course. Prerequisites: Cellular and Molecular Biology (BIO-145). Note: Credit is given for either Topics in Evolution (BIO-202) or Organic Evolution (BIO-125), not both. -<strong>BIO 205 General Botany</strong> A study of the basic structure and functions of plants, with emphasis on seed plants. Functional aspects of structure and development on the cellular, tissue, and whole plant level receive equal emphasis. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-140) and Organismal and Ecological Biology (BIO-155). -<strong>+++MISSING INFO: c.bio205L.long +++</strong> +++MISSING INFO: c.bio205L.desc +++ -<strong>BIO 215 Human Anatomy</strong> A survey of gross and microscopic human anatomy, providing necessary background for students in physiology and body mechanics. Three lectures per week. Prerequisites: Human Biology (BIO-100) or Cellular and Molecular Biology (BIO-145) or Organismal and Ecological Biology (BIO-155). This course does not satisfy any of the requirements for a major in biology. Credit is given for Human Anatomy (BIO-215) or Integrated Human Anatomy (BIO-245), not both. -<strong>+++MISSING INFO: c.bio215L.long +++</strong> +++MISSING INFO: c.bio215L.desc +++ -<strong>BIO 225 Human Physiology</strong> The functional study of the various systems of the human body, including the application of physiological principles to the health professions. Three lectures and one two-hour recitation per week. This course does not satisfy any of the requirements for a major in biology. Prerequisites: Human Anatomy (BIO-215) and either Human Biology (BIO-100), Cellular and Molecular Biology (BIO-145), or Organismal and Ecological Biology (BIO-155). -<strong>BIO 235 Genetics</strong> An exploration of the three main branches of heredity: transmission (classical), molecular, and population genetics. Transmission genetics examines how genes and genetic traits are passed from generation to generation. Molecular genetics probes the structure, function, and regulation of genes, while population genetics investigates through mathematical models the distribution and behavior of genes in populations. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-140), and Organismal and Ecological Biology (BIO-155). -<strong>+++MISSING INFO: c.bio235L.long +++</strong> +++MISSING INFO: c.bio235L.desc +++ -<strong>BIO 275 Aquatic Ecology</strong> Study of the biota of lakes and streams in northern Minnesota and adjacent Ontario, and their abiotic environment. Extensive field sampling enables students to study predation, diel vertical migration, stream drift, induced morphological defenses, and food-web interactions. Regional and North American lake and stream biodiversity and the effects of introduced species and human intervention on aquatic ecosystems are reviewed. Prerequisites: Cellular and Molecular Biology (BIO-145) and Introduction to Biology Laboratory (BIO-140), or Organismal and Ecological Biology (BIO-155) and Laboratory (BIO-150). (Offered summers at the Wilderness Field Station) -<strong>+++MISSING INFO: c.bio275L.long +++</strong> +++MISSING INFO: c.bio275L.desc +++ -<strong>BIO 285 Animal Behavior</strong> Principles and methods in ethology are considered with emphasis on temporal and spatial patterns, adaptive significances, communication, aggression and territoriality, social organization, and the nature of regulatory mechanisms. Prerequisites: One of the following: Cellular and Molecular Biology (BIO-145) and Introduction to Biology Laboratory (BIO-140); Organismal and Ecological Biology (BIO-155) and Laboratory (BIO-150); or Statistical Methods and Data Analysis (PSY-301). (Offered summers at the Wilderness Field Station) -<strong>+++MISSING INFO: c.bio285L.long +++</strong> +++MISSING INFO: c.bio285L.desc +++ -<strong>BIO 295 Spatial Ecology</strong> Study of spatial patterns of organisms in natural, agricultural, and urban landscapes. Emphasis is on how the arrangements of organisms both reflect and feedback on underlying resources and geography. Students learn how to capture spatial characteristics of individuals, populations, species, communities, and landscapes sampled in the field, integrate them with satellite imagery, and analyze them statistically. Use of global positioning system hardware to provide spatial reference for field ecology surveys and use of ArcView as a data management, display, and analysis tool are important features of the course. Three lectures per week. Prerequisites: Organismal and Ecological Biology (BIO-155) and Laboratory (BIO-150). -<strong>+++MISSING INFO: c.bio295L.long +++</strong> +++MISSING INFO: c.bio295L.desc +++ -<strong>BIO 315 Integrated Human Anatomy</strong> Integrates macroscopic human anatomy at the organ and organ system levels with microscopic study of histology and development from an evolutionary and sometimes experimental perspective. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-145L), Organismal and Ecological Biology (BIO-155) and Laboratory (BIO-155L). Credit is given for Integrated Human Anatomy (BIO-315) or Human Anatomy (BIO-215), not both. -<strong>+++MISSING INFO: c.bio315L.long +++</strong> +++MISSING INFO: c.bio315L.desc +++ -<strong>BIO 325 Microbiology</strong> Study of major fields of microbiology with emphasis on bacteria and viruses. Topics include bacterial cell structure, genetics, and pathogenesis as well as immunology and epidemiology. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-145L), Organismal and Ecological Biology (BIO-155), Organic Chemistry I (CHM-221) and Organic Laboratory (CHM-322) or Genetics (BIO-235). -<strong>+++MISSING INFO: c.bio325L.long +++</strong> +++MISSING INFO: c.bio325L.desc +++ -<strong>BIO 335 Conservation and Ecology of Mammals</strong> The study of mammals of Minnesota and the natural history, form/function relations, behavior, distributions, and interaction with their environment and other organisms. Class activities include direct observations, reading tracks and “sign.” Live-trap mark and recapture studies supplemented by readings, lectures, and discussions. (Offered summers at the Wilderness Field Station) -<strong>+++MISSING INFO: c.bio335L.long +++</strong> +++MISSING INFO: c.bio335L.desc +++ -<strong>BIO 345 Techniques in Molecular Biology</strong> An intensive introduction to biological molecular techniques. Students learn how to manipulate recombinant DNA and express and detect protein products in prokaryotic systems. Course methods include cloning, restriction, mapping, ligation, labeling, purification, elution, blotting, hybridization, agarose, and acrylamide gels, protein expression and detection, and immunological techniques. On completing the course, students should have a working knowledge of most methods used in molecular biology research. Course consists of two discussion sessions per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-140), Genetics (BIO-235) and Laboratory (BIO-230), General Chemistry I (CHM-1XX), and General Chemistry II (CHM-1XX). -<strong>+++MISSING INFO: c.bio345L.long +++</strong> +++MISSING INFO: c.bio345L.desc +++ -<strong>BIO 355 Animal Physiology</strong> Study of how organ systems in animal species solve the fundamental problems of staying alive. This includes how to obtain energy, how to procure the raw materials necessary for constructing their bodies, how to gain oxygen from the environment, how to get rid of unneeded substances and toxic materials. The course addresses how these ends are achieved through the cooperation of cells, tissues, organs, and organ systems in a variety of organisms including mammals, birds, reptiles, amphibians, and fish as well as selected invertebrates. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-140), Organismal and Ecological Biology (BIO-155). -<strong>+++MISSING INFO: c.bio355L.long +++</strong> +++MISSING INFO: c.bio355L.desc +++ -<strong>BIO 365 Comparative Chordate Anat</strong> A survey of the chordates and the development and evolution of form in vertebrates, using primarily the shark, mudpuppy, and cat in laboratory. Two lectures, one discussion recitation per week. Prerequisite: Cellular and Molecular Biology (BIO-145), Organismal and Ecological Biology (BIO-155) and Topics in Evolution (BIO-202). -<strong>+++MISSING INFO: c.bio365L.long +++</strong> +++MISSING INFO: c.bio365L.desc +++ -<strong>BIO 375 Integrated Human Physiology</strong> The study of function in terms of basic physical and chemical processes; an introduction to the principles of physiligy using the human organism as a model. Three lectures per week. Prerequisite: Cellular and Molecular Biology (BIO-145), Organismal and Ecological Biology (BIO-155), and Introduction to Biology Laboratory (BIO-140) -<strong>+++MISSING INFO: c.bio375L.long +++</strong> +++MISSING INFO: c.bio375L.desc +++ -<strong>BIO 385 Behavior/Ecology of Vertebrates</strong> Identification, evolutionary history, behavior and ecological relationships of local mammals, birds, reptiles, amphibians, and fish. Students learn and apply survey techniques appropriate for particular groups to understand species/habitat relationships, diversity within groups, and the impact of humans on diversity. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145) and Topics in Evolution (BIO-202). -<strong>+++MISSING INFO: c.bio385L.long +++</strong> +++MISSING INFO: c.bio385L.desc +++ -<strong>BIO 405 Current Topics in Molecular Biology</strong> An intensive exploration of Molecular Biology’s primary literature, focusing on recent advances in DNA, RNA and protein manipulation, characterization, and control. Students read research articles, critically evaluate published data, and communicate technical information effectively. Three lectures per week. Prerequisites: Techniques in Molecular Biology (BIO-345) and Genetics (BIO-235). -<strong>BIO 415 Developmental Biology</strong> An exploration of the developmental processes that occur as an organism grows from fertilized egg to adult organism. The actions and interactions of cells and tissues are examined in the living, growing, and rapidly changing environment of the body. Classical embryology is examined through modern genetic techniques, with special emphasis on how differential gene expression makes us who we are. Survey of research methodologies are a prominent topic. Three lectures per week. Prerequisites: Genetics (BIO-235) and Laboratory (BIO-230). -<strong>+++MISSING INFO: c.bio415L.long +++</strong> +++MISSING INFO: c.bio415L.desc +++ -<strong>BIO 425 Ecology</strong> Study of the interrelationship of living organisms with their environment. The structure and dynamics of populations, communities, and ecosystems are examined through lectures and laboratory or field observations. Three lectures per week. Prerequisites: General Botany (BIO-205) or consent of instructor. -<strong>+++MISSING INFO: c.bio425L.long +++</strong> +++MISSING INFO: c.bio425L.desc +++ -<strong>BIO 435 Cell Physiology</strong> The content, organization, and function of the cell and its components are studied. Other topics include the relationship of the cell to its environment, the cell membrane, enzymes, conversion of matter and energy, cell growth, and cell division. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-145L), Organismal and Ecological Biology (BIO-155), Genetics (BIO-235), and General Chemistry I and Laboratory (CHM-121/-121L). -<strong>+++MISSING INFO: c.bio435L.long +++</strong> +++MISSING INFO: c.bio435L.desc +++ -<strong>BIO 444 Independent Study</strong> Independent work on a selected project under direction of a member of the department. Students are limited to two registrations in Independent Study. May be taken for an X status grade with consent of instructor prior to registration. Prerequisites: Courses providing appropriate background for the project selected and consent of department chair. -<strong>BIO 445 Environmental Microbiology</strong> An examination of the role of microbes in the environment. Topics include microbial diversity, nutrient cycling including biogeochemistry, bioremediation, and biodegradation. The use of molecular methods and microsopy to study microbes in situ are special emphases of the course. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-145L), Organismal and Ecological Biology (BIO-155), Organic Chemistry I (CHM-221) with Organic Laboratory (CHM-322) or Genetics (BIO-235). -<strong>+++MISSING INFO: c.bio445L.long +++</strong> +++MISSING INFO: c.bio445L.desc +++ -<strong>BIO 454 Research Participation</strong> Participation in a research program designed and directed by a biology department faculty member, including some or all of the following: library research, research design, and field or laboratory investigations. Scheduled by arrangement with sponsoring professor with a time requirement of 10 hours per week minimum per course credit. P/NP basis only. May be taken for an X status grade with consent of instructor prior to registration. Research participation credit does not satisfy any of the requirements for a major in biology. (0.2 – 1.0 course credit) -<strong>BIO 455 Molecular Neurobiology</strong> Study of the organization and function of the nervous system, focusing on both cellular physiology and functional neuroanatomy. Topics include the cellular and molecular properties of brain cells, the neurological basis of behavior, and disorders of the nervous system. Three lectures per week. Prerequisites: Cellular and Molecular Biology (BIO-145), Introduction to Biology Laboratory (BIO-140), Organismal and Ecological Biology (BIO-155), General Chemistry I (CHM-155), General Chemistry II (CHM-165) and Genetics (BIO-235) and Lab (BIO-230) -<strong>+++MISSING INFO: c.bio455L.long +++</strong> +++MISSING INFO: c.bio455L.desc +++ -<strong>+++MISSING INFO: c.bio462/463.long +++</strong> +++MISSING INFO: c.bio462/463.desc +++ -<strong>BIO 465 Immunology</strong> An integrated series of lectures designed to familiarize students with cellular, molecular and biochemical aspects of the development of the immune system and the immune response, including B-and T-cell function, antibody structure and function, complement, and major histocompatibility complex formation, with special emphasis on the integration of these parts during the response to infectious agents. Special topics include immunomodulation, vaccination, autoimmunity, and neuro-immune interactions. The laboratory component utilizes existing instrumentation in the biology department and cell culture to explore different aspects of the immune system. Three lectures and one three hour laboratory period per week. Prerequisites: General Chemistry II (CHM 122/122L), Genetics (BIO-235), and Integrated Human Physiology (BIO-375) (or concurrent enrollment in BIO-375). -<strong>+++MISSING INFO: c.bio465L.long +++</strong> +++MISSING INFO: c.bio465L.desc +++ -<strong>BIO 494 Internship in Biology</strong> Investigation of an area of interest through voluntary field placement supervised by a faculty member of the department. A minimum of 140 hours on-site experience is required. P/NP basis only. This course does not satisfy any of the requirements for a major in biology. Prerequisites: declared major in biology, junior standing, and consent of department chair.</p>
<p>-<strong>OCC 365 Oak Ridge Science Semester</strong> See <span class="quarto-unresolved-ref">?sec-ACM-and-international-programs</span></p>
<p>-<strong>HSS 494 Health Professions Externship</strong> This capstone experience for qualified junior and senior students, could finalize a career decision or create an opportunity for a different career path. Using the academic knowledge already obtained through course work, the student will now apply it to real world situations as experiential learning with professional mentors in our community and will gain additional knowledge of what the daily activities and difficulties can, or may be present in their particular internship profession. They will increase their own communication skills, learn interpersonal skills with mentors, staff, clients/patients, gain professional ethics skills, and gain additional topic knowledge while working with their mentors. Some will gain “hands on” training while others will gain their knowledge thru observation of techniques, personal interactions, and through researching pertinent subject matters. Some may gain public speaking experiences, while others may increase their professional writing abilities. Each intern experience will have its own unique set of learning outcomes. Junior or Senior standing with appropriate GPA.</p>
</section>
</section>
<section id="business-administration-and-economics" class="level2" data-number="25.11">
<h2 data-number="25.11" class="anchored" data-anchor-id="business-administration-and-economics"><span class="header-section-number">25.11</span> Business Administration and Economics</h2>
<p>Baranowski, Carstens, Chen, J. Christensen, Crain, Eichhorn (Co-Chair), Hall, Hayes, D., Knudson, Kuennen, Melcher, Nguyen (Co-Chair), Perry, Trout, Westberg.</p>
<p>The Stead Department of Business Administration and Economics offers majors in <strong>ACCOUNTING</strong>, <strong>BUSINESS ADMINISTRATION</strong>, <strong>ECONOMICS</strong>, <strong>INTERNATIONAL BUSINESS</strong>, and INTERNATIONAL ECONOMICS, and minors in economics and international economics. Students pursuing one or more of these are strongly encouraged to consult with departmental faculty to develop specific plans of study.</p>
<section id="business-administration" class="level3" data-number="25.11.1">
<h3 data-number="25.11.1" class="anchored" data-anchor-id="business-administration"><span class="header-section-number">25.11.1</span> BUSINESS ADMINISTRATION</h3>
<p>The study of business administration is designed to develop in its students a high degree of competence in the application of business theories and sound judgment to the solution of business operating problems. Graduates are able to contribute effectively to the activities of their organizations by applying business skills required to plan, analyze, and control company activities. Beyond enhancing the value of a firm, the graduate should have a firm knowledge from which to achieve professional growth in the workplace and/or graduate school. Students majoring in business administration have two options: the business administration major and the international business major (see p.&nbsp;132). The business major is designed to prepare students in the core areas of business administration, with specific focus on management, finance, and marketing. Students are also provided the opportunity to specialize in a particular area through selection of elective courses. The international business major is designed to prepare students for specific challenges related to operating an organization in an international context.<br>
Because of significant overlap in the business administration and the international business requirements, only one of the two majors may be elected by a student. See p.&nbsp;132 for the International Business major requirements.</p>
</section>
<section id="business-administration-major" class="level3" data-number="25.11.2">
<h3 data-number="25.11.2" class="anchored" data-anchor-id="business-administration-major"><span class="header-section-number">25.11.2</span> Business Administration Major</h3>
<p>A major in business administration requires a minimum cumulative 2.0 GPA in all courses counted toward the major.</p>
<ol type="1">
<li>ACC 171 Principles of Accounting I</li>
<li>ECO 175 Principles of Macroeconomics</li>
<li>BUS 190 Statistical Analysis</li>
<li>ACC 215 Principles of Accounting II</li>
<li>ECO 215 Prin Microeconomics</li>
<li>BUS 315 Business Law I</li>
<li>One of the following Management courses:<br>
BUS 250 Principles of Management<br>
BUS 300 Human Resource Management<br>
BUS 387 Adv Top:Human Res Mgt<br>
BUS 470 Strategic Management<br>
</li>
<li>One of the following Marketing courses:<br>
BUS 330 Principles of Marketing<br>
BUS 460 Advertising<br>
BUS 465 Advanced Topics in Marketing<br>
BUS 467 Consumer Behavior<br>
</li>
<li>One of the following Finance courses ECO 225 Money &amp; Banking<br>
BUS 350 Principles of Finance<br>
BUS 352 Corporate Finance<br>
BUS 495 Investment Analysis<br>
ECO 495 International Finance<br>
</li>
<li>Two additional business courses numbered 200 or above</li>
</ol>
<p>Students planning to attend graduate school in business are strongly encouraged to take calculus, additional statistics courses, intermediate level macro/microeconomics, quantitative management courses, and strategic management. Students should also discuss their graduate school plans with a member of the department to determine other courses that may be expected for admission to specific graduate programs</p>
</section>
<section id="concentrations-in-business" class="level3" data-number="25.11.3">
<h3 data-number="25.11.3" class="anchored" data-anchor-id="concentrations-in-business"><span class="header-section-number">25.11.3</span> Concentrations in Business</h3>
<p>Students completing a major in Business Administration may elect to also complete a concentration of courses within a specific discipline in the major. Courses taken to fulfill requirements in the business major may be used to also fulfill requirements in an area of concentration. Students may declare only one concentration.</p>
<p>Concentrations are offered in management, marketing, and sports management. To complete a concentration, a student must meet the following requirements: 1. Completion of a major in Business Administration 2. Completion of five additional courses in which a cumulative 2.0 GPA must be earned. At least three of the five courses must be completed at Coe.</p>
</section>
<section id="management-concentration-in-business" class="level3" data-number="25.11.4">
<h3 data-number="25.11.4" class="anchored" data-anchor-id="management-concentration-in-business"><span class="header-section-number">25.11.4</span> Management Concentration in Business</h3>
<ol type="1">
<li>BUS 250 Principles of Management</li>
<li>Four of the following:<br>
BUS 300 Human Resource Management<br>
BUS 375 Business Ethics<br>
BUS 387 Adv Top:Human Res Mgt<br>
BUS 395 Organizational Behavior<br>
BUS 446 International Business Management<br>
BUS 464 Seminar in Management<br>
BUS 454 Research in Business<br>
BUS 470 Strategic Management</li>
</ol>
</section>
<section id="marketing-concentration-in-business" class="level3" data-number="25.11.5">
<h3 data-number="25.11.5" class="anchored" data-anchor-id="marketing-concentration-in-business"><span class="header-section-number">25.11.5</span> Marketing Concentration in Business</h3>
<ol type="1">
<li>BUS 355 Principles of Marketing<br>
</li>
<li>Four of the following: BUS 280 Business Websites <strong>and</strong> BUS 281 Social Media in Business<br>
BUS 420 Sports Marketing and Communications<br>
BUS 460 Advertising<br>
BUS 461 Marketing Decision Making/Analysis<br>
BUS 465 Advanced Topics in Marketing<br>
BUS 470 Strategic Management<br>
BUS 454 Research in Business<br>
PR 205 Public Relations</li>
</ol>
</section>
<section id="sports-management-concentration-in-business" class="level3" data-number="25.11.6">
<h3 data-number="25.11.6" class="anchored" data-anchor-id="sports-management-concentration-in-business"><span class="header-section-number">25.11.6</span> Sports Management Concentration in Business</h3>
<ol type="1">
<li>SMT 100 Introduction to Sports Management<br>
</li>
<li>Four of the following:<br>
BUS 400 Legal Issues in Sports<br>
BUS 420 Sports Marketing and Communications<br>
BUS 454 Research in Business<br>
ECO 125 Sports Analytics<br>
SMT 300 Sport/Recreation Event Management<br>
SMT 454 Seminar in Sports Management<br>
SMT 494 Internship in Sports Management</li>
</ol>
</section>
</section>
<section id="sec-accounting" class="level2" data-number="25.12">
<h2 data-number="25.12" class="anchored" data-anchor-id="sec-accounting"><span class="header-section-number">25.12</span> Accounting</h2>
<p>Students majoring in accounting have two options: the managerial accounting major and the public accounting major. The managerial accounting major is designed for students interested in pursuing a career in private industry or the not-for-profit sector. The public accounting major is designed for students interested in practicing public accounting and those desiring the Certified Public Accounting (CPA) designation. Because of the identical core course requirements in the managerial accounting and public accounting majors, only one of the two majors can be elected by a student. A student receiving a managerial accounting major may pursue a post-baccalaureate major in public accounting, but when completed, the public accounting major would replace the managerial accounting major in the student’s records.</p>
<p>Requirements for becoming a CPA differ from state to state. All states require that students pass the Uniform CPA examination and many require the completion of 150 semester hours of education prior to certification. The 150 hours can be completed in undergraduate or graduate programs. To become a CPA in Iowa, the Iowa State Board of Accountancy requires that students pass the CPA examination, complete 150 semester hours of education, and complete specified course work in accounting and business subjects. Students majoring in accounting, business, or economics are required to have a minimum of 24 of their 150 semester hours in financial accounting, auditing, taxation, and management accounting courses above the elementary level. If students majoring in any other field wish to become a CPA in Iowa, they must, in addition, complete at least 24 semester hours in business-related courses (not including internships). (One course credit completed at Coe is counted as four semester hours.) Accounting students at Coe should work closely with faculty in the department to determine their plan of study. Students wishing to become a CPA should also check the state board’s education requirements for the state in which they wish to practice.</p>
<section id="managerial-accounting-major" class="level3" data-number="25.12.1">
<h3 data-number="25.12.1" class="anchored" data-anchor-id="managerial-accounting-major"><span class="header-section-number">25.12.1</span> Managerial Accounting Major</h3>
<p>A major in managerial accounting requires a minimum cumulative 2.0 GPA in all courses counted toward the major.</p>
<ol type="1">
<li>ACC 171 Principles of Accounting I</li>
<li>ECO 175 Principles of Macroeconomics</li>
<li>BUS 190 Statistical Analysis</li>
<li>ACC 215 Principles of Accounting II</li>
<li>ECO 215 Prin Microeconomics</li>
<li>ACC 301 Intermediate Accounting I</li>
<li>ACC 315 Managerial Accounting</li>
<li>BUS 315 Business Law I</li>
<li>ACC 334 Computer Applications - Accounting</li>
<li>ACC 351 Intermediate Accounting II</li>
<li>ACC 413 Auditing</li>
<li>ACC 415 Adv Managerial Accounting</li>
</ol>
</section>
<section id="public-accounting-major" class="level3" data-number="25.12.2">
<h3 data-number="25.12.2" class="anchored" data-anchor-id="public-accounting-major"><span class="header-section-number">25.12.2</span> Public Accounting Major</h3>
<p>A major in public accounting requires a minimum cumulative 2.0 GPA in all courses counted toward the major. Students wishing to prepare for the examination to become a Certified Public Accountant should select the Public Accounting major, which meets the guidelines for the breadth of business and accounting courses recommended by The American Institute of Certified Public Accountants. Students at Coe can meet the 150-semester hour requirement by completing 37.5 credits.</p>
<p>If degree requirements are not completed by the end of four years, students pursuing a major in public accounting, who are in good academic standing, and who are full-time students, receive a 60% discount on tuition in the consecutive fifth year. They continue to be eligible to apply for student loans and any available federal and state government grants</p>
<ol type="1">
<li><p>ACC 171 Principles of Accounting I</p></li>
<li><p>ECO 175 Principles of Macroeconomics</p></li>
<li><p>BUS 190 Statistical Analysis</p></li>
<li><p>ACC 215 Principles of Accounting II</p></li>
<li><p>ECO 215 Prin Microeconomics</p></li>
<li><p>ACC 301 Intermediate Accounting I</p></li>
<li><p>ACC 315 Managerial Accounting</p></li>
<li><p>BUS 315 Business Law I</p></li>
<li><p>ACC 334 Computer Applications - Accounting</p></li>
<li><p>ACC 351 Intermediate Accounting II</p></li>
<li><p>ACC 413 Auditing</p></li>
<li><p>ACC 422 Tax Accounting</p></li>
<li><p>ACC 463 Advanced Auditing</p></li>
<li><p><strong>One</strong> of the following:</p>
<ul>
<li>BUS 410 Business Law II</li>
<li>BUS 412 Entrepreneurship &amp; New Business Frm</li>
<li>BUS 464 Seminar in Management</li>
<li>BUS 470 Strategic Management</li>
</ul></li>
</ol>
<p>15.<strong>Three</strong> of the following:</p>
<pre><code>- ACC 313 Fraud Examination
- ACC 401 Fund Acctg &amp; Adv Top
- ACC 451 Advanced Accounting
- ACC 472 Advanced Tax Accounting</code></pre>
</section>
<section id="courses-in-accounting" class="level3" data-number="25.12.3">
<h3 data-number="25.12.3" class="anchored" data-anchor-id="courses-in-accounting"><span class="header-section-number">25.12.3</span> Courses in Accounting</h3>
<ul>
<li><strong>ACC 171 Principles of Accounting I</strong> +++MISSING INFO: c.aac171.desc +++</li>
<li><strong>ACC 215 Principles of Accounting II</strong> Continuation of the study of financial accounting, including the statement of cash flow. A study of managerial accounting and the analysis of financial information for management decision making. Prerequisite: Principles of Accounting I (ACC-171).</li>
<li><strong>ACC 301 Intermediate Accounting I</strong> An in-depth study of financial accounting topics. Emphasis is on income determination, evaluation, and presentation of assets, liabilities, and owners’ equity. Prerequisite: Principles of Accounting II (ACC-215).</li>
<li><strong>ACC 313 Fraud Examination</strong> An examination of real world cases that represent the many types of accounting fraud in order to gain an understanding of the behavioral and social factors that motivate offenders. Emphasis is placed on understanding the exposures to loss and the appropriate prevention, detection, and investigation approaches, including legal requirements for testifying as an expert witness. Prerequisites: Principles of Accounting II (ACC-215) or consent of instructor. (Offered alternate years)</li>
<li><strong>ACC 315 Managerial Accounting</strong></li>
</ul>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../catalog_sections/26_academic_programs.html" class="pagination-link" aria-label="ACADEMIC PROGRAMS">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">ACADEMIC PROGRAMS</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../catalog_sections/28_reserve_officer_training_corps_rendered.html" class="pagination-link" aria-label="RESERVE OFFICER TRAINING CORPS">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">RESERVE OFFICER TRAINING CORPS</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <div class="footer-contents">*Coe College Catalog (2022-2023)*</div>  
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>